### ISSUE TITLE
Social Media stuff

### ISSUE THREAD

**Issue by jbcm627** [thewca/worldcubeassociation.org#10]
I just recalled that this exists:
https://www.youtube.com/user/worldcubeassociation
There might be more things out there of use too. I vaguely recall a twitter account, but maybe that was just CubingUSA.

**Comment by lgarron** [comment]
Creating a Facebook page to host official Facebook pages for competitions could help a lot with reach/engagement with some parts of the world.
(However, it could also create a temptation for organizers to just use those Facebook pages instead of creating websites.)

**Comment by jfly** [comment]
The WCT has been formed, and is taking on these sorts of tasks now =)

**Comment by jbcm627** [comment]
How about links (icons or something) to SM?

**Comment by jfly** [comment]
The WCT working on a redesign of the homepage, so I'm sure we'll have some flashy, annoying social media links soon enough =) Until then, we still have a link to the most important form of social media at the bottom of every page:

![image](https://cloud.githubusercontent.com/assets/277474/26732249/c8a7e6f8-476b-11e7-8fc7-ad17031d2cac.png)

=) =) =) :octocat: :octocat: :octocat: :octocat: :octocat: :octocat:
