### ISSUE TITLE
First software team meeting: who is going to Worlds 2017?

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1000]
Assign this issue to yourself if you're planning/hoping to go to Worlds 2017 and would like to do a software team dinner. Non software team members are welcome to join, maybe we can even do some recruiting =)

**Comment by pedrosino** [comment]
We already have this. It's called registration_open
LOL

**Comment by jfly** [comment]
Wow I suck. What a waste of issue 1k. Gonna resurrect this as something else.

**Comment by ronaldmansveld** [comment]
I can't self-assign tickets, as only admins and other people with write-access to the repo can, but I'll be at worlds, and happy to be recruited ;)

**Comment by lgarron** [comment]
Here's the best picture I have from our dinner. :-)
![dsc04350](https://user-images.githubusercontent.com/248078/29110599-04aa04b4-7c9c-11e7-8aa1-804041bd4eb2.jpg)
