### ISSUE TITLE
Better error handling when trying to register to unnanounced competitions

### ISSUE THREAD

**Issue by SK927** [thewca/worldcubeassociation.org#10021]
**Describe the bug**
I get an error when trying to pre-register on a competition using new registration system

**To Reproduce**
1. Create competition
2. Edit events
3. Try to pre-register as Delegate or organizer

**Screenshots**
![image](https://github.com/user-attachments/assets/e6e69973-5673-41d0-b299-61ca3bb8ca12)

**Additional context**
Competition used for my tests: https://www.worldcubeassociation.org/competitions/Geste2025

**Comment by SK927** [comment]
Hey. Thanks for the response. Is it at least possible to make the error
message more descriptive then?
---
Maxime Lefebvre

**Comment by FinnIckler** [comment]
I will make sure this error gets its own error code and is handled accordingly.

**Comment by SK927** [comment]
Great thanks

---
Maxime Lefebvre

**Comment by dunkOnIT** [comment]
Hmm, now that v2 is enabled globally I think we can allow pre-registering for unannounced competitions?
