### ISSUE TITLE
No way to search people without accounts

### ISSUE THREAD

**Issue by coder13** [thewca/worldcubeassociation.org#1003]
There's /search/users but no way to search for people in general. This is probably obviously because there's little extra information non-users have but for a site that might just want to autocomplete anyone with a wca id, this is needed.

**Comment by jfly** [comment]
Our omni search https://www.worldcubeassociation.org/search and our persons search https://www.worldcubeassociation.org/persons both do this, don't they? Or are you looking for an API for this?

Closing for now, but feel free to reopen if I'm missing something.

**Comment by coder13** [comment]
Sorry yes, api

**Comment by jfly** [comment]
Confusingly enough, `/search/users`, *does* actually search our People table.

Here's the call stack for you:

https://github.com/thewca/worldcubeassociation.org/blob/26ed63b19a2ce8efffab598fbffd6051ac41a800/WcaOnRails/config/routes.rb#L128
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/api/v0/api_controller.rb#L76-L78
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/api/v0/api_controller.rb#L76-L78
Finally: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L558-L577
