### ISSUE TITLE
Additional fields for delegates

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1007]
Ilkyoo asked for these additional fields so the WCA Board can stop maintaining a separate google doc of all the delegates.

- [ ] City, State (just a text field, nothing fancy)
- [ ] Phone number (just a text field, nothing fancy)
- [ ] Notes textarea (possibly used for other email, dates of nomination/demotion, WCA Forum username)

These fields should not even show up for non delegates. Delegates should be able to edit their own "delegate fields", but not other's "delegate fields".

**Comment by BiscuitCubed** [comment]
Just so I know what's going on, is there a key to the labels? Most of them are pretty self explanatory, but a couple aren't (Like ment1)

**Comment by jfly** [comment]
@BiscuitCubed, ment1 and ment2 projects are reserved for onboarding people new to the codebase. Please see https://github.com/thewca/worldcubeassociation.org/wiki/How-to-join-the-WCA-Software-Team for a rough outline of how I picture them being used.

**Comment by BiscuitCubed** [comment]
Okay! Thanks!
