### ISSUE TITLE
Confirm that payment amounts are displayed correctly in v2 registrations

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#10106]
In this competition in staging, the "Paid" column shows a dollar amount as being paid for several pending registrations, but in the Edit Registration menu, it says all refunds have been processed. 

I think this is likely a staging oddity, but would be good to do some testing to briefly confirm this isn't an issue in production.

**Comment by gregorbg** [comment]
What is "this" competition that you're talking about?
