### ISSUE TITLE
Results not being exported

### ISSUE THREAD

**Issue by LeonardoSDT** [thewca/worldcubeassociation.org#10160]
**Describe the bug**
I really don't know if this is an issue but it seems that the results from the competitions of last weekend haven't been exported yet, usually they are available the next day (Monday if they were uploaded to the WCA early on Sunday). Now it's Wednesday and I am starting to believe that there could be an issue with the exportation process.

**Comment by FinnIckler** [comment]
Yes. There is an issue with an upstream library https://github.com/sidekiq-cron/sidekiq-cron/issues/508 . We will make sure this gets fixed in the next 24 hours or so

**Comment by FinnIckler** [comment]
Fixed
