### ISSUE TITLE
Handle server system updates

### ISSUE THREAD

**Issue by gagou9** [thewca/worldcubeassociation.org#102]
Yo,

Currently we have 101 packets to update (sudo apt-get update && sudo apt-get upgrade)
40 something of them are security updates. We should definitely upgrade the system on a regular basis!

I didn't manually throw the upgrade as I wasn't sure if it wouldn't break anything.
@jfly, do you see any problem on manually running apt-get on the production machine?

Handling upgrades automatically may be a scary but should be safe enough, or one can just run apt-get update && apt-get upgrade when they ssh onto the server.

**Comment by jfly** [comment]
Lets make it part of [deploying](https://github.com/cubing/worldcubeassociation.org#deploy)? That way someone should detect if something breaks when we update. Automated scares me a bit =).

We could either add it to the [`pull_latest`](https://github.com/cubing/worldcubeassociation.org/blob/master/scripts/deploy.sh#L3) function, or add a new one. Whatever you think is best!

**Comment by jfly** [comment]
Actually, on further thought, lets add it to [wca-bootstrap](https://github.com/cubing/worldcubeassociation.org/blob/master/scripts/wca-bootstrap.sh). That's the command we need to run everytime we change our chef scripts.

**Comment by gagou9** [comment]
Hm. Why not, but, at some point, aren't we gonna actually stop or dramatically reduce changing our chef scripts ?

**Comment by gagou9** [comment]
So the proposition @jfly and I talked about is to add a cronjob which would check for available upgrades and send an email to admin@ whenever there are.
Does it sound good ?

**Comment by jfly** [comment]
Sounds good to me!

**Comment by jfly** [comment]
See https://github.com/thewca/worldcubeassociation.org/issues/138#issuecomment-337386056. We now spin up a new server fairly regularly, so I don't consider this an issue worth solving anymore.
