### ISSUE TITLE
Allow Competition Organizers To Enter Entry Fees in Dollars

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#1020]
A user creating a competition needs to enter the entry fee in the lowest denomination, so for USD is is cents, for Japenese Yen, it is Yen.

In most currencies it is more natural to use dollars and so the UI would be more intuitive if it was modified. https://github.com/plentz/jquery-maskmoney might be useful for this.

**Comment by viroulep** [comment]
Taking a look at this

**Comment by viroulep** [comment]
Keeping some of my experiments here for the record:
I don't think maskmoney is aware of which decimal is needed for, fortunately we can determine which currency don't have subunit:

> blah = Money::Currency.table.values.select {|v| v[:subunit].blank? }.map { |v| v[:iso_code] }
["BYR", "IRR", "ISK", "JPY", "KRW", "VUV", "XBA", "XBB", "XBC", "XBD", "XDR", "XPT", "xts", "XFU"]

And use this information to set the `precision` of maskmoney to 0 for these currency.

**Comment by jfly** [comment]
Just curious, do we know how many "subunits" go into a "unit"? For example, in the US, it's 100 cents to a dollar, but I can imagine that's not always the case.

**Comment by viroulep** [comment]
There is a "subunit_to_unit" field :)

I tried some hash conversion for javascript reason and ran into a very weird behavior, turns out it's because there is two currency with the same iso_code:

> Money::Currency.table.map { |k,v| [k,v[:iso_code], v[:subunit], v[:subunit_to_unit]] }.select { |v| v[1] == "JPY" }
> [[:jpy, "JPY", nil, 1], [:yen, "JPY", "Sen", 100]]
