### ISSUE TITLE
Staff badges doesn't redirect to correct page

### ISSUE THREAD

**Issue by pranav-027** [thewca/worldcubeassociation.org#10254]
**Describe the bug**

- Board and officers badges still redirect to the teams and councils page
- Every team badge redirects to the default WASP council page (its a default page but it could be improved by using the anchor tag with team friendly Id)

**Expected behavior**

- Board and officers badges should redirect to [Boards and officers page](https://www.worldcubeassociation.org/officers-and-board)  page

- Respective team badges should redirect to it's corresponding team page https://www.worldcubeassociation.org/teams-committees-councils#{friendlyId}

**Comment by maxidragon** [comment]
Duplicate, see #9132
