### ISSUE TITLE
Allow registering for unofficial events or additional data entry columns

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1028]
[A request from Ron](https://groups.google.com/d/msg/wca-admin/ZvNYzuxvFpQ/_7AyenoQBwAJ):

> In order to attract more competitions to use the WCA website for registration, I propose the following.
> 
> 1) In the competition events, also allow some unofficial events for known events (like Kilominx, Mystery event, Rubik's Cube No inspection).
> 
> 2) In the competition events, also allow some unofficial events for unknown events. WCA delegate can enter the name of the event.
> 
> 3) In the competition columns add a few free columns with description and data entry fields (check box, radio buttons, input fields) for end users.
> WCA delegate can enter the name of the column and the field type.
> 
> Some examples.
> Regarding 1) we recently had a request to use the Megaminx event as a registration for a Kilominx event.
> 
> Regarding 3) in Dutch Open I always have to use an external website because I need to register some extra information per competitor:
> - is the competitor a member of the Dutch Cube Club
> - number of guests on day 1
> - names of guests on day 1
> - number of guests on day 2
> - names of guests on day 2

I believe that 1) and 2) can be merged.

**Comment by AlbertoPdRF** [comment]
I'm closing this one in favor of #3954, which is more generic.
