### ISSUE TITLE
Add the poll close date to the /polls page

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1032]
This was requested by James Molloy:

> On the topic of polls, is it possible to get the date of creation and date of poll close added to the polls page? It gives some sense of time as to how long ago some votes were cast. For example I would like to repoll the pillowed cubes at some point as I could imagine the overall census might change, but I don't know how long ago it was polled, so it may or may not be sensible to repoll it this early.

I don't think the creation date is that interesting, more interesting is the date the poll was opened for voting... and of course, [there is only a `confirmed` boolean, not a `confirmed_at` datetime](https://github.com/thewca/worldcubeassociation.org/blob/756402ded19b398f3c6cee2dafa915db1e8a1483/WcaOnRails/db/structure.sql#L676).

I think just adding the poll close date would be a good enough feature.

**Comment by pedrosino** [comment]
Adding a confirmed_at field wouldn't be too hard, but maybe not too useful.

**Comment by jfly** [comment]
On further thought, I think it would be good for us to know how long polls were opened, so I support a `confirmed_at` field as well.
