### ISSUE TITLE
"Copy email" button doesn't work in Teams/Committees page

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#10325]
The envelope icon below turns into a copy icon when hovered over - however, clicking on it does not copy the email to the clipboard.

![image](https://github.com/user-attachments/assets/8ba9aa72-5d81-4575-b7c0-fac8cdc8940b)

**Comment by pranav-027** [comment]
Fixed: https://github.com/thewca/worldcubeassociation.org/pull/10329
