### ISSUE TITLE
CSV export: Region names with commas overflow to next column

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#10336]
Report received:
"some regions (for example, Hong Kong, China or Macau, China) are parsed by most applications (e.g. google sheets) as being 2 columns wide, effectively making records for people from those regions not matching the correct fields. Additionally, on the exports, the birthdate and email fields are undefined for every entry.

To replicate both issues, you can look at the registrations for [this competition](https://www.worldcubeassociation.org/competitions/BerkeleyDecTricubealon2024/edit/registrations)"

I suspect this is because the comma in region names which have commas is not being escaped - @pranav-027 is that an issue you'd like to take a look at?

**Comment by pranav-027** [comment]
Hello @dunkOnIT. Sure I would take a look. You can assign it to me

**Comment by pranav-027** [comment]
Fixed: https://github.com/thewca/worldcubeassociation.org/pull/10337
