### ISSUE TITLE
Add a delegate_id parameter to competition search

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1035]
(See #1034 and #956)

The `/competitions` page can generate some pretty expensive queries when searching.

The `contains?` method calls `delegates.pluck(:name)`, which causes a query per competition to fetch just the names of the delegates. It might be faster if this were done as a map with a call to `includes(:delegates)` before. However, I think it would be even better to remove the delegates from this query. AFAIK, it's only used by https://www.worldcubeassociation.org/admin/delegates to view a delegate's history, and the history pages are very slow to load, and more importantly, just plain wrong (since our search splits on spaces, searching for ["Ray Li"](https://www.worldcubeassociation.org/competitions?display=admin&search=Ray+Li&years=all) includes https://www.worldcubeassociation.org/competitions/SpeedcubingLosAlpes2014. I think we should replace this with a delegate_id url parameter.

@pedrosino, since you built the `/admin/delegates` history page, do you think you could take on improving it to use an explicit delegate_id parameter, and then get rid of the delegate query from `Competition.contains?`.

**Comment by pedrosino** [comment]
I believe @pingskills is working on this at #1051 , right?

**Comment by jfly** [comment]
@pingskills is investigating some possible performance improvements to the existing queries, but that's not going to fix the bugs with pages like this https://www.worldcubeassociation.org/competitions?display=admin&search=Ray+Li&years=all. I've renamed this issue to make it more clear what I'm hoping to be done here.

**Comment by gregorbg** [comment]
Closing as I am not sure this is still relevant after the competition page having been ported to Rails.
Feel free to reopen!

**Comment by Jambrose777** [comment]
This is actually already implemented :) but will need to be modified to allow searching for past delegates #4117
