### ISSUE TITLE
"My competitions" status shows "you are currently on the waiting list" when waiting for registration approval

### ISSUE THREAD

**Issue by Suntooth** [thewca/worldcubeassociation.org#10361]
**Describe the bug**
On the My Competitions page, if you are waiting for a registration to be approved, when hovering over the status icon it says "You are currently on the waiting list." even if the competition is not full and you are not on a waiting list.

**To Reproduce**
1. Register for a competition that requires approval.
2. Go to My Competitions.
3. Hover over the hourglass symbol next to the competition.
4. The message is as described.

**Expected behavior**
It should say something like "Your registration is pending approval."

**Screenshots**
<img width="529" alt="Screenshot 2024-12-03 135824" src="https://github.com/user-attachments/assets/132a4ae2-1a8d-428c-8946-f742b9a44860">

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 133.0

**Comment by FinnIckler** [comment]
Hi. 
This is because the waiting list was just introduced a month ago with the new registration system and this text still reflects the old way where pending meant waiting list. We will make sure to change that, thanks
