### ISSUE TITLE
Partial refunds not showing in "Amount" column

### ISSUE THREAD

**Issue by OJCubing** [thewca/worldcubeassociation.org#10382]
**Describe the bug**
In the registrations page (v2) for a competition, the "Amount" column is empty for any registrations with the status "Refunded", even if the amount was only partially refunded. This also means the amount doesn't appear in the total amount.

**To Reproduce**
Example competition: https://www.worldcubeassociation.org/competitions/BristolWinterBeginners2024/edit/registrations
Registration fee is £20, refund percentage is 75%.

**Expected behavior**
Lucas Hill (cancelled), Alexander Chipperfield (rejected) and Gauthambalaji Subramani (rejected) all had £15 refunded, but their Amount column is blank, rather than £5. The totals should be £45 for cancelled and £10 for rejected.

**Screenshots**
![image](https://github.com/user-attachments/assets/ea8036bb-6fc4-408c-8c0b-c951f61473bd)
![image](https://github.com/user-attachments/assets/fe63be26-ecca-4348-a52e-671f320376f9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome

**Comment by OJCubing** [comment]
Unsure if linked to #10106 as it's got a similar name but the issue seems to be separate.

**Comment by dunkOnIT** [comment]
This has been fixed :)
