### ISSUE TITLE
PDF competition's detail is unreadable when setting website language to Thai

### ISSUE THREAD

**Issue by CristCuber** [thewca/worldcubeassociation.org#10414]
When the language of the website is Thai and try to export competition's detail as PDF (e.g. this link: https://www.worldcubeassociation.org/competitions/BangkokCubeFestival2025.pdf), it is unreadable.

[BangkokCubeFestival2025_th.pdf](https://github.com/user-attachments/files/18095200/BangkokCubeFestival2025_th.pdf)

**Comment by FinnIckler** [comment]
We fixed this before by installing the Thai fonts, maybe we missed this when migrating to docker?

**Comment by gregorbg** [comment]
We definitely did port over the font installation, but maybe the Ubuntu packages have changed over time. Worth taking another look at the detailed configuration.

**Comment by gregorbg** [comment]
Indeed Debian "split off" a separate Thai font package which is preferred by the PDF rendering engine.
The font package is now installed into our runtime, and the issue should be fixed!
