### ISSUE TITLE
Add a jump-to menu on the delegates page

### ISSUE THREAD

**Issue by jbcm627** [thewca/worldcubeassociation.org#1045]
Scrolling through this can take a little while. Having some sort of nav at the top could help, with links to jump to specific regions (eg, "USA West" jumps to an anchor by Chris Krueger's profile). (Additional benefit: helps people link to specific parts of that page.)

**Comment by jfly** [comment]
We did something similar on [/faq](https://www.worldcubeassociation.org/faq). Relevant code [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/static_pages/faq.html.erb).

**Comment by jfly** [comment]
I fixed this in https://github.com/thewca/worldcubeassociation.org/pull/2244. Thanks to @LinusFresz for noticing that this issue can be closed!
