### ISSUE TITLE
Delay on competitions being displayed as bookmarked / accepted

### ISSUE THREAD

**Issue by Gnomeball** [thewca/worldcubeassociation.org#10450]
**Describe the bug**

This evening I noticed a big delay in an update to my competitions page.  

Prior to registering for a competition this evening I removed the bookmarks from two competitions; yet they still remained on the page showing as bookmarked.  After registering, and having my registration accepted for the aforementioned competition, it did not appear on that page in the correct section; it displayed within the bookmarks section, despite not having one.

In the image below I have highlighted these two competitions; 1 is a competition I had an accepted registration for (also note that a right hand icon has not yet appeared), and no longer had bookmarked (it was previously bookmarked, but that had been removed), and competition 2 also no longer had a bookmark applied to it.

![image](https://github.com/user-attachments/assets/42c1460d-0825-43e4-a9da-0ea47cc3a32b)

About 10 minutes after having my registration accepted for competition 1, this page did correctly update, which has led me to question if there has been some kind of delay / caching introduced into the new system you are trialling, or if something perhaps isn't hooked up as seamlessly as it should be, as this functionality was working perfectly a few weeks ago, without any delays, prior to the other changes that have been made.

**To Reproduce**
Steps to reproduce the behaviour:
1. Un-bookmark a competition / gain an accepted registration for a competition
2. Open your competitions page
3. If issue has correctly reproduced (I posted about this initially in another online group, and no one else commented on it), you should not see competitions in the correct place on the page

**Expected behaviour**
The 'my competitions' page to to update without the delay, as previously.

**Screenshots**
See above report.

**Desktop**
 - OS: Linux
 - Browser: Firefox
 - Version: 131

**Smartphone**
 - OS: Android 15
 - Browser: Firefox
 - Version: 133

**Comment by FinnIckler** [comment]
This is because the data is read from the read replica database which can be up to 10 minutes behind when there are a lot of results being posted. This has always been the case and has nothing to do with the new registration system.
