### ISSUE TITLE
Evolution of records doesn't obey the rank field in the database

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1056]
See https://github.com/thewca/worldcubeassociation.org/blob/53894784bb97b797ca539a5d9b7458006e333927/webroot/results/misc/evolution/update7205.php#L36, which hardcodes the order of the events.

It also invents some "extra short names" to fit everything in horizontally, but I feel like we should get rid of those and use [cubing/icons](http://cubing.github.io/icons/) instead:

![image](https://cloud.githubusercontent.com/assets/277474/21554397/2e5490ea-cdc4-11e6-9f88-598bd272bc59.png)

(If we ever want this to look good on mobile, we'll probably need to do a redesign anyways)

**Comment by pedrosino** [comment]
After many tries I found that this file you mentioned doesn't seem to be used. The index.php file right next to it does (and was ignored by git for some reason).

I like the idea of using the icons, will try to do it.

**Comment by jfly** [comment]
The file I linked to *is* used. I'm pretty sure it generates that index.php file you're talking about, which is why it's not stored under git.

**Comment by jfly** [comment]
Your call, but at some point, it might be better to just port the page to Rails.
