### ISSUE TITLE
Change URLs in "nearby competitions" table

### ISSUE THREAD

**Issue by Claster** [thewca/worldcubeassociation.org#1069]
When creating a competition, other close competitions are showing in the "Nearby competitions (within 90 days and 500 km)" table. Their URLs are `https://www.worldcubeassociation.org/competitions/CompetitionName2017/edit/admin` which are not very useful if I can't admin their results (btw, I, as a delegate, can't admin any competitions, including my previous competitions - is this intended?)
It would be nice to change the URL to `https://www.worldcubeassociation.org/competitions/CompetitionName2017/` instead.

**Comment by jfly** [comment]
Ah, yeah, this was created by @pedrosino, and he probably only had the Board in mind when building this.

We might need better vocabulary for this, but "admin"-ing a competition is something that only the Board (and other site admins) can do: this includes the power to mark a competition as publicly visible or not. Regular delegates never have this power, so it's expected that you can't admin any competitions.

**Comment by pedrosino** [comment]
I'll try to take a look at this. What do you think of having just the competition link visible to everyone, and an Admin link only to those with that power?

**Comment by pedrosino** [comment]
A couple screenshots:

Delegate/organizer view:
![delegate](https://cloud.githubusercontent.com/assets/1881933/21655852/c98ac33a-d2a2-11e6-9f6e-2a158c94da74.png)

Admin/Board view:
![board](https://cloud.githubusercontent.com/assets/1881933/21655861/d2a488b6-d2a2-11e6-9e7b-d4a0cc458216.png)

I'll ask other Board members if they actually use that link and if keeping an "admin" link somewhere is necessary or not.

**Comment by Claster** [comment]
> What do you think of having just the competition link visible to everyone, and an Admin link only to those with that power?

Yes, I think that would be awesome! Thanks!

**Comment by pedrosino** [comment]
Luis gave a better idea (I didn't like the look on my proposal anyway).

I'll make the link point to the regular competition view if the user is the organizer or delegate, and keep it pointing to /edit/admin if the user has that power. See below:
![boards](https://cloud.githubusercontent.com/assets/1881933/21679562/fbd44ab2-d32b-11e6-8d34-566315a4ae89.png)


He also said
> In fact, I've been tempted several times to suggest something similar in other cases (like, for example, the "Edit" link in the left menu within competitions pages could redirect to "Organizer View" or "Admin View" depending on the user's permissions).

I would like that too. I'm usually not interested in going to the /edit page, so going directly to admin would be cool.
