### ISSUE TITLE
"Approve" button is one pixel too small when approving a WCA ID

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1071]
![image](https://cloud.githubusercontent.com/assets/277474/21666288/94d9a194-d2a5-11e6-901a-99d68045a8b2.png)

I believe I have encountered this exact problem before in another project using bootstrap, and it was actually related to a rounding configuration setting for SASS. See http://stackoverflow.com/a/40918900.

I'll look into this right now.

**Comment by jfly** [comment]
Whatever's wrong doesn't seem to be related to rounding. See:

![image](https://cloud.githubusercontent.com/assets/277474/21666504/d704b396-d2a6-11e6-8224-7d6131c059b2.png)

I have found that if I disable the `height` rule for `.form-control`, then things line up nicely. For the record, here's the relevant bootstrap source code: https://github.com/twbs/bootstrap-sass/blob/5d6b2ebba0c2a5885ce2f0e01e9218db3d3b5e47/assets/stylesheets/bootstrap/_forms.scss#L117.

Strange, this actually is broken for me over on http://getbootstrap.com/components/#input-groups-buttons. See screenshot:

![image](https://cloud.githubusercontent.com/assets/277474/21666856/608d1174-d2a9-11e6-9a67-b3082efc3037.png)

@FatBoyXPC, could you provide a screenshot of how this bootstrap page looks like for you?

**Comment by FatBoyXPC** [comment]
Looks fine for me!
![buttonandinput](https://cloud.githubusercontent.com/assets/744962/24670169/14e3b5ce-193b-11e7-81a3-57f835419863.png)

**Comment by jfly** [comment]
Ah! Things look fine for me as well, but when I zoom in to 110%, it breaks! So this is not something I care about fixing, and bootstrap 3 is out of maintenence mode anyways, so they're definitely not going to care. 

Out of curiousity, I would be curious what a screenshot looks like for you at 110%, though @FatBoyXPC.
