### ISSUE TITLE
Enable mysql slow query log

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1080]
See http://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html.

We currently have the slow query log turned off, but we should turn it on, *and* enable logrotation of the resulting new file.

```
mysql> show variables like 'long_query_time';
+-----------------+-----------+
| Variable_name   | Value     |
+-----------------+-----------+
| long_query_time | 10.000000 |
+-----------------+-----------+
1 row in set (0.01 sec)

mysql> show global variables like '%slow%';
+---------------------------+--------------------------------------------+
| Variable_name             | Value                                      |
+---------------------------+--------------------------------------------+
| log_slow_admin_statements | OFF                                        |
| log_slow_slave_statements | OFF                                        |
| slow_launch_time          | 2                                          |
| slow_query_log            | OFF                                        |
| slow_query_log_file       | /var/lib/mysql-default/production-slow.log |
+---------------------------+--------------------------------------------+
5 rows in set (0.00 sec)
```

**Comment by larspetrus** [comment]
The dev.mysql.com link requires a PhD in MySQl. This one is more practical: https://www.a2hosting.com/kb/developer-corner/mysql/enabling-the-slow-query-log-in-mysql

There should be very few slow queries, so log rotation shouldn't hold this up.

I'd start with a cutoff of 2 seconds.

**Comment by jfly** [comment]
Strange, that link you included also says 'You should only enable the slow query log for as long as it is necessary to troubleshoot performance issues'. I'm going to ignore their advice =)
