### ISSUE TITLE
Available genders for users and persons are different

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1083]
[Here](https://github.com/thewca/worldcubeassociation.org/blob/aba31178269bf6eb6c4398c4ed2f6a08bf83bbf1/WcaOnRails/app/views/admin/edit_person.html.erb#L25) for persons, and [here](https://github.com/thewca/worldcubeassociation.org/blob/aba31178269bf6eb6c4398c4ed2f6a08bf83bbf1/WcaOnRails/app/views/devise/registrations/new.html.erb#L48) for users.

Is this intended?

**Comment by jfly** [comment]
I don't think this is intenational. @SAuroux, should we update https://www.worldcubeassociation.org/admin/edit_person?person[wca_id]=2005FLEI01 to have a "other" option?

**Comment by viroulep** [comment]
Ping @SAuroux ;)

**Comment by SAuroux** [comment]
Sorry, I must have missed that.

As stated in past discussions, I absolutely support this. However, I am not sure if I am the one to decide this. Definition of available genders falls into the same category for me than definition of available citizenships and should definitely get an OK from the WCA Board.

**Comment by viroulep** [comment]
No problems :)

I guess it would also impact cubecomps (@Luis-J-Ianez), since if we start to export "other" in the registrations csv, it would have to support it too.

**Comment by Luis-J-Ianez** [comment]
The importation of "o" genders in the CSV file is in fact already supported. :) Internally Cubecomps stores "m", "f" or blank.

**Comment by jfly** [comment]
This should be fixed by #1542.
