### ISSUE TITLE
What are all the various WCA registration platforms out there?

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1084]
This issue exists to collect a list of all the WCA registration platforms that exist, and who maintains them. Having an accurate list of these might be useful as we work on #946 (the people that built these websites are the kinds of people who might be interested in the "big" json).

(Inspired in part by this Fantasy Cubing [spreadsheet](https://docs.google.com/spreadsheets/d/1V3mIqmXKtFiocmzh13Y_MJSXPTkdAotSwUEUIicWMX4/edit#gid=2010662859). Last checked by @jfly on 2017-01-14)

## Under active development

- [CubingChina](https://cubingchina.com/) ([GitHub](https://github.com/CubingChina/cubingchina)) - Maintained by @Baiqiang
- [cubecomp.de](https://cubecomp.de/) ([GitHub](https://github.com/fw42/cubecomp)) - Maintained by @fw42
- [Speedcubing New Zealand](https://www.speedcubing.nz/event/mind-games-2017) - Maintained by @jbrungar
- [cuber.com.br](http://www.cuber.com.br/campeonato/) - @pedrosino built this system that has been used a few times (including Worlds 2015). Not on GitHub.
- [cubing-tw](http://cubing-tw.net/event/2017TaipeiOpen/registration) - Maintained by cubingtw@gmail.com.

## Looking to move to the WCA

- [CubingUSA](https://www.cubingusa.com/) ([Closed source GitHub](https://github.com/cubingusa/usa)) - Maintained by webmaster@cubingusa.com
- [Speedcubing Australia](http://www.speedcubing.com.au/AdelaideSummer2017/competitors/) - Maintained by Tim McMahon
- [Tribox](http://tribox.com/open/2017winter/competitors) - [@kotarot says](https://github.com/thewca/worldcubeassociation.org/issues/1084#issuecomment-275511271) "Tribox Open, which we held in this month, uses own registration platform which was developed for only this competitions (but we might use it in next Tribox Open), but it is a kind of ad-hoc system and is not capable of general uses."
- [JRCA](http://jrca.cc/) - [@kotarot says](https://github.com/thewca/worldcubeassociation.org/issues/1084#issuecomment-275511271) "the system was created quite a few years ago and is not maintained anymore".
- [Dutch Opens](http://speedcubing.com/events/dcd2009/registration.html) - Uses a form [like this](http://speedcubing.com/events/dcd2009/registration.html) created and maintained by Ron van Bruchem. He says "We need some extra information from the competitors, which is not available in the WCA form. For example: Member of NKC, Guests on Saturday, Guests on Sunday." I think he'd be willing to move to the WCA website if we had a feature to ask registrants for arbitrary data like this.

## Status unknown

- [polish comps](http://polishcomps.pl/) - [everything we know summarized by @jonatanklosko](https://github.com/thewca/worldcubeassociation.org/issues/1084#issuecomment-271417464)
- [kostkarubika](http://www.kostkarubika.org/zawody/olsztyn-open-2017) - [everything we know summarized by @jonatanklosko](https://github.com/thewca/worldcubeassociation.org/issues/1084#issuecomment-271417464)

**Comment by fw42** [comment]
> cubecomp.de (GitHub) - Still maintained by @fw42?

yep

**Comment by jonatanklosko** [comment]
In Poland there are two main websites
- *polishcomps.pl* - Powers competition pages & registration. [Here](http://santaclaus.polishcomps.pl) is an example one.
- *kostkarubika.org* - It's a general website of the Polish Speedcubing Association and they have a competition pages & registration system. [Here](http://www.kostkarubika.org/zawody/gls-cup-final-2016) is an example.

I don't know the developers' GitHub accounts (not sure if they even have those).

**Comment by viroulep** [comment]
For Tribox we need to summon @kotarot!
Japan uses its own registration system, but as far as I could understand by discussing with Kotaro in Japan, they would be interested in moving to the WCA website after i18n is done.

**Comment by pingskills** [comment]
Tim McMahon is responsible for the Speedcubing Australia site. He will start using the WCA site once it supports payments.

**Comment by TimMcMahon** [comment]
@jbrungar maintains https://www.speedcubing.nz

**Comment by AlexMaass** [comment]
there is also this: http://europe.cubing.net/
I think there were some others that I either can't remember the names of or have started to use the WCA website instead

**Comment by jfly** [comment]
> there is also this: http://europe.cubing.net/

AFAIK, these are just competition websites. I believe they use the WCA website for registration. Someone please correct me if I'm wrong.

**Comment by pedrosino** [comment]
I have a registration system we used a few times (including Worlds 2015): http://www.cuber.com.br/campeonato/

But I don't have it on GitHub :P

I'm pondering whether maintaining it is good or not (which includes moving to another website and maybe re-writing in rails). Main feature is being pt-BR and flexibility to show messages about payment after registration.

**Comment by coder13** [comment]
That reminds me about https://euro2016.cubing.net/
Although the website isn't a typical comp site, it works really well.

**Comment by TimMcMahon** [comment]
Is it worth comparing features of each system? E.g. Would making "possible events" available during registration be desirable so that organisers can determine whether there's interest in hosting particular events without committing to them upfront or would this create more complexity for payment?

**Comment by jfly** [comment]
> https://euro2016.cubing.net/ is worth noting

@Luis-J-Ianez did a great job with that website. Interestingly enough, the actually used the WCA website for registration.

> Is it worth comparing features of each system?

If you'd like to write up a list of features and what systems support what, I won't stop you, but I don't see a huge benefit to it. I can't speak for other registration platforms, but the WCA website is not going to add features just because some other website supports them, we're only going to add features once a bunch of people have asked for them.

**Comment by kimchikoon** [comment]
In Hong Kong, we are using our own system for registration of the cubers, instead of the system in WCA.
The system is taken care by Hong Kong Rubik's Cube Union (HKRCU).

**Comment by micahstairs** [comment]
All competitions in Canada have registration on http://canadiancubing.com/.  It's under active development by Dave Campbell.

I've never seen the code before, but I'm guessing it's in a private repo in https://github.com/canadiancubing.

**Comment by kotarot** [comment]
Hi there,
Yeah, as Philippe mentioned, I know circumstances in Japan (sorry that I didn’t notice my notification for long days).

Most competitions in Japan use [JRCA](http://jrca.cc/) as the platforms.
This website is based on XOOPS Cube application, and the registration system is implemented on the application, but the system was created quite a few years ago and is not maintained anymore. Moreover, the interface is not friendly for non-Japanse speakers.
[Tribox Open](http://tribox.com/open/2017winter/competitors), which we held in this month, uses own registration platform which was developed for only this competitions (but we might use it in next Tribox Open), but it is a kind of ad-hoc system and is not capable of general uses.

So, Japanese delegates and I are willing to move system and use the WCA's system.
And yeah! Internationalization accelerates our motivation to move!
Some Japanese cubers (including a Delegate and me) are now translating the website for i18n.

**Comment by jfly** [comment]
This issue is probably pretty out of date now. @Logiqx put together a pretty neat page here that lists a number of actively used registration platforms: https://logiqx.github.io/wca-ipy/Future_Competitions.html.
