### ISSUE TITLE
FAQ item has wrong wording

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1092]
https://www.worldcubeassociation.org/faq#what-are-the-wca-accounts-for-what-is-the-difference-between-wca-accounts-and-wca-profiles

You are assigned a WCA ID when you **first participate** in a WCA sanctioned competition. When the results from that competition are uploaded, your WCA **profile will be created**, with results from **every competition you have been to**. 

This doesn't add up. Your profile will be created with results from the first competition you attended. The other (future) results will be added to your profile later.
I translated this as something like "....your WCA profile will be created, and all results from the competitions you attend will be added to it."

**Comment by jfly** [comment]
You're right, this text doesn't make a lot of sense. I also am not wild about the term "WCA profile", which doesn't really mean anything.

How about we change that whole paragraph to just:

> You are assigned a WCA ID when **the results from your first WCA sanctioned competition are uploaded**.

?

**Comment by jfly** [comment]
@SAuroux, because I think he may have written that FAQ answer originally.

**Comment by SAuroux** [comment]
Well, the text certainly isn't wrong but feel free to improve the wording.
:)

2017-01-14 23:11 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
> Well, the text certainly isn't wrong

It is, though. It says you're assigned a WCA ID when you first participate in a competition, but you're actually not assigned a WCA ID until the results from your first competition are uploaded.

**Comment by SAuroux** [comment]
Ok, granted. Please just fix it according to your linkings. :)

2017-01-18 22:46 GMT+01:00 Jeremy Fleischman <notifications@github.com>:
