### ISSUE TITLE
Make a script to add a missing result

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1094]
This is not very common, but happens from time to time. Maybe we could have a simple rails script for this. @SAuroux described it as:

> Well, we basically need a script that let's you select competition, event and round and asks you for a WCA ID. It should then add a new data row to results with max(id)+1 and the corresponding competitionId, eventId, roundId, formatId, personId, personName. Afterwards we could use the fix_results script to enter the times.

I think the max(id)+1 should be automatic, right?

Is this feasible/worth the effort?

**Comment by jfly** [comment]
This seems like a good thing to support. I think we should port the fix_results.php script to rails first, however.

**Comment by SAuroux** [comment]
It has to be added that while this is not overwhelmingly common, it is by
far the most annoying regular task that the WRT faces. We currently have
the choice between "hacking" the entry into the database manually or to
re-post the updated competition results, which both takes approximately the
same amount of time.

2017-01-14 22:49 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by AlbertoPdRF** [comment]
Should this issue also be added to https://github.com/thewca/worldcubeassociation.org/projects/4?

**Comment by SAuroux** [comment]
Yes, please. As @jfly already suggested, this could possibly be linked with https://github.com/thewca/worldcubeassociation.org/issues/2107.

**Comment by Jambrose777** [comment]
Dup of https://github.com/thewca/worldcubeassociation.org/issues/74
