### ISSUE TITLE
Editable text section on registration page

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#1095]
It would be really nice to have an area where organizers/delegates could put information regarding registration on the registration form.  Competitors often miss the most important information (how to pay, if we need additional info for lunch/t-shirts, etc.) if it is only left on the website, and may not fill out the form correctly or miss important details.  Here's an example on CUSA:

https://www.cubingusa.com/keepportlandweird2017/register.php

**Comment by pedrosino** [comment]
Jacob Ambrose:
>Hello software team,
>
>I never got a reply to my last email about this.
>
>I've had many complaints (in the 20s now) about how after you register it says you are placed on a "waiting list". People find this term very confusing as they think they cannot fully register for the competition. Regardless of how abundantly clear I am on the information section and registration payment tab on my competitions (see rocket city 2017 for reference) many are still confused.
>
>If there is a better way to make the register page more clear or if possible have an editable textbox on that page where we can put something like "PLEASE FOLLOW ALL INSTRUCTIONS ON THE REGISTRATION PAYMENT TAB" that would help out a lot.
>
>As well, on the automated email sent to competitors upon registering organizers is spelt "organisers".
>
>Best,
>Jacob

**Comment by jfly** [comment]
Reopening: Pedro's work in #1099 is what allows us to not make this a high priority, but definitely do plan to do this at some point in the future.

**Comment by jfly** [comment]
Our automated registration requirements don't cover everything, though. This recently came up with fmc Europe, for instance (although I guess they're probably not using wca registration).

I think the best example of a real problem we have is competitions that require some form of payment other than stripe, but any other sort of registration "requirement" that we don't store in a structured way is a potential problem.

**Comment by jfly** [comment]
Ah! Nevermind, I totally forgot about the `extra_registration_requirements` stuff you added, which you did mention in your post, sorry.

I agree that we can close this now.

**Comment by AlbertoPdRF** [comment]
No problem! :)
