### ISSUE TITLE
Add one FAQ about when/how results are posted

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#1096]
Please add the following (the WRT gets such question regularly...):

**When are the results of a WCA competition uploaded to the WCA website?**

After a competition has ended, the WCA Delegate has to double-check all score sheets and person data to eliminate possible errors. Once this is done, the results are sent to the WCA Results Team (WRT), which is responsible for uploading competition results and maintaining the WCA database. The WRT finally uploads the results to the WCA database as soon as possible. Depending on the size of the competition and the delegate's personal schedule, all this can take only a day or up to a week. Please be patient.

**Comment by viroulep** [comment]
Doing this later today.

**Comment by SAuroux** [comment]
Thanks Philippe!

I would suggest to place this above the profile picture question.
