### ISSUE TITLE
Improve the reply-to of notifications for competitions

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1098]
Right now people reply to "notifications@...", which is the software team.
We get of lot of mails because of this, and most (if not all) are actually for the organizers of the competition.

It would be nice to set the reply-to to the contact address, if any, or one of the organizers (not sure we can have multiple addresses in there).

**Comment by larspetrus** [comment]
5 minutes of googling says SMTP only allows one address in `reply-to`

**Comment by jfly** [comment]
15 minutes of playing around says that comma delimited emails in `reply-to` seems to work for me on gmail =)

## I ran this command after sshing to production

Be sure to change the `To: ` field to your own email. (I'm going to regret this if people start spamming me.)

```
echo -e 'To: jeremyfleischman@gmail.com\nSubject: headers test\nReply-To: sw <software@worldcubeassociation.org>, board <board@worldcubeassociation.org>\n\n' |sendmail -t
```

## What I see in gmail

![image](https://cloud.githubusercontent.com/assets/277474/22317273/693b1dd2-e327-11e6-9cd3-cc20f43adfc2.png)

### After hitting reply (**not** reply all, this is after clicking reply):

![image](https://cloud.githubusercontent.com/assets/277474/22317274/6cd54102-e327-11e6-8509-3b5256fe8f6d.png)


Of course, it's entirely possible that different email clients will handle this differently, but we already have that problem with `Reply-To` (it seems like some email clients just ignore the field entirely).

I vote for just making this change, I don't see how it can hurt anything. This would be a good ment1 project, but I think our inboxes are worth protecting. I'll send in a PR shortly.

**Comment by jfly** [comment]
Furthermore, it turns out we're already including multiple emails in our `Reply-To` headers in other places. See https://github.com/jfly/worldcubeassociation.org/blob/919665b6b85348dada1bd52bb03626b02a549a4f/WcaOnRails/app/mailers/competitions_mailer.rb#L29
