### ISSUE TITLE
Allow delegates to assign WCA ID's to accounts

### ISSUE THREAD

**Issue by BiscuitCubed** [thewca/worldcubeassociation.org#1103]
Other than not having payments integrated, one of the biggest problems I face using the WCA site for registration is people not conecting their WCA account and ID. Most of the time I can email them and get it sorted, but not always. I'm in a limbo with one competitor right now where he's paid, but has not connected his Id (2015FRIT01). I sent an email saying that I'd approve the registration once he attaches his WCA ID, but haven't gotten a response.

My proposal is to let delegates assign ID's to registration of comps they're organizing. Obviously this wouldn't work in all cases (see the Philippines) but where there is no doubt, I think it could be very useful. It might also be a thing where the delegate requests it, and the board/results team approves/declines that request.

**Comment by pedrosino** [comment]
I believe you should be able to go to https://www.worldcubeassociation.org/users/38991/edit or https://www.worldcubeassociation.org/users/27028/edit (whichever has the right email) and input the WCA ID and hit save.
Is that what you need?

**Comment by BiscuitCubed** [comment]
Oh, doh! I should have thought to look at the code to make sure it's not there.

I can't edit it, as I'm not a delegate. Why am I able to see it at all?

**Comment by pedrosino** [comment]
I think because you are an organizer. You are allowed to edit name (and maybe DOB, IIRC).
We're looking into changing this behaviour, since it's a little confusing.

**Comment by BiscuitCubed** [comment]
Just name. Thank you!
