### ISSUE TITLE
Pluralizing keys may require passing the locale

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1113]
I found this at the nearby_admin key. It pluralized competitions wrong in pt-BR.
@jfly found http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-pluralize

@viroulep what do you think?

**Comment by pedrosino** [comment]
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_nearby_competitions.html.erb#L38
and
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/config/locales/en.yml#L720

I was expecting '2 competições ...', but it gives me '2 competiçãos ...' instead.

Maybe just making
```
comp:
  zero: ...
  one: ...
  other: ...
```
would solve it.

**Comment by jfly** [comment]
On https://github.com/thewca/worldcubeassociation.org/blob/e9055daba873f54ae391e6c832d44d54cc1df1a6/WcaOnRails/app/views/competitions/_nearby_competitions.html.erb#L38, you can see that we define a `comp` variable for interpolation in the `nearby_admin` key:

```ruby
comp: t('.comp').pluralize(nearby_count)
```

Pluralizing the `.comp` key as @pedrosino suggested seems like a good solution.

Alternatively, it looks like [Rails's pluralize](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-pluralize) method takes an optional `locale` parameter. @viroulep, should we be passing our locale down into these calls to pluralize?

I'm pretty sure we have lots of other calls to `pluralize` throughout our codebase, @viroulep, should we look through all of them and sanity check them?

**Comment by viroulep** [comment]
Well, if pluralize is called on very simple words and we can check the language pluralization rules are respected, then I'd go with adding the locale parameter to the pluralize calls (saves unneeded work for translators).

Otherwise I would just go for pluralizing the key.

I could take a deeper look at this probably later this evening

**Comment by viroulep** [comment]
This is from [Rails doc for pluralize](http://apidock.com/rails/String/pluralize):

> You must define your own inflection rules for languages other than English.

And according to [this API doc](http://apidock.com/rails/ActiveSupport/Inflector/Inflections) we would need to define a lot of rules.
There is [this](https://github.com/davidcelis/inflections) gem, but the set of languages supported is small.

So all in all, it's probably better to get rid of `pluralize` and go through `I18n.t('...', count: ...)`...

**Comment by jfly** [comment]
Darn, that sucks! Yeah, getting rid of all calls to `pluralize` is probably for the best =( This is probably going to be hard to enforce moving forward*. The best solution is probably to keep an eye on people's PRs.

*crazy idea that we don't actually have to implement: something like i18n-tasks that scans our codebase for calls to `pluralize`, and complains about them. We'll need some way to opt in to allowing this (we probably call `pluralize` in some parts of our code that we don't want to translate, so we'd need some sort of `# i18n-pluralize-ok` comment.

**Comment by viroulep** [comment]
Actually there was not that much uses, [this](https://github.com/thewca/worldcubeassociation.org/pull/1137/commits/54f8e84a0460ea981da4165cf649802b8a250e13) commit fixes them all but two.
The last two that would need to be fixed are part of a to-be-localized text.

There is a bunch of other pluralize uses but I think they are fine, as they are in non-localized part of the website.

Here are the "pluralize" remaining:

```
app/views/competitions_mailer/submit_results_nag.html.erb:2:  Dear <%= "Delegate".pluralize(@competition.delegates.count) %> of <%= @competition.name %>,
*app/views/registrations_mailer/notify_registrant_of_new_registration.html.erb:8:  Your registration is on the waiting list, which currently has <%= @competition.registrations.pending.count %> <%= "person".pluralize(@competition.registrations.pending.count) %> on it.
app/views/server_status/index.html.erb:24:          <%= "job".pluralize(@jobs_that_should_have_run_by_now.count) %>
app/views/server_status/index.html.erb:25:          <%= "is".pluralize(@jobs_that_should_have_run_by_now.count) %>
*app/views/competitions/_competition_info.html.erb:65:                <%= media_type.to_s.capitalize.pluralize(media_of_type.length) %>
app/models/result.rb:66:        return "Expected at most #{hlp.pluralize(format.expected_solve_count, 'solve')}, but found #{unskipped_count}."
app/models/result.rb:70:        return "Expected #{hlp.pluralize(format.expected_solve_count, 'solve')}, but found #{unskipped_count}."
```

(the two marked with a '*' should be removed when the text is localized)
