### ISSUE TITLE
i18n for bootstrap tables

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1124]
Right now a few messages in bootstrap table are not translated, such as the "No matching records found" message.

We can easily pass a locale to a bootstrap table like this:
```html
<table data-toggle="table" data-locale="en-US">
</table>
```
Which we could do [here](https://github.com/thewca/worldcubeassociation.org/blob/277241c4010128ae420e36e3b5948b13b38528e2/WcaOnRails/app/helpers/application_helper.rb#L100).
(I tested it locally)

However it takes only "full" locale code (ie: "fr-FR" instead of just "fr", or "cs-CZ" instead of just "cs").
I couldn't find a working rule to determine the "full" code from the short one, so a solution would be to alias locales in our `application.js`, in a way similar to that:
```js
$.fn.bootstrapTable.locales['cs'] = $.fn.bootstrapTable.locales['cs-CZ'];
```

Anyone's got a better idea?

**Comment by jfly** [comment]
Without digging into the bootstrap-table code, aliasing locales like you describe sounds like a reasonable solution. Can we do it in erb somehow so we can loop over `I18n.available_locales` when doing the aliasign?
