### ISSUE TITLE
Competition announcement is partially localized

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1128]
I just announced a competition and this happened: https://www.worldcubeassociation.org/posts/qingdao-prime-numbers-2017-on-marco-26-2017-in-qingdao-shandong-china

Seems like the month part is localized. I think we should keep posts in english.

**Comment by pedrosino** [comment]
I fixed the post but took a screenshot:
![qingdao](https://cloud.githubusercontent.com/assets/1881933/22186378/fedf6378-e0db-11e6-8c31-9c9038f439ec.png)

**Comment by jfly** [comment]
Tricky!

Relevant methods: [post_announcement](https://github.com/thewca/worldcubeassociation.org/blob/1b7375ee2ef4384945d258249597082e5e9b8aa3/WcaOnRails/app/controllers/competitions_controller.rb#L159) and [post_results](https://github.com/thewca/worldcubeassociation.org/blob/1b7375ee2ef4384945d258249597082e5e9b8aa3/WcaOnRails/app/controllers/competitions_controller.rb#L174).

Probably a good idea to modify our existing tests for this: https://github.com/thewca/worldcubeassociation.org/blob/1b7375ee2ef4384945d258249597082e5e9b8aa3/WcaOnRails/spec/controllers/competitions_controller_spec.rb#L502 and https://github.com/thewca/worldcubeassociation.org/blob/1b7375ee2ef4384945d258249597082e5e9b8aa3/WcaOnRails/spec/controllers/competitions_controller_spec.rb#L523

**Comment by pedrosino** [comment]
Looks like post_results doesn't use the date.
We tracked down the problem to the date_range method from time_will_tell: https://github.com/mbillard/time_will_tell/blob/master/lib/time_will_tell/helpers/date_range_helper.rb#L11

It won't take a forced locale. Maybe we could modify it to accept one.

@larspetrus @jonatanklosko @timhabermaas maybe you know something?

**Comment by larspetrus** [comment]
Can you temporarily change the locale while rendering the announcement?

That would be a clean way to do it.

**Comment by timhabermaas** [comment]
Instead of hacking around the issue I'd c&p the `date_range` code into our code base, remove unused code and remove the entire `time_will_tell` gem. There's no need to keep an unmaintained gem which has a dependency on Rails (might break updating Rails) around if we only use a small subset of one method of it.

**Comment by viroulep** [comment]
@jfly: why do you mention the `post_results`?
As far as I looked, there is no localized part in there, did I miss something?

I like @timhabermaas' suggestion, the helper method's small enough, and tuning it would be easy.

I'll look into this.

**Comment by jfly** [comment]
> @jfly: why do you mention the `post_results`?

Whoops! I just assumed, I didn't look too closely.
