### ISSUE TITLE
Sorting of countries isn't correct in Chinese

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1129]
This is how @Baiqiang does it in CubingChina:
![cc](https://lh3.googleusercontent.com/-ViprbksYBGA/WIW3-UmfMrI/AAAAAAAAZTg/AE4xmvaZ2kMl8tcQkVTRCT_bubRvC1m3QCL0B/h66/2017-01-22.png)

This is how [we do it](https://github.com/thewca/worldcubeassociation.org/blob/1b7375ee2ef4384945d258249597082e5e9b8aa3/WcaOnRails/app/models/country.rb#L27-L31).

**Comment by viroulep** [comment]
@Baiqiang is this correct? (both continents sort and countries)
![attempt-sort-cn](https://cloud.githubusercontent.com/assets/1007485/22255340/631fc982-e257-11e6-8135-31a652a34b8a.png)

**Comment by Baiqiang** [comment]
Yes! Looks nice!
