### ISSUE TITLE
Competitions' table titles are not fully localized

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1130]
We just pass the param [here](https://github.com/thewca/worldcubeassociation.org/blob/1b7375ee2ef4384945d258249597082e5e9b8aa3/WcaOnRails/app/views/competitions/_index_competitions_list.html.erb#L7), we should be localizing the param (there is already keys for that).

Right we have this kind of display:
![ct](https://lh3.googleusercontent.com/-6bl6XM6pxEU/WIVnodPDTOI/AAAAAAAAZRc/4dGFYA2NbFw4EKIBNyKEtGx6q4wAA2WugCL0B/h221/2017-01-22.png)

**Comment by viroulep** [comment]
@Baiqiang, you told me about the need of having a character next to a number in a sentence; do you have the same need in the dropdown menu of the years or is it just specifically in a sentence?

**Comment by Baiqiang** [comment]
No. In the dropdown the character "年" can be omitted.
What I said was the sentence "Past from XX", in which "XX" maybe number or all years. In these two cases, we'd like to translate them into two formats.
Past from 2017=>2017**年**的
Past from all years=>所有的
