### ISSUE TITLE
Registrations mailers need localization

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1147]
On my todo list before next Monday.

Should be pretty simple: take the user attached to the registration, look at their preferred locale, if nil->en, else we output the text in the preferred_locale.
Should come with a test using a foreign locale.

**Comment by jfly** [comment]
Oh, a thought! How about updating our mailer layout to include a friendly message like "This email was sent in <local>, you can change that setting <here>"? Relevant code:

- [mailer.html.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/layouts/mailer.html.erb)
- [mailer.text.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/layouts/mailer.text.erb) - I'm unsure if this is actually used. See #1148.
