### ISSUE TITLE
Round name is not localized

### ISSUE THREAD

**Issue by Baiqiang** [thewca/worldcubeassociation.org#1156]
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_results_table.html.erb#L54

**Comment by jfly** [comment]
@Baiqiang, in the future, please include permalinks in your github issues: https://github.com/thewca/worldcubeassociation.org/blob/58043a6689896ac03465f03413099f5eb735072f/WcaOnRails/app/views/competitions/_results_table.html.erb#L54. You can easily get to a permalink by pressing the "y" key on your keyboard.

**Comment by Baiqiang** [comment]
@jfly Ok. I didn't realize that url wasn't a permalink.

**Comment by jfly** [comment]
Dumping some analysis:

More English in our stupid database schema (https://github.com/thewca/worldcubeassociation.org/blob/583552d8a59d48cf1fdc32d226531b0a3554811a/WcaOnRails/db/seeds/rounds.seeds.rb).

On http://localhost:3000/competitions/My0ResultsComp2016/results/all:

![image](https://cloud.githubusercontent.com/assets/277474/22394215/a4494464-e4ce-11e6-936e-d371e2bebaee.png)

Relevant code here: https://github.com/jfly/worldcubeassociation.org/blob/583552d8a59d48cf1fdc32d226531b0a3554811a/WcaOnRails/app/views/competitions/_results_table.html.erb#L53-L55.

I'll take this on.
