### ISSUE TITLE
Should we stop using i18n-tasks for unused keys in non-English locales?

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1161]
@jonatanklosko suggested that we remove the test for unused keys in our non-en locale files.
The motivation behind that is that we would stop having to edit existing locales (other than English), and that we would have unused keys only for a while, since updates to the locales through the app will remove them.

**Comment by jfly** [comment]
Sure, I would support that change, but I would ask that we add the check to our /server-status page, though. I don't want to assume that everyone is using Jonatan's app.
