### ISSUE TITLE
Events name not being translated in winners and by persons

### ISSUE THREAD

**Issue by Baiqiang** [thewca/worldcubeassociation.org#1166]
https://github.com/thewca/worldcubeassociation.org/blob/84a8bec48b80b37608347e9e8dcd9f63c9771eee/WcaOnRails/app/views/competitions/_results_table.html.erb#L47

I think we can simply change the event.cellName to event.name but now I don't have local env to check it.

**Comment by jfly** [comment]
Yep, this is definitely happening.

On http://localhost:3000/competitions/My0ResultsComp2016

![image](https://cloud.githubusercontent.com/assets/277474/22394216/ad19bfd8-e4ce-11e6-896a-3cb0bf292dd1.png)

On http://localhost:3000/competitions/My0ResultsComp2016/results/by_person:

![image](https://cloud.githubusercontent.com/assets/277474/22394212/95672d26-e4ce-11e6-937e-f067bfce846d.png)
