### ISSUE TITLE
Mobile web app: links to not be opened in web browser

### ISSUE THREAD

**Issue by CameronSamuels** [thewca/worldcubeassociation.org#1168]
Currently when you add the website to your homescreen, it will open all the links you click on in your default browser (known to do this on iPhone).
By changing:
`<a href="link.html">`
To
`<a onclick="window.location='link.html'">`
This is easy to do by adding something along the lines of this to any javascript file/script tag:
`var links=document.getElementsByTagName("a");
for (i = 0; i < links.length; i++) {
    links[i].onclick = function() { window.location=this.getAttribute("href"); }
    links[i].href = "";
}`

**Comment by CameronSamuels** [comment]
You might need to add a class or something identifying the <a>'s that go to a page and the <a>'s that have a href of "\" and is just used for dropdowns. If the ones for dropdowns change to onclick instead of href, that will be bad because you don't wan't it having to refresh the page to do a dropdown, and not do the dropdown because of the refresh. I recommend adding a class to the ones going to another page, and using var links=document.getElementsByClassName("className") instead of document.getElementsByTagName("a").

**Comment by CameronSamuels** [comment]
And using ontouchend for mobile and onclick for desktop will be good so there will be no 0.x second delay for touch. You can check if it is a mobile device using these functions:
`var isMobile = {
	Android: function() { return navigator.userAgent.match(/Android/i); },
	iOS: function() { return navigator.userAgent.match(/iPhone|iPad|iPod/i); },
	Windows: function() { return navigator.userAgent.match(/IEMobile/i); },
	any: function() { return (isMobile.Android() || isMobile.iOS() || isMobile.Windows()); }
};`

**Comment by jfly** [comment]
I just tried this out in android and can confirm that things work fine over there.

CC-ing @lgarron.

**Comment by CameronSamuels** [comment]
We just need to fix it for iPhone. Once you publish it, I can confirm it works, if you don't have an iPhone. By the way, I have an Android too, if we need it to test if no one else can for some reason.

**Comment by CameronSamuels** [comment]
I use BitBucket for my source control, so I am not used to GitHub, so I am still getting use to it, so I probably won't be coding in the repo until a little while.

**Comment by lgarron** [comment]
If we don't want this behaviour, we should remove `<meta name="apple-mobile-web-app-capable" content="yes">` instead. I am strongly against adding Javascript to all links.

**Comment by CameronSamuels** [comment]
If you are strongly against it, which I could understand, because it could slowdown the speed. I have used this code before and it doesn't seem to slow it down. Maybe just 0.x%. But if you don't want to do that, I still recommend keeping that meta tag, because if people don't want the safari, they could just add the page they want to there homescreen. An example would be the competition list, or a certain competition. If they click a link on those pages, it would be fine. But adding the homepage to your homescreen and clicking the competition page would not be good to open in safari. So I say keep it, and people can just add the page they want to the homescreen, instead of the homepage.

**Comment by jfly** [comment]
Before doing anything here, I'd like to understand *why* iOS behaving the way it behaves. Why open safari when there's a regular anchor tag, but not when a link causes some javascript to execute?

> I am strongly against adding Javascript to all links.

@lgarron, I'm not saying I'm a fan of it, but why are you strongly opposed? This is what every single [SPA](https://en.wikipedia.org/wiki/Single-page_application) does, right?

**Comment by CameronSamuels** [comment]
When you use href="link.html", and you are in a mobile web app, it opens in safari. But if you use onclick="window.location='link.html'", it doesn't. This is because window.location doesn't open a link, it changes the current URL.

**Comment by lgarron** [comment]
> @lgarron, I'm not saying I'm a fan of it, but why are you strongly opposed? This is what every single SPA does, right?

Well, now, single-page apps are mainly single-age apps. If you don't go to a different page, it's not a navigation. ;-)

I believe the common fullscreen "Add to Homescreen" sites work is to pull in the full browser UI when you click a cross-origin link.

We should not hack around the semantics of links.
It requires assumptions about browser behaviour, client detection, hacky rewriting or templating on the server, inconsistent client code instead of shipping the same frontend to all users, breaks users' expectations for link behaviour, etc.

**Comment by jfly** [comment]
I'm not willing to make any changes here until I understand **why** iOS behaves the way it behaves. Presumably there's a good reason they do what they do, and I'm nervous about hacking around that.

I'm going to close this issue for now. Someone feel free to reopen this if they can give insight into why iOS behaves as it does.
