### ISSUE TITLE
Having the navbar be in a iFrame to keep consistency

### ISSUE THREAD

**Issue by CameronSamuels** [thewca/worldcubeassociation.org#1169]
Having the navbar in an iFrame would be good. But the iFrame should have no border or style so it will loo like the content is on the page you are on.
Some pages on the website don't have the competition link dropdown, or don't have "my results" link in results dropdown. 
Some pros of having those links on every page will be good and will make changing them in the future be much easier (just like if you change the url of a page)
Some cons of this would be the continuously loading of the page.
So if you think this is a bad idea, you don't have to do it, but it will be good in the future when you add more links or delete links that get obsolete and then you have to change the navbar on every page.

**Comment by jonatanklosko** [comment]
> then you have to change the navbar on every page.

That's not true, we have pages written in Ruby&Rails, but some still use PHP - those don't have the *better* navbar.
As we are getting rid of the PHP code I don't think it makes any sense to work on it. For this reason I'm closing that.

**Comment by CameronSamuels** [comment]
OK. That sound good.
