### ISSUE TITLE
On certain screensizes, the tooltips for the "my competitions" page overlap

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1170]
See:

![image](https://cloud.githubusercontent.com/assets/277474/22392689/f8174fdc-e4b0-11e6-849f-0f8861a578b4.png)

CC-ing @viroulep, @pedrosino, both of whom I believe have worked in this code before.

This is minor enough that I'm going to mark it as a ment1. The simplest fix might be to have one of the tooltips appear below, whereas the other will continue to appear on top.

**Comment by pedrosino** [comment]
Your solutions sounds good.
