### ISSUE TITLE
Registration confirmation email assumes that the competitor will be attending day 1 of a multiday competition

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1177]
Olivér Perge noticed this:

> I am sorry if this question has been raised alredy, but I just noticed something in the automatic acceptance e-mail for Hungarian Nationals 2017. It says: We look forward to seeing you on March 25, 2017! 
> 
> I assume this is an automatically generated sentence which would like to welcome everyone who is accepted, but I also assume that the date is the first date competition by definition.
> 
> I agree that this is a polite and friendly way of welcoming people, but I think it could be confusing for 2+ days competitions, where the competitor might not attend the first day, but could get confused as the sentence implies that they should be there then.
> 
> My alternative solution would be to change it either to:
> - The week of the competition, eg. We look forward to seeing you on the 13th week!
> - The same with the weekend of the competition, eg. We look forward to seeing you on the 13th weekend! (Though I can see it could be a problem for competitions which do not run on weekends.)
> - The dates of the competition, eg. We look forward to seeing you on March 25 or March 26, 2017! (Though it could be too long for 3-4 days competitions.)
> - Have an option to pick which event is being held on which day first in the events list, but I assume this is the most unneccessary and time consuming solution. :)

We do plan to eventually ask organizers for their schedules (#278), so Olivér's last idea isn't so crazy, actually.

An interim solution would be to change the sentence to "We look forward to seeing you on March 25, 2017 (or whatever day your first event is, please check the schedule <here>)"? We could be clever and only add that parenthetical if the competition is more than 1 day. This would require moving the field to input the url of your schedule from the delegate report form to the request a competition form.

**Comment by BiscuitCubed** [comment]
Why not just "We look forward to seeing you at {competition name}!" I don't think there's any need to remind them what the date is. It makes it much more difficult on the code end, and is entirely unnecessary in my opinion.

**Comment by jfly** [comment]
Good call, @BiscuitCubed. I've implemented your idea in #1216.
