### ISSUE TITLE
deploy.sh refers to `origin`, which doesn't work if you are working on a fork

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1182]
See [here](https://github.com/thewca/worldcubeassociation.org/blob/6e2064d7d57ec909961856ef0733d2bece8c2c23/scripts/deploy.sh#L38) and [here](https://github.com/thewca/worldcubeassociation.org/blob/6e2064d7d57ec909961856ef0733d2bece8c2c23/scripts/deploy.sh#L67).

Both of these lines refer to `origin`, assuming that it refers to `thewca/worldcubeassociation.org`. However, for me it refers to `jfly/worldcubeassociation.org`.

@viroulep any ideas for how to fix this?

**Comment by jfly** [comment]
Bah, nevermind. It doesn't really make sense to be running `deploy.sh` locally, it was definitely not written with that in mind. It's a deployment tool, not a tool for local development.

I'm closing this issue. @viroulep feel free to reopen if you disagree.

**Comment by jfly** [comment]
Actually, I'm reopening this because https://github.com/thewca/worldcubeassociation.org/wiki/Building-Regulations-locally#how-to-build certainly makes it sound like this should work locally.

@viroulep, how do you think we should handle this?

**Comment by viroulep** [comment]
I don't see a perfect solution, the best we can do is probably provide an option to the user to override the default remote.
