### ISSUE TITLE
competitions.unscheduled is a bit misleading

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1199]
Right now [`wca_date_range` returns `t "competitions.unscheduled"` if a date is missing](https://github.com/jfly/worldcubeassociation.org/blob/1a20dad042ffa31c431b68ed59a75de4478bb8d1/WcaOnRails/app/helpers/application_helper.rb#L122). This is kind of misleading, however, as this `wca_date_range` method could be used in contexts other than competitions.

@viroulep, how do you feel about renaming this key? Any ideas for a better place to put it?

**Comment by viroulep** [comment]
`common.date.no_date`?
"No date" as a text is probably enough(?).

**Comment by jfly** [comment]
Sure, I like that key. "No date" seems like a safer bet than "unscheduled".

I'll take this on right now =)
