### ISSUE TITLE
Make the Regulations available offline.

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#120]
Trivial using AppCache or service workers.

**Comment by denthebro** [comment]
Should this be done as a pdf download instead? Seems like a simpler and more universal solution

**Comment by viroulep** [comment]
The pdf release already exists today, maybe @lgarron can provide some more details on what he wanted to do with this?

**Comment by gregorbg** [comment]
Ping @lgarron

**Comment by gregorbg** [comment]
Closing as inactive.
