### ISSUE TITLE
Include user WCA ID in thewca-bot PR description

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1215]
(See #1209 and #1212 and https://github.com/thewca/worldcubeassociation.org/pull/1213#issuecomment-276143266)

I think we should include the WCA ID (if they have one) with a link to their WCA results. We could also include a link like https://www.worldcubeassociation.org/users/33471/edit to edit their user. That way, we'll be able to find their email address even if they don't have a WCA ID.

@jonatanklosko, could you take care of this? At some point it might be worth making an erb file for this.

**Comment by viroulep** [comment]
I support this :)
(I actually posted the comment linked, by replying to the mail, but it looks like it made thewca-bot author it!)

**Comment by jfly** [comment]
I was wondering how that happened! GitHub bug?

**Comment by viroulep** [comment]
I also noticed that "author" is cc-ed when the bot creates a PR, just like when you personally create the PR; this is probably related.
