### ISSUE TITLE
Add a "change your mailer language" footer to all our emails

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1223]
I think it would be friendly to update our mailer layout to include a message like "This email was sent in `<locale>`, you can change that setting `<here>`"? Relevant code:

- [mailer.html.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/layouts/mailer.html.erb)
- ~~[mailer.text.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/layouts/mailer.text.erb) - I'm unsure if this is actually used. See #1148.~~

(related #1147 and #1222)

**Comment by LinusFresz** [comment]
While chatting with @jfly about this issue, we've experienced that it is not as easy as editing [mailer.html.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/layouts/mailer.html.erb). First, we'd have to build a "set your locale" page in the user's settings before we could link them to anywhere. On this page, we should do something similar to what the `set_locale` method does:
https://github.com/thewca/worldcubeassociation.org/blob/bac70390148f8011ac602002e528792ff35acff9/WcaOnRails/app/controllers/application_controller.rb#L32

Related: https://github.com/thewca/worldcubeassociation.org/issues/3082. When we store the user's preferred locale directly while they're signing up, most of them would not need to change their profile settings at all.

**Comment by AlbertoPdRF** [comment]
I'll label this issue as a good second issue for now, although I wouldn't be opposed to close it as the system we have in place seems reasonable enough to me.

**Comment by jfly** [comment]
I'm OK with closing this. Now that we've fixed #3082, it doesn't feel super important to me.
