### ISSUE TITLE
Inconsistent translation behaviour in some places (eg OAuth login)

### ISSUE THREAD

**Issue by AlphaSheep** [thewca/worldcubeassociation.org#1284]
I've encountered a few places where translations have been acting weird or inconsistently. Below is an example of a screen I got when trying to log in using OAuth. I had trouble reproducing it.

![screenshot from 2017-02-03 21 34 37](https://cloud.githubusercontent.com/assets/6051586/22605474/b0912b30-ea58-11e6-8932-8b9142c3c4b6.png)

The other example I came across that I did manage reproduce easily:
1. Create a new OAuth application
2. Set scope to something invalid, e.g use a comma to separate the scope instead of spaces
3. Attempt to authorise the application.
Parts of the text on the authorise page seem to use a random language. I tried multiple times and had different languages each time.

![screenshot from 2017-02-03 21 51 53](https://cloud.githubusercontent.com/assets/6051586/22606044/028cefee-ea5b-11e6-8fdc-93474a8e2702.png)

**Comment by jfly** [comment]
Dang, good catch! I've hopefully fixed this over in #1302.
