### ISSUE TITLE
Sign in menu isn't being translated via locale

### ISSUE THREAD

**Issue by cubizh** [thewca/worldcubeassociation.org#1292]
The sign in menu button and its contents are not being translated via regular locale .yml files ("sign_in" key exists, but is not being used, the "Sign up" and "Didn't receive confirmation instructions?" are not in the locale file).
However they are being translated somehow and I can't find any of these words in the entire source code. The problem is in some languages, like portuguese, it's far from ideally translated though.

**Comment by viroulep** [comment]
The `registrations.sign_in` key is use [here](https://github.com/thewca/worldcubeassociation.org/blob/28cd4d079bbba4b111402fe7f7de90a54a45d945/WcaOnRails/app/views/registrations/register.html.erb#L20).

I can explain why you can't find these strings in the locale: the keys you're referring to are provided by the `devide-bootstrap-views` gem, which has locales for all the languages currently present on the WCA website.
The current locale files we use are in the 0.0.10 version [here](https://github.com/hisea/devise-bootstrap-views/blob/v0.0.10/locales/).

If you think the translation is bad, I think the best thing to do is to submit a PR on [this repository](https://github.com/hisea/devise-bootstrap-views)!

**Comment by cubizh** [comment]
Thanks for the explanation @viroulep. I have made the PR to that repo, I sincerely hope they fix it.

**Comment by viroulep** [comment]
Cool, closing this for now then :)

**Comment by cubizh** [comment]
Just to let you know the PR was accepted, so this will be fixed when you update that package :)

**Comment by jfly** [comment]
For the record, here's the link to @cubizh's PR: https://github.com/hisea/devise-bootstrap-views/pull/50.

I don't think we can update this gem until @hisea releases a new version of devise-bootstrap-views. The latest version I see is [1.0.0.alpha1](https://rubygems.org/gems/devise-bootstrap-views), which was released back in December.
