### ISSUE TITLE
Use find_or_create_by! in post.rb

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1299]
See @larspetrus's comment [here](https://github.com/thewca/worldcubeassociation.org/pull/1286#discussion_r99448763) and the docs: http://apidock.com/rails/v4.0.2/ActiveRecord/Relation/find_or_create_by%21.

I'll take care of this after we merge up #1286.

**Comment by jfly** [comment]
@larspetrus, I'm actually not sure how to take advantage of `find_or_create_by!` here. The problem is that we're not creating an empty post, we're creating a post with the title and the body set. Here's the current code:

```ruby
    post = (Post.find_by_slug(CRASH_COURSE_POST_SLUG) ||
            Post.create!(slug: CRASH_COURSE_POST_SLUG, title: "Delegate crash course", body: "Nothing here yet"))
```

This will run, but has incorrect behavior (it will create a new post if the body or title changed):

```ruby
post = Post.find_or_create_by!(slug: CRASH_COURSE_POST_SLUG, title: "Delegate crash course", body: "Nothing here yet")
```

Another attempt:

```ruby
    Post.find_or_create_by!(slug: CRASH_COURSE_POST_SLUG).tap do |post| 
      post.update!(title: "Delegate crash course", body: "Nothing here yet")
    end
```

This looks like it should work (but has the downside of being 2 SQL statements instead of 1). However, this doesn't actually work due to database constraints! See:

```ruby
     Failure/Error:
       Post.find_or_create_by!(slug: CRASH_COURSE_POST_SLUG).tap do |post|
         post.update!(title: "Delegate crash course", body: "Nothing here yet")
       end
     
     ActiveRecord::RecordInvalid:
       Validation failed: Title can't be blank, Body can't be blank, Slug can't be blank
```

I'm going to close this issue, because I don't think there's a way to use `find_or_create_by!` here. Feel free to reopen if it you think of a way that would work!

**Comment by larspetrus** [comment]
`find_or_create_by` takes a block ([see documentation](https://apidock.com/rails/ActiveRecord/Relation/find_or_create_by)). I've never used it, but something like this should work:

    Post.find_or_create_by!(slug: CRASH_COURSE_POST_SLUG) do |post|
      post.title = "Delegate crash course"
      post.body = "Nothing here yet"
    end

There is also this form:
    Post.create_with(title: "Delegate crash course", body: "Nothing here yet").find_or_create_by!(slug: CRASH_COURSE_POST_SLUG)
