### ISSUE TITLE
Create a form for WCA members to submit change requests to the WRT

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#1328]
With the growing amount of WCA members, the WRT gets more and more DOB change requests so that people can claim their WCA-IDs. On the one hand this is great and every corrected DOB is a small improvement of the correctness of our data. However, the WRT regularly wastes too much time on individual change request because of several issues:

- people do not include their WCA IDs
- people do not really write understandably
- people fail to include an appropriate proof of identity/DOB
- more...

A very good way to improve efficiency would be a form on the website, dedicated to this use case. The link to this form could be included in our FAQs, in the error that appears when someone tries to claim a WCA-ID with a false DOB or simply be the sole content of a WRT reply to an incomplete change request. On the fly, I have something like this in mind:

Name: (string)
WCA-ID: (**no** searching field! I would expect that people would too often select a wrong WCA-ID of someone with same/similar name otherwise. But it should check if a valid WCA-ID was chosen)
Correct date of birth: (YYYY-MM-DD format)
Proof of Identity: (attachment)
Description: _To proof your identity and your correct date of birth to us, you have to attach a picture of any legal document (identity card, driver license, ...) where your name and date of birth are visible and understandable for an English speaker._

SEND

Sending the form should generate a mail to the WRT with name, WCA-ID and DOB included and the uploaded picture as an attachment.

**Comment by Luis-J-Ianez** [comment]
In order to make the list the more comprehensive the better: identity card, driver license, student card, passport, birth certificate,...

**Comment by Luis-J-Ianez** [comment]
One thing that Sébastien didn't mention but most likely he had in mind: if this form is accessible only for identified users (which makes sense, uh?) we could add a checkbox telling something like "I want to assign automatically my ID to my account %{email} when my DOB if fixed".  Two birds with a shot.

**Comment by SAuroux** [comment]
No, I actually didn't have that in mind and also don't want this. :)

People generally have to contact us to fix their DOB because they messed up during registration for their first competition. Once it is fixed, they should claim their WCA-ID just like everyone else. I don't think that the WRT should even waste a millisecond doing this. Apart from that, this would be circumventing the normal process, which we explicitely discourage in the delegate crash course.

**Comment by SAuroux** [comment]
PING

We currently get like ~2 such time-wasting requests per day on average. Could one of the coders please have a look at this and comment?

**Comment by jonatanklosko** [comment]
Hey, sorry for the delay, I'm already working on this =)

2017-03-02 10:26 GMT+01:00 Sébastien Auroux <notifications@github.com>:
