### ISSUE TITLE
Get some insight into how many people are using languages other than English

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1329]
@larspetrus suggested this, and I like it!

**Comment by pedrosino** [comment]
Not sure what you mean or what your plans are, but
```
select preferred_locale, count(*) as user_count from users
where preferred_locale is not null
group by preferred_locale
order by user_count desc
```
```
en 	284
es 	114
ru 	49
fr 	42
zh-CN 	29
it 	12
hu 	11
pt-BR 	10
nl 	9
ja 	8
zh-TW 	7
da 	6
de 	6
pl 	6
hr 	5
pt 	2
```

**Comment by jfly** [comment]
There are 4 kinds of users not using English:

1. Unlogged in users who have chosen a language (their preference is stored in their session, which I believe means a cookie)
2. Logged in users who have not chosen a language (we serve them whatever language their browser asks for)
3. Unlogged in users who have not chosen a language (we serve them whatever language their browser asks for)
4. Logged in users who have chosen a language (we store their preference in the `preferred_locale` database column you just provided a query for)
