### ISSUE TITLE
Regulations <% provide(...) %> statements not working because Rails defaults to Raw instead of ERB

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1347]
Rails 5 changed the default file processor from ERB to RAW (see [this](https://wyeworks.com/blog/2016/1/26/upgrading-to-ruby-on-rails-5-0)), which means that app/views/regulations/index.html is not working.

One fix would be to rename index.html to index.html.erb, but that will require changes to the [WCA regulations compiler](https://github.com/thewca/wca-regulations-compiler).

See https://www.worldcubeassociation.org/regulations/:

![image](https://cloud.githubusercontent.com/assets/277474/23110044/f2c5aea0-f6d2-11e6-9b83-142c56de5d23.png)

**Comment by viroulep** [comment]
that sounds good to me, the html target is used only for the website anyway!
