### ISSUE TITLE
What's the point of the ORDER BY in export_public.php?

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1372]
See [here](https://github.com/thewca/worldcubeassociation.org/blob/bf3edce49b52d0a01362f63d661142deb4dd256a/webroot/results/admin/export_public.php#L23-L24). I don't get what the point of this ORDER BY is, people are going to be inserting these rows into their own database anyways. This ORDER BY is very expensive for our export, so it would be nice to get rid of it.

@Baiqiang, what do you think?

**Comment by Baiqiang** [comment]
The only reason I can think of is to let the data looks more beautiful. I think it can be removed.

**Comment by FatBoyXPC** [comment]
Could it possibly be for the TSV?

**Comment by Baiqiang** [comment]
@FatBoyXPC I asked @cs0x7f if he used the order in the TSV files. He said no. I don't any other app uses it.

**Comment by FatBoyXPC** [comment]
Yeah, I was thinking more from a human perspective. The order by is not necessary at all for any sort of programmatic parsing of the file.

@jfly could you look at the access logs and get a rough estimate of IP count that downloads the TSV file on some sort of regular interval?

**Comment by jfly** [comment]
That is certainly something that someone (not me) could spent their time on if they want!

**Comment by Baiqiang** [comment]
After some digging, I found where the error raises.
![image](https://cloud.githubusercontent.com/assets/2390434/23370060/6ceda512-fd4e-11e6-8e39-67e26bb06b2d.png)
![image](https://cloud.githubusercontent.com/assets/2390434/23370066/71f52166-fd4e-11e6-9bcd-d0b3bd945539.png)

See the above screenshots. The `mysql_unbuffered_query` does't raise an error while the `mysql_fetch_array` raises one.
