### ISSUE TITLE
Add a "select all" button on Manage Events

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1375]
Requested by Ilya:
>Hello Software team!
>
>I understand you are busy in more global tasks but I would like ask you to add button "Check all" in menu "Manage events" when delegate creates competition. I almost always delegate competition with 15-18 events and my touchpad is tired :P
>
>Thank you for your great work!
>
>Best Regards,
>Ilya Tereshko

**Comment by jfly** [comment]
I anticipate that this page is going to change a bit as we add support for rounds, cutoffs, and groups, so it might make sense to wait on this, as it's not a very critical feature.
