### ISSUE TITLE
Broken link for TNoodle if trailing slash is missing

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1380]
#1346 removed the code ensuring we have a trailing slash for [this](https://www.worldcubeassociation.org/regulations/scrambles/) url. If you go there the link to TNoodle works, however if you go [here](https://www.worldcubeassociation.org/regulations/scrambles) (same url without the ending slash), the TNoodle link is broken.

Not sure how to fix this yet (we must not make #1345 appear again).

**Comment by jfly** [comment]
Gah, I really dislike that rails behaves this way (multiple urls for the same conceptual resource). This probably doesn't comes up in normal rails because rails encourages you to use absolute links everywhere. So, one solution would be to switch to absolute links, but who knows we don't have relative links elsewhere? Furthermore, how would we prevent future relative links? I'd be more supportive of reintroducing some variant of the `ensure_trailing_slash` code that I removed during the rails5 upgrade.

**Comment by jfly** [comment]
@coder13, I totally forgot about this, but this is probably what @KitClement ran into over the weekend. He probably went to https://www.worldcubeassociation.org/regulations/scrambles instead of https://www.worldcubeassociation.org/regulations/scrambles/.

**Comment by jfly** [comment]
@larspetrus [said](https://github.com/thewca/worldcubeassociation.org/pull/1498#issuecomment-291556985):

> I haven't checked how it works, but this option might solve this generally:

> `config.action_controller.default_url_options = { trailing_slash: true }`

@larspetrus, unfortunately, that option only affects url helpers that generate routes, it doesn't issue any any redirects if someone tries to visit a page without a trailing slash.

To demonstrate what that option does, notice the different return values from calling `users_path` here:

```ruby
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> bin/rails c
Running via Spring preloader in process 31077
Loading development environment (Rails 5.0.1)
irb: warn: can't alias context from irb_context.
irb(main):001:0> include Rails.application.routes.url_helpers
=> Object
irb(main):002:0> users_path
=> "/users"
irb(main):003:0> Rails.application.config.action_controller.default_url_options[:trailing_slash] = true
=> true
irb(main):004:0> users_path
=> "/users/"
irb(main):005:0> 
```

**Comment by viroulep** [comment]
Could we do this through nginx with a list of affected resources?
AFAIK the affected url are:
- `/regulations`
- `/regulations/history`
- `/regulations/scrambles`
- `/regulations/translations`

all these need some trailing slashes to work properly.

**Comment by jfly** [comment]
Thanks for the ping here. I'm looking into https://github.com/tkellen/rack-slashenforce right now. If that doesn't work out, solving this at the nginx layer seems acceptable to me.
