### ISSUE TITLE
Base entry fee calculated or displayed wrong when creating new competition

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#1386]
There seems to be a problem with the "Base entry fee" field in the competition form.

We tried to enter an amount of 20 Euro, so we selected "EUR" in the dropdown menu and entered 2000 (Euro cent, which is the lowest denomination of Euro) in the text field. It is now displayed as "€2,000.00" so this is obviously not interpreted as the lowest denomination.

Maybe the information text is just outdated? :-)

**Comment by viroulep** [comment]
Indeed it's just outdated :)

We recently added a mask to display the currency symbol and make the input easier for the user, so now it's actually entered in the most common form by the user, and then it gets converted to the amount in the lowest denomination transparently.
