### ISSUE TITLE
Check that the currency used is supported by Stripe

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1404]
When using online payments we don't check that the currency is supported by Stripe.
No payment will be charge, but it will be discover after someone tries to make a payment.
We should check the currency after a stripe account has been linked.
It's not that simple, it depends on which country the linked Stripe account is based (see [here](https://support.stripe.com/questions/which-currencies-does-stripe-support#supportedcurrencies)).

**Comment by dunkOnIT** [comment]
Closing because @gregorbg if memory serves Stripe does not expose the information which would allow us to check whether the user's account supports a given currency when linking? [I may be confusing Stripe with Paypal in this regard]
