### ISSUE TITLE
Past competitions not competed in

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#1407]
Right now,

If you sign up for a competition and either don't compete or don't have your registration approved. Then the competition still shows up in the past competitions. Would it be possible to fix it to where your past competitions only had comps you've competed in?

(Note this could be a weird error that's a special case. I sign up, was approved, then moved back onto the waiting list. This may cause different behavior from that that I described earlier)

**Comment by jfly** [comment]
Closing for the reason mentioned in https://github.com/thewca/worldcubeassociation.org/pull/1429#issuecomment-289513324.

**Comment by jfly** [comment]
[@Jambrose777 said](https://github.com/thewca/worldcubeassociation.org/pull/1429#issuecomment-289518219):

> A possible alternative would be to have it when the results go up to have the competition show up for only those people(and possible deleage/organizers as well) but this would keep the time in between the end of the competition and before results go up he same as it is currently.

[@jfly said](https://github.com/thewca/worldcubeassociation.org/pull/1429#issuecomment-289520104):

> Ha! So instead of having a "past competitions" section, you want us to have a "competitions with results uploaded" section? And in that section, we would only show competitions for which you have results?

**Comment by Jambrose777** [comment]
I guess kinda the layout that would avoid the issue you described would be to do this:

When you regsiter for the waitlist/approved lists, those show up where they do now.

Then when the competition is over they show up in past competitions.

Then whenever results go up, if you are not in the results (or the delegate/organizer) then that competition is deleted from your past competitions.

So the only change would be removing those competitions that you didn't actually go to after the results go up.

**Comment by Jambrose777** [comment]
I don't know the biggest issue I have is whenever I regsiter, get approved then can go. If the organizer choses to move me to the waiting list rather than delete me then I am unable to edit my regsitration and delete myself, so I'm eternally stuck with that competition in my past competitions.

**Comment by jfly** [comment]
That sounds reasonable. Alterntiavely you could divide this page into two sections: "comps without results" and "comps with results".

**Comment by Luis-J-Ianez** [comment]
I can understand that showing "fake past my competitions" is a problem for people **approved** who did not attend **past competitions without results posted yet**.  But we are having cases of people in the waiting list and even in the deleted list of competitions with results published for whom fake competitions are shown.

Is there any problem in restricting the fake competitions to "people approved in past competitions with results not posted yet"?

**Comment by jfly** [comment]
[One idea from @Mollerz](https://github.com/thewca/worldcubeassociation.org/issues/1947#issuecomment-331137929):

> It might be an idea so that if you go to the past competitions page and it shows 0 competitions, it could ask a little question saying "Have you competed before? You will need to claim your WCAID! <Link here>".
