### ISSUE TITLE
Notification for competition announcements in a country

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#1410]
I think it'd be nice to receive a notification for when competitions get announced in a place you specify. 

Originally I thought it'd be nice to receive just notifications for the country you compete for, however there are plenty of people who live in countries different to who they compete as, not to mention it would be an absolute pain for for example the US where there are loads of competitions that you wouldn't attend. I've  thought of a couple of options for this.

- A checkbox to receive notifications for the country you represent. This simplifies it for people that live in smaller countries that don't travel outside where they live, for example the UK.

- A pin you place down on a map similar to how the competition location picking is done. And it will tell you when competitions are announced within a certain distance. Good for places like the US or larger countries that want to know when competitions are happening _near_ to them. Or for very small countries where people often travel outside that area to attend competitions.

I think this would be nice for those of the world that don't know about their own countries homepages, or if their country doesn't have a hub or anything. Any other suggestions welcome.

**Comment by jfly** [comment]
Please see #732 and #114, which covers your second bullet point. In the interest of keeping things simple, I don't think it's worth building your first bullet point as well.

**Comment by jfly** [comment]
(In case my tone was kind of dry in that previous post, I would LOVE to see this get implemented, we just haven't had anyone take this on yet)

**Comment by Mollerz** [comment]
Yeah that makes sense, I had a look but I couldn't find anything similar, guess I should have looked harder! And I fully agree with your comment on only implementing the first bullet point.
