### ISSUE TITLE
Better association between a Stripe account and a competition

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1414]
Right now disconnecting a Stripe account from a competition will disconnect it from all competitions using this account.
This is an annoying side effect I removed [here](https://github.com/thewca/worldcubeassociation.org/pull/1368/commits/bd74bb250593ef7df35d7b304db46e0c36a395cb).

So we may need to think of another (competition-based) way of handling Stripe account.
Options:
 - Do nothing, once an account is connected, it stays connected.
 - Give organizer the option to unlink the stripe account for the competition.

In any case I think we:
 - Shouldn't be able to disconnect if payments have been made
 - Shouldn't be able to connect another account if payments have been made (I think a charge is linked to an account, so refunds would be broken if the connected account change(?))

Note that in any case the Stripe account owners can disconnect their account from the whole WCA Website from their Stripe dashboard.
So there may be situations where the second point above can actually happen.

**Comment by pingskills** [comment]
I like the idea of not having an option to disconnect but a message saying this can be done through Stripe and affects all competitions using this Stripe account. 

On the other side when creating a competition we actually connect the Stripe account for each competition even if it's already connected. 

So another option is to have a non competition specific page for connecting, and maybe disconnecting, and then a page for linking competitions to a Stripe account. The problem with this is how do you authorise the linking? With the current setup you need the Stripe credentials.
