### ISSUE TITLE
Improving computation of auxiliary data.

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#1450]
Updating auxiliary data is currently part of the results posting procedure. The script has never been fast, but with the steady growth of our database it starts to become unbearably slow. I am not exaggerating if I say that running it currently consumes about half the time needed for a regular posting procedure (assuming results with no special issues).

Recently, the results team shortly discussed this already with @jfly following one of his results submission. There he stated:

_Presumably it is slow (and getting slower) because it operates on every single result in our database? Do you have any ideas for improving this? I wonder if some of these auxiliary tables it's building could disappear if we create appropriate database indices._

Of course, the results team would be happy about any kind of improvement. A significantly faster script would already be great, but a general handling of most cache without the need to compute it manually would of course be even better.

**Comment by Baiqiang** [comment]
One idea is we don't compute all results at a time. 
As we know, we rarely change the results which recorded far from now. For example, results before 2016 may never be changed. So we can store the computed results before 2016 permanently (or update it monthly, quarterly, etc), and every time we only compute results after 2016. In this way, we may save much time in computing I think.
To implement this, we may change lot.

**Comment by jfly** [comment]
Would it be possible to move this script out of the "posting competition results" pipeline and instead run it asynchronously in the backround like some of our other slower scripts?

**Comment by SAuroux** [comment]
Rather not. As an convincing argument, let me quote your reply from the Berkeley results submission: "I'm excited to see my new pb oh single (9.95s =)), but was bummed to see it's not on my personal profile yet. Did you by chance skip running compute_auxiliary_data?" :)
