### ISSUE TITLE
It's not possible to clear the base entry fee

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1468]
The `base_entry_fee_lowest_denomination` [starts out NULL](https://github.com/jfly/worldcubeassociation.org/blob/f1bd4a3f748cac7110f43409bbb7b50b8392e5b3/WcaOnRails/db/structure.sql#L55), but after you set it to something, it's not possible to clear it out, instead it gets set to zero.

@viroulep I'm assigning this to you because you added the cool price picker. How do you think we should handle this? I imagine we could write whatever code is necessary to support actually setting the database field back to NULL, or we could treat 0 the same as NULL.

**Comment by pedrosino** [comment]
I think a fee of 0 is not really a fee, so it could be treated the same as NULL.

**Comment by jfly** [comment]
Then maybe we should change the database field to default to 0 instead of NULL so we don't have two different cases to deal with?

**Comment by pedrosino** [comment]
Yeah, that sounds good too.
