### ISSUE TITLE
Remove rails version from Chef script

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1469]
See https://github.com/thewca/worldcubeassociation.org/blob/e9d957c16596c86f58fa904202a3fe39e66bfac5/chef/site-cookbooks/wca/recipes/default.rb#L115-L117.

I have no idea why this is here, maybe at some point in time I thought Rails had to be installed globally. Let's definitely try removing these 3 things and see if things still work.

**Comment by jonatanklosko** [comment]
Should've been closed before!
