### ISSUE TITLE
Payment and competitor limits

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#1475]
Since there's no competitor limit hard coded into the WCA system, competitions may be in a state where they are able to accept payment but don't have any more room in the competition.  The current options for dealing with this:

1) Close registration early using the time functions.  This prevents payments from competitors who have yet to register, but also prevents waitlisted competitors from paying if a spot opens.
2) Leave registration open.  This allows waitlisted competitors to pay when a spot opens, but *anyone* can also pay erroneously, causing organizers to potentially process many refunds (which I believe costs money to do?)

Ideally, I think a way to get around this would be to have a place to set the competitor limit for a competition -- when this limit is reached, the competitors on the waiting list is unable to pay their fees unless an organizer overrides this for a particular competitor.

**Comment by jfly** [comment]
At the time Kit filed this issue, he was not aware that the WCA website supports refunding registration fees, which I believe is a full refund that Stripe takes no percentage off of. With that tool in mind, the best solution is to let people register and pay, and just refund their registration fee once you realize you're not going to be able to let them compete.

I'm going to close this issue. Automating registration and enforcing registration limits can continue to be discussed over in #328.
