### ISSUE TITLE
Dirty dirty hack for Kit for Rose City 2017

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1493]
This diry hack can be removed on May 22nd, 2017 (after [Rose City 2017](https://www.worldcubeassociation.org/competitions/RoseCity2017) ends).
@KitClement will explain all here.

**Comment by KitClement** [comment]
Yeah, sorry about this :(

We are using two venues for this event, one of which is a library and has intense restrictions on collecting payment.  They knew our Saturday events required payment, but as presently shown, there is no way anyone on the registration page would know not to pay.  The library didn't have a login and we exchanged many emails detailing how our registration system works, and they didn't buy our explanation, and required an in person meeting regarding this.  We discussed putting information in tabs, and having a dedicated registration tab for library registration, but they didn't think it was clear enough, and wanted a message on the registration page.  The library "threatened" to have their own registration for their event, which couldn't collect the necessary WCA data, which would have been really annoying to deal with.  

So, that's how we ended up here. Cases like this are why I opened issue #1095 originally.
