### ISSUE TITLE
Proposition of Personal psych sheet

### ISSUE THREAD

**Issue by Cubeur-manchot** [thewca/worldcubeassociation.org#1497]
Hi everyone !
(first I'm sorry if I don't post at the good place, I don't use GitHub very often)
I recently thought about a small new functionnality on the competition pages : a personal psych sheet. When competitors look at a competition psych sheet, they have to look at the psych sheet of each event to know in each event if they have a chance to get a good place. But they could want to just have their own predicted rank in all events, without the other peoples names, like this :
https://drive.google.com/open?id=0B23xBbKROAE4THN2RFBza3lqWlU
It would be presented like the actual psych sheet, but with only one name and all events, and could be compared with the results per person (for example this one : https://www.worldcubeassociation.org/competitions/OnlyCubeOpen2017/results/by_person).
That's only a little new functionnality, but it might not be too hard to implement (all the data is already loaded for the actual psych sheets, it's the same thing here) and can be practical.
Tell me if that's a good idea or not :)

**Comment by jfly** [comment]
Hey @Cubeur-manchot, this is a neat idea, but not something I think belongs on the WCA website. We have plans for some APIs that will allow other people to build things like this very easily, though. If you're a coder and interested in hearing more about this, check out [WCIF](https://github.com/thewca/worldcubeassociation.org/wiki/WCIF).
