### ISSUE TITLE
Images in delegate reports

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#1507]
It seems like delegates often forget or are not able to resize and compress images they want to add to their delegate reports. On the one hand, if you download these images automatically, the inline placement might destroy the formatting. Thunderbird can handle this by displaying the images in the size of the window, but Gmail just displays the image full size and adjusts the linebreaks accordingly, so you have to scroll a lot to read the text. On the other hand, downloading 20 MB of images when it's not necessary is not too great as well.

As far as I can see there are two options how this could be improved:
- Add the images as a link and not embed them inline.
or
- Use an upload tool to resize and compress the images, so they have a reasonable size for displaying them inline and for downloading.

There is already a similar suggestion in #483, but as it is only a question there, I am creating this new issue to emphasize that I would appreciate an improvement a lot. :-)

**Comment by jfly** [comment]
Ahahaha, I suppose you just read the report for Best Open 2017?

Yes, image uploads is definitely something I'd like to support, I don't want people going to the hassle/inconsistency of resizing images offline.

Honestly not sure when we'll be able to make this a priority, though =(

**Comment by Baiqiang** [comment]
I think we can do two things first:
1. Add a note saying should add pic's url instead of the website containing the pic.
2. Add the style to image which limit the max-width when rendering the html from markdown.

**Comment by jfly** [comment]
> 2. Add the style to image which limit the max-width when rendering the html from markdown.

We do already have a `max-width` rule here: https://github.com/jfly/worldcubeassociation.org/blob/6b8a42146874f699f1970ff9397cff50cbae23eb/WcaOnRails/app/assets/stylesheets/delegate_reports.scss#L4. I think that, plus [premailer-rails](https://github.com/fphilipe/premailer-rails) would get the css working in emails.

**Comment by Baiqiang** [comment]
@jfly But I don't see there's no style attribute on the `img` tag.

**Comment by jfly** [comment]
I see. Well, I'm pretty sure that the gem is supposed to do that somehow, so we'll have to figure out how to set up the gem correctly. https://github.com/fphilipe/premailer-rails#how-it-works says "t collects the URLs of all linked stylesheets", but I don't know if we have any linked stylsheets in our emails.
