### ISSUE TITLE
UI for selecting events is confusing

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#1519]
It's not clear to some people which color indicates that an event is selected -- three of our registrations for Rose City have had competitors choose the exact opposite of the event selection they desired.  See examples below:

![773489950601312065-account_id 1](https://cloud.githubusercontent.com/assets/6166412/24940972/953cf76a-1efb-11e7-927a-2bc613683b8a.png)
![2017-04-08](https://cloud.githubusercontent.com/assets/6166412/24940974/96661ffe-1efb-11e7-83a4-6450a687dbd2.png)
![2017-04-11](https://cloud.githubusercontent.com/assets/6166412/24940976/97c111ec-1efb-11e7-8854-fc3acbe3835c.png)

It might be more clear to provide a text list of events that people have signed up for, use checkboxes, or make the grey icons distinguishable from the black icons in some way that makes them look unselected (smaller, maybe).

**Comment by jfly** [comment]
Could you include a screenshot of the UI that is confusing people?

**Comment by BiscuitCubed** [comment]
I believe he's talking about this one. 

![registration](https://cloud.githubusercontent.com/assets/16313471/24983637/05c9defa-1fae-11e7-96cf-dbe5851a301f.PNG)

**Comment by KitClement** [comment]
Yes, specifically, this part:

![image](https://cloud.githubusercontent.com/assets/6166412/24983739/fc235256-1f9d-11e7-8b63-3ac32069baa1.png)

While you can potentially figure it out via the "All" and "Clear" buttons, it's not obvious enough whether grey or black icons represent events that are selected/unselected.
