### ISSUE TITLE
People mailing to WCT instead to organizers

### ISSUE THREAD

**Issue by LinusFresz** [thewca/worldcubeassociation.org#1531]
The WCT has some trouble receiving mails regarding competition stuff („I want to register another guest“, „I confirm my attendance“, etc.). Normally we would simply send them this link where they can look up a contact mail: https://www.worldcubeassociation.org/faq#how-can-i-register-for-a-competition-who-can-i-refer-to-if-i-have-problems-registering-for-a-competition

But I have an example: https://www.worldcubeassociation.org/competitions/EretumOpen2017
![image](https://cloud.githubusercontent.com/assets/277474/25083514/5db35a90-230c-11e7-8494-1c33c7d2bef9.png)
There is no contact mail at all, so I can understand why they use the contact form of the WCA website instead of the organizers’ mail. Our first suggestion would be something like making this contact information a must instead of an option, replacing empty contact information with the organizers’ mail address or hide the WCA contact link. 
Do you have better ideas on how to avoid this type of mail?

There is a second example: https://www.worldcubeassociation.org/competitions/HelsinkiOpen2017
![image](https://cloud.githubusercontent.com/assets/277474/25083573/a4a3fff4-230c-11e7-82a1-6686e6d366e9.png)
Picture that you are an average cuber with average IT knowledge and you reach a competition page looking forward to "contact the organizers“. One can notice that the „contact“ link at the bottom (linking to WCT now) could be more noticeable to some visitors than the „contact“ link in the middle of the page (which is the correct one). Jeremy made the suggestion to change the contact-link behavior on competition pages, which would be an option as well.

**Comment by jfly** [comment]
Great points, Linus! I agree that we should always have a "Contact" link, if the user didn't specify one. I think the most reasonable thing to put there would be a link to email all the delegates and all the organizers. I've created #1532 for that.

Let's use this issue to discuss how to handle the contact link in the footer when the user is on a competition page. I see a few options:

1. Fix #1532 and wait and see how thing go. Maybe the WCT stops getting silly emails and no more work is required (haha, yeah right).
2. Remove the contact link when you're on a competition page.
3. Change the contact link to contact the competition contact info when you're viewing a competition page.
4. Change the contact link to pop up an alert saying "are you *sure* you want to contac the WCA and not the organizer of this competition?"

2, 3, 4 would get weird for old competitions where the organizers and delegates are both no longer involved.

I also am not sure how easy it will be to define "when you're viewing a competition page", which would make it hard to decide when 2, 3, 4 are in effect.

Currently I think just doing 1) is the best first step, and then waiting to see how things go. @LinusFresz, how do you feel about that?

**Comment by LinusFresz** [comment]
I like the automatic adding of a contact link!

Yes, I feel like 2.-4. would mean also a lot of work for the Software Team. The best way right now should be to go with 1, in my opinion. If the WCT still receives a lot of mails regarding competition stuff afterwards, we might need to rethink about this again.

Out of 2.-4. I would prefer option 2, which means simply hiding the contact link on competition pages. Until now we did not receive any mails from people asking about competitions in the past, so it should be no problem for organizers/delegates receiving mails about this because there are none. But this is just a note if option 1 will not solve the problem. :)

**Comment by jfly** [comment]
> Until now we did not receive any mails from people asking about competitions in the past, so it should be no problem for organizers/delegates receiving mails about this because there are none

I don't think it's that simple, unfortunately. We're talking about people contacting the WCA when they really want to contact the competition organizers, but the flip side of that is people contacting competition organizers when they really want to contact the WCA. Contacting the WCA is a big hassle for us, but at least they get a response. Emailing a retired cuber it's impossible to say what would happen, very possibly the email disappears.

Anyways, I think we're in agreement that we should start with 1. Now to find someone to do it...

**Comment by LinusFresz** [comment]
Ooooh right, I see your point there! Ok this leads to the conclusion that it is definitely better if the WCT receives some more mails regarding competition stuff instead of missing important mails like you mentioned them.

**Comment by jfly** [comment]
Great. I'm going to close this issue, and start working on #1532.
