### ISSUE TITLE
Potential security flaw in ranking page

### ISSUE THREAD

**Issue by ron-popov** [thewca/worldcubeassociation.org#1548]
when going to the rankings page you can change the get value of the number of persons you would like to see and it will display it. It will work with really large numbers as well like the integer max value and even higher, I think this could easily be used in a ddos attack for example using really large numbers and causing a really big load on the servers , i would suggest setting a limit to how high this number can be, Should be a really simple fix in the "webroot/results/events.php" file , it's just that i don't really know php and would like to mess around with an unfamiliar language :P

**Comment by jfly** [comment]
Did you notice that we also have a ["All Persons" option](https://github.com/jfly/worldcubeassociation.org/blob/7d61b560cfe2b984ea8fdd923b8dd443696d81db/webroot/results/events.php#L45)? Give that we support that, I don't see any problem with letting users ask for fewer than every single person.

I'm going to close this issue. When someone ports the relevant page to Rails, they're welcome to change the behavior if they feel it's necessary.
