### ISSUE TITLE
Delegates following the history link from the delegates spreadsheet page get a "You don't have access to this page" warning

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1550]
Delegates recently gained access to this page:

![image](https://cloud.githubusercontent.com/assets/277474/25242226/be224136-25ad-11e7-8ed4-6d99045ee84b.png)

But when the click the "history" link above, they see this:

![bildschirmfoto 2017-04-20 um 15 58 26](https://cloud.githubusercontent.com/assets/277474/25242198/a3797f02-25ad-11e7-990b-46415801d48f.png)

Instead, they should see the history of their competitions.

**Comment by pedrosino** [comment]
> Instead, they should see the history of their competitions.
I would be in favour of this, but not in favour of they being able to see the history of *all* competitions.
