### ISSUE TITLE
Event counter on registration breaks up the design

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1555]
I don't know if this was intentional, but the All | Clear buttons look off:

Admin view
![events](https://cloud.githubusercontent.com/assets/1881933/25300042/5241ed64-26dd-11e7-9992-fe21fab8fcec.png)

Normal registration
![events reg](https://cloud.githubusercontent.com/assets/1881933/25300043/58b69c6c-26dd-11e7-88eb-47f39da6cc63.png)

**Comment by jfly** [comment]
Yeah, this was definitely expected. I'm going to close this issue, feel free to send in a PR if you have an idea for improving it!
