### ISSUE TITLE
Discussing a better solution for determining whether linkings computation is needed

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1576]
(See #1572, where this discussion started.)

The current implementation looks if there are any Results that appeared within the last hour. This implementation has a few quirks to it:

1. This means there's a 1 hour period after results are uploaded where we *always* need to compute linkings, even if the linkings were up to date. For example:
  - Results uploaded at 1am.
  - Generate linkings at 1:10am.
  - At 1:30am, we think we still need to generate linkings, because the most recently modified results is within the last hour (I think this is actually fine because we only schedule work 1 time per hour, but it's still weird)
2. If we miss a cron job, we'll decide never to generate linkings. For example:
  - Results uploaded at 1am.
  - We check at 2:10am if we need to generate linkings, and decide not to. We never end up generating linkings for the results uploaded at 1am.

The weirdness with 1) and 2) above are a result of the fact that we're not taking into account how old the `linkings` table is. I can think of 3 solutions to this (ranked from @jfly's favorite to least favorite):

1. Create a new table to track when jobs were last executed. I could see this being useful for other, future jobs.
2. Use a custom mysql command to figure out when the table was last written to. This was @jonatanklosko's first implementation, but it didn't work because our production version of mysql is out of date. We could look into updating mysql on amazon RDS, though. @larspetrus points out that this would make a future migration to postgresql harder.
3. Add a `updated_at` column to the `linkings` table. This would let us know when the linkings table was last modified, but would also mean storing a whole bunch of extra data we don't need.

**Comment by larspetrus** [comment]
Yeah, that scheme will fail for sure.

Some version of solution `1` is the right thing.

_When_ the last job ran doesn't seem bullet proof. It should be clear _which_ competitions have been computed.

I also wonder what happens if the cron job activated _during_ result upload.
