### ISSUE TITLE
Our nginx config should redirect HTTPS traffic to www.worldcubeassociation.org

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1603]
Right now, our [nginx config](https://github.com/thewca/worldcubeassociation.org/blob/315a7ae80a92052647edb029f8570de98d60a9f8/chef/site-cookbooks/wca/templates/worldcubeassociation.org.conf.erb#L319-L328) only redirects https://worldcubeassociation.org to https://www.worldcubeassociation.org:

```
~ @kaladin> curl -Is https://worldcubeassociation.org | grep '^Location'
Location: https://www.worldcubeassociation.org/
```

All other domains do not get redirected:

```
~ @kaladin> curl -Iks https://34.208.140.116
HTTP/1.1 200 OK
Server: nginx/1.11.8
Date: Fri, 05 May 2017 23:34:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 40687
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"1529a1ef97336a06c371c34fd0bc9d4b"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _WcaOnRails_session=eUErdENxM1RzK3ovVlBNZUZ5M0V6UVpadytaUSt1OTkyaWx0ZStTRE1CYU44QmsreDcvU3UraEYxTHVNVXJLQ1cxdnJvRi9SVmVKQmI1WnF0ZUQ4b0ZmZWp3Qno5cnVWZlEwZWk3N0FMekViRFpGQTlrTmpHaWY4MUd0VlJGdCtUeFBZMFgybXlRWkNvWk9LckVBQ1BVTVhVQXBNNndIbTZnUklzSVFjNm4wPS0tRXA1WmY2SkFTc2hRdGd2M0ZJTkF6Zz09--a557596511b8a81f8cd6906dc1f48a6df2139bc6; path=/; HttpOnly
X-Request-Id: babc5cd8-db96-49d5-858d-0ed6acb93058
X-Runtime: 0.033267
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload


~ @kaladin> curl -Iks https://foo.com --resolve foo.com:443:34.208.140.116
HTTP/1.1 200 OK
Server: nginx/1.11.8
Date: Fri, 05 May 2017 23:33:50 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 40680
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"dc8e0f8678949645d59d1880e43de067"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _WcaOnRails_session=M0FaUlR1UzRpYTdnRWdOT0FCUTB0Rjdhb1cyTE1tY0QwM0ZKTlhXVlZ1eGF4RXVIcHNzeG9vVzJEcmRDQVVVUGJoNUFERmpWZnhTNmhWWUoxQis2ZWNNYnRwZm5ScTRvaktqVTd0YzVlci9BS2NWblBQYjdVZFFlVTBURmw1dEV2MGJuU2g0Zi9qbmR6aS9QcEJxd2FoT2xsT09hb3Y3aDFYd2R2UHZMT3JzPS0tSW5SZHBpRDdKTUlJYW43L25LaTdVUT09--564cd22bf4cf6f89d8b9e1cfd63c3f83c2295506; path=/; HttpOnly
X-Request-Id: 30262dfa-511a-41bd-9dc7-ee266ecf342a
X-Runtime: 0.036643
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

This caused a bug where some WRT members submitted results using https://34.208.140.116, and urls containing https://34.208.140.116 were generated in posts on the homepage. @jonatanklosko fixed these by hand, but I think the only permanent fix is to make sure that people only visit our site with HTTP Host header equal to "www.worldcubeassociation.org".

**Comment by larspetrus** [comment]
Sounds like another fix could be to change whatever code is writing the URL to the DB?

**Comment by jfly** [comment]
That would be another solution! We're using the rails url helpers to generate these urls. http://stackoverflow.com/a/8523014 shows a solution for rails that hopefully would work.

**Comment by lgarron** [comment]
> This caused a bug where some WRT members submitted results using https://34.208.140.116, and urls containing https://34.208.140.116 were generated in posts on the homepage.

How did they do that? Did they click through certificate errors?

Anyhow, I support only responding with WCA data when they're connecting using a host we have a certificate for. That's safe, and should be sufficient for all users.
(If not, then we should carefully consider cases where it's not sufficient.)

**Comment by jfly** [comment]
> Did they click through certificate errors?

I'm pretty sure they did. @SAuroux can confirm this.

**Comment by lgarron** [comment]
> I'm pretty sure they did.

😢 


How's this?
- Respond with WCA data only on the correct origin:
 - `www.worldcubeassociation.org` on port 443 in prod
 - `localhost` on port 3000 in dev
- Redirect any port 80 HTTP requests to HTTPS on the same host.
- Redirect https://worldcubeassociation.org to https://www.worldcubeassociation.org 
- [`return 444;`](http://nginx.org/en/docs/http/request_processing.html#how_to_prevent_undefined_server_names) on any unknown hosts so that nothing will work by accident.

**Comment by jfly** [comment]
I tried implementing the [`return 444;`](http://nginx.org/en/docs/http/request_processing.html#how_to_prevent_undefined_server_names) on staging.worldcubeassociation to no avail.

## What I did

I added this to the bottom of /etc/nginx/conf.d/worldcubeassociation.org.conf and restarted nginx:
```
server {
  listen 80;
  server_name "";
  return 444;
}
```

## How I tested it

### Before

```
~/gitting/worldcubeassociation.org @kaladin> curl -Ik https://54.191.255.17
HTTP/1.1 200 OK
Server: nginx/1.11.8
Date: Mon, 08 May 2017 23:08:10 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 40573
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"d8568a93793e68e879f3d713980c3430"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _WcaOnRails_session=YTBNSWdaMUpwakpuMlhpc0Z5TVRORVBNNk42dVUvNmZmT1hqNEVQOWgwWU5MRDlEMFBNVmY1bWZSTHYyZDhHK0k3RGpyZ2orSDJrODVzWkRnNVg0S3lNcEVEQU9HazI4L1V3WFY0Sng0OUdHQW9kVjArVHM1V2RrTitDeGdOb0s0WERVWUV3YVRMUEdvQU9CWWVzbk90ZFVoSVFIbnZMTHJveTJ2QnN0emdRPS0tUXY2ZTFJODczbnhJUWxKR2Y3bnI5Zz09--61f2a043f8b157d943f61ff8c17c84a3c0fa0c93; path=/; HttpOnly
X-Request-Id: 0a923902-96c6-4a76-976a-09d78e4a28e1
X-Runtime: 0.031611
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

### After

```
~/gitting/worldcubeassociation.org @kaladin> curl -Ik https://54.191.255.17
HTTP/1.1 200 OK
Server: nginx/1.11.8
Date: Mon, 08 May 2017 23:08:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 40573
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"505366abcbfb5e9fe5c8d6a750406a60"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _WcaOnRails_session=clc5K1pqWUc1QzNIZEl1cWtERDVWVHFnRjhjWmU0bTRhYTVVZWtHRkNNZGM2Nm1RQW9hczJpMW1NVHhaL0xiS1hyekNxMksyTzhITGxDN2ZxWTJWanJDS2x4VE9adTVac0Y3S3dVeUxXQUFwMEdya0N5Y2g1TldzSUJDQU5zL2Rqa0ZPMXF4ai9qbVRGbzExMlp0aG5TOGlCdWFGWFVsRFJjbmR5VXQzZWRrPS0tR0U2MWFLVXlRenN4bExMV0dJTENUdz09--51d20e3d4d63057be6ab54154e480e688c90e384; path=/; HttpOnly
X-Request-Id: d4e5a698-6251-413f-9b41-cdf719b9a0b3
X-Runtime: 0.030851
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

**Comment by lgarron** [comment]
> I added this to the bottom of /etc/nginx/conf.d/worldcubeassociation.org.conf and restarted nginx:

Try putting it at the top?

Possibly also try the `default_server` directive: http://nginx.org/en/docs/http/server_names.html

(Sorry, I can't test myself right now.)

**Comment by jfly** [comment]
> Try putting it at the top?

Ok, location *does* matter, putting it above the other `listen 80` server block means this works now!

```
~ @kaladin> curl -I http://54.191.255.17
curl: (52) Empty reply from server
```

Please note: in my previous test, I was testing against HTTPS instead of HTTP. This server block doesn't address the analogous HTTPS issue:

```
~ @kaladin> curl -Ik https://54.191.255.17
HTTP/1.1 200 OK
Server: nginx/1.11.8
Date: Mon, 08 May 2017 23:17:21 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 40573
Connection: keep-alive
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"d6afb19a7d8c859f6dfdb3dc7708d798"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _WcaOnRails_session=T3I0WlNYS2N5dmNxTjhwMTNUVCt3Q2V2SXM3c3JSdVREcWpNWEhMQ2VwY2V5cTBxN05BRndUWlJpQWJCNjFOSzI0UXhwYUNzV3FGSUE2Nm5YekdpYkJqOWxiRUsxUmpzeVlYbGdLbUF5eTNoR3NpelZGM1N6anVHQTdLV0x0ZXBDQ2gweXEvRHFBWmE0VzBocVV0c3A3VWxJM25rMng5WFFmKzlXUzZaV2trPS0tMStUQU1vdnBDaDIza2hjZkE2L1REZz09--7b366e1fc4cc91859dd5faaf02b27fe25da2accd; path=/; HttpOnly
X-Request-Id: 4cbbce2a-f61e-479c-b254-49f5d5bf81e9
X-Runtime: 0.032546
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

@lgarron, how would you change the nginx config to return 444 on HTTPS traffic to the wrong domain?

**Comment by lgarron** [comment]
Jeremey asked me to take another look at this. `worldcubeassociation.org`'s config looks good in prod.
