### ISSUE TITLE
Posting results announcement fails when < 3 people competed in 3x3x3 final round

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1607]
At [Korean Spring Picnic 2017](https://www.worldcubeassociation.org/competitions/KoreanSpringPicnic2017), only 2 people competed in 3x3 final round, which triggered [this code](https://github.com/thewca/worldcubeassociation.org/blob/ef4e57980de3b73d83abf63a179ec52212704ffc/WcaOnRails/app/controllers/competitions_controller.rb#L200).

@SAuroux doesn't really care how this is handled, so we just need to some somthing sensible here (the most reasonable feeling thing to me is to only announce 1 person if 1 person competed, and only 2 people if 2 people competed).

**Comment by larspetrus** [comment]
It looks like this a special case for the `'333'` event.

Is it handled differently for other events?

**Comment by jfly** [comment]
If a competition held 3x3, we show the podium for that event. If the competition did not hold 3x3, then we only announce that results of the competition are now available. A future world might have a feature where you can select the "main event" of a competition, if you don't hold 3x3.
