### ISSUE TITLE
CSRF vulnerability when posting results

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#161]
As a quick hack to get things working over in PHP land, I changed `competitions/:id/post/announcement` and `competitions/:id/post/results` be GET requests, rather than POSTS. This should be changed once check_comp_data.php has been ported to Rails.

In #1606, you can see that @jonatanklosko implemented a similar hack for compute_auxiliary_data.

**Comment by ronaldmansveld** [comment]
@jfly is this ticket still relevant?

**Comment by jfly** [comment]
Yes it is. See https://github.com/thewca/worldcubeassociation.org/blob/00b66534978cd467eff5c0ecef0e12971deb2bcf/webroot/results/admin/scripts/check_comp_data.php#L166 and https://github.com/thewca/worldcubeassociation.org/blob/7e651365cbbd7d12239b6e5f912ddfd3905d642a/webroot/results/js/data_upload_help.js#L14.
