### ISSUE TITLE
Competitions admin view looks off

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1621]
![image](https://cloud.githubusercontent.com/assets/1881933/25948566/76326904-362a-11e7-89b3-b57e9b09cf97.png)

The orange was not supposed to look like this. Also, the date field is overflowing (see first line)

**Comment by jfly** [comment]
@pedrosino, can you take this on?

**Comment by pedrosino** [comment]
Jonatan changed it on d12e982
