### ISSUE TITLE
Too much information on accepted registration page

### ISSUE THREAD

**Issue by SqAtx** [thewca/worldcubeassociation.org#1623]
I registered to a competition today and if i go to the Register tab again I can see this box:
![register](https://cloud.githubusercontent.com/assets/4351932/25983811/e25a7f60-369b-11e7-97f6-f6f54f96d10d.png)
It's the same one there was when I was actually registering, only now:
- It don't need the "We autopopulated this with your preferred events, which you can edit here" text
- Nothing happens if I click on the events (which is expected) but the All and Clear buttons are here and working, which feels odd.
- The comment box is still here (even if I can't select it)

It's somewhat related to #941.

Pretty minor but I thought I'd mention it :)

**Comment by jfly** [comment]
The comment box is intentional, this is how you'd see the comment you left if you had left one. I agree with your other two points, though.

**Comment by jfly** [comment]
Thanks for the suggestions! I've created #1627 to address 2 of them. I don't think we should get rid of the disabled comment box, however.

**Comment by SqAtx** [comment]
Thanks for making the change!

I agree that it makes sense for the comment box to be there.
