### ISSUE TITLE
Periodically check database consistency

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#165]
(Some of our results administration scripts already do a lot of consistency checking)

Some things we're not currently checking:
- [ ] `competition_organizers` and `competition_delegates` points to a real `competition_id` and a real `organizer/delegate_id` (https://github.com/cubing/worldcubeassociation.org/blob/35429867b293ac817aa789b88697da276706128c/WcaOnRails/app/models/competition.rb#L128-L135)
- [ ] All competitions have valid `countryId`s (see this [bug](https://github.com/cubing/worldcubeassociation.org/commit/b3db567f328aeaae933ce728631ad2879cd675ce))
- [ ] Check for non delegates with subordinate delegates #93 
- [ ] Persons without Results: `select Persons.id, Persons.subId, Persons.name from Persons left join Results on Persons.id=Results.personId where Results.id`
- [ ] Results without Persons - @Luis-J-Ianez 
- [ ] Persons without Id - @Luis-J-Ianez 
- [x] Old competitions without Results (not an error but a warning? @Luis-J-Ianez checks this every Friday and emails the delegates)
- [ ] Results without Competitions (? not sure this ever happened) - @Luis-J-Ianez 
- [x] Registrations for events that aren't being offered (#385)

**Comment by timhabermaas** [comment]
Could these issues be solved using database constraints?

**Comment by jfly** [comment]
I looked into database constraints for foreign keys, and I vaguely recall discovering that sqlite doesn't support foreign key constraints? However, after googling just now, it looks like it actually does. Definitely worth looking into.

**Comment by Luis-J-Ianez** [comment]
Some ideas coming quick to my mind:
* Results without Persons
* Persons without Id
* Old competitions without Results (not an error but a warning? I check this personally every Friday and email the delegates, so...)
* Results without Competitions (? not sure this ever happened)

**Comment by jfly** [comment]
I just added a `rake db:data:validate` script here: https://github.com/cubing/worldcubeassociation.org/commit/168d45d50b7cbba6d33d84c2cd0e90fdbb4bf2d0. I think we could achieve everything we want here if we just ran this script periodically (we'd need to make sure we have a validations for all the of things mentioned in this issue)

**Comment by jbcm627** [comment]
It might also help to check for potential duplicate persons (is there a less verbose query?):

```sql
SELECT * FROM Persons
INNER JOIN (SELECT *, count(*) FROM Persons
  GROUP BY name, countryId, gender, year, month, day
  HAVING COUNT(*) > 1
) AS duplicates ON (
  duplicates.name = Persons.name
  AND duplicates.countryId = Persons.countryId
  AND duplicates.gender = Persons.gender
  AND duplicates.year = Persons.year
  AND duplicates.month = Persons.month
  AND duplicates.day = Persons.day
)
```

This currently produces the following:

Showing rows 0 - 7 (8 total, Query took 2.1979 seconds.)

2008WONG01  1 Aaron Wong  USA
2012WONG03  1 Aaron Wong  USA
2007KIMD01  1 Daniel Kim  Canada
2016KIMD02  1 Daniel Kim  Canada
2006KIMD01  1 David Kim USA
2014KIMD02  1 David Kim USA
2011WUFA02  1 Fan Wu (吴凡) China
2013WUFA01  1 Fan Wu (吴凡) China

**Comment by larspetrus** [comment]
I don't have the DB, but something like this should work:

SELECT * FROM Persons GROUP BY name, countryId, gender, year, month, day
HAVING count(*) > 1 ORDER BY name



-- 
Procrastinators - the Leaders of Tomorrow

**Comment by jbcm627** [comment]
Ah - that almost works. The tricky part seems to be getting both of the duplicate entries, not just one.

**Comment by jfly** [comment]
Is `GROUP_CONCAT` the answer here?

```sql
SELECT GROUP_CONCAT(id) FROM Persons GROUP BY name, countryId, gender, year, month, day
HAVING count(*) > 1 ORDER BY name
```

**Comment by SAuroux** [comment]
Results team note: not too long ago (beginning of this year) I ran a
similar query to identify duplicates resulting in >40 potential duplicate
pairs. We put lots of work into fixing these and what Jim found there is
the remainder of these pairs which are all found to be likely not
duplicates. :)

2016-05-08 0:19 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
Out of curiosity, I just ran our database validation script on production, and it took almost one full hour:

```
~/worldcubeassociation.org/WcaOnRails @production> time RAILS_ENV=production rake db:data:validate
...
real    53m37.350s
user    34m56.089s
sys     0m46.780s
```

**Comment by jfly** [comment]
Now that #944 has merged up, I tried running our database validations again:

```
~/worldcubeassociation.org/WcaOnRails @production> time RAILS_ENV=production rake db:data:validate &> /tmp/2016-10-18-rake-db-data-validate

real    17m14.348s
user    10m56.339s
sys     0m15.887s
```

(Note that most of the time saved is probably because we're writing to a file instead of the screen)

We have 12433 invalid rows in our database:

```
~/worldcubeassociation.org/WcaOnRails @production> wc -l /tmp/2016-10-18-rake-db-data-validate 
12433 /tmp/2016-10-18-rake-db-data-validate
```

**Comment by jfly** [comment]
I don't think this is a very high priority for us right now. Closing.
