### ISSUE TITLE
Fewest Moves appearing twice in competition results 

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1652]
![image](https://cloud.githubusercontent.com/assets/1881933/26229133/a7895b34-3c15-11e7-8da0-20d6e2bc2ec2.png)

See the 2 lines saying "3x3x3 FM"
It should be one title and the two winners listed.

If I'm not wrong it used to be that way in the old design

**Comment by jfly** [comment]
For example:

![2017-05-18_11 04 17_1120x459_kaladin](https://cloud.githubusercontent.com/assets/277474/26229174/824b6d88-3bf4-11e7-9b30-93591b63a293.png)
