### ISSUE TITLE
Make Travis use the latest bundler whenever it is possible

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#1662]
Temporarily we force Travis to use `bundler 1.14.6` due to #1656.
#1660 should be reverted once jish/pre-commit/issues/258 (aka rvm/pluginator/issues/10) is resolved and everything works well with the latest version (`bundle update pre-commit`).

**Comment by mpapis** [comment]
fixed in pluginator 1.4.1

**Comment by jonatanklosko** [comment]
Thanks @mpapis!
