### ISSUE TITLE
/archive instead of /legacy?

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#1672]
In #1651, we moved the old forum to `/legacy`. My instinct is that this doesn't have the right connotations unless you know English well, or know what it means for software.

I'd like to propose moving it to `/archive` instead.

@jfly, @jonatanklosko , if I want to send a PR without a full checkout, can I just update the single route added in #1651?

**Comment by jonatanklosko** [comment]
I'm in favour of this. Yeah `:legacy` -> `:archive` is the only thing.
