### ISSUE TITLE
Sorting competitors by name appears broken

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#1677]
See https://www.worldcubeassociation.org/competitions/WC2017/registrations for example

When the page first loads, the sorting is fine, but clicking "Name" again does no longer result in a proper sorting.

I already had a quick chat with @jonatanklosko to confirm this is a bug. He confirmed and asked me to open an Issue. He also had the idea, that Javascript might sort by links to profiles instead of displayed names.

**Comment by LinusFresz** [comment]
Just a quick comment: It is still a sorting, but by WCA ID (descending). I noticed the same if I sort by country first, and then again by name, which makes the ranking ascending starting with the oldest WCA ID.

**Comment by Laura-O** [comment]
@LinusFresz Which is the result of sorting by URLs. 😃
