### ISSUE TITLE
Gender stats

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#168]
In September, 2017, the WCA delegates were asked "Should the WCA website allow filtering rankings by gender?" The results of the poll were 84 yes and 31 no.

There are a few issues related to this. See:

- https://groups.google.com/forum/#!msg/wca-delegates/lhY0MsfN-rw/OGjWHVFaAgAJ - Relevant discussion on the WCA delegates list
- https://github.com/cubing/wca-regulations/issues/160 - Relevant WRC issue on this topic
- https://github.com/thewca/worldcubeassociation.org/issues/301 - Port events.php to Rails
- https://github.com/thewca/worldcubeassociation.org/issues/1919 - Change the way records are displayed on events.php

There is some uncertainty about how we want to handle people with gender `o`. Either we allow filtering by "male, female, or other", or we only allow filtering by "male or female".

**Comment by Laura-O** [comment]
As already mentioned in https://github.com/thewca/wca-regulations/issues/160, the WRC has asked the WCA delegates about their opinion:

_Should the WCA website allow filtering rankings by gender?_
Yes - 84 votes -73.04%
No - 31 votes - 26.96%

It would be great if the software team could implement this. If you need any help, ideas or suggestions, please let us know.

**Comment by jfly** [comment]
Thanks @Laura-O! Since I know you're good at this, do you mind posting some screenshots mocking up how you could see this feature working? We also need to decide how we should handle people with `NULL` gender (meaning we never asked them for their gender), and people with `o` gender (meaning they do not want to be shown as male or female on our website).

**Comment by jfly** [comment]
One of the big concerns people have with this feature is that it's going to look like the WCA is saying it believes that gender somehow impacts people's speedcubing ability, and that we've decided to start awarding "world records by gender", which is very much *not* the intention here. The intention is for this to just be some fun, new filter on the data that might also motivate non-male speedcubers to continue the hobby.

@lgarron posted some thoughts for how to visually make this distinction in #1919.

**Comment by Laura-O** [comment]
My first reaction was "Of course we should also show 'other'" but as these are not that many competitors, these rankings would be quite empty. Furthermore, this allows finding all competitors with "other" gender. I am not sure if these competitors would be fine with that.

Anyway, here is a suggestion how this could look like:
The WCA recognizes records for events and regions, so these filter options are the most important and this should be visible.
There are three more filter options: gender, year and number of people/results. As these do not represent any officially recognized records, I would suggest to add them as additional search options and make them collapsible.

### Default:
![search](https://user-images.githubusercontent.com/362249/30253081-4b860e86-967e-11e7-9ef4-85e14da2de46.png)

### Collapsed:
![search-collapsed](https://user-images.githubusercontent.com/362249/30253080-4b823536-967e-11e7-9475-e813c0534716.png)

### Alternative: Collapsed without caption:
![search-collapsed-alt](https://user-images.githubusercontent.com/362249/30253091-8db83ea0-967e-11e7-9560-3063e55cad11.png)

**Comment by jfly** [comment]
I like the proposal, @Laura-O! I do find it a little strange to move the "number of people to show" select below the fold. (Honestly a better UI might put that at the bottom of the list, since that's where people are going to notice there are only 100 people showing.)

**Comment by RockGirl0506** [comment]
I think this idea should be implemented soon as more people would be encouraged to participate.

**Comment by RockGirl0506** [comment]
At my last competition, I asked around if rankings for female cubers should be listed separately on the WCA, and I got a quite positive result. Most people agreed that having a separate ranking for female cubers would motivate many more girls to participate and would be a nice idea in general. I would like to suggest if you could add this to the WCA website.
Thanks.
