### ISSUE TITLE
Sort registrations by accepted date

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1694]
Right now we can sort them by when the registration was created, but many competitions now require pre-payment, so the date that actually matters is when the person fulfilled all requirements.

(Sorry if this exists already, I fell a little off the grid with recent changes)

**Comment by jfly** [comment]
See PR #1484 (in particular [this screenshot](https://github.com/thewca/worldcubeassociation.org/pull/1484#issuecomment-291281463)), which is all about sorting the (still misnamed) waiting list. It sounds like that's not relevant for you though, because you're asking about sorting by accepted date, which presumably means you want to sort the accepted registrations table? Why would you ever want to sort that table?

**Comment by pedrosino** [comment]
Yeah, that's different. (Why isn't it merged?)

One use I can think of is you are giving some gift/prize to the first X people who registered. Going through email to find this out can be a little boring and/or messy.

**Comment by pedrosino** [comment]
Ah, duh, it is merged :P

**Comment by jfly** [comment]
I see. Yes, looking through email to figure that out sounds annoying. This might be a slippery slope though... other things I could imagine caring about include:

1. Sorting by number of competitions attended.
2. Sorting by distance travelled for this competition.

That said, this seems simple enough to add, and if it actually makes your life easier, then I'm not opposed to adding it. It's worth noting that this might interact weirdly with any future features to allow competitors to edit their existing, approved registrations.

**Comment by pedrosino** [comment]
I don't think we should allow competitor to edit approved registrations, since those might require a new payment.

This isn't anything critical. What is the correct tag?

**Comment by jfly** [comment]
> I don't think we should allow competitor to edit approved registrations, since those might require a new payment.

Let's continue that discussion over on #941 =)

> This isn't anything critical. What is the correct tag?

I tagged this with "registrations". I can't think of a better tag than that.

**Comment by dunkOnIT** [comment]
This is now possible in the new reg system :smile:
