### ISSUE TITLE
Friendly error pages

### ISSUE THREAD

**Issue by jbmertens** [thewca/worldcubeassociation.org#17]
Would be good at some point.  I don't think we need an automatic search or anything for 404s, but something cute, at least :)

**Comment by lgarron** [comment]
Show a randomly scrambled cube? :-P

("We couldn't resolve your request..."

**Comment by jfly** [comment]
Cute!

**Comment by lgarron** [comment]
http://cube.garron.us/misc/CubeVille/cube_sad.php?name=Jim&action=share
![screen shot 2015-05-01 at 17 25 22](https://cloud.githubusercontent.com/assets/248078/7439175/12d59ea8-f027-11e4-8da5-115f41a0fe7a.png)

**Comment by gregorbg** [comment]
ALso relevant: Ideas and discussions over at #3170

**Comment by dunkOnIT** [comment]
@gregorbg is this tech debt? ie, should it be in the "Technical Debt" project?

**Comment by gregorbg** [comment]
Strictly speaking, No. We did not actively "choose" this current, simple error page solution as it comes pre-packaged with Rails out of the box. So we're not cleaning any mess that _we_ caused (of course we were the ones choosing Rails in the first place, but I wouldn't want to dig that deep to argue in favor of labelling an issue as technical debt)

**Comment by dunkOnIT** [comment]
Amazing, thanks Finn!
