### ISSUE TITLE
Automate changes detection of the WCA Countries list

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1721]
Although automating the change in the db is not possible, it should be easy to detect changes compared to the version in the official WCA Regulations repository, and display a big warning/email the team.

See discussions [here](https://github.com/thewca/worldcubeassociation.org/pull/1650#issuecomment-308511948).

**Comment by larspetrus** [comment]
Could we detect it in a test that goes red before deployment?

I don't actually know which two things can go out of sync with each other, so I have to ask clueless questions...

**Comment by gregorbg** [comment]
Is this option still relevant despite the `wrc-states` feature of https://github.com/thewca/wca-regulations-compiler ?

**Comment by viroulep** [comment]
I think we can close this, but not because of `wrc-states`: a test was added in #4409, so if we try to update the country list without updating the rest, something will go red :)
