### ISSUE TITLE
Remaining erb in Regulations

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1727]
There is some erb rendered here: https://www.worldcubeassociation.org/regulations/history/official/2015-07-01/.
It should actually be interpreted to provide the title for the page.

I'll try to take a look at it in the upcoming week, it should be fairly easy to fix.

**Comment by jonatanklosko** [comment]
[These files](https://github.com/thewca/worldcubeassociation.org/tree/regulations-data/regulations/build/regulations/history/official/2015-07-01) are missing the `.erb` ending, thus being rendered as they are without preprocessing.

**Comment by jonatanklosko** [comment]
Closing via #1756.

**Comment by viroulep** [comment]
Thanks a lot @jonatanklosko!
