### ISSUE TITLE
Add the newly created WCA Financial Committee (WFC) to the website

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1729]
There are a few steps to this:

- [x] Set up a google group (wca-finances@googlegroups.com), and add cmhardwick@gmail.com, cwwright.uk@gmail.com, james.g.molloy@gmail.com to it. @jonatanklosko, you created a doc with instructions to do this, right? Could you add a link to it here?
- [x] Set up an email forward. Either finances@ or wfc@ should point to wca-finances@googlegroups.com. See https://docs.google.com/document/d/17w9Pzfk1kz1vM8dDFHe7XKFRmAdWKlAyxgEV8K6MrSU/edit, which also has this payments@ address that @pedrosino created. @pedrosino, should that address also forward to the WFC? Do they know about that address and the corresponding Paypal account?
- [x] Create a new team (wfc), this will involve a database migration. For consistency, we should also update our teams.seeds.rb file.
- [x] Add members to the wfc team.
- [ ] Update [/contact](https://www.worldcubeassociation.org/contact) and [/about](https://www.worldcubeassociation.org/about) to include the WFC. I've contacted Chris Hardwick to get the relevant blurbs for the team.

**Comment by jfly** [comment]
@pedrosino, I don't have time to do this, could you take this on?

**Comment by jonatanklosko** [comment]
Actually you created the document and I added my thoughts there, I guess you mean [this thing](https://docs.google.com/document/d/1WrayKZcTCWuHJuAhBNnZDbtCnKdxckOLYYEHAnImy-U).

**Comment by jonatanklosko** [comment]
From Chris:

> About blurb:
> 
> WCA Financial Committee (WFC): Chris Hardwick (treasurer), Chris Wright, and James Molloy
> This team is responsible for managing the finances of the WCA
> 
> Contact blurb:
> 
> WCA Financial Committee (WFC)
> finance@worldcubeassociation.org
> (finances of the WCA)
> Chris Hardwick (treasurer), Chris Wright, and James Molloy

**Comment by pedrosino** [comment]
> @pedrosino, should that address also forward to the WFC? Do they know about that address and the corresponding Paypal account?

It should. I just set that up. I'll let them know about it.

**Comment by pedrosino** [comment]
First steps are done. I'm waiting for someone to confirm if I *have* to install ruby 2.4.1 in order to make migrations and PRs.

**Comment by jfly** [comment]
You can try to do stuff with an old version of ruby, but I personally wouldn't want to try it. If travis is happy, then things should be fine.

**Comment by pedrosino** [comment]
The thing is that trying bin/rails s or bin/rails g migration is failing.

I guess I'll try rmv once more and hope it goes well...
