### ISSUE TITLE
advancement_condition > next percent bug?

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1735]
There seems to be an extra % after the %{percent} in this key.

**Comment by jfly** [comment]
Are you referring to [this line](https://github.com/thewca/worldcubeassociation.org/blob/218820c650bd2c62ad892e49c46ca7aadcc4df10/WcaOnRails/config/locales/en.yml#L102)?

```yaml
    percent: "Top %{percent}% advance to round %{next_round_number}"
```

This looks fine to me, what do you expect it to be?

(I'm going to close this issue, feel free to reopen if I'm misunderstanding)

**Comment by pedrosino** [comment]
OH! Now I realise the second % is actually a percent sign. LOL
