### ISSUE TITLE
List of competitions on profile

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/worldcubeassociation.org#1740]
Right now you can only see competitions on a per event basis. You can generally use 3x3 as a metric for what competitions you've been to, but this often isn't all inclusive (FMC USA, for example).

**Comment by jfly** [comment]
Isn't this covered by the [my competitions](https://www.worldcubeassociation.org/competitions/mine) page? (closing this issue, feel free to reopen if I misunderstand).
