### ISSUE TITLE
Delegates admin page gets wrong info

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1766]
The page at https://www.worldcubeassociation.org/admin/delegates is reading the wrong "region" for delegates.
Instead of the region filled by Board/Senior (which appears at https://www.worldcubeassociation.org/delegates), it shows the "Location description" which delegates themselves fill. This causes a mess because there's no structure/format for that field

**Comment by viroulep** [comment]
Currently the `admin/delegates` page is displaying both the region filled by Board/Senior *and* the location description.
Do you think we should only display the region displayed on https://www.worldcubeassociation.org/delegates ?

**Comment by jfly** [comment]
Eep! Sorry, I didn't realize this issue exists. Please let's continue this discussion over on https://github.com/thewca/worldcubeassociation.org/issues/3493.
