### ISSUE TITLE
Add all kind of championships to profile pages

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#1797]
At the moment only World Championship podiums are displayed in the profile. Once we have all the necessary data stored in the `championships` table, we should be able to add continental/national championship podiums as well.

**Comment by jfly** [comment]
@jonatanklosko didn't mention this, but as mentioned in the [design document](eligible_country_iso2s_for_championship), this is going to be tricky to do for National Championships, where more citizenships than just the country can be eligible to win. As @Baiqiang says about the China Championships:

> We hold the first China Championship in 2015. Competitors come from China, Hong Kong, Macau and Taiwan (collectively called Greater China) could win the national title then

This may be implemented with an additional table in the database, or perhaps some special if statement in our ruby code. Whatever we do, I believe the WRC should document this on [the list of recognized countries](https://www.worldcubeassociation.org/regulations/countries/).
