### ISSUE TITLE
Check for other deprecation warnings

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1805]
We don't want to run again into something similar to https://github.com/thewca/worldcubeassociation.org/pull/1804!

I'll also write a test for it.
Assigning it to myself because it should have been part of the mentioned PR but I don't have time for it right now.

**Comment by jfly** [comment]
I manually looked through the output of `git grep "\.find(" | grep -v params | grep -v "\.js"` to try to see other calls to `.find(` that pass in an AR object instead of an id, but I did not see any.
