### ISSUE TITLE
Improve email message when changing an account's email address

### ISSUE THREAD

**Issue by jbcm627** [thewca/worldcubeassociation.org#1814]
I just changed my wca account email, and got a potentially misleading message:

> Welcome [old email address]!
> You can confirm your account email through the link below:
> Confirm my account

I guess [this template](https://github.com/thewca/worldcubeassociation.org/blob/3edc01e652db9e66356af2dcd7dd2fa518d88604/WcaOnRails/app/views/devise/mailer/confirmation_instructions.html.erb) was used, which I assume is also used for new accounts. However, a better message with the new email would be... better :)

**Comment by jfly** [comment]
I dug into this a bit. [Here's the relevant devise code for confirmable](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/confirmable.rb#L50-L51), which calls either [`send_on_create_confirmation_instructions`](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/confirmable.rb#L177-L182) or [`send_reconfirmation_instructions`](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/confirmable.rb#L122-L128), both of which call [`send_confirmation_instructions`](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/confirmable.rb#L112-L120).

I'm not sure what the right way to do this is. Perhaps override `send_on_create_confirmation_instructions` in the User model to send a different email customized for newcomers?

**Comment by LinusFresz** [comment]
Fixed in https://github.com/thewca/worldcubeassociation.org/pull/3009.
