### ISSUE TITLE
"Refund Payment" is easy to accidentally click when updating competitors' registration

### ISSUE THREAD

**Issue by yuxuibbs** [thewca/worldcubeassociation.org#1819]
Right now, the button for "Refund Payment" is yellow (btn-warning) and it's the most eye catching thing on the page. It's very easy to accidentally click "Refund Payment" (yellow button) instead of "Update Registration" (white button that blends into the page) when updating a competitor's events. 

Could we make the "Update Registration" button a color that isn't white? Maybe blue or green?

James Hildreth and I keep almost accidentally refunding competitors' registration when competitors ask us to update their registration (to change their events list). One person has accidentally gotten their registration refunded and they still have not repaid their registration fee after emailing them. 

I'm willing to make the change myself if necessary but I will need someone to walk me through some parts (pretend it's a ment1 or ment2).

**Comment by KitClement** [comment]
I would also like to add that it wouldn't hurt to add a pop-up dialog for confirmation of the refund. Even if we change the color, it's still quite easy to misclick.

**Comment by jonatanklosko** [comment]
I'm surprised to hear we don't ask for a confirmation at the moment, I will make the improvement soon!

**Comment by jonatanklosko** [comment]
@yuxuibbs @KitClement FYI, I've just deployed both changes =)
