### ISSUE TITLE
Add support for tentative events

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1821]
(The Board has asked for this, as they are getting strict about requiring that events be announced in advance.)

This actually shouldn't be too tricky to implement: a db migration, an admin UI update to put a "tentative" checkbox next to each event, and an update to the competition public page to separate the events by tentative and "for sure".

One open question would be how this affects the competition search by events feature (I'm guessing that it shouldn't affect it at all, searching for comps with 444 will include comps that are tentatively going to run 444).

**Comment by jfly** [comment]
Brandon Mikel pointed out that this is more important now that we have first class support for scheduling on the WCA website.

**Comment by AlbertoPdRF** [comment]
I already talked with @viroulep about a possible implementation of this: on the "Manage events" page, there could be a checkbox for every event that you have to check if you want the event to be tentative, and this event would be displayed differently both in the "Events" and in the "Schedule" pages.

**Comment by jfly** [comment]
Quick note tentative events are being discussed over on https://github.com/thewca/wca-regulations/issues/614. Let's try to remember to update this issue with the results of that discussion!

**Comment by AlbertoPdRF** [comment]
Tentative events will be explicitly forbidden with https://github.com/thewca/wca-documents/pull/40, so I think this issue can be closed.

**Comment by jfly** [comment]
:tada: :exclamation: I agree that we can close this.
