### ISSUE TITLE
Manage Tabs Preview doesn't load with large amounts of markdown used

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#1842]
For ABHC, neither the Scramblers nor Groups tab loads the preview. I'm assuming that this is because there is a large table. When it is purely text or there is only a small amount of markdown used it doesn't have an issue. I have to update and load the actual tab to check whether it is correct if I wanted to make an update.

**Comment by jfly** [comment]
Could you reproduce this on [staging](https://staging.worldcubeassociation.org/) and give us a link?

Either way, this is probably going to be a bug/limitation of [simplemde](https://github.com/sparksuite/simplemde-markdown-editor), but we can take a look!

**Comment by jonatanklosko** [comment]
I think I know what's going on. I see we use a GET request that probably has some length limitation on parms. I believe this should be a POST instead (actually it is my fault that we don't do so already). I will work on that once I'm back home (next Tuesday) unless someone fixes it =)
