### ISSUE TITLE
Split Person.name into name and "name in non-latin-alphabet"

### ISSUE THREAD

**Issue by timhabermaas** [thewca/worldcubeassociation.org#186]
The name column currently looks like this: `Kanneti Sae Han (คันธ์เนตี แซ่ห่าน)` That's pretty annoying to work with. You're forced to parse the string to get to the name in latin letters (like in #175).
Solution:
- Add another column containing the name in the local language (`NULL`able)
- Rake task for migrating the old data to the new format
- Fix the displayed names across the page / add a helper method to the `Person` model for concatenating the string

**Comment by jfly** [comment]
I don't think we should ever need the name in latin letters. We show the names with parens everywhere else, why should the statistics page be different?

**Comment by timhabermaas** [comment]
Well, showing them in the "Most Sub-X solves in Rubik's Cube" table would break the layout. We're just lucky that people's names are short enough right now. For all other tables it seems fine to display the extended version.

Let me turn this around, though: If we have the chance to reliably fix this, why shouldn't we? As it currently stands we can't style the different name representations differently nor can we add e.g. a line break if we want to format it differently. Do you happen to know the rationale behind putting the names into the same column (and fixing the format for the future)?

**Comment by jfly** [comment]
I don't know the history here, although I do believe @clementgallet experimented with a separate column at one point. See the introduction of `localName`: https://github.com/cubing/worldcubeassociation.org/commit/adbdb87cfd54f249525096a0f403ccb1d5bb05d0#diff-ff776dbaca12f9490c2652a6f32d497cR82, `romanName`: https://github.com/cubing/worldcubeassociation.org/commit/92ce436968ba60ae939d541e346907677ba30405#diff-533adb3961ca4823d5e3207e75b95453R70, and their removal: d9f1b41c51f2c4b89d46f805f98c55c1e4d379f2. @pochmann, @jbcm627, @SAuroux, or Ron might know the motivation behind these changes. It would also be worth sending an email to results@ to see if anyone remembers why this didn't work out, or has a case for why we should or shouldn't do it now.

**Comment by jbcm627** [comment]
I remember some discussions.. there was an issue for this over on
wca-website-php that ended up with the decision that it was more simple to
keep the names together (no effort required for no changes). There are
pros/cons either way. I don't know anything about those commits though.

**Comment by jfly** [comment]
Just read through a bunch of old emails Jim linked me to. Some potentially useful food for thought: https://www.speedsolving.com/forum/showthread.php?38247-Naming-conventions-for-WCA-cubers. No word as yet on why Clement added these separate fields and then removed them.

**Comment by denthebro** [comment]
This seems irrelevant now. Maybe close this issue?
