### ISSUE TITLE
Add # of Events column to registration tab

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#1893]
In the UK we set our prices based off of the number of events people are competing in. Unfortunately this means we have to click the Show Events tab and count manually, which humans are innately terrible at.

It'd be nice to see a column of how many events someone is registered for outside of the Show Events screen.

**Comment by jfly** [comment]
Related: #1674.

**Comment by AlbertoPdRF** [comment]
I'm labeling this issue as a good first issue!

**Comment by danieljames-dj** [comment]
I would like to take this, is anybody already working on this?

**Comment by viroulep** [comment]
I don't think so!
