### ISSUE TITLE
Switch from rails-assets-autoNumeric to yarn

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1900]
`autoNumeric` version 4 seems to have dropped jQuery and instead uses ES6 imports. We should be able to take advantage of this with our webpacker setup. I ran into this while working on #1899.

@viroulep, could you take this on sometime after #1899 gets merged up?

**Comment by viroulep** [comment]
I can probably take a look at this around next week, this is not just a simple change in where we get the library from, there are a lot of stuff to update, see [here](https://github.com/autoNumeric/autoNumeric/blob/master/doc/HowToUpgradeToV4.md).

**Comment by jfly** [comment]
No rush, get to this when you have some time. Thanks!
