### ISSUE TITLE
Implement alternative payment schemes for Stripe

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1925]
@Laura-O has asked for support for SOFORT payments. Here are some comments from her about SOFORT:

> I already mentioned some problems with pre-payments via Paypal in the report of this year's German Open. However, handling registration for the German Nationals brought me to the verge of despair. Although the instructions were quite clear (confirmed by non-cubers), many people do not read that their registration is only complete after paying the registration fee. Others pay a wrong amount of money or pay without giving their name.
This could have been prevented with a website with an integrated payment system (i.e. the WCA website), but this is currently not an option for us as Stripe only allows paying via credit card. Germans don't like using credit cards and many do not even have one, so this would probably cause even more issues. We would definitely give it a try if support for SOFORT payments was added.

Ron has also asked for IDEAL payments, there are some Stripe docs about that [here](https://stripe.com/docs/sources/ideal).

Unfortunately, implementing support for these alternative forms of payments is non trivial: it seems like some of them require us to set up a webhook for Stripe, and we have a build our own UI/UX flow to let people choose the form of payment they want.

**Comment by gregorbg** [comment]
Closely related to #3497

**Comment by saranshgrover** [comment]
Can we close this in favor of #3497? They seem to be the same thing.

**Comment by gregorbg** [comment]
Yes, I guess now that we have mentioned the issue GitHub will also show that they are related.
Closing in favor of #3497
