### ISSUE TITLE
Move delegates to separate table

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1931]
Right now we stored delegate's information on the Users table, which is not a bad practice and probably not sustainable.

Having a separate table would make it easier to record new information, assign seniors and such.

**Comment by jfly** [comment]
> which is not a bad practice

I think you mean it **is** a bad practice =)

**Comment by pedrosino** [comment]
Yeah, sorry :P

**Comment by larspetrus** [comment]
Moving existing and future delegate specific info to its own table seems like the right idea, yeah.  As in most Rails projects, our User class is awkwardly big already.

Is it currently more than `delegate_status`?

**Comment by pedrosino** [comment]
Right now we have the following columns:
delegate_status
senior_delegate_id
region
delegate_id_to_handle_wca_id_claim (?)
location_description
phone_number
notes

83 delegates have notes empty, 6 have some information, while other 106 have NULL. Not sure why :)

We currently don't store when people became delegates or were demoted in the database. That would be an interesting information to have. We could also have coordinates for where they are (those who are willing to share it, of course), so we can make a cool map.

**Comment by pedrosino** [comment]
Sorry, delegate_id_to_handle_wca_id_claim is for when users claim a WCA ID. It stores the id of the delegate they choose to validate it. The name is a little awkward :P This could also use a separate table, maybe.

**Comment by cubewhiz** [comment]
It would be helpful if the Delegates table (available in the Panel) could be sorted by Senior Delegate. It would also be helpful to see the date of appointment. Is that part of this issue or would this be separate?

**Comment by jfly** [comment]
@cubewhiz, this issue is just an internal refactoring of our code and database, @pedrosino will not be adding any new features as part of this. Adding delegate start/stop dates is an interesting problem that we attempted to tackle in the past, but decided it wasn't worth the effort vs the benefit. See #680 and #725. For the record, it's still something I personally would like to address, it just hasn't risen to the top of our priorities yet.

**Comment by pedrosino** [comment]
Once this one is ready (which I cannot make promises about), I plan to track appointment/promotion/demotion dates too.

**Comment by AlbertoPdRF** [comment]
I'm closing this one in favor of #4222.
