### ISSUE TITLE
Change e-mail subject about registration

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1938]
Suggested by Tim McMahon:

>Could the waiting list / registration e-mail please be changed to make it obvious that a competitor is on the waiting list?
>
>Currently:
>"Subject: You have registered for Australian Nationals 2017"
>
>Proposed:
>"Subject: You are on the waiting list for <competition>"

**Comment by SAuroux** [comment]
This will create more confusion than remove confusion for sure, since the common process is that someone will accept your registration soon after you registered.

Why not simply keep everything 100% accurate:

"Subject: You have filled the registration form for Australian Nationals 2017"

**Comment by Mollerz** [comment]
Would it be an option to let us customise this email? Different regions all have different registration procedures and it would be nice to be able to tell someone what the next steps are.

**Comment by pedrosino** [comment]
> Would it be an option to let us customise this email? Different regions all have different registration procedures and it would be nice to be able to tell someone what the next steps are.

This would be nice indeed.

**Comment by jfly** [comment]
For the record: customized emails get weird with translations.

**Comment by pedrosino** [comment]
I guess the idea would be customized per competition.

**Comment by Mollerz** [comment]
Yes indeed, customised per competition. I had it in my head that on the Edit page there would be the default email, and then before registration opens you may personalise the message. I assume there would be some syntax to show the waiting list numbers as well?

**Comment by jfly** [comment]
I get that this is about an email customized per competition, internationalization is per *user*, not per competition. If someone from the US and someone from Brazil register for a competition in Brazil, how would we show them an English and Portuguese message, respectively?

**Comment by pedrosino** [comment]
We don't make websites in english for brazilian comps, so they would get an email in portuguese...

**Comment by Mollerz** [comment]
What about if the default email template was used, then it can be localized per user. However if a personalized email is used for the competition, when selected the organiser would get a message notifying them that their email would be sent to everyone and would not be localized - then that is the sole message received by competitors, regardless of localization?

If I register for a competition abroad, I would expect information in that language to be honest.

**Comment by ronaldmansveld** [comment]
I agree with James here. Competition emails can be sent out in whatever the
main language for that competition is.
However, if the organisers see that there are a large number of foreign
competitors they're free to include an (English) translation on the bottom
of the email, similar to what the organisers for world's did. With a custom
email, the organisers have the freedom to do so.

Ronald

**Comment by KitClement** [comment]
Wanted to bump this back up to at least consider the change that Tim suggested. We had a case with a free competition this upcoming weekend where a competitor thought they were fully registered but were actually on the waiting list due to the competitor limit. I'd prefer something like:

"Subject: Your registration for Australian Nationals 2017 is submitted and pending approval"

This seems to cover cases where registrations may be approved very soon, but also makes it clear that it is not approved yet. I think this would fit into most registration schemes.

**Comment by KitClement** [comment]
We just had another case of a competitor's parent that saw the "You have registered for..." email and thought they were set, but did not complete payment and had their registration deleted. I'd really like us to make the simple change to what I had suggested 3 months ago in my previous reply to avoid further confusion.
