### ISSUE TITLE
Add support for partial refund of registration's fees

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1951]
Requested by @KitClement and would probably be useful to others as well.

Right now the refund request uses a charge id to refund the charge as a whole, but apparently simply adding an `amount` field would enable an arbitrary refund (see [here](https://stripe.com/docs/refunds#api)).

A few comments/idea:
 - what happens if we request a refund higher than the initial charge?
 - we could have the current button changed to a dropdown which changes the input based on what the user wants (ie: full refund would only show a button, partial refund would show button+text input).

**Comment by ToastyKen** [comment]
Any chance we could raise this in priority? We're hoping to finalize our refund policy for Nationals before we launch registration on January 9.
