### ISSUE TITLE
Map display only lists first day of comp

### ISSUE THREAD

**Issue by Randomno** [thewca/worldcubeassociation.org#1972]
When viewing comps with the Map view, it's impossible to tell how many days a competition lasts as only the first day of the competition is shown (e.g. if a comp from October 21-22, it would only say October 21). I think it would be fairly helpful to change this.

**Comment by jfly** [comment]
Good call! Here's the relevant code: https://github.com/thewca/worldcubeassociation.org/blob/f7b30fa73ab92b807da24a8b94e11c50f3b3fcde/WcaOnRails/app/helpers/competitions_helper.rb#L99.
