### ISSUE TITLE
Make it visible that a competition is a championship

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#1983]
I think it would be cool to add an information to the competition page about its championship type.
Any fancy ideas concerning the design?

**Comment by jfly** [comment]
I don't currently have any suggestions, but am very supportive of this idea! Cc-ing @lgarron and @baiqiang in case they have any thoughts.

**Comment by EvilPotato1216** [comment]
Maybe a trophy icon with the country's flag or if it's worlds, then something else.

**Comment by lgarron** [comment]
What would be the main motivation for this? The competition page is pretty crowded, and I think we need a stronger purpose than "it would be cool". The use case would also give us an idea of how clearly we mark championships, and how.

Note that many championships already have "Championship / National" in the title.
Possible examples of reasons to add an icon (although I think they are too weak as stated):

- Is it meant for competitors to notice championships they might participate in?
- Is it meant to show off how many championships we have?

Any other thoughts?

**Comment by Baiqiang** [comment]
I like this idea. Maybe a simple line like this?
![image](https://user-images.githubusercontent.com/2390434/35081711-b0c31ba8-fc50-11e7-8bd9-1f1f5a289417.png)

@lgarron 
There're 325 championships and 188 of them contains "champion" or "nation" in the name. That is ~57%.
And there some competitions have two types of champions. An icon might be confusing?

**Comment by lgarron** [comment]
> I like this idea. Maybe a simple line like this?

Ah, I assumed "competition page" meant https://www.worldcubeassociation.org/competitions

I don't see the harm in listing the championship type on a competition's individual page like  in @Baiqiang's mockup. The information is relevant, and I don't see the need to keep this as dense as the table of all competitions.

**Comment by Baiqiang** [comment]
@lgarron 
If you meant the competition index page, I fully agree with you.
Maybe we can add a filter so we can see the championships in a country/continent.

**Comment by EvilPotato1216** [comment]
We could make the the name of the competition or the its details **bold** so that people know that it's important. Maybe Nationals could be in a specific color, like red, and Continental or Worlds could be in another color. This would draw attention towards the competition.

**Comment by Laura-O** [comment]
Encoding information by making it bold/colored is not making the information easier to notice and understand.
And I can't see why these championships need to get more attention. Championships are probably the competitions that get the most attention already.

**Comment by viroulep** [comment]
I kind of like the idea of a trophy icon (next to the competition's name, on the competition's page) with some kind of popover indicating the championship type(s).

**Comment by UnsolvedCypher** [comment]
Is everyone happy with the changes in #3715, or would people still like something more added for championships?

**Comment by viroulep** [comment]
I think the PR has very much addressed this issue :)
