### ISSUE TITLE
Board members should have senior delegates

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2002]
This will likely conflict with @pedrosino's work on #1931.

Other stuff to remember:

- [x] https://www.worldcubeassociation.org/delegates needs to be updated somehow to reflect this. Should Board members show up twice on the /delegates page? Should the Board really be listed on the /delegates page? My understanding is that there is no need for a Board member to actually be a delegate.
- [ ] Verify that when a Board member confirms a competition, his senior delegate is notified.

**Comment by pedrosino** [comment]
I don't think they should appear twice in the page. This senior thing is mostly for internal organization in the competitions process.

**Comment by cubewhiz** [comment]
I think it makes more sense to list Board members under their senior delegates on the WCA Delegates page. Board members are already listed as such on the "About the WCA" page, and I think that's probably enough.

**Comment by jfly** [comment]
@pedrosino, could you work on this instead of #1931? While it would be nice to pull the delegates out into a separate table, I think it would be better to abandon that effort for now and fix this real problem.

**Comment by pedrosino** [comment]
I will try :)

**Comment by pedrosino** [comment]
Would this be the only change needed?
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L299-L308

**Comment by jfly** [comment]
Very possibly!
