### ISSUE TITLE
Move Board members to a team, rather than treating them as delegates

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2003]
This will let us store the history of our Board members, and also allow us to have Board members who are not delegates.

Related: #2002 and #1931.

**Comment by pedrosino** [comment]
This makes sense since Board members don't need to be delegates (IIRC). It would be rather simple from a database point of view, since we would only need their user_id and dates (and maybe their region).

**Comment by pedrosino** [comment]
Change the way @ board_members object is found: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/static_pages/about.html.erb#L17-L21

Change this to not select the board team (?): https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/static_pages/about.html.erb#L23-L31

Remove this: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/static_pages/delegates.html.erb#L10

Change this too: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/static_pages/contact.html.erb#L16-L28
