### ISSUE TITLE
Delete corresponding registrations when a competition is deleted

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2007]
As @viroulep suggested, we should add a `dependent: destroy` here:

https://github.com/thewca/worldcubeassociation.org/blob/c0e33e783dd47817cb2a6b3cbaff2145daca5344/WcaOnRails/app/models/competition.rb#L8

When doing this, we should also create a migration to remove all existing registrations for nonexistant competitions (we have 231 of these):

```ruby
irb(main):012:0> Registration.where('competition_id not in (select id from Competitions)').size
   (51.4ms)  SELECT COUNT(*) FROM `registrations` WHERE (competition_id not in (select id from Competitions))
=> 231
```

I'd like for @AlbertoPdRF to take this on, because it will be a great way for him to learn about database migrations. If he's too busy to work on this today, I'll find someone else to take this on.

**Comment by AlbertoPdRF** [comment]
Let's do it! :)
