### ISSUE TITLE
Give Board members the power to add/remove events for confirmed competitions

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2037]
Both Ron and Olivér have requested this.

**Comment by cubewhiz** [comment]
It is indeed annoying not being able to do this.

Just out of curiosity, can this only be done by delegates/organizers right now?
Can they do so even when the competition is confirmed?

**Comment by jfly** [comment]
Delegates and organizers are not capable of adding or removing events for confirmed competitions. The Board is capable of uncomfirming a competition, so Board members can unconfirm a competition, make changes, and then reconfirm the competition.

**Comment by jfly** [comment]
I'm pairing on this with Adam Walker right now.
