### ISSUE TITLE
Website link should have different presentation if it's the page you're already on

### ISSUE THREAD

**Issue by ToastyKen** [thewca/worldcubeassociation.org#2074]
Steps to reproduce:
1. Go to a competition page whose competition website is hosted by the WCA, e.g.:
https://www.worldcubeassociation.org/competitions/BerkeleyFall2017

Expected behavior:
Some indication that this is the official website for the competition.

Actual behavior:
2. See the Website link and think maybe the main competition site is elsewhere.
3. Click Website link.
The same page you are already on opens in a new browser tab. O_o

Suggested solutions:
a) Simply hide the website link if you're already here.
b) Display "(You are here.)" after the website link if you're already there.

Caveats: It might be non-trivial to be sure that the website is the WCA page itself if it's just a URL. Might make more sense in the code to have a simple boolean checkbox for "external_website" or "wca_hosted_website" or something.

**Comment by jfly** [comment]
> Caveats: It might be non-trivial to be sure that the website is the WCA page itself if it's just a URL. Might make more sense in the code to have a simple boolean checkbox for "external_website" or "wca_hosted_website" or something.

We actually do have this already, see [`generate_website`](https://github.com/thewca/worldcubeassociation.org/blob/a20d2f02e1513a0c5c5b26438755be9860f802be/WcaOnRails/db/structure.sql#L43).

In fact, you can see the [`def website`](https://github.com/thewca/worldcubeassociation.org/blob/a20d2f02e1513a0c5c5b26438755be9860f802be/WcaOnRails/app/models/competition.rb#L412-L414) that implements the behavior @ToastyKen doesn't like.

**Comment by SqAtx** [comment]
I was thinking about fixing this but it looks like [it has already been done](https://github.com/thewca/worldcubeassociation.org/commit/414b2c5dfea3290c67567b328f5b44d6ebaa2cd4)!

@jfly I think we can close this :)

**Comment by jfly** [comment]
Nice, thanks @pedrosino!

**Comment by AlbertoPdRF** [comment]
As this has already been fixed (as stated above,) I'm closing the issue!
