### ISSUE TITLE
Streamline associating accounts with WCA IDs for first time competitors

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#21]
One minimally invasive idea would be to have the WCA collect emails (or even better: WCA user ids) as well as birthdays, gender, name, and country. In the future, we could streamline this even more by doing competition registration on the WCA site.

**Comment by jfly** [comment]
Unfortunately, there are many barriers to the WCA to collecting more information:

- An undocumented CSV format for registrations that would need to change and cubecomps would need to understand
- The only way cubecomps exports data is via an excel
- The WCA competition JSON format would need to change

**Comment by jfly** [comment]
One idea (inspired by @SAuroux) to avoid touching all the software mentioned above:

Update `persons_finish_unfinished` (that's when we assign WCA IDs) to check for registrations for the competition we're uploading with an exact match of gender, dob, citizenship, and name. If we find such a (approved!) registration, then we can look up the corresponding user and assign their WCA ID directly.

**Comment by cubewhiz** [comment]
As more and more competitions are using the WCA site for registration, it makes a lot more sense for WCA IDs to be automatically assigned in that way.

**Comment by jfly** [comment]
@timreyn, are you still planning to work on this? If not, we have a couple of people in the pipes who might be good candidates to work on this in the next month or two.

**Comment by timreyn** [comment]
Haven't been recently, I ran into issues getting the php part of the site running on my new laptop. Go for it!

**Comment by EdHollingdale** [comment]
As I said in #3933 I think this is an important issue that will save a lot of hassle. To @jfly 's question:

> I can say with some confidence that the "Has WCA ID competed exclusively at competitions I have delegated? If yes, continue" was not usually true for me when I was a delegate. Do you feel like this is an important check to have?

The main reason I have that as a check when looking at ID claims is "am I able to view all of the relevant registration data". The equivalent question for a system would be "has the WCA ID competed exclusively at competitions using WCA registration". 

For me, 80%+ of all claims are people who have been to one competition, claiming their ID in the first two weeks immediately following that competition. I've also noticed a small bump again once registration opens for the next competition in that city/region. However I imagine this was different a few years ago when accounts etc. were first introduced.

I imagine on the back end it would be even easier to verify them - was the account claiming the ID the same used to register for the competition? Does the competitor name match? Did that WCA ID compete at that competition?

I'm excited to see what can be done in this space!

**Comment by Jambrose777** [comment]
There’s additional checks too:
Like dob, country, if the wcaid is already claimed.

**Comment by EdHollingdale** [comment]
Random sample from me: 226 requests this year. Estimating 1 minute per request to look at name, check profile, find registration, find email address, and approve that is 4 hours this year doing work some code could do - just for one delegate.

**Comment by tussosedan** [comment]
I'll try taking a look
@viroulep
