### ISSUE TITLE
Change Feet format to Average of 5

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#2118]
The WRC has decided to change the format of Feet to "Average of 5". Technically this means that we will move Feet from [9b2](https://www.worldcubeassociation.org/regulations/#9b2) to [9b1](https://www.worldcubeassociation.org/regulations/#9b1) so it has the same formats as the other events mentioned in this regulation.

**Important Disclaimer**: This is currently "only" a WRC decision. Regulation changes have to be approved by the WCA Board which didn't happen yet, so this is not official.

**Timeline:**
We did not discuss how and when this change should happen. The current plan is to change the regulations at the beginning of December. It might be reasonable to do the format change for Feet later and only announce it with the release of the new regulations.
This also depends on when the software changes are ready and how they are implemented. There will probably a short period when Mo3 Feet results are pending and Ao5 results are ready to be posted.

**Changes**
I am not able to post a complete list of necessary changes here, but some of these are:
* [x] Results posting
* [x] Rankings: the rankings don't change, but we will have a mix of Mo3/Ao5 results.
* [x] Event management page for competitions: replace Mo3 with Ao5
* [x] TNoodle: the default setting for the number of scrambles for feet has to be changed
* [ ] non-WCA score taking websites (cubecomps & cubingChina) have to support Ao5

**Comment by viroulep** [comment]
I've edited your list of changes to be check-able, even if it's not exhaustive we'll have to handle at least that.

Explicitly mentioning @Luis-J-Ianez et @Baiqiang for the last bullet.

**Comment by Luis-J-Ianez** [comment]
I'm 99.999% positive this would take from me like 1 minute updating the events table plus 5 minutes testing.

**Comment by Baiqiang** [comment]
Cubing China supports Ao5.

**Comment by viroulep** [comment]
See thewca/wca-regulations#479 and thewca/wca-regulations#299 for the related issues and discussion.

**Comment by Mollerz** [comment]
What is the timescale for this change? We want to announce a competition with two rounds of Feet for next March. Obviously the reason we are holding two rounds is due to the change to average of 5.

**Comment by Laura-O** [comment]
@Mollerz This is still not approved/decided yet, but I am quite confident that you can hold Ao5 rounds in March 2018.

**Comment by Laura-O** [comment]
The Board has approved the change.

To give an update on the timescale:
We are not ready yet with the other changes, but the remaining steps will take at least 4 weeks. We are in the week before Christmas then, which is usually quite a busy time for everyone, so January 2nd, 2018 seems like the best solution for me.
I will post an update here when we have news.

**Comment by cubewhiz** [comment]
Just as a follow-up, are all of these handled by now?

**Comment by jfly** [comment]
As far as I know, all this work is done! Please reopen if there's anything left to do (@Luis-J-Ianez can speak for cubecomps and @Baiqiang can speak for cubingchina)

**Comment by Luis-J-Ianez** [comment]
yeah yeah yeah, it's done since Jan 3 or 4 in cubecomps.
