### ISSUE TITLE
[Suggestion] Change policy of 1 comp every 26 days.

### ISSUE THREAD

**Issue by ShadowMCS** [thewca/worldcubeassociation.org#2128]
I never really saw the point of this rule. I think it should be reduced to about half the time, or just to a fixed amount of comps per month. The 200km radius is a pretty considerable amount of area, and this pretty much means only 1 comp per month per area. In addition, comps in my area (Northeast), fill up extremely quickly. If more comps were permitted this would be less of an issue.

I heard from Sam that this rule was possibly being changed, I would like to hear from someone else though if this is happening or if there is a chance of this happening.

**Comment by coder13** [comment]
Closing because of #2195
