### ISSUE TITLE
Allow users to "Follow" competitions

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#2147]
Might be nice idea to allow competitors to follow a competition, that gives you a notification for when registration opens.

Currently a competitor has to just remember when registration opens or set their own calendar event on a personal app to be notified when registration opens. Seems somewhat simple to allow people to follow a competition to be notified when this occurs?

As a sub-point. It might also be a sensible idea to give a notification/email warning for organisers and delegates of a competition a couple of hours before registration is due to open to remind them that they'll have to manage incoming registrations.

**Comment by cubewhiz** [comment]
We have this now via bookmarking.

**Comment by Mollerz** [comment]
Closed ^
