### ISSUE TITLE
Contact button on competition pages is not user-friendly

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#2153]
At the moment, in order to contact the organizer, you must click the orange envelope next to the word "Contact" on the competition site, which then opens a mailto link, which may open the email program on your computer, but on many computers it will just open a blank tab with the email and some encoded characters in the address box. I don't think this is very intuitive behavior, as 

1. It's not clear that the envelope is a link to some people
2. Opening a blank page will often lead people to believe that something isn't working, and people will not think to copy the emails from the address box. 

I would suggest that the envelope be changed to text that says "Click here to contact organizers" which would either give a list of the organizers' emails (the list would appear on the competition information page), or lead the user to a contact form so that organizers' emails aren't publicly displayed. 

As of now, the WCT still receives a large amount of emails intended for competition organizers. This is being dealt with in other ways, but I think one of the issues that needs to be addressed is the relative difficulty of extracting the organizer's email on a computer that doesn't behave well with mailto links.

**Comment by jfly** [comment]
I believe this was fixed by #2197. @UnsolvedCypher, please reopen if there is remaining work today. Also, in the future, please comment your commits with appropriated `fixes #...` notation so issues automatically get closed!

**Comment by UnsolvedCypher** [comment]
Ok, this looks good for now. And I'll be sure to do that, thanks for letting me know!
