### ISSUE TITLE
 The field scramble in Scrambles table should be extended

### ISSUE THREAD

**Issue by Baiqiang** [thewca/worldcubeassociation.org#2157]
After #1922, all scrambles of an attempt for multi-blindfolded are stored in the scramble field. Thus there're many scrambles' length over 500, which is the current max length of the field `scramble`. This means we've lost a lot of scrambles in our database.

**Comment by larspetrus** [comment]
Can the lost scrambles be recovered from backups?

**Comment by jfly** [comment]
Unfortunately this data is not in our backups =( We didn't change the size of this column at any time, we just changed the type of stuff we're trying to put into it. Fortunately, the WRT should have all the missing data in email attachments, so we should be able to get one of them to recover this data for us.

**Comment by larspetrus** [comment]
Aha, the inserts failed silently!

**Comment by jfly** [comment]
> Aha, the inserts failed silently!

Yeah :cry: :sob: :sob: Hopefully the email I just sent out explaining the whole situation makes sense.
