### ISSUE TITLE
The scramble on export doesn't contain "\n"

### ISSUE THREAD

**Issue by Baiqiang** [thewca/worldcubeassociation.org#2158]
There's only one line for all multi-blindfolded scrambles after #1922, which should contain `\n` in the export.

**Comment by Baiqiang** [comment]
@jfly Yes. For TSV file, containing `\n` will be strange. Currently the WCA website doesn't show the scrambles so we should fix this IMO. Otherwise people will be confused if the see a loooooooong scramble.

**Comment by jfly** [comment]
@Baiqiang, could you look into improving export_public to include newlines when generating the SQL dump?
