### ISSUE TITLE
Add a specific "registration-requirements" field to competitions

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#2179]
One of the changes in the new Regulations release will be to make mandatory the announcement of the requirements that a competitor has to fulfill in order to complete their registration. To do so, as suggested by @viroulep, we think that a specific field in the competition form makes sense. Additionally, this field would have to be locked once the competition is confirmed. Please, see thewca/wca-regulations#489.

**Comment by viroulep** [comment]
I've assigned this one to me, I'll make sure to give me time to tackle it this weekend.

**Comment by ToastyKen** [comment]
I think the registration requirements message should be displayed on the registration page itself, just before you pay.

(Fyi in our experience for CubingUSA Nationals 2018, despite having a How to register tab and a giant notice on the comp page, people still fail to read those.)

**Comment by ToastyKen** [comment]
I also filed issue #2478 on adding a custom refund policy message to the registration page, which may be related to this.
