### ISSUE TITLE
Rename the events according to the next release of the Regulations

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#2182]
The events on the Regulations have been renamed, so we should rename the ones on the website too:

Rubik's Cube -> 3x3x3 Cube
Rubik's Clock -> Clock

More information in thewca/wca-regulations#479.

**Comment by jfly** [comment]
(Just to be clear, I'm not at all opposed to this change, I just want to make sure we're consistent about how we handle changes to event names).

We did a whole delegate vote the last time we changed the names. I'm not saying we should do a vote again, but it does seem a little strange to first tell delegates "hey, we care what you think about even names", but then next time we say "the WRC gets to pick event names, pending approval of the Board".

Could we get an explanation of why we're making this change? All I see is https://github.com/thewca/wca-regulations/pull/479#issuecomment-345231094, which says "However, there's still "Rubik's Cube" in some places, and Rubik's Clock, which we would prefer not to have.".

I'd also like a writeup from the Board explaining why we voted on event names one time, but decided not to vote on them this time.

**Comment by SAuroux** [comment]
@jfly as far as I understand it, the WRC is not even involved in this: https://github.com/thewca/wca-regulations/pull/510

**Comment by AlbertoPdRF** [comment]
"Rubik's" is a registered trademark. We must not use it. The Board itself has decided upon this for the best of the WCA. Besides, we thought that although we voted on it recently, many people's minds may have changed in light of recent facts. Also, I think that last time we voted for the order of the events and not the name itself, although this specific topic was brought up to the discussion.

**Comment by Laura-O** [comment]
I completely agree with Jeremy's reply.
And to make it clear again: this is not a WRC decision. I learned about this in https://github.com/thewca/wca-regulations/pull/510 and was surprised as well.

**Comment by jfly** [comment]
Just did a quick search through our codebase for occurrences of the word "Rubik". Most of them are in translations, but some of them are in code that will need to change:

```
...
WcaOnRails/spec/features/competition_events_spec.rb:      accept_alert "Are you sure you want to remove all 1 round of Rubik's Cube?"
webroot/results/admin/export/template.README.txt:  Events                                     WCA events (Rubik's Cube, Megaminx, etc)
webroot/results/includes/_header.php:<meta name="keywords" content="rubik's cube,puzzles,competition,official results,statistics,WCA" />
webroot/results/includes/statistics/appearances_in_333_top_100_results.php:  "Appearances in Rubik's Cube top 100 results",
webroot/results/includes/statistics/best_podium.php:  "Best Podiums in Rubik's Cube event",
webroot/results/includes/statistics/blindfold_333_consecutive_successes.php:    "Rubik's Cube Blindfolded longest success streak",
webroot/results/includes/statistics/blindfold_333_success_rate.php:  "Rubik's Cube Blindfolded recent success rate",
webroot/results/includes/statistics/sub_x.php:  "Most Sub-X solves in Rubik's Cube",
webroot/results/index.php:    <dd>Rubik's Cube rankings, Megaminx rankings, 5x5x5 blindfolded rankings, ...</dd>
webroot/results/index.php:    <?php print externalLink('http://www.rubikscube.info/', 'Josef Jelinek'); ?>.<br />
```

**Comment by cubewhiz** [comment]
The Board will make an announcement explaining this change.

**Comment by cubewhiz** [comment]
This change has now been announced to WCA Staff and External staff via email from the WCA Board.

**Comment by jfly** [comment]
In the latest email from the Board:

```
As you may have seen in the separate email, the Board has decided to rename two events:
* Rubik's Cube has been renamed to 3x3x3 Cube
* Rubik's Clock has been renamed to Clock.

We also wish to change the order of events as follows:

3x3x3 Cube
2x2x2 Cube
4x4x4 Cube
5x5x5 Cube
6x6x6 Cube
7x7x7 Cube
3x3x3 Blindfolded
3x3x3 Fewest Moves
3x3x3 One Handed
3x3x3 With Feet
Clock
Megaminx
Pyraminx
Skewb
Square-1
4x4x4 Blindfolded
5x5x5 Blindfolded
3x3x3 Multi-Blind
```

**Comment by coder13** [comment]
Another instance that needs to be be changed: https://www.worldcubeassociation.org/results/misc/evolution/
