### ISSUE TITLE
Delegates page to include historical and current "terms"

### ISSUE THREAD

**Issue by TimMcMahon** [thewca/worldcubeassociation.org#2185]
It would make it easier for the Board to manage Senior Delegates and for Senior Delegates to manage Candidate Delegates if the Delegates page (under Panel) included historical and current terms served. The Board would be able to see when a Senior Delegate was appointed, when their term expires, and whether they've served in that role previously. This information could be used to help manage a Candidate and ensure that they're on track to being promoted to the status of a Full Delegate (i.e. conduct a review and provide feedback after a certain period of time).

It would be nice if such data could be displayed on a WCA Profile (e.g. a former delegate who volunteered in that role for five years). The role, start date and end date could be listed.

**Comment by SAuroux** [comment]
This seems to be part of https://github.com/thewca/worldcubeassociation.org/issues/680

**Comment by cubewhiz** [comment]
This is also related to #1931

**Comment by cubewhiz** [comment]
I think that this information is not just useful, but instead necessary. Candidate Delegates may only be promoted after they have delegated at least 3 competitions AND served for at least one year. However, there is no place to look up when a delegate was appointed. In most cases, the Senior Delegate can look up the appointment date from emails, but when a Senior Delegate is replaced and did not nominate the existing candidates himself, this is not possible.

**Comment by cubewhiz** [comment]
Yes, that is a fair statement.

**Comment by AlbertoPdRF** [comment]
I'm closing this one in favor of #4222.
