### ISSUE TITLE
Add a field for registration information

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#2188]
We currently have tabs, and the following texts at the registration page: 
> Please check the information about registration to find out if you need to do something else, like paying a registration fee. 

> Please check competition's information for instruction about how to pay

(not sure if this is always shown)

> Your registration is pending. For approval, you may need to pay a registration fee. Check the competition website for details. 

But I think it would be valuable to have a custom field for additional information. This could be more useful (and less confusing) than the generic message above.

Related: #2051

**Comment by cubewhiz** [comment]
Wasn't this taken care of?

**Comment by jfly** [comment]
Yup! @viroulep took care of this in https://github.com/thewca/worldcubeassociation.org/pull/2183. Good catch, @cubewhiz!
