### ISSUE TITLE
Provide the community with a way to share statistics

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#219]
Right now, there's no good way for members of our community to share interesting stats. Lots of people have local copies of the wca database, but after you post something, it's just a matter of time until it grows out of date. See the [Odd WCA stats thread on speedsolving](https://www.speedsolving.com/forum/threads/odd-wca-stats-stats-request-thread.26121/).

If we could come up with a good general solution to this problem, then we could get rid of our misc statistics page, which would be a great simplification.

There's a neat product called mode analytics, which @nanma80 has played around with here: https://github.com/nanma80/mode-wca. However, Mode's api has a long standing bug that prevents us from easily uploading a database export to them. I've talked to their support team, and they don't seem to be prioritizing fixing it.

After some searching, it looks like [redash](https://github.com/getredash/redash) is an open source project that sounds similar to mode. I'd definitely like to play around with it.

**Comment by pingskills** [comment]
@jfly is this something we are still considering?

**Comment by jfly** [comment]
Kind of. Mode's api has a long standing bug that prevents us from easily uploading a database export to them. I've talked to their support team, and they don't seem to be prioritizing fixing it.

I do think the community would benefit from some mode-like website that lets you easily link directly to interesting queries. Its something I personally am very interested in working on, but I don't know needs to be an official wca project. It might make more sense as a community site.

**Comment by jfly** [comment]
After some searching, it looks like [redash](https://github.com/getredash/redash) is an open source project that we could spin up ourselves if we want.

**Comment by pochmann** [comment]
What do you mean with getting rid of our misc statistics page would be a great simplification?

**Comment by jfly** [comment]
The misc statistics page is rather expensive to generate. Simply caching the page isn't good enough, as it takes several minutes to generate the page the first time someone visits it. The current PHP implementation and our [attempted rails port](https://github.com/thewca/worldcubeassociation.org/pull/175#issuecomment-218896242) require some sort of background page generation that can do this page generation offline. If we ever move to a world with multiple application servers, this will mean all of our application servers will be periodically doing the same work, or we'll have to build even more infrastructure have a background worker store these generated stats in the database.

If we could reimplement the existing statistics in a separate service designed specifically for stats (I'm thinking redash), then we could just delete the existing stats page, which would make our lives a little easier, and would provide the community with an easy way to see up to date statistics provided by entities other than the WCA.

**Comment by kinch2002** [comment]
I'm only good with the stats themselves... Totally lost with all the different services and ways of genarating/displaying them. I'd be happy with the idea of many people being able to contribute new stats with code for them, but perhaps we need some sort of moderation of what is submitted.

**Comment by larspetrus** [comment]
I don't know anything about any stats page, I just want to mention that with multiple rails servers, you typically set up a shared cache using `memcached` or `Redis`.

**Comment by jfly** [comment]
Closing this issue. I think something like @jonatanklosko's approach in [wca_statistics](https://github.com/jonatanklosko/wca_statistics) is a very clever, and cheaper solution to this problem.
