### ISSUE TITLE
Extract manual statistics computation into a job

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#2207]
This should be called from an application job, without the `>/dev/null 2>&1 &` part.
https://github.com/thewca/worldcubeassociation.org/blob/966f5b0afc5bc543d65de43abfb38ea6cd5dde88/WcaOnRails/app/controllers/admin_controller.rb#L102

If someone does #305 before this one, it would likely be closed.

**Comment by gregorbg** [comment]
Closing in favor of https://github.com/thewca/statistics
