### ISSUE TITLE
Only allow one person to upload results at a time

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#224]
Right now, people can start uploading results for a competition simultaneously, which can result in a mess.

It would be cool if people first had to grab a lock before they can upload results. I feel like this would go nicely with #223.

**Comment by gregorbg** [comment]
@thewca/wrt Is this issue still relevant to your workflow?

**Comment by Jambrose777** [comment]
Yes, but I don’t see any good solutions. Essentially only 1 person can work on results at any given time. We combat this by sending an email right before we start working on results to the team and then once they are posted there’s another email.

**Comment by danieljames-dj** [comment]
Now after the migration from PHP, we can upload results in parallel without any issues. Thanks to @gregorbg.
