### ISSUE TITLE
Competitions with results show up in Upcoming Competitions

### ISSUE THREAD

**Issue by sam596** [thewca/worldcubeassociation.org#2240]
Browsing upcoming competitions and it seems that if a comp was held today, finished, and the results were uploaded all on the same day, the competition shows up in upcoming competitions, rather than in progress or past competitions.

[Gyazo Screenshot Example](https://gyazo.com/5dfcc0abb05253f3adf34d458e91588e). Also, not isolated since I noticed it on an Indian comp yesterday also.

**Comment by jfly** [comment]
I agree, a competition should be declared over if it's results are uploaded. Relevant code here:

https://github.com/thewca/worldcubeassociation.org/blob/a77968d3b161072003098fe67a7881c00ae260c3/WcaOnRails/app/models/competition.rb#L663-L665

**Comment by coder13** [comment]
Does this need to be closed?

**Comment by pedrosino** [comment]
Yes, it was fixed on #2361
