### ISSUE TITLE
Total actual competitor count on General Info page

### ISSUE THREAD

**Issue by ToastyKen** [thewca/worldcubeassociation.org#2248]
After a competition's results have been posted, please include total competitor count on the General Info page.

This number is useful for planning purposes.

Right now there's no easy way to get this number. You can look up 3x3 Round 1 count, but not EVERYONE always competes in that, so this number is not necessarily correct.  Trying to count unique competitors manually across different events is onerous.

**Comment by jfly** [comment]
Good idea! Could you include a screenshot mocking up what you'd like this to look like?

**Comment by ToastyKen** [comment]
Sure: Mockup:
![num competitors](https://user-images.githubusercontent.com/2019068/33623033-89807b5e-d9a4-11e7-9d1d-ab2d3b47273b.png)

It should only appear AFTER results have been submitted.

Btw, example: CubingUSA Nationals 2017 had 633 3x3 R1 competitors, but, according to the [stats page](https://www.worldcubeassociation.org/results/statistics.php#most_persons), it actually had 656 total competitors.  The stats page only contains the top 10 competitions of all time though, so I can't use it to look up competitor count at smaller comps.

**Comment by ToastyKen** [comment]
It'd also maybe be okay if it only appeared on the By Persons page?

**Comment by DanielEgdal** [comment]
What I do currently is going to the "By person" page, then I use the search function (ctrl+F) and search "WCA profile", then it gives the total count, as it says how many times it says "WCA profile" and every competitor has that.

**Comment by jfly** [comment]
@pedrosino, always assign issues to yourself before you start working on them!

**Comment by pedrosino** [comment]
@ToastyKen just to let you know that this was done.

Let us know if you think the design could be improved somehow.

**Comment by ToastyKen** [comment]
Thanks! That's perfect!
