### ISSUE TITLE
Move the WCA workbook assistant to the web

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#225]
This would go nicely with #223. Some reasons why this makes sense:
- "Don't repeat yourself" - right now, we have some checks that are implemented only in the WA, some checks that are only in our results admin scripts, and some checks that are implemented in both places. Any time a new event or a new format is added, both the WCA website and the WA need to be updated.
- The WA is pretty good at checking things, but is super annoying to use when anything needs to be fixed. We could try to build a better tool on the WCA website.
- We could also move more checks from our results scripts out to the delegates.

**Comment by pedrosino** [comment]
Why is this closed? You only fixed the footer thing...

**Comment by jfly** [comment]
It should not be closed! I had a typo in the commit which accidentally closed this one.

**Comment by AlbertoPdRF** [comment]
Actually, what's the plan with the Workbook Assistant? I mean, on a world with WCA Live in place it doesn't really make sense to still use something like it, right? Should the checks that the Work Assistant performs be added to the work @viroulep is doing as a part of https://github.com/thewca/worldcubeassociation.org/projects/4?

**Comment by jfly** [comment]
The plan is still to get rid of the Workbook Assistant (WA) in favor of having data entry tools (such as a the not-yet-existent WCA Live) upload results directly to the WCA website.

All the checks that the WA does that the WCA website doesn't do should get added to https://github.com/thewca/worldcubeassociation.org/projects/4.

Another critical thing the WA does is that it has a pretty fancy UI for merging scrambles and associating them with actual rounds that happened. We'd need to build some sort of UI on the WCA website for uploading/slicing/dicing scrambles before we can get rid of the WA.

**Comment by AlbertoPdRF** [comment]
> All the checks that the WA does that the WCA website doesn't do should get added to https://github.com/thewca/worldcubeassociation.org/projects/4.

Sounds good! Do we perhaps have a list of those somewhere?

> Another critical thing the WA does is that it has a pretty fancy UI for merging scrambles and associating them with actual rounds that happened. We'd need to build some sort of UI on the WCA website for uploading/slicing/dicing scrambles before we can get rid of the WA.

Yes, that will indeed be necessary.

**Comment by jfly** [comment]
> Do we perhaps have a list of those somewhere?

Unfortunately, not one that I know of =( I think someone would have to read through the WA and compare it to what the WCA website does. Alternatively, it's possible that someone like @viroulep or @SAuroux might just happen to know off the top of their heads?

**Comment by SAuroux** [comment]
Off the top of my head I'd say that with all of Philippe's recent work, there might not actually be any check left that is only done by the WA. @viroulep what would you say?

**Comment by viroulep** [comment]
Yep, I think what we need now is some kind of UI (that goes well into the expected WCA Live to website workflow) to be able to attach scrambles to a specific round, and generate the appropriate json :)

**Comment by AlbertoPdRF** [comment]
Wow, that's great news then! Based on this last comment, I'm adding the `design` label to the issue. Once WCA Live is in place we can revisit this!

(CC'ing @jonatanklosko, as he's the one developing WCA Live.)

**Comment by viroulep** [comment]
I tried to implement a drop-in replacement for the WA here: https://viroulep.github.io/scrambles-matcher/
(https://github.com/viroulep/scrambles-matcher for the source code)

People interested in testing it should feel free to do so :)

**Comment by gregorbg** [comment]
Closing this as we very actively use `scrambles-matcher` now.
Great work, Philippe!
