### ISSUE TITLE
Use < or > for cutoffs instead of <= and >= respectively

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#2260]
Regulations state

> 9g2) Whether a competitor proceeds to next phase of a Combined round, must be decided by ranking (best x competitors) or by result (all competitors with a best result **under** x) of the first phase.

And the potential ambiguity has been fixed [here](https://github.com/thewca/wca-regulations/pull/467/files).

The change should apply both to the code and the WCIF document.

**Comment by jfly** [comment]
I've updated the [WCIF doc](https://docs.google.com/document/d/1hnzAZizTH0XyGkSYe-PxFL5xpKVWl_cvSdTzlT_kAs8/edit#) to reflect this.

I'll send in a PR shortly fixing our code accordingly.
