### ISSUE TITLE
import_persons.php basically only uses names when importing data

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2286]
See the where condition here: https://github.com/thewca/worldcubeassociation.org/blob/abc382dbcd338bd83c599b1640a8e005ac042305/webroot/results/admin/scripts/import_persons.php#L33-L34

It's only matching on `name`, `countryId`, and is restricting the search to people who competed in this particular competition.

We run `import_persons.php` *after* running `persons_finish_unfinished.php`, so it should be possible to match on WCA ID here. In order for this to be possible, we'll need to update `persons_finish_unfinished` to update the `InboxPersons` as well as the `Persons` and `Results` tables here:

https://github.com/thewca/worldcubeassociation.org/blob/abc382dbcd338bd83c599b1640a8e005ac042305/webroot/results/admin/persons_finish_unfinished_ACTION.php#L58-L62

**Comment by jfly** [comment]
@Baiqiang, do you have any time to look into this? Jacob Ambrose just ran into this.

I think this should be a fairly straightforward change to the two files mentioned above. It's just a bit annoying to test, unfortunately =(

**Comment by Baiqiang** [comment]
I'm going to fix this now.

**Comment by Jambrose777** [comment]
to close the loop, All persons data affected by this issue has already been corrected in November(6-7 cases), by them claiming their ids (speculation of some of the 80 cases that this could have happened in), or when uploading results (2 comps in Jan).

~~~sql
SELECT temp.competitionId, temp.personName, GROUP_CONCAT(temp.personId SEPARATOR ' '), COUNT(*) as num
FROM (
    SELECT r.competitionId, r.Personname, r.personId, p.day, p.month, p.year
    FROM Results r
    INNER JOIN Persons p ON r.personId = p.id
    GROUP BY r.competitionId, r.personId
) temp
GROUP BY temp.competitionID, temp.personName, temp.day, temp.month, temp.year
Having num > 1
~~~
