### ISSUE TITLE
Number of competitions in person profile API

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#2312]
At the moment the person profile API provides a lot of useful information, but it would be nice to have the number of competitions people attended.

It would be helpful for planning purposes, especially for filtering experienced competitors.

Thank you! :heart_eyes:

Edit: and also useful for generating neat nametags.

**Comment by Laura-O** [comment]
This was implemented in #2400 so I am closing this issue. Thanks @jonatanklosko 😄

**Comment by jfly** [comment]
Thanks for staying on top of stuff, @Laura-O!
