### ISSUE TITLE
Need a version of Rails's excerpt and highlight that handle transliteration

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#238]
To work around this, we're [calling `transliterate` before using `excerpt`](https://github.com/jfly/worldcubeassociation.org/blob/85dbbeae67287b16a1af653feb7062f4a32aae7d/WcaOnRails/app/helpers/application_helper.rb#L41-L54), which has an unfortunate side effect of removing information. Note how it works well in the selectize dropdown, but not on the results underneath:

![2015-11-22_731x322_kaladin](https://cloud.githubusercontent.com/assets/277474/11326179/4bac6a18-9117-11e5-9eea-538a2335eb15.png)

Also note how Düsseldorf _is_ getting highlighted here, but we've lost its umlaut:

![2015-11-23_1317x534_kaladin](https://cloud.githubusercontent.com/assets/277474/11344872/8ae136d0-91c8-11e5-9893-6612c3a694e5.png)

**Comment by jfly** [comment]
I've reached out to a group of people who have more Rails experience than I [here](https://groups.google.com/forum/#!topic/wca-software/5Byofl7XnVE). Waiting to see what they say.

**Comment by jfly** [comment]
I also created a StackOverflow question here: http://stackoverflow.com/questions/34166987/rails-gem-for-transliterate-highlight. No responses =(

**Comment by oyyq99999** [comment]
There's a workaround to resolve the question mark issue, but I'm not sure what **side effects** it would take.
We can do the transliterate process by ourselves with regexp replace as following

```ruby
"Düsseldorf".mb_chars.normalize(:kd).gsub(/[\p{Mn}]/,'').to_s
```

Which produces `Dusseldorf`. And Obviously It won't destroy non-latin characters.

The `\p{Mn}` means non-spacing marks, here's quote from the unicode specification

>Mn = Mark, nonspacing
>Mc = Mark, spacing combining
>Me = Mark, enclosing

You can use `\p{M}` to indicate all of them, which is **NOT** recommended

**Comment by jfly** [comment]
Ahh, neat trick! I'm no expert on character encodings, but from experimentation, it looks like this would behave more nicely than our current solution using transliterate:

```
irb(main):005:0> "Yu Nakajima (中島悠)".mb_chars.normalize(:kd).gsub(/[\p{Mn}]/,'').to_s
=> "Yu Nakajima (中島悠)"
irb(main):006:0> "Düsseldorf".mb_chars.normalize(:kd).gsub(/[\p{Mn}]/,'').to_s
=> "Dusseldorf"
```

That all said, it would be nice of we wrote our own versions of `highlight` and `excerpt` that handle this for us.

**Comment by oyyq99999** [comment]
Hi, I came up with another idea and it solves the whole issue but it's a little bit tricky and possibly buggy. I wrote a demo in python [here](https://gist.github.com/oyyq99999/0998ff3e3cd7100f0ca56b09de7da9ab)

The process:
 1.  Separate the original string to pieces by transliterate result and then;
 2. Transliterate each piece and concat the results (which solves the question mark issue), and then;
 3. Highlight it as usual and finally;
 4. Do the reverse of the transliteration on the highlighted string by comparing with the original one and try re-transliterate non-matching parts to match, then replace the matching result by the original substring.

Known issues:
 1. If a transliterate result is separated by the highlighting tags, the highlight result would be slightly off the search pattern, the separated substr would come after the tag(s) separating them. Here's an example. Considering the original string is `ænd` and the matching pattern is `end`, the highlighted result will be `a<strong>end</strong>`. When in the reverse transliterate process, the `a` and `e` need to get together to get back to `æ`, with the code in the demo this will result in `<strong>ænd</strong>`. If the original one was `ndæ` and we are highlighting `nda`, it would result in `<strong>nd</strong>æ`.

**Comment by jfly** [comment]
Thanks for the ideas, @oyyq99999! It would appear that there is no community solution to this problem. I've gone ahead and created https://github.com/jfly/translighterate so we can make our own gem. I'd really appreciate it if you could take a look over there and let me know what you think. I used your transliterate trick from before.
