### ISSUE TITLE
Changing nationality makes SOR 0 instead of highest rank +1

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#2399]
... for events with no result for the new country.

See: https://www.worldcubeassociation.org/results/misc/sum_of_ranks/?regionId=Finland&average=Average

**Comment by jfly** [comment]
Hey @Baiqiang, do you have any time to look into this? Thanks!

**Comment by bugybunny** [comment]
Screenshot for later to show how it looks as Reto has almost completed every average/mean.

![image](https://user-images.githubusercontent.com/5311105/40848531-ce06eda6-65bf-11e8-905f-2cf032b2a36c.png)

**Comment by Mollerz** [comment]
Updated screenshot: 
![image](https://user-images.githubusercontent.com/7948340/71727559-90c08500-2e32-11ea-8ebc-2b0e0300753e.png)

**Comment by Baiqiang** [comment]
@jfly sorry for the very late reply. i will look into this asap.
