### ISSUE TITLE
Registration Flow Improvement

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#2413]
It's been mentioned many times that the waiting list isn't actually a waiting list, people get confused etc. All organisers are well aware of the system. However, having recently opened registration for a couple of competitions, the amount of confusion from outside of the WCA is really really high. I've lost count about how many times I've had to explain the system, as a result I have spent some time collating my thoughts on how to improve it. 

Let me start off by saying the current system is actually pretty good, but there needs to be a lot of refining. This is important because it needs to be _intuitive to someone who has never seen the system before._ I'm going to break down this issue into the major sections and some possible implementation ideas.

## **Waiting List**
This is the biggest problem as it is not the correct name for the list and therefore is immediately confusing to basically everyone. It currently implies that the registration process is over, and they now have to wait. So many competitors have missed out due to this, we often get emails asking "It says I'm 12 on the waiting list, do I just have to wait now?" and then we have to tell them that there are plenty of places available and that they can pay and get confirmed.

- I propose that we first rename the current "Waiting List" to "Pending Registrations List". The initial email sent out to competitors should state that the email is being received since the registration has been accepted by the _system_, and there may be more steps to complete the registration, and to check the competition website.
- The competitor limit is coded in for every single competition, and there are specific regulations related to the competitor limit now. I suggest that we split the "Accepted Registrations" section into two. Pressing accept should do what it did before, however, if the "Accepted Registrations" list is full per the competitor limit, then anyone accepted past this point is added to the "Waiting List". Hooray, correct nomenclature! The competitor would then receive the first email that they currently receive for registering, stating that it has been accepted _by the organisers_, and that they are now on the "Waiting List" with the position as well.

We also often have people message us when they are actually on the waiting list asking what position they are. "Where am I on the waiting list now?" they ask.
- I propose that once this new waiting list is added, on the "Register" page, there is a box that specifically states that they are _on_ the waiting list, and what their position is as well. This would save so many emails. There could potentially be a checkbox that they could tick called "Waiting List Update Emails" which would inform them every time they move position on the waiting list.

## **Payments**
Sending people to PayPal or an external website to pay is a horrendous pain. It also means we have to do the registration confirmations ourselves and cannot let our organisers do it as we don't want to give them access to our PayPal.

- Please let us have more customisation of the payment system! Allowing us to set the amount either per individual event, or by group of events, would be so great. For example, in the UK we generally do some sort of tiered system so that people that register for 1-4 events pay £10, 5-8 events pay £15, and then 12+ events pay £20. It would also be nice for some competitions to charge individually per event, for example at Spanish Championships it was a €10 flat fee, and then €1 for each event registered for. Having different ways to customise the payments would be wonderful and means we can keep everything central within the WCA.

## **Events**
The +Show Events button is a nice addition to help speed up the page when not required, however is it possible to add a short column to show a count of events for each competitor that isn't linked to this? As mentioned above, we often use tiers, and some places do payment amounts based off of number of events. Having a number to look at instead of counting would be really useful.

## **Comments**
The comments are useful, however I feel like there should be a second level of comments that can only be seen by organisers. For example if someone has been approved without payment, we can add an organiser comment that can't be edited or seen by the competitor to communicate to other organisers who might be wondering about the situation.

That's all I have for now, but I _really_ think that the waiting list needs to be amended as a high priority. The others are definitely much lower priority and may not even be required with the initial improvements to the system.

**Comment by jfly** [comment]
Thanks for the great feedback, @Mollerz. The currently situation definitely needs some polish, and it's embarrassing how long it has been going on. Unfortunately, most active members of the WST are pretty busy with other (also high priority) projects right now, and we haven't had anyone available to focus on registration stuff for a while.

What's the simplest possible thing we can do right now to make things better? Could we solve a lot of the pain by updating the text of the first email we send competitors? Here's the current text of that email. Do you have a suggested rewrite of that email that you think would improve things?

![image](https://user-images.githubusercontent.com/277474/34818715-8127c424-f670-11e7-8af6-1d479572506c.png)

**Comment by Mollerz** [comment]
Thanks for the comment @jfly - I understand a lot of the team are working on other projects but I thought I would get this out here so there is some direction to aim for. As for the email, maybe something like the following:

"You just registered for <comp>.

Your registration has been accepted by the system and is pending approval from the organisation team.

Please note that registrations are not automatically approved so please be patient if you have not been accepted straight away. There may be more registration steps to follow before your registration will be approved. To see the approval criteria please visit the competition website. You can also check the status of your registration <here>.

Regards,
<Orga team>"

This still has most of the same information in it, but doesn't hint towards a waiting list which seems to be the biggest problem. And it also states that there may be further steps to follow, such as an external payment required. How does this sound?

**Comment by jfly** [comment]
I like this! @jonatanklosko, do you have any time to make this quick change to the registration email?

**Comment by BiscuitCubed** [comment]
Changing the name of the wait list is easily the most important thing at the moment. I like the email draft that @Mollerz proposed, but I think that "Your registration has been accepted by the system" is both redundant and confusing. I think that removing that bit, reordered a couple of the sentences and added a bit about lack of payment being the most common reason for delayed payment makes it slightly more useful and clear, though mollerz suggestion is certainly better than what we had. This is my proposed changes. 

"You just registered for <comp>.

Your registration is pending approval from the organisation team.

There may be more registration steps to follow before your registration will be approved. To see the approval criteria please visit the competition website. The most common reason for delayed approval is needing to pay a registration fee. Please note that registrations are not automatically approved so please be patient if you have not been accepted straight away. You can also check the status of your registration <here>.

Regards,
<Orga team>"

**Comment by Mollerz** [comment]
@BiscuitCubed That phrase actually got changed thankfully, I didn't like it either. See the merged request here: https://github.com/thewca/worldcubeassociation.org/pull/2430

**Comment by ToastyKen** [comment]
Only the email has been updated, right? If you log in and look at your status, I think it still says you're on a waiting list?  How hard would it be to have that page say "Pending Approval/Waiting List" at least or something as an interim measure?

**Comment by shelchang** [comment]
Changing the wording of the email isn't enough because people don't read instructions. The list is still called a "Waiting List", and people see it and think they're on a waiting list because registration is full.

**Comment by UnsolvedCypher** [comment]
What about also including registration requirements in the email? We now have these filled out for competitions, so it might be helpful to remind people that they need to pay/send an email/whatever for their registration to be accepted.

**Comment by shelchang** [comment]
I think changing the wording of the email is already something that has been done, but it is an incomplete solution to the problem, which is that the pending approvals list is called a waiting list even though the majority of the time that's not what it is.

**Comment by Mollerz** [comment]
@UnsolvedCypher The email does now suggest that there may be more steps to complete for the registration, such as making a payment.

I think we just need to wait for the main contributors to finish on their current high priority projects and then switch to working on this one. We have a system in place, it's not ideal but it does work.

**Comment by Mollerz** [comment]
The registration requirements section has recently been updated and the schedule builder has also been completed. Might be a good time to work on this if someone has the time. 

Adding related issues: 
https://github.com/thewca/worldcubeassociation.org/issues/2444
https://github.com/thewca/worldcubeassociation.org/issues/2123
https://github.com/thewca/worldcubeassociation.org/issues/1674

**Comment by Mollerz** [comment]
The registration for our first competition since the pandemic has happened and filled up very quickly. Within 3 days we had around 70 competitors on the waiting list. I forgot how awful dealing with a waiting list is for both organisers and competitors. We had to deal with tons of emails asking where people are on the waiting list (which also results in us having to **count** as well since the current list isn't numbered) and they have to email in to find out as there is no way to know otherwise. We even had a couple of competitors exclaiming that we've "stolen" their money as they were not on the competitor list but the payment had been completed.

I cannot stress enough how beneficial rejigging the page with a proper waiting list of paid and accepted competitors, which is also visible to the public and numerated so that any individual can easily check where they are on the waiting list.

**Comment by coder13** [comment]
> The registration for our first competition since the pandemic has happened and filled up very quickly. Within 3 days we had around 70 competitors on the waiting list. I forgot how awful dealing with a waiting list is for both organisers and competitors. We had to deal with tons of emails asking where people are on the waiting list (which also results in us having to **count** as well since the current list isn't numbered) and they have to email in to find out as there is no way to know otherwise. We even had a couple of competitors exclaiming that we've "stolen" their money as they were not on the competitor list but the payment had been completed.
> 
> I cannot stress enough how beneficial rejigging the page with a proper waiting list of paid and accepted competitors, which is also visible to the public and numerated so that any individual can easily check where they are on the waiting list.

I agree that this process could still be improved. Perhaps an "official" waiting list could be implemented that allows you to queue people into it manually once the registration requirements have been met. Then a user's registration would be something like "on waiting list" from "pending".

**Comment by dunkOnIT** [comment]
RIP Mollerz you would have loved the new registration system
