### ISSUE TITLE
Custom deleted registration message for CubingUSA Nationals 2018 (or in general)

### ISSUE THREAD

**Issue by ToastyKen** [thewca/worldcubeassociation.org#2429]
Currently, when we delete a registration,the competitor gets a canned set of possible reasons for deletion.

For CubingUSA Nationals 2018, the main reason is because they don't qualify in any events, but this is not one of the canned reasons, leading to confusion.

In priority order:

(a) Highest priority: Could we add a message in the deleted registration message for CubingUSA Nationals 2018 saying, "Your registration may have been deleted because you don't have a qualifying time. Please see the registration page for information about qualification requirements."

(b) More general solution:  Allow competitions to add a custom deleted registration message in general.

(c) Lower priority: Allow organizers to set an optional custom message per deletion to indicate that exact reason for deleting that particular registration.

The current message:

> Your registration for CubingUSA Nationals 2018 has been deleted. Possible causes are:
> 
> You did not submit all the required details
> You asked for withdrawal
> You didn't meet the registration criteria (for example, paying the registration fee in advance)
> The competitor limit has been reached and there are no more spots available
> You registered twice or more times
> If you think this is an error, please reply to this email.

**Comment by pedrosino** [comment]
Hi @ToastyKen 

Maybe @jfly has a better answer, but I think having a custom message *only for you* is probably as hard as allowing everyone to have a custom message.

One easy solution would be to add "You did not meet the qualification criteria" to the existing message. Would that help?

**Comment by jfly** [comment]
Isn't this what "You didn't meet the registration criteria" is trying to tell you? How about adding something to the parenthetical, something like:

> You didn't meet the registration criteria (for example, paying the registration fee in advance or you did not meet the qualifying times for events)

**Comment by ToastyKen** [comment]
We'd be perfectly happy with Jeremy's suggestion. :)
