### ISSUE TITLE
Edit reports and keep it structured

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#2435]
The WQAC asked for permission to unlock reports for editing, but we find this problematic for a couple reasons:

- people (delegates) must somehow be informed that the report was changed. If it's posted again, the date of submission would be the new one, giving the false impression that the report was sent much later than it actually was;
- sending a new email could cause confusion like "wait, I think I read this report already..."
- the best solution now seems to be just replying on the report thread at the google group

One thing that could work is to send a new e-mail to the existing thread (how? maybe just Re: [automatic generated title]) telling what was changed, diffchecker/github style. Not sure how feasible this is and if we should actually spend time doing it.
Or just say the report was updated, and you can see the new version here. Then on the website mark the edited parts.

**Comment by Laura-O** [comment]
I agree that this is problematic for the reasons you mentioned.
Furthermore, we should make sure that edits do not destroy references. We occasionally use the numbering to refer to incidents in other reports. When delegates are allowed to change all parts of the reports, this could result in two differently numbered lists.

**Comment by gregorbg** [comment]
I am not sure whether this feature is still relevant.
@thewca/wqac Please provide your input soon, to figure out whether we should discuss this further.

**Comment by DanielEgdal** [comment]
Personally I don't see much of a reason for unlocking posted reports for editing in the way described above. 
I can only see two scenarios where this would be necessary:

1. The report is sent prematurely (potentially entirely empty)
2. The report is mashed together with the template (has happened around 5 times I think) making it very difficult to read.

For the first scenario, the WRT has in the past just cleared the input, which works well.

For the second point, this is pretty annoying and should in some cases be fixed. I think the WRT already has access to edit these reports. If we saw the reason to fix these, I think WQAC could coordinate such a fix with the WRT and the Delegate who made the mashed report. But realistically, the best would simply be to have the way we display the template be more intuitive and avoid this occurring in the first place.

**Comment by saranshgrover** [comment]
Thanks for your input - I am closing given we don't have anything else to do here.
