### ISSUE TITLE
Allow People To Be Notified Of Competitions

### ISSUE THREAD

**Issue by EvilPotato1216** [thewca/worldcubeassociation.org#2440]
We could work on a feature where the user could choose their locations and a radius around them. When a competition is announced near them, they will get an email. With the current website, users have to continuously check the website for new competitions. This would be a neat feature which could help the users of the website.

**Comment by jfly** [comment]
Thanks for the suggestion, @EvilPotato1216! We actually already have an issue for this, see #114.
