### ISSUE TITLE
Can't authorize the application

### ISSUE THREAD

**Issue by drfb** [thewca/worldcubeassociation.org#2442]
I was able to use it a year ago but now I can't authorize the app anymore.

My app ID: 6751d55b9b1cc5710fed3a47d9c69eca871af9b0f83ec5388a5b0cebe1f93037
Sample request:
![wca-oauth-error](https://user-images.githubusercontent.com/12893349/34913752-cdb0e24e-f940-11e7-8f7d-77fb76910ebf.png)

The webview is not working either.

**Comment by drfb** [comment]
My bad, I'm doing it wrong. I got it working now.

**Comment by jfly** [comment]
Sweet! For future readers, it's always nice if you tell us what you figured out that you were doing wrong =)
