### ISSUE TITLE
Change birthdate field on sign up page to make it clear that we're asking for *your* birthdate, not the delegate's birthdate

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2453]
We just received a pretty amusing email about our sign up page:

> I already have competed in a competition and have a WCA ID but it is telling me to sign up, so I am not sure if I am doing anything wrong. When I say that I have already participated in a competition, it asks me to put the name of the delegate, which I think was <<<<<, and their birthdate. The problem is that I don’t know the delegates birthdate. Not sure what to do here, I appreciate the help.

## Currently

![image](https://user-images.githubusercontent.com/277474/35025378-06b6fa28-fafa-11e7-9479-aeb46bc9dd82.png)

## Proposal

Move the birthdate field up, and change the label to say "Your Birthdate"

![image](https://user-images.githubusercontent.com/277474/35025407-333acfe8-fafa-11e7-8b50-e0dfacebeea3.png)

**Comment by EvilPotato1216** [comment]
Yeah, that's a good solution.

**Comment by pedrosino** [comment]
LGTM

**Comment by subhankar-panda** [comment]
Has this been patched yet? I was looking to get started with contributing to the codebase

**Comment by jfly** [comment]
This would be a great first issue for you, Subhankar! Let us know if you have any questions about how to get started!

**Comment by jfly** [comment]
Are you still working on this, Subhankar? If not, Adam Walker is going to start working on this this weekend.

**Comment by Rubiks-boy** [comment]
I will begin working on it.

**Comment by subhankar-panda** [comment]
Whoops, been away for a couple of weeks, sorry for not replying!
