### ISSUE TITLE
A Mobile App for WCA

### ISSUE THREAD

**Issue by EvilPotato1216** [thewca/worldcubeassociation.org#2456]
This is just an idea but should we start working on an application of WCA for mobile instead of the user using a specific browser? This could help many people. Obviously, we're not going to make the app offline cause that'll stock up the servers. Any thoughts?

**Comment by jfly** [comment]
Thanks for the suggestion, @EvilPotato1216. We are not planning to make a mobile application at this time. If there is stuff that does not work well on mobile, let's focus on improving the responsiveness of the website.
