### ISSUE TITLE
Schedule Management

### ISSUE THREAD

**Issue by tobipch** [thewca/worldcubeassociation.org#2457]
IMHO I find the current state of how to put in schedules in WCA-Tabs very unsatisfying.
Basically there are three ways to implement schedules nowadays.

### Markdown
To me this just doesn't look user-friendly. I find it to be a lot easier to get and remember information of a nicely formated schedule ([Hotel Cube 18 Schedule](https://www.worldcubeassociation.org/competitions/HotelCube2018#3536-zeitplan-schedule)) than from a markdown schedule ([SC Mental Breakdown 18 Schedule](https://www.worldcubeassociation.org/competitions/SwisscubingMentalBreakdown2018#3259-schedule)).

### Import Pictures
This gives you the opportunity to implement a nicely formatted and clear schedule. You have all the freedom design-wise but here the problem is adapting the schedule. Everytime you have some changes in the schedule you have to upload the picture again and copy the link in it. Of course you can say "then just upload the schedule when it's finished" but even then you may see something you have to adapt only after you uploaded it.

### External Websites
No problems with keeping it up-to-date and you can design it however you want. But the goal is to have everything in one place, so even with these advantages I'd always prefer Tabs.

Maybe I'm missing something out or I'm just too lazy, don't hesitate to tell me.

I think with an improvement on this topic a lot more competitions would use Tabs and keep everything central and easy for competitors.

**Comment by cubewhiz** [comment]
This issue already exists (#278).

I would love to see this integrated with the feature in which organizers/delegates select the Events for the competition (schedule should match selected events & rounds). One of the issues would be dealing with the tentative events (#1821).

**Comment by jfly** [comment]
Yes, please let's continue this discussion over on #278.
