### ISSUE TITLE
Single times not appearing in competition psych sheets

### ISSUE THREAD

**Issue by Gomorritas** [thewca/worldcubeassociation.org#2468]
Title says it all. I don't see the single  in psych sheets anymore, for example here: [https://www.worldcubeassociation.org/competitions/CubeduKorea2018/registrations/psych-sheet/444](https://www.worldcubeassociation.org/competitions/CubeduKorea2018/registrations/psych-sheet/444)

**Comment by jonatanklosko** [comment]
Hey @Gomorritas, it's related to the problem of auxiliary data computation we encountered today. I've just fixed it and it should look good now!
