### ISSUE TITLE
Allow adding custom refund policy message on the registration page

### ISSUE THREAD

**Issue by ToastyKen** [thewca/worldcubeassociation.org#2478]
Currently, the registration page just lists the price of registration.

Many competitions do not allow refunds.  CubingUSA Nationals only allows 50% refunds.

This is important information that needs to be present on the registration page so warn people properly.

(Related to issue #2179 on displaying registration requirements, since that should also be on the registration page.)

**Comment by viroulep** [comment]
I feel like this kind of information would definitely belong to the "registration requirements" field.
If so I've implemented showing this field over in #2183.

**Comment by viroulep** [comment]
@thewca/wrc-team what do you think?
The registration requirements field is frozen post-announcement, I feel like any refund policy should be announced beforehand too.

**Comment by Laura-O** [comment]
Yep, I agree.
I think it's reasonable to give all important information regarding the registration in one place, so the refund options should be in the requirements field as well.
