### ISSUE TITLE
Gender choice on the website

### ISSUE THREAD

**Issue by gagou9** [thewca/worldcubeassociation.org#248]
We still have only Male and Female, which is quite ridiculous to me!
For your information a few countries officially recognize a third gender. In france the first "neutral gender" exists now for about a week!!!! That's really important to accept this and show we support that cause. I do support this cause very strongly ;)
So my asking is : would it be possible to have 4 choices when choosing gender : Male, Female, Neutral, unspecified
That would really really be awesome.

**Comment by jfly** [comment]
We don't ask for a gender when creating an account, is this for when you register for a competition?

Would Male, Female, Other be good enough? Or do people want to identify as Neutral rather than Other? I'm so not qualified to make this sort of a decision...

**Comment by Laura-O** [comment]
I think differentiating between male, female and other is good enough.
You will probably never find a solution that suits everyone. Once you add the option neutral, people will also ask for none and then transgender, non-binary, FTM, MTF, etc.
I don't want to criticize anyone for identifying with one of the aforementioned, but as the majority of competitors defines themselves as female or male, I think "other" for everything else is good.

**Comment by gagou9** [comment]
I would prefer "unspecified" than "other", as "other" is a bit pejorative to me.

**Comment by jfly** [comment]
This is fixed by #1542. Internally we store "o", but we render it as "" (empty string).
