### ISSUE TITLE
Two new columns in _nearby_competitions_table.html.erb for the board

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/worldcubeassociation.org#2482]
The quality of the requested competitions could be better checked if the board (or any team announcing in the future) could have two new columns in this table: "limit" and "number of competitors" (the latter only if results are posted).

**Comment by jfly** [comment]
@pedrosino, could you take this on? It should be a fairly straightforward project =)

**Comment by pedrosino** [comment]
I'll try.
