### ISSUE TITLE
Rewording the hints under "Remarks" in the competition forms

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/worldcubeassociation.org#2489]
While a new form is implemented with specific checkboxes for the article Z, can we please have this text...

https://github.com/thewca/worldcubeassociation.org/blob/6f8ce63120916716b8d750841df8c8625f69b6b8/WcaOnRails/config/locales/en.yml#L366

...reworded to:
Some additional information you want to pass on to the board. For example, elaborate your reasons if this competition is requested less than four weeks away, or if you are requesting the application of Article Z (***LINK***). Please fill this out in English!

**Comment by AlbertoPdRF** [comment]
Please, capitalize Board :P

**Comment by jfly** [comment]
@pedrosino, don't forget to assign issues to yourself!
