### ISSUE TITLE
Records API endpoint

### ISSUE THREAD

**Issue by ronaldmansveld** [thewca/worldcubeassociation.org#2491]
Currently the API does not have an endpoint to get all the current WR/CR/NRs.

This endpoint will be a requisite for the WCA-Live program, and can be useful for other interested parties as well.

Pinging @coder13 as he may have additional information for this ticket.

**Comment by jfly** [comment]
It's worth noting somewhere that wca-live is going to want to show PBs as well, right? I suppose you guys can get that information from the WCIF that originally comes in from the WCA? Also curious how you plan to handle the case where the world record is broken twice at a competition, or perhaps it is broken at two simultaneous competitions.

**Comment by ronaldmansveld** [comment]
It's mostly to replicate the current functionality in cubecomps, where if someone enters a time that would result in WR/CR/NR, we warn the person doing data-entry, so they can double-check what they've entered.

Good point about the PB's, I know remember that CC does indeed show those on the result pages. I don't think that should be part of this endpoint though, I think it's better to include PB's with the person.

Breaking the world record is not something I'm too worried by. After all, a WR/CR/NR isn't recognised until after the results have been uploaded and checked by the results committee. A WR/CR/NR indication would therefor only mean 'faster than the current official *R' not that it will be recognized as the new *R, as there are too many factors outside of our control that may influence that.

**Comment by jonatanklosko** [comment]
@jfly JFTR we already have an endpoint to get personal bests ([example](https://www.worldcubeassociation.org/api/v0/persons/2005FLEI01)), apart from WCIF data.
