### ISSUE TITLE
Remove Admin View tab for organizers

### ISSUE THREAD

**Issue by Rubiks-boy** [thewca/worldcubeassociation.org#2514]
Small tweak, but within the competition's edit page, hide Admin View as a option for organizers. Currently, if organizers click this link, they are redirected to the home page with an error message, which could be confusing for new organizers.

This:
![screen shot 2018-01-31 at 8 47 36 am](https://user-images.githubusercontent.com/24919355/35635619-a53ce58a-0663-11e8-95ab-b1b9c3de1897.png)

Into this:
![screen shot 2018-01-31 at 8 48 09 am](https://user-images.githubusercontent.com/24919355/35635636-ae4a40aa-0663-11e8-8ef4-35c16732ec93.png)

**Comment by jfly** [comment]
Thanks for the report, @Rubiks-boy! We tend not to notice this stuff, because all members of the WST are in fact site admins, so we see that link and can click on it. Would you be up for sending in a quick PR that hides this link for people who can't click on it?

**Comment by Rubiks-boy** [comment]
Yep. I'll work on it this weekend.

**Comment by jfly** [comment]
Great! I've assigned the issue to you, because apparently github lets me do that now, even though you're not a member of our organization =)

**Comment by jfly** [comment]
Thanks @Rubiks-boy! Feel free to reach out to me if you're looking for ideas for anything else to work on =)
