### ISSUE TITLE
WCA Facebook style "groups" for rankings

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#256]
CubingUSA does state rankings, but CubingUSA's website is going away ~~soon~~ eventually.

In order to do #114, we're going to need to ask people where they live, so that does open the door for the WCA website showing all cubers in a region, and ranking them.

@jbcm627, would something super generic like a yelp style pan and zoom with an automatically updated ranking list alongside seem like an acceptable solution? I like this because it doesn't have anything US specific in it.

**Comment by jbcm627** [comment]
That is an option, and sounds interesting. Rather than just use "visible" competitors on a map, we could do something using Google's reverse geocoding:
https://developers.google.com/maps/documentation/geocoding/intro#reverse-place-id
...and maybe allow filtering by all the "political"-type address components.

**Comment by jfly** [comment]
Just to explain @jbcm627's idea, he's suggesting hitting the google api whenever someone adds or changes their address, and stashing their "political" type address components in our database. This would let use easily find all people in a region, and we wouldn't even need to do any distance type queries!

**Comment by jfly** [comment]
Copy pasting from an email with the Board:

@jfly:
> What I think could make sense is to add a concept of "groups" to the WCA website. This would be kind of like Facebook groups. For a given group, you could look at the rankings of all it's members. This would be useful for cube clubs, as well as states, provinces, and other arbitrary regions. We wouldn't bother with history of records or anything like that, so this should be completely invisible to the Results Team.
>
> If we like this idea, I would propose adding this feature soon, and seeing how/if it gets used over the next 6 months. For example, I'd be curious to see if we end up with multiple groups for the same region.

Ron:
> I like the concept of groups mentioned by Jeremy. I would have the following requirements:
- WCA decides which groups we accept
- each group must have one or more administrators
- each administrator must first be approved for that group by WCA
- each group can be moderated by administrator or managed by user, to decide who can become member of the group
- each group might have requirements, either explicit (group 'female cubers in FL' must be female) or informal ('cubers in FL')
- some groups might be exclusive: e.g. you cannot be member of 'cubers in FL' and cubers in CA'' 

> In other words: if we make groups, we should think this out carefully and implement it well.

In addition to providing a way to do state rankings, this is needed because the WCA is probably going to stop recognizing certain territories as countries, and it would be nice to give those communities an opportunity to view rankings.

**Comment by jfly** [comment]
> this is needed because the WCA is probably going to stop recognizing certain territories as countries, and it would be nice to give those communities an opportunity to view rankings.

This already happened, see https://www.worldcubeassociation.org/posts/changes-of-countries-recognized-by-the-wca. I no longer believe it makes sense to implement something like this on the WCA website. I could see it as a good 3rd party website, however.
