### ISSUE TITLE
Please make "Registration requirements" mandatory

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/worldcubeassociation.org#2576]
The regulations force this field to be in our competitions forms, but at this moment competitions can be saved and confirmed with this field blank. At least if the WCA is the competition website, this field must be filled up. And overall, it wouldn't harm if this key piece of information is requested always.

**Comment by jfly** [comment]
@Rubiks-boy, this is a really important, hopefully easy issue to address. Do you think you could take it on? Thanks!

**Comment by Rubiks-boy** [comment]
I’d be happy to work on it. I’m relatively busy this week, but if I don’t get a chance to work on it sooner, I’ll do it this coming weekend.

**Comment by cubewhiz** [comment]
Sort of related, I'd actually prefer if the text from this field was not included in the email sent to the board. It makes the email we receive very cluttered.

**Comment by Luis-J-Ianez** [comment]
+1 to @cubewhiz

**Comment by jfly** [comment]
@Rubiks-boy, when you get around to working on this issue, feel free to either include @cubewhiz's request in your PR, or feel free to make a separate issue for it and address it in a separate PR. Whatever you believe is easiest.

**Comment by Luis-J-Ianez** [comment]
Every time a delegate submits a form without this section, it's a hassle for the Board. Can we please have this done?

**Comment by Rubiks-boy** [comment]
I apologize that I have been so flaky on this. I thought my schedule would die down and I would have a chance to work on this, but it does not appear that I will any time over the next month. Please assign this issue to someone else to work on. I am sorry for any inconvenience I have caused.

**Comment by pedrosino** [comment]
There's #2774 which would become obsolete with this.

**Comment by jfly** [comment]
@pedrosino, I'm going to close this issue since you've merged up https://github.com/thewca/worldcubeassociation.org/pull/2774.

**Comment by pedrosino** [comment]
I'm not entirely sure, but I think @Luis-J-Ianez meant that delegates shouldn't be able to confirm the competition if the field is empty.

**Comment by jfly** [comment]
Ohhhh, sorry, I misread your original comment.
