### ISSUE TITLE
Registration Requirements formatting is broken on the competition main page

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#2589]
See here: https://www.worldcubeassociation.org/competitions/HastingsOpen2018

As you can see the formatting on the right hand side of the page is different to the formatting that should be showing when you are on the Register page.

**Comment by viroulep** [comment]
argh sorry!

**Comment by viroulep** [comment]
@Mollerz: not related to the issue, but I noticed that some of your links are broken in the registration requirements :s

**Comment by Mollerz** [comment]
Yes because I haven't updated them fully :)
