### ISSUE TITLE
4BLD ranking for South America doesn't work

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#2603]
https://www.worldcubeassociation.org/results/events.php?eventId=444bf&regionId=_South%2BAmerica&years=&show=100%2BPersons&single=Single

It just appears blank here. Brazil and World work, though.

**Comment by Baiqiang** [comment]
This has occurred several times. The reason is someone was visiting this page while we're computing aux data. And it cached an empty results. It's fixed now.
