### ISSUE TITLE
Allow senior delegates to see unannounced competitions

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#2604]
Senior delegates receive an email when a competition is confirmed. But we can't easily follow (or participate in) the email thread, since we can't see the competition details until it's announced.

It would be helpful if the senior delegate for a competition's delegate could see /competitions/:competitionId.

**Comment by pedrosino** [comment]
Hi @timreyn 
I was looking for the source and found this:
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L644
which uses
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L464

So, should we include the senior in can_manage_competitiom? or just give the ability to view the competition before it's announced?

**Comment by timreyn** [comment]
Senior delegate in can_manage_competition sounds fine to me.

**Comment by jfly** [comment]
I agree with @timreyn. That should be simplest and easiest!
