### ISSUE TITLE
Change bootstrap's warning color?

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#263]
Don't know if this is possible, but the warning "yellow" looks very dull and bad to me. I'd like something more...I don't know...colored?

@lgarron @jfly

**Comment by jfly** [comment]
Could you include a screenshot? @FatBoyXPC probably has an opinion on this. He's our resident bootstrap expert.

**Comment by FatBoyXPC** [comment]
If you are going to change that color, I propose doing it by overriding the
variable. Please not, I do not mean to override it in variables.less, but
to redefine the variable with the new value (in some file that we always
call upon when compiling the LESS). We never want to modify core bootstrap
files as a simple update could take away all of our modification.

**Comment by pedrosino** [comment]
![2015-12-09-183747_1077x528_scrot](https://cloud.githubusercontent.com/assets/1881933/11698062/0162613e-9ea4-11e5-98ec-b30cd8d08911.png)

Example

**Comment by lgarron** [comment]
> very dull and bad to me

Could you explain this in more detail? "Dull" (not interesting/noticeable) and "bad" (noticeable) sound very different to me.

**Comment by pedrosino** [comment]
More like dull. It's bad in the sense that it is too discrete.

**Comment by lgarron** [comment]
> too discrete

I'm assuming you meant "discreet".
I think it's fine as-is, but then again I don't use the tool. Do you have a link I could test?

**Comment by pedrosino** [comment]
worldcubeassociation.org/competitions/new

Try creating a comp which has another one within 500km and 90 days.

**Comment by jfly** [comment]
I also think it looks fine as is, but am open to being convinced.

**Comment by AlbertoPdRF** [comment]
As there wasn't a consensus 4 years ago and it doesn't seem like this has raised too much interest, I'm closing it!
