### ISSUE TITLE
Broken link on user edit form

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#2649]
1) find a person with no DOB in the database (e.g. 2017EDMO02 = https://www.worldcubeassociation.org/users/78769/edit)
2) try to set their WCA ID and birthdate
3) save

The error on the subsequent page has a `<a>` tag that doesn't get linkified:

> The form contains one error:
>WCA ID We do not have a birthdate recorded for this WCA ID. Please contact the WCA Results Team using `<a href="/contact/dob">this dedicated form</a>`.

![dob_form](https://user-images.githubusercontent.com/3885929/36952052-bfb4390c-1fd8-11e8-8b4e-666c45cfa91e.png)

**Comment by jfly** [comment]
OH WAIT SORRY I MISREAD EVERYTHING. I thought you were asking about the error message. Instead you were talking about the broken link, sorry. Reopening this issue and marking it as a bug.

**Comment by jfly** [comment]
I'm having trouble reproducing this. From code inspection, I can't see any reason why this link wouldn't render as a proper link. In your steps to reproduce, you say "find a person with no DOB in the database". Do you mean a user with no DOB, or a person with no DOB (https://github.com/thewca/worldcubeassociation.org/wiki/Why-do-we-have-both-%22users%22-and-%22persons%22%3F)?

Are you able to reproduce this on staging?

**Comment by timreyn** [comment]
I mean a person with no DOB.

Reproduced by assigning https://staging.worldcubeassociation.org/users/29569/edit?section=general to 2009BOBO01.

The source of the page says:
> `We do not have a birthdate recorded for this WCA ID. Please contact the WCA Results Team using &lt;a href=&quot;/contact/dob&quot;&gt;this dedicated form&lt;/a&gt;`
