### ISSUE TITLE
Add Spectator Information Field

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#2668]
The WCT gets a lot of inquiries asking about whether they can spectate at a given competition, and unfortunately this is something organizers often omit from their websites. It would be great to add a field similar to the registration requirements field that would say what the requirements are for spectating (whether you need to register, buy a ticket, etc).

**Comment by jfly** [comment]
I think this should be implemented a little differently than registration requirements. Most competitions allow all spectators, so I think we should have a checkbox (or maybe a dropdown?) to select if there are any restrictions, and if there are, then a textbox appears that you must fill in with any restrictions. On the backend, this would still be just a single null-able text field.

**Comment by fangorntheent** [comment]
That makes more sense than just having a text field.

**Comment by AlbertoPdRF** [comment]
Should this issue be closed now that we have the automated registration requirements and the `extra_registration_requirements` field?

**Comment by UnsolvedCypher** [comment]
Yes, closing :smiley:
