### ISSUE TITLE
Improve Contact Form

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#2690]
The WCT has developed a mockup for the WCA website contact form.
It aims to have users select the competition they're referring to so their email can be directed to the organizer, not the WCT, and allow tagging of incoming messages to the WST. The biggest addition would be the competition selection box, which would contain competitions in the future and in the past 2 months. If a competition is selected, the email should go to all of the organizers and the competition Delegate.

WST, would this be possible to implement? Do you have any suggestions for this design?

![contactform](https://user-images.githubusercontent.com/3170853/37477150-4d15537c-284d-11e8-9075-66a310574595.png)

**Comment by jfly** [comment]
I've created https://docs.google.com/spreadsheets/d/1ModhMvi0mZh-VrOkoIGTgm98UgEED6nFkKylNb9hVS8/edit#gid=0 to discuss what exactly should happen when these various options are selected.
