### ISSUE TITLE
Show registration open/close on competition main page

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#2699]
From Ron:
>"Hi software team!
>
>Here a change request via mail. Not sure how I could do this on Github.
>
>Recently we received some complaints from competitors who were not aware that registration was closing for a competition. You can only see this information on the registration page of the competition, and then well hidden at the bottom of the page. Example:  https://www.worldcubeassociation.org/competitions/AlbanianOpen2018/register
>
>I think the closing date for registration for a competition should be on the Info page of the competition. You can also include the opening date if that date is in the future.
>
>Thanks for considering."

**Comment by jfly** [comment]
I think we've already got too much stuff on the info page, but I do agree that this is more important that some of the information we already have on our info page, so it should also go there. @viroulep, could you take care of this? Thanks!
