### ISSUE TITLE
FAQ CubingUSA Competition Guide deadlink

### ISSUE THREAD

**Issue by TimMcMahon** [thewca/worldcubeassociation.org#2710]
The CubingUSA Competition Guide Link on https://www.worldcubeassociation.org/faq returns a HTTP 404 error.

Page cannot be found:
http://www.cubingusa.com/ctutorial.php

**Comment by cubewhiz** [comment]
We transitioned from cubingusa.com to cubingusa.org and that guide was not (and won't be) published on the new site.

A separate guide is being created, but perhaps we can remove that reference for now.
