### ISSUE TITLE
Broken email address on competition page

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#2713]
https://www.worldcubeassociation.org/competitions/NacionalesUruguayasUCHI2018

The first organizer's email address has two _'s in it.  These are being formatted as <em></em> and breaking the email address link.

**Comment by jfly** [comment]
@timreyn, I don't see anything wrong right now. Presumably something has been changed on the page you linked to?

I *imagine* that at one point, the contact field was set to something like `[testing_one_two](mailto:test_one_two@example.com)`, which does render as:

![image](https://user-images.githubusercontent.com/277474/38459919-05d4ff92-3a65-11e8-9bce-d5791c020a24.png)

This is just the way markdown works, though, and if you want the underscores to show up, you have to escape them like this: `[testing\_one\_two](mailto:test_one_two@example.com)`, which correctly renders as:

![image](https://user-images.githubusercontent.com/277474/38459928-24e6da9a-3a65-11e8-99b3-c469dc9cc1ec.png)

I'm going to close this bug, but I'm happy to continue a discussion about what you think we should do here.
