### ISSUE TITLE
What all data does api provide ? 

### ISSUE THREAD

**Issue by mzfr** [thewca/worldcubeassociation.org#2714]
I was willing to know what all kind of information be extracted from API.
I have tried and following link works
* [delegates](https://www.worldcubeassociation.org/api/v0/delegates)
* [competitions](https://www.worldcubeassociation.org/api/v0/competitions)
* [person](https://www.worldcubeassociation.org/api/v0/persons)
* `https://www.worldcubeassociation.org/api/v0/<wca_id>`
Is there anything else ?

**Comment by jfly** [comment]
Hi @mzrf. We do not currently have documentation of our, API, but you can figure out what we support by looking at our routes file and then the corresponding code: https://github.com/thewca/worldcubeassociation.org/blob/727f065b508bcc9f7089faf84be761d719e0bffc/WcaOnRails/config/routes.rb#L156-L179.

**Comment by mzfr** [comment]
@jfly Thank you for this.
just want to know are you guying planning to write doc any time soon ?

**Comment by jfly** [comment]
We have no plans of writing a doc while our API stays on v0.

**Comment by mzfr** [comment]
@jfly  ok thanks for the help
