### ISSUE TITLE
Give delegates some automated options for dealing with WCA ID claims they can't approve

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#273]
(@sauroux suggested this in an email thread)

> How about giving delegates the opportunity to reject a request? A delegate could be able to select between two different options:
> - "I don't know you, please select a different delegate for your claim request."
> - "I am not able to verify your identitty, please contact me seperately to prove this is really you."
>   As a result, the claim request should be cancelled and the person that sent the claim request will get the according notification.

I think these are great ideas, but probably wouldn't fit into our (already very crammed) edit a user page. The WCA ID approval page should probably be pulled out into a new page.

For the record, everything you describe is currently possible, it just requires a bit more work than clicking. To reject a request, you just clear the "unconfirmed WCA id" field. If you want to send the claimer a message, you should have received an email with the request, you can just reply to that email with whatever message you want. That's what I've been doing with requests from people I don't remember, and I think it's a good opportunity to put in a message like "send me photo id, or we can do this in person at the upcoming XYZ competition".

**Comment by AlbertoPdRF** [comment]
I'm closing this one in favor of #21.
