### ISSUE TITLE
Change Nearby competitions criteria

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#2739]
When editing a competition, nearby competitions are currently shown with a criteria of "within 90 days and 500 km." The WCA Board uses this list of competitions to determine if there are any proximity collisions, but we also use it to determine if the competitor limit is appropriate.

I propose to change the criteria to instead be "within 180 days and 250 km." Doing so should better allow us to determine if a competitor limit is appropriate for the competition.

**Comment by pedrosino** [comment]
Hi all,

this is fixed here:
https://github.com/thewca/worldcubeassociation.org/pull/2757

Please test if it works as expected.


Pedro

**Comment by cubewhiz** [comment]
I just checked it out. Looks like it works!
