### ISSUE TITLE
Sum of ranks of Europe does not display any content

### ISSUE THREAD

**Issue by YTCuber** [thewca/worldcubeassociation.org#2871]
When I go to 
[here](
https://www.worldcubeassociation.org/results/misc/sum_of_ranks/?regionId=_Europe&average=Average), the only thing that gets displayed is this:
![grafik](https://user-images.githubusercontent.com/20047592/40002892-3cf4e042-5792-11e8-8258-0e7bece4f5ce.png). Other countries or continents work (I tested some of them, but not all). It looks like the rank information does not even get included in the source code, so this is most likely browser-independent.

**Comment by jonatanklosko** [comment]
Hey, the link you provided works just fine for me. It might've been a temporary issue resulting from new data being computed. I'm going to close this for now =)
