### ISSUE TITLE
Misleading registration period information & dynamic tweak

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#2873]
I'm currently creating a new competition and noticed that the Registration Period is shown as follows:

`Online registration will be open from Friday, November 23, 2018, 7:00 PM GMT to Friday, January 4, 2019, 11:59 PM GMT. Other forms of registration may be allowed (such as registration at the door). Be sure to read through all the competition details to find out.`

Those last two sentences in there could be horribly misleading. In the UK we never have registration at the door and a lot of competitions only allow prepayments. Someone might read that and think "oh they have registration at the door" and leave it at that, even though it says to read through all the competition detail. I believe this section should only say the registration period sentence showing when it opens and when it closes. On the WCA page the Registration Requirements are written in their entirety _immediately below_. So I believe these sentences are almost completely pointless. So instead this should just show:

`Online registration will be open from Friday, November 23, 2018, 7:00 PM GMT to Friday, January 4, 2019, 11:59 PM GMT.`

And on the topic of this, would it be possible to tweak it to show tense? Like the following if registration is open:

`Online registration opened Friday, November 23, 2018, 7:00 PM GMT and will close Friday, January 4, 2019, 11:59PM GMT.`

And for closed:

`Online registration opened Friday, November 23, 2018, 7:00 PM GMT and closed Friday, January 4, 2019, 11:59PM GMT.`

**Comment by larspetrus** [comment]
I'd phrase it `will close` just so the two sentences don't look almost identical.

**Comment by jfly** [comment]
This parenthetical was added in https://github.com/thewca/worldcubeassociation.org/pull/2799 by @viroulep at the request of @Luis-J-Ianez. @Mollerz, could you work with @Luis-J-Ianez to come up with a final wording for this, and we can make the change?

Thanks!

**Comment by jfly** [comment]
Ok, sounds like @Luis-J-Ianez is on board with this change! @Mollerz, could you update your original post to include an example of what we should say if registration has not yet opened?

**Comment by Mollerz** [comment]
@jfly Updated

**Comment by jfly** [comment]
Thanks, @Mollerz!

@pedrosino, do you have any time to take this on?
