### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#289]
I'm creating this issue not as a guarantee that this will ever happen, but just to have a place to record how many times that has been requested, and why.
1. [@Luis-J-Ianez asked](https://groups.google.com/d/msg/wca-software/mMl3jZ6Pgfg/qj74lF84DQAJ) about translating [`/faq`](https://www.worldcubeassociation.org/faq)
   
   > Would it be crazy having those FAQ translated into several languages?  For the sake of consistency they should be available in English only, like the rest of the website.  On the other hand, when we felt that the comprehension of the texts was important, we translated the Regulations.  So, maybe having the FAQ translated is not a bad idea. And they are quite short. What do you think? 
   - Luis also informed us that it's virtually impossible for non English speakers to register for competitions. See #317.
2. Ilya asked about translating the entire website:
   
   > WCA have been thought anything about multilanguage website before? Sometimes we have registrations where competitor chooses 3x3 blindfolded but he wants to compete in only 3x3. He doesn't understand Rubik's Cube is 3x3 and he chooses something where is "3x3". Also sometimes competitors ask me "Will be our language on the website some day?"
3. [Cendy asked](https://groups.google.com/d/msg/wca-admin/Bt5-ZcoB0eQ/vsyZDEgfDwAJ) about translating the `/register` page:
   
   > anyway, I've been thinking lately to also translate the registration page instead of translating the regulation only. 
   > it would help the people who want to register but didn't know English language. :)
4. [Raúl asked](https://groups.google.com/d/msg/wca-admin/Bt5-ZcoB0eQ/wLPjyDQDEAAJ)
   
   > I also think translations are a vital part of this (somehow related to my last request) and I'm willing to help with spanish translations or coding.
5. @gagou9 created an #246 for this.

**Comment by jfly** [comment]
[Raúl](https://www.worldcubeassociation.org/results/p.php?i=2013MORA02) expressed some interest to me.

**Comment by viroulep** [comment]
I mentioned it in one of my reports a while ago, several french people has been asking for having a translated version of the registration process, because they did not speak english and did the whole registration by sometimes guessing what to put where.

**Comment by jfly** [comment]
I think we can close this issue :smile: This is definitely happening.
