### ISSUE TITLE
Email forwarding without Google DNS

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#29]
We currently rely upon Dreamhost to handle email forwarding for our domain: https://panel.dreamhost.com/index.cgi?tree=mail.addresses&. If we want to move away from dreamhost, we'll have to figure out a replacement for this.

**Comment by jfly** [comment]
I talked to @gagou9 about this, and his suggestion was to set up exim4, and use it set up email aliases in `/etc/aliases`. With a local SMTP server, we could also get rid of mandrill.

**Comment by jfly** [comment]
This is currently being handled by google domains webui (I configured it by hand). I'm moving the DNS registration from my personal gmail account to a new wca.software@gmail.com account.

**Comment by ronaldmansveld** [comment]
Is this still a relevant ticket? Or has all of this been taken care of by using google domains and/or google groups?

**Comment by jfly** [comment]
Yeah, we don't need this anymore! Status quo is ok for now, but I do expect that we're going to make a lot of changes once we switch to google apps. That's a whole different thing, though.
