### ISSUE TITLE
Change your password form should be clear about the fact that it's asking for your *new* password, not your current password

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2914]
Here's what the page currently looks like:

![image](https://user-images.githubusercontent.com/277474/40805963-ccbabab8-64d4-11e8-865f-6b989fa694eb.png)

The field labelled "Password" is kind of ambiguous. It sounds like it should be your current password, but the only reason you're here is because you don't know your current password! We should change this label to "New password".

I feel less strongly about if we should change the label of the second field from "Password confirmation" to something like "New password confirmation" or even something like "Please confirm your new password".

**Comment by alokpant** [comment]
@jfly Took a look at what Google does, they use:

New Password and Re-enter New Password

![image](https://user-images.githubusercontent.com/6135761/40810029-cfa3d2ac-652c-11e8-8cbc-2a07cbba8a61.png)

Can I pick this issue up?

**Comment by jfly** [comment]
Yes, please! Thank you @alokpant!

**Comment by alokpant** [comment]
@jfly Looks like same label is used across Sign Up and Password Change page. So for now I have just change: Password Confirmation to Re-enter Password. 

If it is need to change: Re-enter Password to **Re-enter new password** in Password Change page only, then I will add two labels in translation file and use them.

**Comment by jfly** [comment]
> Looks like same label is used across Sign Up and Password Change page

We should definitely change that, then!

**Comment by alokpant** [comment]
@jfly Thank you for merging my PR.

**Comment by jfly** [comment]
Fixed in https://github.com/thewca/worldcubeassociation.org/pull/2916
