### ISSUE TITLE
SOR table headers should have a more distinguishable look

### ISSUE THREAD

**Issue by bugybunny** [thewca/worldcubeassociation.org#2915]
Right now the table headers are really hard to see.
![image](https://user-images.githubusercontent.com/5311105/40847794-a023f372-65bd-11e8-90a2-f090903c51ac.png)

Another color would be better. Even better would be a scrolling table header. I can’t seem to find an example right now but I’m sure you know what I mean. As soon as the user starts scrolling, the header always stay at the top of the screen.

I guess https://github.com/thewca/worldcubeassociation.org/blob/3edc01e652db9e66356af2dcd7dd2fa518d88604/webroot/results/misc/sum_of_ranks/index.php#L82 is responsible for the style of the header. I have no idea for something better visible so I’ll leave it to someone else.

**Comment by Mollerz** [comment]
If I recall the stats page is kind of on hold for now. We've requested some stats to add and upgrade the look etc. but there are some other more important things to be doing first :)

**Comment by AlbertoPdRF** [comment]
I'll add this issue to https://github.com/thewca/worldcubeassociation.org/milestone/2 to make sure we handle it properly when porting this part of the code!

**Comment by gregorbg** [comment]
Closing this issue in favor of https://github.com/thewca/statistics
