### ISSUE TITLE
If delegate_status_allows_senior_delegate a senior_delegate should be required

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#2933]
The title is self explanatory I think. I came when around this while working on #1046, and actually I started fixing it, until I saw how many tests it broke :P 

Adding such a validation is quite easy:
```ruby
validate :must_have_senior_delegate
def must_have_senior_delegate
  if User.delegate_status_allows_senior_delegate(delegate_status) && !senior_delegate
    errors.add(:senior_delegate, I18n.t('users.errors.must_be_present'))
  end
end
```

And the test too:
```ruby
it "requires senior delegate if delegate status allows it" do
  delegate = FactoryBot.create :delegate

  delegate.senior_delegate = nil
  expect(delegate).to be_invalid_with_errors(["must be present"])
end
```

Also, a change is needed on the en.yml file:
```ruby
must_be_present: "must be present"
```

I think the issue is that the factory by default generates a `delegate` without a `senior_delegate`, but I'm not sure how to change that or if that will break another awful lot of tests. Anyway, I felt that this deserved a separate issue and PR, so here I am :)

**Comment by jfly** [comment]
This sounds like a reasonable change to me. It should be possible to update our `delegate` factory to create a senior delegate for each delegate it creates. I wonder if this would have a measurable effect on how long it takes for our tests to run....
