### ISSUE TITLE
Capitalization of the word "Delegate" is not consistent across the website

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#2934]
As @jfly pointed out on #2917, the capitalization of the word "Delegate" is not consistent across the website, as for instance can be seen in:

https://github.com/jfly/worldcubeassociation.org/blob/efcd848621418fd54dd6d7c8be42faf2f2dd1511/WcaOnRails/config/locales/en.yml#L380

and:

https://github.com/jfly/worldcubeassociation.org/blob/efcd848621418fd54dd6d7c8be42faf2f2dd1511/WcaOnRails/config/locales/en.yml#L314

**Comment by jfly** [comment]
Thanks for filing this, @AlbertoPdRF. Which do we want to aim to use?

**Comment by AlbertoPdRF** [comment]
The appropriate capitalization is "Candidate Delegate", "Delegate", and "Senior Delegate".
