### ISSUE TITLE
Update the way to handle registration requirements

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#2978]
Changing the registration requirements field from a text box to a system of check boxes that automatically generates the text to be displayed seems to be the best way to make sure that this field complies its purpose. Right now, organizers and Delegates can write whatever they want there and it's difficult and time consuming for the Board to make sure that everything is correctly and concisely explained, so we would appreciate if something like [this](https://docs.google.com/spreadsheets/d/1n8F45uVclXB0Wukxp4q6T10ug9_WASZ-Hu23Y_5qi0I/edit?usp=sharing) could be implemented soon.

Related: the text under the information field is less relevant now that we have this registration requirements field, so we should update that text, as it does not need to include the competitor limit and entry fees seem more relevant to registration requirements than to information.

**Comment by jfly** [comment]
I just chatted with @AlbertoPdRF about this a bit. The goal here is to get rid of the free form "registration requirements" textbox in favor of structured ui components. This has two benefits:

- We'll be able to autogenerate (and translate) well thought out text for more of the common cases
- It will be easier for the Board to sanity check these things when approving competitions

**Comment by AlbertoPdRF** [comment]
As I couldn't do a proper mock up, here's my handmade schema for how the UI would look like:

![image](https://user-images.githubusercontent.com/26309166/41788999-f7cb8040-764d-11e8-90fb-d0261187e4ca.png)

- What's already done?
  - Check to use the WCA website for registration
  - Make it possible to enable donations
  - Ask/don't ask about guests (actually, this could be reworded a bit)
  - Registration open and close dates, although this would have to be asked always
  - Specify competitor limit
  - Ask for currency and base fee

- What is needed to be done?
  - Add checkbox to ask if the competition is free
  - (The checkbox on the schema about the refund policy shouldn't be there, it should be mandatory to specify one)
  - Add refund options and limit date
  - Ask if OTS registration will be offered, and what's the registration fee
  - Small text box for additional information

I think this covers everything.

**Comment by jfly** [comment]
> Add checkbox to ask if the competition is free

Is there a reason why you think it's better to make this a checkbox vs asking the user to enter the amount and handling 0 as "free"? I feel like adding a checkbox is just going to be cluttering the UI for the common case where competitions are not free.

> Add refund options and limit date

I think we should be clear about what this limit date means. Specifically, what happens *after* the limit date? What if an organizer wants to provide full refunds up to a certain date, and partial refunds after a date? That also reminds me:  how often do competitions still have changing registration fees over time and per event fees? Up until now, we've been ok not supporting everything an organizer might want to do, but if we're going to try to capture this information in a structured way, then I think we either need to force organizers to obey the stuff we support, or we need to support everything they want to do, right?

> Small text box for additional information

That reminds me. We also need to know what to *do* with all this new information people are going to potentially be able to give us. How are we going to surface this new information on our existing public facing screens?

**Comment by AlbertoPdRF** [comment]
> Is there a reason why you think it's better to make this a checkbox vs asking the user to enter the amount and handling 0 as "free"? I feel like adding a checkbox is just going to be cluttering the UI for the common case where competitions are not free.

I think some kind of double check is necessary for the case of free competitions just in case, although maybe there is something more practical than my proposal. Any idea?

> I think we should be clear about what this limit date means. Specifically, what happens after the limit date? What if an organizer wants to provide full refunds up to a certain date, and partial refunds after a date? That also reminds me: how often do competitions still have changing registration fees over time and per event fees? Up until now, we've been ok not supporting everything an organizer might want to do, but if we're going to try to capture this information in a structured way, then I think we either need to force organizers to obey the stuff we support, or we need to support everything they want to do, right?

Well, this is exactly the same case as the registration fee: there are infinite options, but having everything available on the website is quite difficult. I think for a first version it would be enough to offer a strict deadline when you go from the specified refund policy to no refunds ater the limit date. But yes, you are right: eventually, we will have to choose between forcing organizers to obey the stuff we support, or support everything organizers want to do.

> That reminds me. We also need to know what to do with all this new information people are going to potentially be able to give us. How are we going to surface this new information on our existing public facing screens?

The idea is that some text gets automatically generated (which means it can be translated) depending on the options that the organizers chose. This text will be displayed right where now goes the text that the organizers write on the "Registration requirements" field, on the info page.

**Comment by AlbertoPdRF** [comment]
Also, #2668 could be handled as a part of this. This is the possible rewording of the ask/don't ask for guests I was thinking about before.

**Comment by cubewhiz** [comment]
Instead of:
[ ] The competition is free

I think the field that asks for the fee is enough. However, if the fee is not zero, the following options should be available.
[ ] Payment is collected at the venue
[ ] Payment is collection online

**Comment by pedrosino** [comment]
The existing fee textbox can be integrated with a check box about competition being free or not. If it's (un)checked, the field for the fee is visible or not.

**Comment by AlbertoPdRF** [comment]
For some reason this issue didn't get closed when #2999 was merged, so I'm closing it now.

**Comment by jfly** [comment]
Note the missing hashtag in the [commit message](https://github.com/thewca/worldcubeassociation.org/pull/2999/commits/b4060720ae41078bd4f7622e4d0ab72837edd349):

![image](https://user-images.githubusercontent.com/277474/44634087-72e33600-a949-11e8-800f-1c888f372522.png)

**Comment by AlbertoPdRF** [comment]
Argh, it seems like it got missing in one of the squashes. Thanks for clarifying!
