### ISSUE TITLE
Actually store the submitted results JSON, rather than simply attaching it to an email

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2980]
A MEDIUMTEXT (16MB) column should be big enough to hold the results json of even the largest competitions (@SqAtx did some research into this and I think he found that large competitions are like 4MB json files?).

@SqAtx looked into adding a MEDIUMTEXT column to our database to store the full contents of the JSON, but ran into issues with that (I don't remember the specifics). I see no reason why this should not work, though.

Once we're storing the json in the database, then we can make life much easier on the results team, by getting rid of the whole "download json, upload the json" flow in favor of just letting them start the results submission process.

**Comment by larspetrus** [comment]
Maybe it doesn't matter, but the JSON should be highly (90%+) compressible to take vastly less DB disk space.

It could also be a candidate for storing in S3, rather than the DB.

**Comment by SqAtx** [comment]
Hey I'm not sure either. I remember being concerned about scalability but the biggest results file as of last october was 775kb, which is an order of magnitude smaller than the MEDIUMTEXT field. So that's not actually a problem.
I _think_ the problems were in ActiveRecord, like you couldn't have a MEDIUMTEXT field as part of an ActiveRecord? I may be wrong.

**Comment by SqAtx** [comment]
How do we actually use the JSON file? Where is it uploaded at the moment?
AIUI, we upload the file to the website and that populates the results, right? Do we just need the JSON file for backup? In that case, it would make more sense to store it in S3, I think.

Well that's a lot of questions, but it boils down to:
1- What is the current process?
2- What do we want it to be?

**Comment by viroulep** [comment]
#3127 uses it to populate the inbox tables and then drop it.
The WRT didn't seem to need it besides that goal, so if we store it it's definitely only for backup purpose!

**Comment by jfly** [comment]
I don't think it's worth storing the JSON just for backup purposes. In the fullness of time, the submitted JSON should be fully formed WCIF documents.

1. Removing the WCA Workbook Assistant entirely, which means giving delegates the ability to upload scrambles to the website along with results.
2. Alerting about differences between the announced schedule and the actual schedule, includes events and rounds.
3. Storing the actual schedule somewhere so we can automatically assign records appropriately.
4. Giving delegates the ability to fix results mistakes on the website, rather than sending them back to whatever data entry tool they used.

Whether we implement these things by storing the raw WCIF JSON in our database, or by parsing the WCIF and storing it in other tables is kind of an implementation detail I don't think we need to figure out right now. I'm going to close this issue and we can file new issues for future features we want to build around the "submitting results" flow.
