### ISSUE TITLE
Deprecating TNoodle 0.13.3

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3016]
As discussed over email, we're going to try introducing TNoodle 0.13.4 while still allowing use of TNoodle 0.13.3. Since the new version of TNoodle doesn't actually change the scrambling algorithms, it's safe to do this. However, we do want to eventually require that delegates not use 0.13.3. This issue tracks that.

@Laura-O, would you be able to work with @SAuroux to determine when a good time for that switch would be?

**Comment by jfly** [comment]
Note that we cannot do https://github.com/thewca/worldcubeassociation.org/issues/2992 until we stop allowing delegates to use TNoodle 0.13.3.

**Comment by SAuroux** [comment]
I don't think that there is much to work out there. The sooner, the better.

**Comment by Laura-O** [comment]
My suggestion would be July 2nd and allowing delegates to use 0.13.3 for two weeks. Does that sound good, @SAuroux?

**Comment by lgarron** [comment]
> My suggestion would be July 2nd and allowing delegates to use 0.13.3 for two weeks. Does that sound good, @SAuroux?

I missed this suggestion and independently suggested 1 week in the thread. Does that still sound okay to you, @Laura-O?

**Comment by Laura-O** [comment]
Yes, I was unsure whether we should choose 1 or 2 weeks, so that's okay!
