### ISSUE TITLE
More granular permissions for "admin access to competitions"

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3017]
Currently, we give people admin access to a competition if they `can_admin_results?`. We recently gave the WQAC permission to approve and announce competition (see #3013 and #3010), but that required giving them `can_admin_results?` power, which includes access to phpMyAdmin.

We'd like to have more granular permissions for this. Here's a not-very thought out proposal, just trying to get the conversation started:

## Currently

if `can_admin_results?` -> allowed to `post_announcement`
if `can_admin_results?` -> allowed to `admin_edit`
if `can_admin_results?` -> allowed to `post_results`

## New system

(`can_admin_competitions?` is a hypothetical new permission. Maybe it would be better to call it `can_announce_competitions?`?)

if `can_admin_competitions?` -> allowed to `post_announcement`
if `can_admin_competitions?` -> allowed to `admin_edit`
if `can_admin_results?` -> allowed to `post_results`

@jonatanklosko, what do you think? I'm definitely open to alternative suggestions here.

**Comment by pedrosino** [comment]
I think this is a good idea.
Is the ability to edit a post included in "allowed to post_announcement"?

**Comment by jonatanklosko** [comment]
Sorry for the late response, I like the idea! I've just implemented it in #3026 making `can_announce_competitions?` an alias for `can_admin_competitions?`, and ensuring that someone able to `post_announcement` can also create/edit posts (as pointed out by @pedrosino).
