### ISSUE TITLE
Port regions.php (Records) page to Rails

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#302]
There are a lot of buttons on [regions.php](https://www.worldcubeassociation.org/results/regions.php?regionId=&eventId=&years=&mixHist=Mixed+History) page. I'm not sure if there's potential to clean them up, however.

![2016-01-05_1742x154_kaladin](https://cloud.githubusercontent.com/assets/277474/12133277/946346a8-b3d8-11e5-9687-4bcde816f839.png)

**Comment by AlbertoPdRF** [comment]
I'm going to take this one on after I'm done with #4394, so I'm  assigning myself to it :slightly_smiling_face:
