### ISSUE TITLE
Port person.php (p.php) page to Rails

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#303]
See https://www.worldcubeassociation.org/results/p.php?i=2011ETTE01 for an example.
- [ ] It would be nice to have unique ids for every row on this page, so people can link directly to a result in competition.
- [ ] An idea I just discussed with @pedrosino: we could update this page to show past (and ongoing) competitions that this person registered for, but whose results have not yet been uploaded

**Comment by pedrosino** [comment]
Thinking on starting to work on this...

Where should this go? We currently don't have a /results folder. Should we create it? Maybe /persons?

**Comment by jfly** [comment]
`/results` might be a bit of a pain since PHP controls that. We could get it to work with more granular Nginx rules, however. `/persons` seems good to me, though!

**Comment by pedrosino** [comment]
https://staging.worldcubeassociation.org/persons/2007GUIM01

I made the picture take 50% of the width...we are wasting a lot of space now with being 300px wide but having all blanks to the sides.

The page doesn't look too much fun...could use more colors

I changed the way we represent previous rounds of the same competition. It used to be a lighter font (or lower opacity, I didn't check). I left it normal and made the final round bold.

**Comment by jfly** [comment]
This looks great, Pedro!

I'm not opposed to adding color, but I'd really like for that to be done as a later PR, because the correct decisions on stuff like that are less obvious to me.

How do you feel about centering the profile picture amid the available whitespace? Right now it looks like it might be a bit left.

**Comment by pedrosino** [comment]
Things to be done
- [ ] Add the history map
- [ ] Link the PB to the round inside history
- [ ] Links colors (?)

**Comment by viroulep** [comment]
Just in case you never visited [CubingChina](http://cubingchina.com/results/person/2007GUIM01), I like how the person's page looks like there!

There is a bit too much information, and it's sometimes difficult to notice important information (eg: I like better how @pedrosino emphasized the final rounds), but some ideas may be taken from there :)

**Comment by jonatanklosko** [comment]
Closing as the page was ported to Rails quite a long time ago.

@jfly do the checkboxes still apply?
1. I've never had the need of linking to specific result, but I imagine this being useful =)
2. Showing ongoing competitions would be inconsistent, given that not all competitions use WCA registration. This may make more sense in the future though (once we import registrations).

Let me know what the state of these two is, and I will create corresponding issues if needed.

**Comment by jfly** [comment]
No need to create issues for these, methinks. I'd say if someone is motivated to take one of these things on, please feel free to send in a PR, but I don't think it's a priority for the team =)
