### ISSUE TITLE
Bug- Clicking Results Upload Button

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3045]
From time to time WRT members will have an issue when uploading results where each result will be uploaded multiple times.
<img width="637" alt="screen shot 2018-06-24 at 12 17 39 pm" src="https://user-images.githubusercontent.com/11577241/42198058-e6a94848-7e53-11e8-9e60-dc372c02598e.png">
For us to fix this, we must remove the temporary results and scrambles then reupload.

I believe I have nailed down the cause to hitting the upload button multiple times before receiving a request.

I also believe that the upload button calls a post method based on the output of Network in DevTools. I think a possible fix would be to change this to a put method.

**Comment by jfly** [comment]
> I believe I have nailed down the cause to hitting the upload button multiple times before receiving a request.

Fun =)

> also believe that the upload button calls a post method based on the output of Network in DevTools. I think a possible fix would be to change this to a put method.

Http method verbs are just conventions. Changing this method from a POST to a PUT wouldn't magically make the backend code idempotent. I think the simplest fix would be to disable the submit button after it is clicked. We aren't actively working on the old PHP code anymore, so don't expect anyone to take this issue on. If you are interested in working on it, feel free to take it on!
