### ISSUE TITLE
Rename "registration_requirements" column to "extra_registration_requirements"

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3050]
@AlbertoPdRF's work in https://github.com/thewca/worldcubeassociation.org/pull/2999/ makes it so the registration requirements column is no longer required to be filled in. Instead, the registration requirements are now structured data, and our `registration_requirements` string column is just some extra space in case our structured data doesn't fully capture the special stuff for this specific competition.

@AlbertoPdRF, do you think you take this on after your work in #2999 goes live?

**Comment by AlbertoPdRF** [comment]
I was planning to do this as a part of #2998.

Although I'm not sure of my availability for the month of July, I'll try to finish with everything related to #2999.
