### ISSUE TITLE
Build a /wdc page

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3052]
At first, it will be pretty simple:

- If the person logged in is part of WCA Staff (TODO: figure out what "WCA Staff" is), then display a list of banned competitors (see #3051), along with a message that this is only visible to WCA Staff.
- If the person logged in is the leader of the WDC, then show a link to edit the "banned competitors team"
- Then display a list of all posts tagged "WDC" (just https://www.worldcubeassociation.org/posts?tag=wdc does).
- Add a link to /wdc to our navbar (https://fontawesome.com/v4.7.0/icon/bullhorn):
![image](https://user-images.githubusercontent.com/277474/42234710-3ff40a0e-7eaa-11e8-8725-f11aaaeb074f.png)

@AlbertoPdRF or @pedrosino, could you drop us a link to the document where "WCA Staff" is defined?

**Comment by AlbertoPdRF** [comment]
Sure, I'll forward a thread to software@ right now.

**Comment by jfly** [comment]
@LinusFresz is going to start working on this!

**Comment by jfly** [comment]
@LinusFresz doesn't have the bandwidth to work on this right now, so I'm going to take this on.

**Comment by lgarron** [comment]
As mentioned on an email thread: `/wdc` doesn't mean anything to the average competitor.

The WRC has `/regulations` and `/incidents`. I'd be happy to share the latter, and I think it would behoove us to pick a name for a WDC URL that makes more sense out of context.

**Comment by LinusFresz** [comment]
> As mentioned on an email thread: `/wdc` doesn't mean anything to the average competitor.
> 
> The WRC has `/regulations` and `/incidents`. I'd be happy to share the latter, and I think it would behoove us to pick a name for a WDC URL that makes more sense out of context.

My suggestion would be `/disciplinary` instead of `/wdc`. That would make it a clear distinction between competition incidents and disciplinary actions. 
That aside, the average competitor won't get access to the list of banned competitors, so it's not too important to give this a meaningful name, right?

**Comment by lgarron** [comment]
> That aside, the average competitor won't get access to the list of banned competitors, so it's not too important to give this a meaningful name, right?

I think we should be prepared for more information in the future! I'd love for use to make forward-looking choices in that regard.

Else, would [`/posts?tag=wdc`](https://www.worldcubeassociation.org/posts?tag=wdc) work for the public, with something like `/internal/wdc` for the internal WDC stuff?

**Comment by jfly** [comment]
Lorenzo is ok with us merging this up, so I'm doing it!
