### ISSUE TITLE
Don't show "website" link when there's no external website

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#3155]
Since most competitions don't have an external website, it's a little confusing to have a link on each competition page (e.g. https://www.worldcubeassociation.org/competitions/IVETECJacareiOpen2018) to itself.

**Comment by jfly** [comment]
@AlbertoPdRF, you've been working with this code recently, could you take a look at this?

**Comment by AlbertoPdRF** [comment]
I can definitely take a look, but I don't know when I'll be able to.

**Comment by pedrosino** [comment]
I'm guessing an if at https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_competition_info.html.erb#L21 would work, right?

I'll try to do that shortly.

**Comment by AlbertoPdRF** [comment]
Yes, I think that should be it! I'm passing the issue to you then :)

**Comment by pedrosino** [comment]
Let us know what you think, @timreyn

**Comment by timreyn** [comment]
Thanks Pedro!
