### ISSUE TITLE
Add the site-wide header to the database export page.

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#316]

**Comment by jfly** [comment]
This will certainly happen as part of porting everything to rails. This might actually be the very last page to get ported, however.

**Comment by lgarron** [comment]
Sure, take your time. Just wanted to make sure we have a bug for it.

**Comment by lgarron** [comment]
This way, you also get to close more bugs for the same amount of work! :-D

**Comment by danieljames-dj** [comment]
By site-wide header, it means the navigation bar to switch to another page right? I think this is already implemented. Can someone please confirm too?

**Comment by lgarron** [comment]
Indeed, https://www.worldcubeassociation.org/export/results has the header now.

**Comment by danieljames-dj** [comment]
Thanks for the confirmation.
