### ISSUE TITLE
Add menu or home page link to 404 page

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#3170]
https://www.worldcubeassociation.org/non-existent is very generic right now.

I'm not a fan of error pages that are too silly or try too hard to be "helpful", but the current error is very generic:

<img width="645" alt="screen shot 2018-08-02 at 02 30 47" src="https://user-images.githubusercontent.com/248078/43575594-143de524-95fc-11e8-80c2-0e63eb809f83.png">

**Comment by jfly** [comment]
Related: https://github.com/thewca/worldcubeassociation.org/pull/691.

**Comment by UnsolvedCypher** [comment]
Our current error pages are static, but dynamic [error pages](https://mattbrictson.com/dynamic-rails-error-pages) may be better so we can show the navigation menu. Is the WST ok with going in that direction? Or, maybe just dynamic 404 and have all other pages be static in case Rails has crashed completely?

**Comment by jfly** [comment]
I personally would rather have simple, static error pages that link to the home page. Like [Google's 404](http://google.com/404-ed):

![image](https://user-images.githubusercontent.com/277474/50544669-0c01b200-0bb3-11e9-9927-709d98176264.png)

**Comment by AlbertoPdRF** [comment]
This should be a good first issue, right? I labeled it as such.

**Comment by moralsh** [comment]
I was writing a similar feature request and then found out this one, Could we get somebody from WCT to design cool images to add to the 404 or 50x pages? here's an idea we used on another website:

![image](https://user-images.githubusercontent.com/12932500/71310370-acc82d80-2413-11ea-9744-ee9d8e3ab209.png)

also, apart from a home page link, we could add a small FAQ or contact information. I might try to come with a full example this holidays.

**Comment by denthebro** [comment]
Seems related to issue https://github.com/thewca/worldcubeassociation.org/issues/17
One of these should probably be closed, as we already have over 300 issues to sort through

**Comment by gregorbg** [comment]
Closing in favor of #17
