### ISSUE TITLE
Would it be legal to have a box to put finished cubes in so that they aren't all in a messy pile on the desk/table during a MBLD attempt?

### ISSUE THREAD

**Issue by TommyCherry** [thewca/worldcubeassociation.org#3197]

**Comment by pedrosino** [comment]
Hi @TommyCherry 
This repository is for the WCA website. You may want to ask this question at the [Regulations repository](https://github.com/thewca/wca-regulations) or directly to the [WCA Regulations committee](regulations@worlcubeassociation.org)

**Comment by TommyCherry** [comment]
@pedrosino thanks. Sorry for posting in the wrong place. I'll repost in the regulations repository
