### ISSUE TITLE
Prompt results poster for a winner if there is no 3x3x3

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#322]
Can we get the website to prompt something like this when there is no 3x3?

I would imagine something like this:
When the post for results is created….
1. if the competition has 3x3, then just do what we usually do. 
2.if the competition has no 3x3, then ask whether or not to announce a winner by some other event
2.1. If yes, then the user can choose an event and the post will be created accordingly. 
2.2. If no, then the post would be created with no winner. 

— ILKYOO

**Comment by jfly** [comment]
I took care of this in https://github.com/thewca/worldcubeassociation.org/pull/1683. Closing this issue!
