### ISSUE TITLE
Incorrect warning about submitting results

### ISSUE THREAD

**Issue by Goosly** [thewca/worldcubeassociation.org#3222]
As a delegate, after I just submitted results, I still get this warning on the competition page:
"Note: Please submit results for this competition! You can upload them here."
And I also still have a notification about it.

This is incorrect and should be changed to something that makes clear that the results have been submitted, but the Results team hasn't published them yet. This way a delegate won't submit results twice, by accident.

I should also not be able to edit/fill in the submit-results-page when I've already submitted results.

**Comment by viroulep** [comment]
I believe it will be taken care of in #3127, I've adjusted the `user_should_post_competition_results?` [here](https://github.com/thewca/worldcubeassociation.org/pull/3127/files#diff-848ffc153c457b964c6c8a9d204cea61R226), and used it to issue the warning on the competition page.
