### ISSUE TITLE
Payments can be refunded months after a competition.

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3224]
With the current system, I am able to refund a payment months after the competition. I believe the same may be true for organizers and delegates to be able to do. This can be potentially harmful as someone can refund payments and cause the person with the stripe account to loose money, which they may not have.

Please correct me if I'm wrong, but this seems to be the behavior of the website. I have no way to test that this is true other than being able to see the refund button on past competitions.

Maybe closing this option after 2 weeks would be beneficial (leave it open for a little bit to ensure refunds are sent out properly).

**Comment by FatBoyXPC** [comment]
Jacob,

I'm pretty sure you can test this on staging, just login as an organizer
that's not a delegate.

James

**Comment by Jambrose777** [comment]
is it possible to make payments on staging?

**Comment by FatBoyXPC** [comment]
I think so? I know Stripe has a fully functional sandbox, I guess I just
haven't poked around on staging to make sure we're using test credentials.
I imagine we are, though, because we played with it on staging before we
pushed it live.

**Comment by viroulep** [comment]
We can definitely test payment on staging!
When connecting a Stripe account to a competition, there should be a "skip this form" on the development warning header put by Stripe on the login page.

And yes, I agree we should define some period of time after which refund can't be done (both implemented client side and in the backend).
Especially given that if someone *really* wants to issue refund months after, they can always do so through their Stripe dashboard.

I'd suggest to let the refund button available for some time after the competition (to accommodate use-cases where the registration payment acts as a deposit which is returned upon participation to the competition).
The 2 weeks time frame sounds pretty good to me.

As far as the implementation is concerned, this could be implemented as a `before_action` filter in the controller, and a basic date check in the view.
Assuming that the developer has a working Stripe local test account that should be a good first issue.
I'd suggest to wait until #4616 is merged to implement this, as the refund spec has been touched a bit by the PR.
