### ISSUE TITLE
Showing if a championship type is already in use for the year

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3225]
One of the requirements for a competition to be recognized as a national championship is:
There’s no other similar competition the same year.
In other words, the same championship for the country, continent, or world cannot be used twice in one year.

It would be nice if the members announcing competitions had easy access to this information whenever they are announcing competitions.

**Comment by jfly** [comment]
I like this idea! @Jambrose777, where do you think would be a good place to put this information? Some ideas, not necessarily good ideas, but just to get the conversation started:

- A message on the `notify_board_of_confirmed_competition` email: https://github.com/jfly/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions_mailer/notify_board_of_confirmed_competition.html.erb
- Re-use our existing `warnings_for` infrastructure on the competitions model: https://github.com/jfly/worldcubeassociation.org/blob/91327af231729416552f36a216617469eb0d673d/WcaOnRails/app/models/competition.rb#L229. This should cause a nice warning to show up on the top of any of the competition pages. We could restrict this message to people who `can_announce_competitions`.

**Comment by Jambrose777** [comment]
Option 2 would be very nice!

**Comment by viroulep** [comment]
@jamesquinn1 mentioned it in the overall issue for the WCAT, but it happened in the past that there were multiple championship competitions per country per year.

As far as I know, it only happened in Brazil in 2014 ([here](https://www.worldcubeassociation.org/competitions/BrasileiroInverno2014), and [here](https://www.worldcubeassociation.org/competitions/BrasileiroVerao2014)).

@Jambrose777 where does this requirement come from?
I couldn't find it in the WIP for the [competition requirements policy](https://github.com/thewca/wca-documents/pull/40), nor in the Delegate's crash course, nor in the other competition policies (name, proximity).
I quickly went through the motions but couldn't find it either.
The competition name policy mentions championships, but not any year-based restriction.

When implementing this, we should probably make sure to only validate competitions created after the policy/motion entered in effect; it would be inconvenient to have "invalid" `Competition` object when they were actually valid at that time.

**Comment by AlbertoPdRF** [comment]
Hm, this seems like the obvious thing that no one thought before to add explicitly somewhere :/ Does it make sense using the same championship type more than once in a given year? Does this happen in any sport? What was the reasoning behind Brazil's case @pedrosino?

**Comment by Jambrose777** [comment]
Thanks @viroulep, I've added a suggestion with the rules that have been followed for championship types. For Brazil, we will for sure change this to be 0 or 1 championship for the year!

**Comment by Jambrose777** [comment]
The Brazil Championships in 2014 have been fixed.

**Comment by timreyn** [comment]
I'm taking a stab at this, using approach (2) that Jeremy suggested above.

**Comment by AlbertoPdRF** [comment]
That's great news! I've just assigned you to the issue. Feel free to reach out if you need any help :slightly_smiling_face: 

By the way, I'd like us to ask the WCAT whether they think a warning on the email is also due.

**Comment by Jambrose777** [comment]
> By the way, I'd like us to ask the WCAT whether they think a warning on the email is also due.

Personally, I think it would fit in with the new changes. We'd basically want red flags to show up, and this would certainly be a red flag.
