### ISSUE TITLE
Competition Subregions

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3226]
It may make sense to have a competition subregion attribute in the competitions table.

WRT/WQAC is currently going through the process of standardizing the formats of the cities used per country.
Typically the preferred city format is either 'city' or 'city, subregion'. However once these changes are made, it may be hard to enforce the correct use per country via human approval. 

It may be beneficial to add an attribute for the subregion. This would change, for example, a USA's city from: 'Atlanta, Georgia' to city: 'Atlanta' subregion: 'Georgia' and can automatically be formatted to Atlanta, Georgia when displayed. There are many other countries that will use this format, and other countries that may want to switch to it in the future.

In addition, it may be beneficial once the list is compiled of these countries that will use subregions to have them be required for those countries when creating a competition. This would make it to where I could no longer enter just a city if it is a USA competition.

**Comment by Jambrose777** [comment]
Writing this out it may be better for the competition creation UI to soley handle this (rather than the database).
so the UI would have something like:
City: Atlanta
Subregion: Georgia
and the it would compile that into a city to store of Atlanta, Georgia.

This could still make use of the requiring/making the subregion only available for certain countries.

**Comment by jfly** [comment]
I am very supportive of this idea! I'm going to close this in favor of https://github.com/thewca/worldcubeassociation.org/issues/361.

> so the UI would have something like:
> City: Atlanta
> Subregion: Georgia
> and the it would compile that into a city to store of Atlanta, Georgia.

For the record, one problem with a UI like this is that it it's a "write once" sort of experience. Once you've stored "Atlanta, Georgia" in the database, there's no way to get back out the city and the subregion for editing purposes.
