### ISSUE TITLE
Javascript errors on Safari 9: unable to see exact registration date

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#3228]
Email from a competitor's parent who could not see the exact date of a competition registration opening time, I asked them to provide a screenshot, see below. Initial impression appears to be a Safari problem, not sure if the width of the webpage is causing the issue.

Screenshot of https://www.worldcubeassociation.org/competitions/ManchesterOpen2019/register:

![image](https://user-images.githubusercontent.com/277474/44376177-19dc5380-a4ac-11e8-976d-651d04021fb0.png)

**Comment by jfly** [comment]
@Mollerz, in the future, please don't link to external websites hosting images. You can copy paste them directly into github. I've updated your post for you. It's also nice to include a direct link to the problematic page whenever possible, which I have also updated your original post with.

The screenshot looks like there was a javascript error that prevented the localized time from rendering. I'll see if I can reproduce this on a friend's iPad.

**Comment by jfly** [comment]
I am able to reproduce this over on BrowserStack using their iPhone emulator.

![image](https://user-images.githubusercontent.com/277474/44385123-50799480-a4d3-11e8-99fd-3b3fded7878c.png)

The "Can't find variable: Intl" is referring to this line of javascript:

![image](https://user-images.githubusercontent.com/277474/44385173-6dae6300-a4d3-11e8-964a-42279baec3cf.png)

**Comment by jfly** [comment]
Looks like the iPhone 6S is using Safari 9.0?

![image](https://user-images.githubusercontent.com/277474/44385422-38eedb80-a4d4-11e8-8083-2135a9b31843.png)

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_compatibility, Safari 10 is when support for `Intl.DateTimeFormat` was added.

I just checked Google Analytics, and Safari 9 makes up 1.29% of our traffic, so this (unfortunately) is probably worth fixing:

![image](https://user-images.githubusercontent.com/277474/44385823-70aa5300-a4d5-11e8-8d31-5b4805bcfe15.png)

@lgarron, any suggestions for if/how we should work around this?

**Comment by Mollerz** [comment]
Thanks for the tip @jfly - I'll take those into consideration for future issues!
