### ISSUE TITLE
Add a footer with links to WCA's social media accounts

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#3242]
I think that this will help us give more visibility to the accounts and also engage people more.

As @Laura-O was working on re-designing the website, maybe she has already thought about this.

**Comment by jfly** [comment]
For the record, we have been adding a lot of stuff to the footer. On mobile, we're basically out of space:

![image](https://user-images.githubusercontent.com/277474/44385998-0514b580-a4d6-11e8-89c4-14292393df66.png)

Ideas:

- Privacy and Disclaimer could potentially get combined? In some sense they're both about our users rights.
- FAQ and Contact could potentially get combined or one of them removed.

I definitely would like to hear @Laura-O and or @lgarron's thoughts on this.

**Comment by AlbertoPdRF** [comment]
Or maybe we can add a second footer? With a different style and only for those links, which are a bunch by the way.

**Comment by Laura-O** [comment]
> As @Laura-O was working on re-designing the website, maybe she has already thought about this.

Yep, I already considered that and have that in my drafts. I think it's more or less standard to put a contact form, the privacy policy and social media icons in the footer, so I support Alberto's idea.

I also don't think the mobile footer is too large or is getting too large if we add the logos for FB, Twitter, and Instagram. A large footer doesn't force users to scroll more, which is usually the reason to avoid including too much content on a mobile page.
On the contrary, if users want to find information which is usually in the footer, they can find it  without navigating through the menu. So 👍  for adding the links.

**Comment by lgarron** [comment]
I would prefer to have more social media in the footer, and consolidating some of the other links if needed.

Could we combine "Privacy" + "Disclaimer" into "About" and "FAQ" + "Contact" into something like "Questions"?

**Comment by cubewhiz** [comment]
@AlbertoPdRF how many is "a bunch?"

**Comment by AlbertoPdRF** [comment]
@cubewhiz Facebook, Twitter, Instagram, Reddit, Twitch, Weibo?, and I don't know if I'm missing anything.
