### ISSUE TITLE
Extra spaces in the competitors name section

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#3243]
From Roman via email:
>Hello all,
>
>I face this little issue for the second time: when a new competitors sign up for the WCA website and fill the name section, he sometimes mistakenly put an extra space in the beginning or at the end, or two spaces between his name or surname. It only becomes noticable when I export the .csv and start to work with data (i.e. creating badges or groups info) and is very hard to notice otherwise. Can we add a validation for these cases?

edit: @jambrose also asked for this for `Competitions.cityName`:

> For fields like cityName the delegate can enter "Atlanta, GA " which causes the city to be displayed as "Atlanta, GA , United States"
> 
> There are ~15 cases like this involving city name currently in the DB, but are easily fixable. I'm curious if there are other fields that would need to be fixed and if we are able to automatically trim these upon form submission.

https://github.com/holli/auto_strip_attributes might be a useful gem for this.

**Comment by cato-hga** [comment]
Hello, is this issue still available?

**Comment by jfly** [comment]
Totally! Do you want to work on this, @cato-hga?

**Comment by cato-hga** [comment]
I can sure try! This is my first time working on an open source project. @jfly

**Comment by jfly** [comment]
Best of luck! Feel free to reach out to the WCA Software Team over email if you have questions.
