### ISSUE TITLE
Inconsistency in the Custom Dates feature in 'Competitions'

### ISSUE THREAD

**Issue by BlargMeister** [thewca/worldcubeassociation.org#3250]
I noticed recently that the Custom Dates feature in 'Competitions' would only show competitions that only occurred within the parameters. As such, if I were to search for competitions between 2018-08-16 and 2018-08-22, as seen here:
![image](https://user-images.githubusercontent.com/42611676/44467549-0b607a00-a61b-11e8-8646-d183871040c9.png)
The results would not show this competition:
![image](https://user-images.githubusercontent.com/42611676/44467604-3519a100-a61b-11e8-834a-e2177db604fd.png)
Which started during the parameters set.
If I then searched for competitions between 2018-08-23 and 2018-08-29, the Pchelka Open would also not appear in the results, as seen here:
![image](https://user-images.githubusercontent.com/42611676/44467784-a9544480-a61b-11e8-97f4-1bb122842228.png)

I think that because the current system for Custom Dates can create inconsistencies such as the one shown here, it would make more sense to standardize it by e.g. having the day a competition starts be the day it would show up under competitions when those parameters house that date, regardless of when the competition finishes, which would add a layer of consistency to the results given.

**Comment by jfly** [comment]
Thanks for the detailed report including screenshots!

I don't think "consistency" is a fair word to use here. The code always does the same thing =) For the record, here it is: https://github.com/thewca/worldcubeassociation.org/blob/ae3c915762a8e7c7d1ea14c78d795bb91170ddbb/WcaOnRails/app/controllers/competitions_controller.rb#L98-L99.

Basically, this is saying "include competitions that are fully contained in the search window". It sounds like people might be less confused if we instead changed this search to find "all competitions that intersect with this window of time at all".

@jonatanklosko, does that sound like a reasonable change to you?

@FatBoyXPC, this would be a great issue to TDD, can you take it on?

**Comment by jonatanklosko** [comment]
I don't have a strong preference here, so if overlapping sounds less confusing that inclusion, I'm fine with it!
