### ISSUE TITLE
Edit events page: bug with across rounds cumulative time limits

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#3254]
Reported by @coder13:
>Reporting a bug:
When you have 2 (or more, didn't check) rounds that are using a single cumulative time limit and you delete one of the 2 rounds, the other event doesn't correctly update knowing you removed that round.
Say you setup 4bld and 5bld to be using a single cumulative time limit, remove 5bld, 4bld will still think it's time limit is 4bld + 5bld rounds 1.
photos:
![image](https://user-images.githubusercontent.com/881394/44113298-76a2fc30-9fbc-11e8-96ca-865ce90c3ddb.png)
![image](https://user-images.githubusercontent.com/881394/44113325-8a9d4f56-9fbc-11e8-8737-5316497edbd2.png)

I did not investigate it, but there is probably something wrong in the `edit-events` pack when updating a cumulative time limit across rounds.

**Comment by viroulep** [comment]
Note to anyone fixing this: you should get rid of the `FIXME` introduced by #4065 as it exists because of this issue.

**Comment by kr-matthews** [comment]
I believe this bug is fixed.

> Note to anyone fixing this: you should get rid of the `FIXME` introduced by #4065 as it exists because of this issue.

But the `FIXME` mentioned above is still in the codebase.

**Comment by dunkOnIT** [comment]
Opened #8656 to keep track of the FIXME
