### ISSUE TITLE
Non-Delegate Board Members Cannot View Delegate Panel

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#3258]
Board members are no longer required to be Delegates, but non-Delegate Board members do not have the link visible in the drop-down menu to view the Delegate Panel. They have access to the page by visiting the link directly, but no navigation to it.

**Comment by Jambrose777** [comment]
They should have access to that page via: Drop-down menu, Admin, Delegates (towards bottom).

I do believe there is no easy access to the crash course.

**Comment by AlbertoPdRF** [comment]
The thing is that non-Delegate Board members don't see this:

file:///storage/emulated/0/Android/data/com.evernote/files/Temp/Shared/imagen.jpg
