### ISSUE TITLE
Ask delegate for main event (additional validation when confirming competitions)

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#327]
Right now, when announcing the results of competitions without 3x3, the results team needs to contact the delegate and ask them how they'd like the results to be announced.

Instead, we should show a "main event" dropdown. Obviously, we should require that the chosen main event is actually being offered at the competition. Some thoughts:
- Do we want to allow them to choose "no winner"?
- Should we allow choosing a main event even if when the competition does have 3x3?
- What should the announcement creation code do if the so called "main event" wasn't actually run? (competitions sometimes drop events)

**Comment by SAuroux** [comment]
Hey Jeremy, it looks like you misunderstood something. This should be an
option, not a requirement.

So the answer to 1) is clearly "yes", this is how things are currently
handled by default if there is no 3x3x3.

Concerning 2) the answer should be "yes" as well, since we have done so a
few times in the past if requested by the delegate.

Concerning 3), can't the dropdown just propose events that were held at the
competition according to the Results table?

2016-01-14 22:26 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
About 3), I'm still confused about if this is something we want to provide at competition announcement time, or when results are being uploaded. If we want to wait until results are being posted to ask about this (which makes sense, since it's only then that we know for sure which events were held at the competition), then we can't ask the delegate, as it's a results team member who would be uploading results.

Maybe this should wait until we ask delegates to upload results JSON directly to the WCA website (#223).

**Comment by SAuroux** [comment]
This will just be an option during the results posting process (when making the results anouncement, to be precise). Either the delegate who submits the results makes a valid special request or we go with the default setting. There is no reason to wait for anything before realizing this. 

By the way: This issue has really low priority. If still not clear: The goal is just the automation of making the results anouncement based on a different Event than 3x3x3, which currently requires manually rewriting the text and copying WCA profile links. But this does not happen very often.

**Comment by jfly** [comment]
A lot of work related to this just happened in PR #1683. We don't actually ask delegates for the main event, instead there's a dropdown that the WRT has to select when uploading results (it defaults to 333 if 333 was held at the competition):

![image](https://cloud.githubusercontent.com/assets/277474/26731932/9a658936-476a-11e7-8bb3-c61f8a412f4c.png)

I think it's okay for now for the WRT to have to ask the delegate what the main event should be if 333 was not held, rather than adding a new field to our database for "what was the main event at this competition". @SAuroux, I'm going to close this issue, feel free to reopen if you think it's important for us to store this data in a structured way.

**Comment by SAuroux** [comment]
No, closing this issue is perfectly fine for me. :)

2017-06-02 17:10 GMT+02:00 Jeremy Fleischman <notifications@github.com>:
