### ISSUE TITLE
Organizers can't opt-out of registration notifications anymore

### ISSUE THREAD

**Issue by LinusFresz** [thewca/worldcubeassociation.org#3287]
https://github.com/thewca/worldcubeassociation.org/pull/2999 changed the way organizers can opt-out of registration notifications: before is got merged they could opt-out whenever they wanted, now they can't anymore after the competition got announced. I see two ways to deal with this:

1.  Remove "You can opt out of receiving registration emails here." from the registration mails any organizers receives and force them to create an own filter if they do not want to have all registration emails in their mailbox or 
2. let organizers again change this setting after the competition got announced again.

Option 2 was used for a long time and I don't see any reason why we should change that.

**Comment by jfly** [comment]
> A change introduced in #2999 was that nothing would be editable anymore

What part of #2999 changed this? I don't see anything relevant in competitions_controller.rb...

**Comment by AlbertoPdRF** [comment]
Removing lines 233 and 261 [here](https://github.com/thewca/worldcubeassociation.org/pull/2999/files#diff-50eb0d6308b5cd05b00f821ef9ed1379) changed this.
