### ISSUE TITLE
Trim whitespace on any field that has text

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3313]
For fields like cityName the delegate can enter "Atlanta, GA   " which causes the city to be displayed as "Atlanta, GA   , United States"

There are ~15 cases like this involving city name currently in the DB, but are easily fixable. I'm curious if there are other fields that would need to be fixed and if we are able to automatically trim these upon form submission.

**Comment by jfly** [comment]
Closing this in favor of #3243.
