### ISSUE TITLE
Deprecation warning about `moment.updateLocale`

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3353]
I've started seeing these warnings when running feature tests and in the javascript console:

>Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

According to https://github.com/fullcalendar/fullcalendar/issues/3471, this happens if for some reason you are trying to define the same locale twice in moment. It looks like we explicitly load moment locales at the top of our appllication.js, and then we go on to load `fullcalendar/locale-all`, which apparently redefines all the locales.

I guess this means that right now, we're including moment locales two times in our javascript bundle. Also, all these warnings are pretty distracting, and are training me to ignore them (which is a Bad Thing). Also, the fact that this is a deprecation notice makes it sound like maybe they won't allow us to do this forever.

This diff causes the warnings to go away for me:

```diff
diff --git a/WcaOnRails/app/assets/javascripts/application.js b/WcaOnRails/app/assets/javascripts/application.js
index a6c9041a..bba4b092 100644
--- a/WcaOnRails/app/assets/javascripts/application.js
+++ b/WcaOnRails/app/assets/javascripts/application.js
@@ -25,29 +25,6 @@
 //= require jquery.floatThead.js
 //= require cocoon
 //= require moment
-//= require moment/cs.js
-//= require moment/da.js
-//= require moment/de.js
-//= require moment/es.js
-//= require moment/fi.js
-//= require moment/fr.js
-//= require moment/hr.js
-//= require moment/hu.js
-//= require moment/id.js
-//= require moment/it.js
-//= require moment/ja.js
-//= require moment/ko.js
-//= require moment/nl.js
-//= require moment/pl.js
-//= require moment/pt-br.js
-//= require moment/pt.js
-//= require moment/ro.js
-//= require moment/ru.js
-//= require moment/sk.js
-//= require moment/sl.js
-//= require moment/vi.js
-//= require moment/zh-cn.js
-//= require moment/zh-tw.js
 //= require moment-timezone-with-data
 //= require bootstrap-datetimepicker
 //= require bootstrap-table
```

I'm not sure if this breaks anything.

A cleaner fix would be to somehow include fullcalendar and the fullcalendar translations, but *not* have fullcalendar also define the moment translations for us. I'm not sure if there's any good way for us to do that, though. @viroulep, any thoughts?

**Comment by viroulep** [comment]
From the [fullcalendar doc](https://fullcalendar.io/docs/locale):

> When you load a FullCalendar locale file, it also loads the translations for MomentJS and jQuery UI Datepicker (if the library is already on the page).

So what we could do is loading only locales that we need instead of just loading all.

I'll go ahead and submit a PR with that.
