### ISSUE TITLE
Registration period is not shown if WCA registration system is not used

### ISSUE THREAD

**Issue by Baiqiang** [thewca/worldcubeassociation.org#3363]
For example: https://www.worldcubeassociation.org/competitions/LanzhouAutumn2018

**Comment by pedrosino** [comment]
I guess it's fine to show it if it exists, but not require it from those who use a different registration system. 
Or maybe it is? That would be a call for the Board to make.

**Comment by Jambrose777** [comment]
We've recently been putting it in there regardless if WCA is used or not. It just creates more clarity for the user to see all the information on WCA (Which is a plus).

**Comment by AlbertoPdRF** [comment]
I think it makes a lot of sense to require and display this information always, regardless of which registration system is used.
