### ISSUE TITLE
Delegates are in "cc" and "reply_to" for result submission emails

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#3366]
Relevant bit of code:
https://github.com/thewca/worldcubeassociation.org/blob/702ffd97f43e6fc2973ac3c1bd117f4e317143e1/WcaOnRails/app/mailers/competitions_mailer.rb#L128-L131

Not sure about other email services, but in Gmail this causes the delegate's email to appear twice once you click Reply All:
![image](https://user-images.githubusercontent.com/1881933/45258608-d41af880-b390-11e8-8da0-ea1d283429b3.png)

**Comment by pedrosino** [comment]
In the WRT we always (or at least should) reply all, so I think the reply _
to field could be removed, as the delegate is already in cc.

Em Qua, 12 de set de 2018 04:23, Jeremy Fleischman <notifications@github.com>
escreveu:

**Comment by cubewhiz** [comment]
This has been happening recently in the notifications when Delegates are more than a week late on reports, too. Was something recently changed to cause this?

**Comment by jfly** [comment]
I don't think anything changed here recently. Is this causing a problem for anyone? Or is this purely a cosmetic issue?

**Comment by pedrosino** [comment]
I don't know how email systems behave when you are mentioned twice in the addresses. For me is more of an OCD thing :P

**Comment by SqAtx** [comment]
My guess is that the mail client is doing something different.

We haven't modified the code for the results submission email or the report nag mentioned by @cubewhiz 
([relevant code here](https://github.com/thewca/worldcubeassociation.org/blob/702ffd97f43e6fc2973ac3c1bd117f4e317143e1/WcaOnRails/app/mailers/competitions_mailer.rb#L114-L117))
@cubewhiz, are you also using Gmail, by any chance?

I also looked at Rails' `ActionMailer` and it doesn't seem like the behavior has changed.

It's a common pattern (in our code, at least) to have email addressed both in the `reply_to` and the `cc` field, and I think there is a use case for that. It **seems** that in that case, Gmail doesn't realize that it's sending an email with somebody both in the `to` and `cc` fields.

If this is a problem and we want to fix it, the first thing I would do is try to open one of those emails with a different email client.

**Comment by cubewhiz** [comment]
Yes, it was using Gmail.

You're right--the email is only going to board@ in cc, but the reply-to is board@ so when you reply, it adds it to the to: field.

This isn't causing any problems that I'm aware of--I think it's strictly cosmetic. I think there's more important things to worry about for now, so I think it's best if we focus on something else unless someone is feeling the urge to fix this.

**Comment by jfly** [comment]
Agreed that this seems like a purely cosmetic issue. I'm going to close this issue because it doesn't seem useful to track. If someone feels like fixing this, feel free to send in a PR :)
