### ISSUE TITLE
Allow at the door (on the spot) registrations

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3437]
(cc-ing @ronaldmansveld)

For @ronaldmansveld and @coder13's work on WCA Live, it would be nice if the WCA website allowed adding registrations at the door. This way, they don't have to build any fancy UIs for that, instead organizers can add people directly to the WCA website, and then WCA Live can just resync.

This will run into some trouble with registrations without a corresponding WCA account. There are two ways to handle that:

1. Allow creating registrations without a corresponding user (ie, changing this code: https://github.com/thewca/worldcubeassociation.org/blob/2f207910681a24c19b60eae486cddafbe2753e0e/WcaOnRails/app/models/registration.rb#L22)
2. Create user accounts. This will require collecting people's email addresses at the door, which is a hassle, but probably a good thing to do, as it allows them to prove their identity to us later on! We'd need to build some sort of "you just registered for this competition with this email address, click here to confirm your email address and set your password" email to handle this.

I think I prefer 2?

Another thing worth mentioning is that @jonatanklosko and I have discussed adding support for importing registrations into the WCA website (either via CSV upload or some other API). This would allow 3rd party registration platforms (such as are used in Poland) to get their data into the WCA website, which will allow smoother use of WCIF tools. Right now, someone using groupfier has to upload registration CSV because there's no guarantee that there is registration information on the WCA website. This will also need to happen if people want to use WCA Live.

@jonatanklosko, would you be interested in working on this?

**Comment by ronaldmansveld** [comment]
Note that at the moment WCIF is the _only_ way to get registrations into WCA Live.

Competitions without their registrations in the WCA website can therefore (at least during the intitial phase) *not* use WCA Live.

I'd prefer to keep WCIF the only way, as uploading a registration CSV to WCA Live will bring along a lot of complications, like missing data such as personal bests etc.

If third-party registration tools are wide-spread, than it may be worth making sure that there is an API endpoint to handle new registrations. This endpoint can then be used by third-parties (and WCA Live) directly, or by the WCA website when importing a CSV or similar.

One difficult point may be how to deal with registration deadlines though. Is uploading a CSV after the deadline allowed? Or only when there are 0 registrations after the deadline? Who is allowed to add registrations after the deadline? etc.

**Comment by AlbertoPdRF** [comment]
It would be easier if we could require Delegates to only use WCA Registration, although several issues have to be taken care of before we are on that position: #1084, #329, #21
