### ISSUE TITLE
Enforce competitor limit

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#3451]
Feature request: prevent organizers from accepting competitors after the competitor limit has been reached, or at least raise a warning before they do so.

The competitor limit is set as part of the competition announcement, and it requires WQAC approval to increase.  Right now there's nothing stopping an organizer from (accidentally or intentionally) admitting extra competitors.  This happened for a competition I'm delegating.

**Comment by AlbertoPdRF** [comment]
The intention was to do that together with #2472, but I don't think anyone is working on that.

**Comment by cubewhiz** [comment]
Ideally, I would love to see #328 finally implemented, but this would at least be a step in that direction.

Don't worry, Tim, it's happened to more than just you.

**Comment by timreyn** [comment]
Hi!  I'd like to bump this up as we're now much more strict about going over competitor limits than we were a few months ago.  It's an easy mistake to admit too many competitors, and it's a very bad competitor experience to be admitted then declined from a competition.

@UnsolvedCypher do you think you can get your PR (or something like it) merged soon?

Thanks!

**Comment by Rubiks-boy** [comment]
I can work on this :)

**Comment by AlbertoPdRF** [comment]
Ok, I'm assigning the issue to you!

Please note that some work on this regard was already started over on #3712. I'm going to go ahead and close that PR due to inactivity, but it can be a useful starting point for you, together with the comments @jfly left there!

**Comment by timreyn** [comment]
Bumping this since it happened again at a competition in my area. 

Duncan, will the new registration system address this?

**Comment by FinnIckler** [comment]
Yes, this is not possible both with checks both in the frontend and in the backend
