### ISSUE TITLE
Reject very-recent dates of birth

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#3455]
One competitor registered for a recent competition with date of birth 2018-08-10.  I did not see any infants competing, so I think that was a mistake :)

Selecting the current year rather than your birth year is a pretty common mistake, and should be prevented by the account creation system.  Maybe we should require new accounts to be at least 3 years old, and say "if this is not a mistake please contact the WST" or something like that.

**Comment by Goosly** [comment]
Another solution would be to only give a warning. If they still submit it, it can be fixed after attending their first competition, like we currently do.

**Comment by jfly** [comment]
I'm going to pair on this with someone soon. Please nobody else take this issue =)
