### ISSUE TITLE
Automated Registration Requirement register link

### ISSUE THREAD

**Issue by sam596** [thewca/worldcubeassociation.org#3460]
Currently, if a competition is not using WCA Registration, the link that the line "Register for this competition here" links to is just the competition website. 

IMO, there should be a box in the admin section underneath the "website" entry, with the link directly to the registration page of the competition, not the competition site. Then the line in the registration requirements should point to this URL.

**Comment by sam596** [comment]
Example:
![image](https://user-images.githubusercontent.com/31994452/46907824-68d4c100-cf10-11e8-9895-81989deeb474.png)

This is from [Project Jastrzębie-Zdrój 2018](https://www.worldcubeassociation.org/competitions/ProjectJastrzebieZdroj2018), as the automated requirements only link to the competition webpage, the delegate felt it necessary to add an additional link to the registration form, cluttering the page.

**Comment by AlbertoPdRF** [comment]
I will try to tackle this over next weekend!
