### ISSUE TITLE
Figure out how we want to handle delegate metadata

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3493]
I'm spinning this issue out of the email thread titled "Filtering of Delegates". I put together this document examining the current state of the world: https://docs.google.com/document/d/131XH6UM-KNvOVPi95RUX-YHQ3d4sv8qqAUdEPglK5Cs/edit#.

The current state of the world is pretty messy, but I don't know what the right thing we want to do is. @ronaldmansveld, could you take a look at this and maybe think about how we should tackle this? Thanks!

**Comment by AlbertoPdRF** [comment]
I'm closing this one in favor of #4222.
