### ISSUE TITLE
Highlight results by clicking on a medal kind

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#3571]
This feature was requested through the website form.
Someone suggested that we implement a link per kind of medal in the "Medal Collection" of a person's profile.
Clicking this link would highlight rows in the results which correspond to this medal kind (eg: clicking on the "gold" link would highlight all first places during a final round).

It may be possible to implement this by:
  - assigning a specific css class to each kind of result (eg: `medal-bronze` and so on) (note: I didn't check, maybe we already do this).
  - clicking the link would toggle a class on the parent element (eg: `highlight-bronze`)

This way we would just have to implement a css style similar to:
```css
.highlight-bronze {
  .medal-bronze {
    // do something highlighting
  }
}
```

**Comment by f3rmat** [comment]
Do you have a proposed UX for this?
As in how this will look like exactly and what happens if a person toggles more than one medal category at once?

**Comment by f3rmat** [comment]
I have been able to make rough changes on my local. [This](https://drive.google.com/drive/folders/1bHljyRAuqs5o2pml7ttQpQUWOK8wZ5Oz?usp=sharing) is what it looks like. 
Clicking on any medal count toggles highlight for the corresponding rows. User can click on more than one types of medals and the corresponding rows are highlighted based on that.
