### ISSUE TITLE
Add a character limit to the registration comment field?

### ISSUE THREAD

**Issue by sam596** [thewca/worldcubeassociation.org#3578]
There have been a few occurrences of people misusing the comment field when submitting a registration, and posting very long and irrelevant messages in them. I suggest limiting this field to a more suitable size?

**Comment by jfly** [comment]
Hmm... what limit do you suggest?

I worry that adding a limit would do more harm than good. When people put long messages, what sort of problem does this actually cause?

**Comment by sam596** [comment]
People have submitted the entire Bee Movie Script as their registration comment. I just see absolutely no reason why there isn't a character limit on the field. Any long queries can just be sent via the contact link on the info page.

Since I have database access, I can see that of the longest 6 comments ever, 4 have been at UK competitions, so I notice it more. The longest comment that seems half reasonable was 971 characters long, which was a decent two paragraphs, but in my opinion still unnecessary. I can see small comments being fine, such as expressing interest in staffing a competition, stating that they may be only attending on X day, or saying you might have X guests (if guests are enabled).

Anything more important should be stated in an email direct to the contacts listed on the info page (IMHO).

**Comment by sam596** [comment]
Just had another "copypasta" comment at 3300+ characters at the most recent UK competition registration opening.

**Comment by Mollerz** [comment]
Extended twitter length seems way more than reasonable, like 280 characters? If you want something arbitrary :P

**Comment by jfly** [comment]
Ok. I am not opposed to adding a limit. I don't know what that limit should be, but I don't want that to get in the way of us actually adding a limit. I do think that if we're going to pick something modest like 280 characters, we need to build/find a UI component that does a nice job of showing the user just how many characters they have left to type.

**Comment by f3rmat** [comment]
I worked on this a bit. Which of these looks better? 
Does [this](https://drive.google.com/drive/folders/1aNCmbgwX52ohNc91AEUPot5F3UcwWUiE?usp=sharing) look okay?

**Comment by jfly** [comment]
Oh, awesome! Both look pretty good to me, but does the overlay one get weird if the text makes it that far?

**Comment by f3rmat** [comment]
Yes the overlay one gets weird if the text makes it that far. I tried to style it in a way so that it doesn't happen but haven't been able to. 
The CSS for the other option (where the count lies entirely out of the body of the textarea) is pretty straight forward and seems to work well across screen dimensions.

**Comment by jfly** [comment]
Sounds like we should take the non-overlay approach, then!
