### ISSUE TITLE
Advancement conditions are not clear about average vs single

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3597]
The edit ui just says "with a result", which at least is a little ambiguous:

![image](https://user-images.githubusercontent.com/277474/48435948-6e514100-e732-11e8-91ae-2a2e59fbc5f2.png)

The schedule page is even worse, because it states very explicitly that this is for single, whereas it's really for "whatever the round is ranked by":

![image](https://user-images.githubusercontent.com/277474/48436006-90e35a00-e732-11e8-815a-b7b947be96b4.png)

The WCIF document doesn't explain this at all, it just [loosely uses the term `AttemptResult`](https://docs.google.com/document/d/1hnzAZizTH0XyGkSYe-PxFL5xpKVWl_cvSdTzlT_kAs8/edit#heading=h.8f1qg7imx3ou). I think it would be good to update that doc to be explicit about what the intended interpretation of this field is.

@viroulep, sorry to throw more stuff at you when I haven't reviewed any of your existing PRs, but do you have any time to work on this?

**Comment by jonatanklosko** [comment]
Closing in favor of #5661.
