### ISSUE TITLE
Unspecified gender is changed in the posting results process

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/worldcubeassociation.org#360]
This is far from being important or urgent.  I'm mostly documenting this in order for us to get rig of this bug when we're ported to rails.  The WCA allows unspecified genders for competitors who doesn't want to make public that information or doesn't feel themselves attached to the classical male / female gender.

Well, at some point posting results these empty genders are silently altered, and this should not happen.

**Comment by jfly** [comment]
(Somewhat related to #248)
