### ISSUE TITLE
Design problems on Windows browser

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#363]
See

![image](https://cloud.githubusercontent.com/assets/277474/12741600/c59fa8aa-c932-11e5-8d10-9cf7fbaa1120.png)

**Comment by AlbertoPdRF** [comment]
Update: the social media links introduced in #3577 don't show up! Maybe the title should be updated to something like "Design problems on Windows browser."

**Comment by gregorbg** [comment]
Internet Explorer has been deprecated by Microsoft and Edge has been upgraded to use WebKit.
I don't think this is relevant anymore. Feel free to reopen though!
