### ISSUE TITLE
Update competitor tutorial

### ISSUE THREAD

**Issue by suushiemaniac** [thewca/worldcubeassociation.org#3630]
**Is your feature request related to a problem? Please describe.**
I'm not frustrated at all :)

**Describe the solution you'd like**
Competitor Tutorial PDF bump from Version 2018-08-28 to 2018-11-27

Changelog:
- Updated Photo Credits
- Remove two unnecessary blank pages at the end

**Describe alternatives you've considered**
None

**Additional context**
The Competitor Tutorial PDF has to be manually updated by WST for the time being.
Please use the PDF that can be found here: https://drive.google.com/a/worldcubeassociation.org/file/d/1WT8IIpAnzzT5F0WGCyoPpT6cIu9UFftR/view?usp=sharing

**Comment by AlbertoPdRF** [comment]
Hmm, if the file is hosted on a Team Drive, I believe people from outside our organization can't download files; have you tried to download it while signed in to your `@wca` account or your personal one?

**Comment by jfly** [comment]
I tried with my personal gmail. With my gsuite account I see the same behavior.

**Comment by suushiemaniac** [comment]
I have made sure that the link is accessible even from the outside world. There is a checkbox which says "allow access from outside your organisation" that I ticked. Strange...

**Comment by suushiemaniac** [comment]
I have broadened access permissions for everyone within the organisation. Please try again from your @wca accounts
