### ISSUE TITLE
Better contact link for competitions

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#3633]
Many of the contact links for specific competitions are mailto links, which can be problematic because in my experience, many people haven't set up associations for these links on their systems. This can result in the link opening a blank tab or opening the system mail client that the user doesn't use.

Instead, we now have the [website contact form](https://www.worldcubeassociation.org/contact/website) which allows competitors to contact organizers directly. To avoid mailto links, could we perhaps instead use these links to link to the contact form with the competition name pre-filled?

**Comment by dancing-jules** [comment]
Good point. Why not just write the email address in plaintext?

**Comment by jfly** [comment]
Writing the email address in plaintext seems like punishment for users who *do* have things set up correctly.

I am also not a big fan of contact forms, but that may be a good option...

**Comment by dancing-jules** [comment]
But how many people who don't know how to setup a standard email program, know how to look into the bottom left corner of the screen?

And if you write it in plaintext, you can still have as a clickable link.

**Comment by jfly** [comment]
> And if you write it in plaintext, you can still have as a clickable link.

Ah, sorry, I forgot that that's not the case right now. That also sounds reasonable to me.

**Comment by AlbertoPdRF** [comment]
From @jfly on #721:

> Another problem is that organizers want to be able to provide a single email to contact the entire organization team at once, rather than giving out their individual emails.

One possible solution could be to let organizers add an alternative email address and use that one on the website contact form (if available) instead of the individual emails.
