### ISSUE TITLE
Ruby Sass is being deprecated

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#3649]
Ruby Sass is [being deprecated](https://sass-lang.com/ruby-sass). Places where we still use it:

- We should switch from using `sass-rails` to `sassc-rails`.
- `scss_lint` [suggests moving to another tool](https://github.com/sds/scss-lint#notice-consider-other-tools-before-adopting-scss-lint). They suggest stylelint or sasslint, which are both npm packages. **UPDATE**: This is being taken care of in https://github.com/thewca/worldcubeassociation.org/pull/4381
- ~`bootstrap-sass` still depends on `sass` but there's an [issue](https://github.com/twbs/bootstrap-rubygem/issues/159) to update this dependency to `sassc`, which should hopefully be resolved in the near future and allow us to update. This is slightly off-topic, but does the WST plan to remain on Bootstrap 3 for a long time, or are there any plans to upgrade to 4 in the future?~ **UPDATE**: This is done, it looks like [the version of `bootstrap-sass` we're using now depends on `sassc`](https://github.com/thewca/worldcubeassociation.org/blob/3aeada0f22d1f0aebe641718cba567e6d83fed42/WcaOnRails/Gemfile.lock#L116)
- `font-awesome-sass` has migrated to `scss`, but upgrading that gem breaks the WCA site because some icon names have changed. [This script](https://gist.github.com/ilanben/38ef4d4545cb74089375af0ceecf439b) is a good starting point for the migration process, but more work is required.

**Comment by jfly** [comment]
> This is slightly off-topic, but does the WST plan to remain on Bootstrap 3 for a long time, or are there any plans to upgrade to 4 in the future?

We don't have any plans to move off of Bootstrap 3. I'm not opposed to it if someone wants to take it on, but my gut feeling has been that it would be a big project with little reward. However, if it it causing us to be unable to upgrade other key pieces of our stack, then I would definitely say it's worth upgrading or replacing it.

**Comment by UnsolvedCypher** [comment]
Ok, thanks. Bootstrap 3 shouldn't be a problem for upgrading to sassc.

I'm looking at what needs to be done to move to sass-lint, and that the configuration file can be automatically converted. However, I'm having trouble figuring out where the pre-commit hook ties in with the linter- would you mind pointing me in the right direction?

**Comment by jfly** [comment]
We use the `pre-commit` Gem, which has baked in support for `scss_lint`. See https://github.com/jish/pre-commit#available-checks for more information. I think we'll have to do 1 of 2 things:

1. Add a custom check to our pre-commit that uses `stylelint` or `sasslint`. This should be possible by editing our `config/pre_commit.rb` file. Then you could remove [`:scss_lint` here](https://github.com/jfly/worldcubeassociation.org/blob/00b66534978cd467eff5c0ecef0e12971deb2bcf/config/pre_commit.yml#L6)
2. Change the `pre-commit` gem to support `stylelint` or `sasslint`.

2) feels better to me, although might be more work.

**Comment by UnsolvedCypher** [comment]
I've opened an issue on the `pre-commit` repo letting them know what the situation is with `scss-lint`, but I'm not holding my breath for them to come out with a fix. I'm not quite sure what you mean by option 2, are you suggesting that we switch to another gem? Or that we write a plugin for `pre-commit`?

**Comment by jfly** [comment]
I'm suggesting that we send in a PR to the `pre-commit` folks adding support for an alternative to `scss-lint`.

Could you include a link to that issue you filed?

**Comment by UnsolvedCypher** [comment]
Sure, [here](https://github.com/jish/pre-commit/issues/278)'s the link. Their [contribution page](https://github.com/jish/pre-commit/blob/master/.github/CONTRIBUTING.md) links to a repo with example plugins and says to open a PR if we wish.

**Comment by UnsolvedCypher** [comment]
I'm not sure about the pros and cons of this and the effort involved, but [`overcommit`](https://github.com/brigade/overcommit) looks like it is a robust and widely used hook manager Gem.
