### ISSUE TITLE
Change records color display.

### ISSUE THREAD

**Issue by theoleinad** [thewca/worldcubeassociation.org#3654]
**Feature request:** 
Set up colors to the records shown in profiles and/or other webs:
Tentative suggested colors: 
WR - Blue #0366d6
CR - Red #e36209
NR - Green #28a745
PR - #fc4a0a

This is so the users can differentiate easier which type of record has been broken. 
Looks good and people liked the idea.

**Comment by dancing-jules** [comment]
That red is more orange than the orange is and they are barely distinguishable. 
![image](https://user-images.githubusercontent.com/33940391/50792348-eec09800-12c4-11e9-9278-9b5f665bcae2.png)

**Comment by AlbertoPdRF** [comment]
This is probably a good first issue, so I'm labeling it as such.
