### ISSUE TITLE
WCT Redesign of About/Donation and Teams/Committees Pages

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#3661]
The WCT has completed some mockups of changes to the WCA website. Our goals were:

- to add donation information to the about page
- make the about page better showcase the organization
- put teams and committees on their own page with increased legibility
- reduce duplication between the about and contact pages for listing team and committee members
- use the contact form for most contact requests rather than the current contact page, which often results in emails going to the wrong place

So, we have made the following changes:
- new about page with donation information to replace the old one
- new teams and committees page that includes description, members, and contact information
- contact links now go to new contact form that automatically routes emails to the right place rather than making people read a list of emails

The mockups can be viewed at the links below. We would like some feedback from the WST, WFC, and the Board, but also from anybody else who has feedback on these ideas. Public commenting is enabled on all of these links, so if you have feedback about a specific part of the design, please feel free to leave a comment.

[New about page](https://drive.google.com/file/d/10tnEOr6XF6Z5jaZC8_yp6Upk3tfgDeA6/view) (the "Donate with PayPal" now says "Donate with Credit Card" and links to our Guidestar donation page)
[New teams and coommittees page](https://drive.google.com/file/d/1KCuZLrVRYdjic7y9cQ87sPmxllRJkD6S/view) (Board members and officers have been added to this page, please see the discussion below for screenshots)
[Teams and committees in the navbar menu](https://drive.google.com/file/d/17zagSmal0NctkKk92uW2QScj4jCCSVd6/view)

**Comment by cubewhiz** [comment]
I really like the new pages. I think they're far better than the old ones.

While not a "team" in the same sense, I think the Board of Directors should appear on the Teams and committees page.

**Comment by UnsolvedCypher** [comment]
Here's what the Board section looks like if added in. The WCT can come up with a description (unless the Board would prefer to do that). 

BOARD is obviously not an appropriate abbreviation for the Board, so this can either be omitted entirely or if there isn't a reason for it to be the way it is now, it can be changed to Board.

![screenshot from 2018-12-09 21-42-09](https://user-images.githubusercontent.com/3170853/49707979-af3a5980-fbfb-11e8-95d6-c85fa90f3a4a.png)

**Comment by cubewhiz** [comment]
Yes, I think that is fine. I think it is okay to omit the abbreviation. I trust the WCT to come up with an appropriate description. You can use the Motion for the Board of Directors as a guide as to what we do.

It would be a nice bonus if the officer titles could be included, though I don't think they are indicated anywhere so this probably means adding an additional step with an amount of work I am not familiar with. However, this information is probably important enough to display.

**Comment by UnsolvedCypher** [comment]
@cubewhiz Thank you for your feedback. I agree that the titles are important to have. Do you know where I might find who holds the officer titles? I gather from your signature that you're the Executive Directory, but I don't see any pages listing who holds other titles.

WST- Is this something you would like to discuss adding into the database? Or, it be best to hardcode this now and add the titles in at a later time?

**Comment by cubewhiz** [comment]
Alberto is secretary, Olivér is Chair, I am Executive Director, Chris is Treasurer (though that is always wfc leader).

**Comment by DanielEgdal** [comment]
Is there some logic in the current order og teams and committees? Wouldn't it make more sense to have it sorted alphabetically?

**Comment by DanielEgdal** [comment]
WQAC is placed above WRC, WRT, and WST. 
Apart from that, the rest is sorted alphabetically.

**Comment by DanielEgdal** [comment]
My bad...

**Comment by UnsolvedCypher** [comment]
@cubewhiz I've added the officers above the Board and differentiated them from the Teams and Committees with black. This is consistent with how Senior Delegates are differentiated on the Delegates page. What do you think?

![screenshot from 2018-12-13 18-14-11](https://user-images.githubusercontent.com/3170853/49973399-eca42d00-ff02-11e8-8a71-a13c19a5523b.png)

**Comment by cubewhiz** [comment]
Yep, I think that looks great!

**Comment by AlbertoPdRF** [comment]
I like this pretty much, thanks @UnsolvedCypher for working on it!!!

I just wanted to point out that from now on we should enforce the guidelines that the WQAC crafted for Delegates' avatars for Committee/Team members avatars too.

**Comment by UnsolvedCypher** [comment]
@AlbertoPdRF that is a good point, some of the members don't have avatars as of now. It would probably be good to email all WCA staff to let them know that they should upload a compliant avatar.

@ChrisWrightWCA Would you mind looking this on behalf of the WFC as one of the pages concerns donations?

**Comment by AlbertoPdRF** [comment]
Can the WCT take care of that @UnsolvedCypher?

**Comment by AlbertoPdRF** [comment]
Thanks! Personally I don't have anything else to add, I'm excited for this change to go live! :)

**Comment by UnsolvedCypher** [comment]
@viroulep asked about how this would look on mobile, so here are some screenshots:

![screenshot from 2018-12-18 13-12-19](https://user-images.githubusercontent.com/3170853/50173980-f5ac4a00-02c6-11e9-9590-aedf9597b224.png)
and scrolled further down:
![screenshot from 2018-12-18 13-12-48](https://user-images.githubusercontent.com/3170853/50173984-f7760d80-02c6-11e9-856d-e6961ed74721.png)

Because of the limited horizontal space, there generally aren't many team members per line. I'm ok with how this looks, but if others think this looks messy, we could either center each line, or allow one member per line.

**Comment by cubewhiz** [comment]
It would probably look better with one member per line on mobile, but I don't have strong feelings about this (and this is probably a waste in landscape view). Some other thoughts for mobile (without regard or knowledge of how much work they are to implement) might be to include the picture only or to have the team members in a collapsible nest that can be opened or closed for each team/committee.

**Comment by cubewhiz** [comment]
How is this coming along?

**Comment by AlbertoPdRF** [comment]
This has been handled in #4269.
