### ISSUE TITLE
Unnecessary "Changing your email will require confirming the new email" hint shows up on the signup page

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3665]
Sign out, and go to https://www.worldcubeassociation.org/users/sign_up. You'll see the following:

![image](https://user-images.githubusercontent.com/277474/49701544-acf7e100-fba2-11e8-9b48-7460159940a5.png)

I think this was actually broken in e839a21f09f826c61ef9e6c8f5fabf2d113dd18d, which happened around Fri Apr 1 19:30:48 2016 +0200. Looking at archive.org, things seem to be:

- ok on March 29, 2016: https://web.archive.org/web/20160329174247/https://worldcubeassociation.org/users/sign_up
- bad on Aug 11, 2016: https://web.archive.org/web/20160811004203/https://worldcubeassociation.org/users/sign_up

We only want this "Changing your email will require confirming the new email." to show up on the user edit page, not on the sign up page. One fix might be to move the `simple_form.hints.users.email` translation key somewhere else, and then updating our users edit page to explicitly reference it. @viroulep, how does that sound?

**Comment by viroulep** [comment]
Wow, so it went unnoticed for more than 2 years :o

Yes I agree with the suggested fix: it's either this or force a blank hint on the signup form, but the latter wouldn't prevent this behavior from occurring in the future...

**Comment by f3rmat** [comment]
I tried working on this but when I created a new translation key, it was not picked up. 
However if I made changes to the value of an existing translation key, the changed value was reflected immediately. 
Is there some config flag I have to switch on/off for a new key to picked up?
