### ISSUE TITLE
Rename registrations fields

### ISSUE THREAD

**Issue by zeecho** [thewca/worldcubeassociation.org#3693]
When creating a competition, the website shows this:
![2018-12-14-170944_1010x95_scrot](https://user-images.githubusercontent.com/5508488/50014100-49671c80-ffc3-11e8-9876-57da6b0c1cf3.png)

But we actually can "close registration" and have "on the spot registrations". Therefore, wouldn't it be clearer to speak about "online registration" instead of just "registration" for the fields in the screenshot?

Maybe it's nitpicking but, for a competition, we actually asked ourselves if we could close the registration a few days before the competition while still allowing on the spot registrations and I'm pretty sure we can.

**Comment by jfly** [comment]
Hmm... are these fields used to encode registration start/end dates even if the competition doesn't have online registration? I'm thinking of a competition where the only way to register is to go to a physical store and pay a dollar amount during the "registration period".

**Comment by zeecho** [comment]
Interesting remark, I did not think about that. 
Currently, if you do not check "I would like to use the WCA website for registration", you can either leave this field blank or fill it (while it's mandatory to fill it in case of registration on the WCA website). So, as you said, I guess it might be used by organisers who accept only physical registration then

**Comment by Jambrose777** [comment]
Closing this as OTS registration can be considered a separate registration period, once #3267 is added, I believe this would make it clear exactly what a registration period is defined to.
