### ISSUE TITLE
I18n isn't possible in the admin panel

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#3695]
The admin panel currently can't be internationalized because the locale code is in `application_controller.rb` which is inherited by most of the site, but not by `admin_controller.rb`. Should the application controller be inherited? Or should the locale code be duplicated?

I realize not a lot of people use the admin panel so it's not a huge priority, but there is some text there like the avatar guidelines that is stored as a translation key for the rest of the site but has to be copied over every time it changes. Also, some method calls return translated text so you can end up with something like "Data was last computed 9 días ago and took 7 minutos".

**Comment by jfly** [comment]
Hmm... it looks like `AdminController` does inherit from `ApplicationController`. See: https://github.com/thewca/worldcubeassociation.org/blob/1c2fbac334d21ae0590cf738ee2d1fd577792664/WcaOnRails/app/controllers/admin_controller.rb#L5 Am I missing something?

**Comment by jfly** [comment]
I'm going to close this issue. Please reopen if there's something I'm missing here!
