### ISSUE TITLE
Internationalize competition and result announcements

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#3713]
Since competition and result announcements follow a template format, it might make more sense for them to be stored not as text but as some kind of object that can be rendered in the locale of the current user. This would make a large part of the front page much more friendly to any non-English speaking users.

**Comment by jfly** [comment]
I have not been following the website redesign work, but my gut feeling is that nobody actually looks at these posts on our homepage, so I don't think it's actually worth improving them, I think it would be better to get rid of them.

**Comment by AlbertoPdRF** [comment]
As even with the website redesign these announcements will still exist (although they won't be where they are now,) I think this is worth handling.

I'm labeling the issue as a good second issue.

**Comment by jfly** [comment]
Do we actually think these posts are valuable, though? If we don't think they are, then we should get rid of them, even if it's not part of this initial redesign.

**Comment by AlbertoPdRF** [comment]
I think they are, although for sure they do not belong where they are now. However, it would be interesting to know what other people think about them!

**Comment by jonatanklosko** [comment]
Personally I don't read any announcements. Thinking about it, it's probably that most of them are not relevant to the user:
- if you care about some competitions' results, you check them live on Cubecomps, knowing that eventually they will end up on the WCA website
- usually there are *many* other ways of getting informed about competitions, for me it would be:
  - Facebook events that I'm invited to
  - Polish Association website where competitions are listed *way* before they are announced, so by checking that list from time to time I get the sense of competitions I may be interested in. I imagine that community in most countries has this kind of communication channel, either a website or Facebook group. On top of that, using WCA competition search is definitely way better than scrolling for interesting announcements.

Additionally email notifications already cover the relevant result announcements, and same could go for competitions, see #114.
