### ISSUE TITLE
Have 4x4x4 Blindfolded & 5x5x5 Blindfolded Means implemented onto the WCA site

### ISSUE THREAD

**Issue by kingmathyall** [thewca/worldcubeassociation.org#3721]
With 4BLD and 5BLD soon to be officially recognized as of the new regulation changes (if approved), some changes should be made on the site to reflect this change.

This would be recognizing records based on past results, showing mean results on profiles, and rankings.

**Comment by Julio974-TheHexahedron** [comment]
I guess this is going to be done

**Comment by cubewhiz** [comment]
The changes have not been approved. Let's wait until the new set of Regulations are announced.

**Comment by jfly** [comment]
Could someone link to the relevant regulations for this? And how exactly do we want to handle this, especially for past results? Are we going to recognize a bunch of past world records (as we somewhat controversially did for 333fm and 333bf when we added support for mean?) If so, that's more of a WRT thing, so cc-ing @SAuroux..

**Comment by kingmathyall** [comment]
@jfly This was a preemptive issue if the new set of regulations are approved. The specific regulation change can be found here:
[Issue 547](https://github.com/thewca/wca-regulations/pull/547)

**Comment by Jambrose777** [comment]
I think Sébastien missed this. WRT can investigate and assign the appropriate records. (I have many missing schedule information already from a previous investigation). As long as the check records script works for big bld averages, they should be easy to find, verify, and assign for us!

**Comment by SAuroux** [comment]
I missed this indeed. Nothing to add to what Jacob said!

**Comment by lgarron** [comment]
> Are we going to recognize a bunch of past world records (as we somewhat controversially did for 333fm and 333bf when we added support for mean?)

While I disagreed with the decision to do this with past events, I think we should be consistent and award retroactive records for this, too.

**Comment by pedrosino** [comment]
> While I disagreed with the decision to do this with past events, I think we should be consistent and award retroactive records for this, too.

If we come to the conclusion that it was a bad/wrong idea, we shouldn't do it again just for the sake of consistency.

**Comment by Mollerz** [comment]
`If we come to the conclusion that it was a bad/wrong idea, we shouldn't do it again just for the sake of consistency.`

Having said that, this is going to be the last time something like this happens, and I think it is fine to be consistent in this case.

**Comment by Julio974-TheHexahedron** [comment]
> > If we come to the conclusion that it was a bad/wrong idea, we shouldn't do it again just for the sake of consistency.
> 
> Having said that, this is going to be the last time something like this happens, and I think it is fine to be consistent in this case.

Exactly. The last event that wouldn't have any mean or average computed would be multi-blindfolded, and it doesn't seem like a good idea to add it. So, as long as no new events are added, this will be the last means added.

**Comment by EdHollingdale** [comment]
Where is this currently sitting? The new regulations come into force tomorrow - I assume this would entail a non-trivial amount of work on the website end and in the results database. There have been some people who are under the assumption of "my record will be recognised in X hours" or similar.

**Comment by lgarron** [comment]
Okay, as of #4105:

- [ ] `Check results` knows about means.
- [ ] `Compute auxiliary data` computes means.
- [ ] Averages show inline with results in profiles
  - [ ] PR averages are shown in orange

<img width="944" alt="Screen Shot 2019-05-01 at 00 19 41" src="https://user-images.githubusercontent.com/248078/57008775-4a31d100-6ba7-11e9-8bbc-f06b3a248991.png">

TODO:

- [ ] Regional record means (NR/CR/WR) are computed.
- [ ] Personal record means show at top of in profile.
- [ ] [Records page](https://www.worldcubeassociation.org/results/regions.php?regionId=&eventId=444bf&years=&mixed=Mixed) list means.
- [ ] [Rankings page](https://www.worldcubeassociation.org/results/events.php?eventId=444bf&regionId=&years=&show=100%2BPersons&average=Average) lists means.

**Comment by lgarron** [comment]
Here we are:

<img width="789" alt="Screen Shot 2019-05-01 at 00 35 27" src="https://user-images.githubusercontent.com/248078/57009038-0c35ac80-6ba9-11e9-8e04-d137675993de.png">

I've accepted all regional records as recommended by the [record check](https://www.worldcubeassociation.org/results/admin/check_regional_record_markers.php?eventId=444bf&competitionId=&show=Show). There is only one checkbox remaining:

<img width="1188" alt="Screen Shot 2019-05-01 at 00 36 33" src="https://user-images.githubusercontent.com/248078/57009058-32f3e300-6ba9-11e9-9f16-b234f386e6a6.png">

4x4x4 BLD was on Sep. 22 at VIT Rubik's Cube Challenge 2017, so the Lord Of The Minx 2017 mean is *not* an NR and I've left the box unchecked.

**Comment by lgarron** [comment]
Okay, I think everything I know about is covered. If there are follow-up issues, let's file new issues.
