### ISSUE TITLE
Big cube event icons

### ISSUE THREAD

**Issue by shelchang** [thewca/worldcubeassociation.org#3746]
Event icons need to be easily distinguishable at a glance. The big cube icons (5x5 through 7x7) fail at this especially when displayed at small size. An easy way to improve this would be to incorporate an arabic numeral, e.g. 
![2018-12-25-150705_49x50_scrot](https://user-images.githubusercontent.com/1166834/50427275-666bdd00-0858-11e9-83c0-6adcd1e577f3.png)

**Comment by jfly** [comment]
Could we continue this discussion over on https://github.com/cubing/icons/issues/13?

Unfortunately, the last time we tried to change this, we got pretty tied up in "everyone agrees the current thing isn't great, but nobody can agree on how to make it better".
