### ISSUE TITLE
Change teams edit page to prevent losing history

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3753]
Right now, the team history page looks something like this:

![image](https://user-images.githubusercontent.com/277474/50530198-31f25e00-0ab0-11e9-97dd-d92f6f31d00d.png)

A few issues here:

1. Yellow is a pretty random color to indicate "no longer a team member". I think we should change that to a separate, labelled category.
2. It's possible to change someone to be a leader, and that's almost certainly **not** what we want people to do. Instead, we want old rows to remain immutable, and only for new rows to be added. I'm not sure what a good UI for this would be, but even a bad UI would be better than the current UI.

I'll work on changing the UI so these sorts of undesirable changes are no longer possible.

**Comment by AlbertoPdRF** [comment]
Yes. Your record would be a total of 4 entries:

1. First period as regular member (no boxes checked). From: membership starting date. To: first Leader term appointment date.
2. First period as Leader (Team Leader box checked). From: first Leader term appointment date. To: end of first Leader term date.
3. Second period as regular member (no boxes checked). From: end of first Leader term date. To: second Leader term appointment date.
4. Second period as Leader (Team Leader box checked). From: second Leader term appointment date. To: two years from second Leader term appointment date.

@jfly Leader end of terms dates should be something nice to go into the Board digest email we were talking of offline the other day. The same would be great for Seniors, although I think we can't do that with the way we handle Seniors now.

**Comment by AlbertoPdRF** [comment]
Oh, it seems what I proposed isn't possible at all, because terms can't overlap :P But it will work if you subtract one day to all the "To:" dates.

**Comment by Jambrose777** [comment]
Would we be interested in correcting the past entries of leadership positions?

**Comment by AlbertoPdRF** [comment]
Yes, definitely! The Board has been trying to get the dates that we are missing since this issue was opened. I will update the doc with what we've got later today (if you grant me edit access :P).

**Comment by Jambrose777** [comment]
Shared with Edit access!

**Comment by Jambrose777** [comment]
I see someone has updated the WRC page 1 minute ago
![image](https://user-images.githubusercontent.com/11577241/51295280-e95dfe80-19e4-11e9-87ae-582411ce3ca5.png)
as far as I can tell this is far from what we intend to have (actually they deleted Lucas's start date)

**Comment by lgarron** [comment]
> as far as I can tell this is far from what we intend to have (actually they deleted Lucas's start date)

I updated my latest term. I actually can't add my non-leadership term, because the page thinks I'm demoting myself.

On top of that, I can't find the date I started my co-chair/leadership term the first time.

**Comment by AlbertoPdRF** [comment]
I added what I could to the spreadsheet, and also shared it with others who may help finish completing it!
