### ISSUE TITLE
Make import registrations from CSV feature visible once needed

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#3756]
The registrations import implemented in #3726 is hidden for now (https://github.com/thewca/worldcubeassociation.org/commit/61e9e65f3bcbcee6192a011fc56b7f6c4b142414). This commit should be reverted when we importing the registrations becomes necessary (e.g. for wca-live and groupifier-next to work).

**Comment by LinusFresz** [comment]
I think this can be closed due to https://github.com/thewca/worldcubeassociation.org/pull/3841 being implemented?

**Comment by jonatanklosko** [comment]
Good point, thanks!
