### ISSUE TITLE
Registrations for nonexistant events

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#377]
If someone removes an event from a competition, there can be people who have already registered for that event. This results in pretty funky behavior. Copy pasting an email with Oliver about this:

```
I, [2016-02-03T09:30:54.263721 #31398]  INFO -- : Started PATCH "/competitions/HungarianNationals2016/registrations/all" for 213.222.165.69 at 2016-02-03 09:30:54 +0000
D, [2016-02-03T09:30:54.265401 #31398] DEBUG -- :   ^[[1m^[[36mUser Load (0.3ms)^[[0m  ^[[1mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 378  ORDER BY `users`.`id` ASC LIMIT 1^[[0m
I, [2016-02-03T09:30:54.266600 #31398]  INFO -- : Processing by RegistrationsController#update_all as HTML
I, [2016-02-03T09:30:54.266653 #31398]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "registration-90584"=>"1", "registrations_action"=>"accept-selected", "competition_id"=>"HungarianNationals2016"}
D, [2016-02-03T09:30:54.279122 #31398] DEBUG -- :   ^[[1m^[[35mCompetition Load (11.8ms)^[[0m  SELECT  `Competitions`.* FROM `Competitions` WHERE `Competitions`.`id` = 'HungarianNationals2016' LIMIT 1
D, [2016-02-03T09:30:54.279651 #31398] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `Competitions`.* FROM `Competitions` WHERE `Competitions`.`id` = 'HungarianNationals2016' LIMIT 1^[[0m  [["id", "HungarianNationals2016"]]
D, [2016-02-03T09:30:54.281138 #31398] DEBUG -- :   ^[[1m^[[35mUser Exists (0.2ms)^[[0m  SELECT  1 AS one FROM `users` INNER JOIN `competition_organizers` ON `users`.`id` = `competition_organizers`.`organizer_id` WHERE `competition_organizers`.`competition_id` = 'HungarianNationals2016' AND `users`.`id` = 378 LIMIT 1
D, [2016-02-03T09:30:54.281522 #31398] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `Competitions`.* FROM `Competitions` WHERE `Competitions`.`id` = 'HungarianNationals2016' LIMIT 1^[[0m  [["id", "HungarianNationals2016"]]
D, [2016-02-03T09:30:54.282581 #31398] DEBUG -- :   ^[[1m^[[35mRegistration Load (0.2ms)^[[0m  SELECT  `Preregs`.* FROM `Preregs` WHERE `Preregs`.`competitionId` = 'HungarianNationals2016' AND `Preregs`.`id` = 90584 LIMIT 1
D, [2016-02-03T09:30:54.283848 #31398] DEBUG -- :   ^[[1m^[[36m (0.8ms)^[[0m  ^[[1mBEGIN^[[0m
D, [2016-02-03T09:30:54.284745 #31398] DEBUG -- :   ^[[1m^[[35mUser Load (0.2ms)^[[0m  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 378 LIMIT 1
D, [2016-02-03T09:30:54.285752 #31398] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `Competitions`.* FROM `Competitions` WHERE `Competitions`.`id` = 'HungarianNationals2016' LIMIT 1^[[0m  [["id", "HungarianNationals2016"]]
D, [2016-02-03T09:30:54.286743 #31398] DEBUG -- :   ^[[1m^[[35m (0.1ms)^[[0m  ROLLBACK
I, [2016-02-03T09:30:54.287137 #31398]  INFO -- : Completed 422 Unprocessable Entity in 20ms (ActiveRecord: 13.3ms)
F, [2016-02-03T09:30:54.289123 #31398] FATAL -- :
ActiveRecord::RecordInvalid (Validation failed: Events invalid event ids: 333fm):
  app/controllers/registrations_controller.rb:104:in `block in update_all'
  app/controllers/registrations_controller.rb:102:in `each'
  app/controllers/registrations_controller.rb:102:in `update_all'
  lib/middlewares/warden_user_logger.rb:10:in `call'
  lib/middlewares/fix_accept_header.rb:12:in `call'
```

It looks like you were trying to update registration 90584, which corresponds to https://www.worldcubeassociation.org/registrations/90584/edit, Niki herself? Is it possible that Niki registered for 333 fewest moves, and then you removed the event?

I'm not sure what the best solution to this is. Instead of a validation error, we could just remove all invalid (no longer offered) events when you try to update a registration that is registered for an event that is not being offered.. When events are removed from competitions, should we go and update all the corresponding registrations to remove their registration for the event? I almost feel that we should not allow removal of an event unless nobody is registered for that event...

**Comment by jfly** [comment]
This also affects the number of events we show people as being registered for on a registrations page such as this: https://www.worldcubeassociation.org/competitions/RiseofCubersTagum2016/registrations

**Comment by larspetrus** [comment]
I think deleting registrations when an Event is deleted is the right solution. If an event doesn't happen in the real world, it shouldn't be in the DB.

The deletion is easily managed in Rails with **dependent: :destroy** on the relationship.

**Comment by jfly** [comment]
Deleting registrations for events that aren't happening is an option, I was thinking it would be courteous of delegates to notify people that events are being removed, along for a reason (and that they could keep track of who they've notified by seeing who is still registered for an event that is not happening). I am also thinking ahead towards a world where we support payment for registration, in which case we'd probably want to refund people who paid for events that aren't happening.

**Comment by larspetrus** [comment]
I'd ignore those concerns until notifications and/or payments are actually implemented. It adds a lot of complexity and pain to try to adapt to potential future features on top of real current requirements. This is mostly the YAGNI principle argument, which we may not agree on.

That said, while I prefer the cascading deletes, making populated events undeletable is also a valid solution. The important thing is that the app stops corrupting the DB.

It's also important to clean up any remaining such bad data in the DB!

**Comment by timhabermaas** [comment]
I'm with @larspetrus, simply deleting the registrations sounds like the least complex way to fix this.

**Comment by jfly** [comment]
Ok, on further digging, there is no relationship between events at a competition and registrations for a competition. Instead, each Registration has a string field (`eventSpecs`) with a space separated list of event ids. See https://github.com/cubing/worldcubeassociation.org/blob/9afd301346c5cb65c64a1c5f486de29580e17a35/WcaOnRails/app/models/competition.rb#L302-L306. I'm pretty sure this means we can't make use of Rails's `dependent: destroy` feature. Given that mess of a schema, I think it might be simpler to disallow deletions, which I've done in https://github.com/cubing/worldcubeassociation.org/pull/385.

**Comment by pedrosino** [comment]
I guess the best way is to change the schema and give the
organizer/delegate a warning if they try to delete an event which has
registrations already.

Then If they confirm, it would delete all related registrations too.
Em 09/02/2016 02:23, "Jeremy Fleischman" <notifications@github.com>
escreveu:
