### ISSUE TITLE
Schedule Calendar View All venues at once[Feature Request] 

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3785]
**Issue:**
When having a competition be multiple venues, the schedule will appear on 2 different tabs, but never all at once. This can be completely confusing as whenever a competitor goes to the schedule, they will only see the one day.
![image](https://user-images.githubusercontent.com/11577241/50731144-7bcfe980-112b-11e9-872e-74fa54615765.png)

**Describe the solution you'd like**
Have a select all venues option at the top that is automatically selected.

**Describe alternatives you've considered**
I'm not sure how to get the schedule to appear on 1 tab without listing it as the same venue. (I could do this by naming the Venue "Competition Venue" and having the rooms be the actual buildings, but I feel that is event more confusing).

For those with admin access, you can view the schedule at this competition as an example: https://www.worldcubeassociation.org/competitions/PeachState2019#competition-schedule

**Comment by Jambrose777** [comment]
There's also a bug involved with this:
The link at the top of the page below the venue selection (in the picture, "Paulding County Senior Center"). This will always link to the competition coordinates,  which in the case of multiple venues will leave one of the selected venues to the wrong place.

**Comment by Jambrose777** [comment]
The competition mentioned ended up being announced with the alternative mentioned. I can create another competition with this if needed.

**Comment by jfly** [comment]
>whenever a competitor goes to the schedule, they will only see the one day.

Do you mean "only the see the one venue"? I agree that this is confusing.

It seems reasonable to me to want to show the schedules all venues of a competition at once, and maybe that should even be the default. I'm curious what @viroulep thinks here.
