### ISSUE TITLE
Records Order

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3787]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11577241/50740734-eaab5200-11c0-11e9-83d8-98226fb68d60.png)
These records show up in the incorrect order. They have the same date circa, but the faster records display lower on the list.

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/results/regions.php?regionId=&eventId=333fm&years=&mixHist=Mixed+History

**Expected behavior**
Fastest times are more at the top?
- This isn't as easy as it sounds. Take for instance If the average was also broken at the same date circa, where would this go in the list? So I'm not for sure on a solution without having it look at the schedule, which is far off in the future if I recall correctly.

**Comment by Julio974-TheHexahedron** [comment]
According to 9i2 (https://www.worldcubeassociation.org/regulations/#9i2), Jaziorski and Rafalski's world records shouldn't be counted.
Also, maybe change a bit the code to allow double records (single and average broken at the same time) to be on a single row?

**Comment by Baiqiang** [comment]
@Julio974-TheHexahedron In fact, the records were not broken on the same day but our database doesn't record on which day it was broken.
