### ISSUE TITLE
Bookmarking option for upcoming competitions where registration hasn't been opened

### ISSUE THREAD

**Issue by willgwizz** [thewca/worldcubeassociation.org#3797]
**Is your feature request related to a problem? Please describe.**
Whenever a new competitions are announced, competitors who are interested would definitely want to be able to easily keep track of these easily. Now in 2019 where competitions are announced much ahead of time, potential competitors may find it hard to keep track of multiple competitions of interest as "My Competitions" doesn't include them.

**Describe the solution you'd like**
A bookmarking system where such competitions can be made available for competitors to view in "My Competitions" where they can also easily cancel competitions they've decided to not attend. Additionally, perhaps organizers could have access to view the number of people who've bookmarked their competition prior to registration opening.

**Describe alternatives you've considered**

**Additional context**
Competitors will then be able to easily manage all their competitions whether past, present or future. Organizers will also be able to anticipate the number of competitors that will register, this will be really helpful especially in scheduling, logistics and overall management.

**Comment by jfly** [comment]
Thanks for the suggestion, @willgwizz! I would be supportive of a feature like this if someone wants to spend the time to build it.

**Comment by Mollerz** [comment]
This could also drop a couple of notifications to you for when a competition is say a few days from opening, and another one (and potentially an email?) for when there is only an hour left before registration opens.

As we are well aware, some competitions fill up in only a couple of hours, if not a few minutes in some very rare cases. Having these notifications could be very useful to avoid missing out.

**Comment by AlbertoPdRF** [comment]
I've labeled this as a good second issue.

**Comment by timreyn** [comment]
I'm going to work on this.

**Comment by timreyn** [comment]
Here's what I've done (still working on tests and cleanup)

- Add a bookmark icon to the competition page when signed-in 
![not_bookmarked](https://user-images.githubusercontent.com/3885929/63234373-0cfb5880-c203-11e9-9ce2-6ee32aff93a2.png)
![bookmarked](https://user-images.githubusercontent.com/3885929/63234380-0ff64900-c203-11e9-9517-0ddd73866686.png)

- Add the list of bookmarked competitions to "My Competitions"
![my_competitions_bookmarked](https://user-images.githubusercontent.com/3885929/63234423-28666380-c203-11e9-849c-231155ca2370.png)

- Sends an email to all users with the competition bookmarked, as well as the delegates and organizers, 24 hours before registration opens.

- If there are multiple registration periods, re-send the email 24 hours before registration re-opens, but don't send to people who are already registered.

## Feedback requested:

- Is the term "bookmarked", and the "bookmark" icon, self-explanatory?  Would another term be clearer, like "starred" or "saved"?
- Is the bookmark icon on the competition page too prominent?  If so, any thoughts on where else it should go?
- Should we surface the list (or number) of users who have bookmarked a competition to organizers + delegates?  I think I won't do that in this PR, but it could be useful as a follow-up.

**Comment by AlbertoPdRF** [comment]
Wow, this looks nice! :rocket: 

Here's my personal view on your feedback:

> - Is the term "bookmarked", and the "bookmark" icon, self-explanatory? Would another term be clearer, like "starred" or "saved"?

I think it is! Just in case you haven't yet, adding a tooltip that says "Bookmark" when hovering over the icon should help.

> - Is the bookmark icon on the competition page too prominent? If so, any thoughts on where else it should go?

I don't see any other place where it would be better right now, but maybe others do. What I would be interested is in seeing how this looks like for a championship competition.

> - Should we surface the list (or number) of users who have bookmarked a competition to organizers + delegates? I think I won't do that in this PR, but it could be useful as a follow-up.

The number of users that have bookmarked a given competition would be something cool to know in my opinion. Maybe it could even be publicly displayed.

As another possible follow up, we could also use it this to email non-registered users that have bookmarked a given competition with the live results link once the competition has started (although that will have to wait until we offer a live results link on the website :stuck_out_tongue: )

**Comment by timreyn** [comment]
Thanks @AlbertoPdRF !  Yes, I have a tooltip as well.

Here's a championship: 
![not_bookmarked_championship](https://user-images.githubusercontent.com/3885929/63262447-f7fae580-c253-11e9-9ea2-a3e946715bf0.png)

**Comment by willgwizz** [comment]
Hey guys!

It's amazing to see the progress so far!


  *   Is the term "bookmarked", and the "bookmark" icon, self-explanatory? Would another term be clearer, like "starred" or "saved"?

In my personal opinion, I think 'bookmarked' is more suitable as it denotes something you just want to keep in view rather than make it straight out important.


  *   Is the bookmark icon on the competition page too prominent? If so, any thoughts on where else it should go?

I agree with Alberto. But just to add on, perhaps there could be a trophy symbol (like on the actual competition page) next to bookmarked championship competitions to make those stand out more(?)


  *   Should we surface the list (or number) of users who have bookmarked a competition to organizers + delegates? I think I won't do that in this PR, but it could be useful as a follow-up.

In terms of organizing, I really think it would be a good way of gauging the expected number of registrants even before registration opens for a given competition. This way, organizers can (if possible) even adjust the competitor limit to suit the demand, especially when it comes to championship competitions. The numbers can probably also be an indicator of the demand for competitions in a given area.

With regards to making the numbers public, I don't see anything wrong with that, I think the community would be interested in knowing too. The live results link sounds great as well!

Anyways, thanks for all the effort put into making my suggestion a reality, definitely looking forward to see it on the website!

Best,
William Gan (WCT)



________________________________

**Comment by timreyn** [comment]
Thanks for the feedback William!

I filed #4508 to track adding an icon to the my_competitions page.

I'll plan to add the number of users who have bookmarked a competition as well, though I may not include this in the first PR as it's already a bit large.

**Comment by pedrosino** [comment]
>Is the bookmark icon on the competition page too prominent? If so, any thoughts on where else it should go?

I think the place is right, but it could be a little smaller. Right now it's taller than the competition name, which seems a bit exagerated.
Also, I'm not sure about the colors. It may not be that clear that all-black means "active". Perhaps make it yellow or something else not too distracting. Or make the "empty" one a shade of gray instead of black border.

**Comment by AlbertoPdRF** [comment]
> Here's a championship:
> ![not_bookmarked_championship](https://user-images.githubusercontent.com/3885929/63262447-f7fae580-c253-11e9-9ea2-a3e946715bf0.png)

Thanks! Just a nitpick: I think it would look better/clearer if the bookmark icon was always the left-most one.

> I'll plan to add the number of users who have bookmarked a competition as well, though I may not include this in the first PR as it's already a bit large.

Maybe another follow-up issue is due listing all the possible future additions we have discussed about? Just so they don't fall through the cracks.

**Comment by timreyn** [comment]
I made the empty one lighter gray, and put it before the championship trophy, I think it looks better now!

I also added the number of users who have bookmarked.

![not_bookmarked_championship](https://user-images.githubusercontent.com/3885929/63391339-13fba580-c380-11e9-9177-12774a8ce507.png)

I think the only remaining suggestion to track is emailing users when the live results link is available.  Is there an issue / a plan to have a live results link on the website?  This sounds like a part of that project, rather than a standalone issue.

**Comment by AlbertoPdRF** [comment]
> I think the only remaining suggestion to track is emailing users when the live results link is available. Is there an issue / a plan to have a live results link on the website? This sounds like a part of that project, rather than a standalone issue.

I don't think there's a plan at the moment. We had a small discussion about it on Slack, but nothing else that I can think of at the moment.
