### ISSUE TITLE
Sending multiple "The results of competition are posted." emails

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3802]
**Describe the bug**
Whenever posting results If a WRT member clicks on the button a second time or accesses the post link. The post is blocked by the website for a duplicate title, however a second email is sent to all competitors of the competition.

**To Reproduce**
Post the results announcement twice.
Button:
![image](https://user-images.githubusercontent.com/11577241/50942847-067c5580-1458-11e9-9499-de4cfbffcaeb.png)
Specific link (replace competitionID with the competition):
https://www.worldcubeassociation.org/competitions/competitionID/post/results?event_id=333

**Comment by jfly** [comment]
Thanks for the report, @Jambrose777! Here's the relevant code: https://github.com/thewca/worldcubeassociation.org/blob/65df8c75f2fb4eed5df790397e3af93c928ec621/WcaOnRails/app/controllers/competitions_controller.rb#L345-L348

I think an acceptable fix would be to not allow posting the results announcement if the results have already been posted.

**Comment by jonatanklosko** [comment]
Fixed in #4072.
