### ISSUE TITLE
Competitions can last 7 days

### ISSUE THREAD

**Issue by jamesquinn1** [thewca/worldcubeassociation.org#3809]
**Describe the bug**
WCA website says comps can last 6 days, but competitions can be set to be 7 days.

**To Reproduce**
Set a competition to 7 days

**Expected behavior**
Either say 7 days is limit or make 6 days the limit.

**Comment by jfly** [comment]
Oh, nice find! I've sent out a PR with a fix for this. Thanks @jamesquinn1!
