### ISSUE TITLE
Waiting list public visibility

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#3810]
Waiting lists are not displayed publicly for obvious reasons, so organizers and Delegates are contacted to ask how big a waiting list is and what position said competitor is on the waiting list.

An extra field to be included in registration requirements when the limit is reached could display this information. Something like "The registration limit for this competition has been reached. The current waiting list has XX people on it."
During the creation of the competition page the Delegate should be given the choice to select either 'Waiting list is counted by paid' and 'Waiting list is counted by total including unpaid' since some competitions require payment to order the waiting list. This requires some level of implementation of elements of #3451 but doesn't require the automatic registrations in #328 

Additionally, there could be a column appended to the right side of the table on https://www.worldcubeassociation.org/competitions/mine page displaying waiting list position. This would stop members having to contact organizers/Delegates while maintaining the privacy of waiting list order.

**Comment by Mollerz** [comment]
https://github.com/thewca/worldcubeassociation.org/issues/2413 Also covers having a separate waiting list section.

**Comment by c-goodyear** [comment]
For starters, it would lead to more congestion of the information pages, and more confusion especially for first timers registering. It also doesn't serve much of a purpose, the registrations are public because those people will (should) be attending the competition.
It also stops people not cancelling (if they can no longer attend) on purpose if they don't want the waiting list #1 to get a spot.
IMO it's just as irrelevant as wanting removed/deleted registrations to also be publicly visible.

**Comment by viroulep** [comment]
FYI these information are actually "public": except from who have paid what and when: pending and deleted registrations are in the public export of the database; so if you setup the website locally (or just get the developer dump, or just go on staging which may lag behind) then you'll be able to log in as a competition manager and see when everyone submitted their registration (it's not directly the waiting list, but it's reasonable to assume people paid pretty much immediately after registering).

**Comment by SAuroux** [comment]
It should be added that many competition use payment system other than stripe. In such cases the WCA website cannot give accurate information about the current state of a waiting list.

**Comment by wcajaepark** [comment]
Agree that waiting list itself should not be public (it can create unnecessary confusion most of all) but we really need to have information whether you're on the waiting list or not. With current system, if you're the first timer, you did everything required (registering and making payment) but there is no information about where you are. I'm getting tons of emails from waiting listed competitors for almost every competition. People rarely read all the regulations and they may not know what the competitor limit is nor what happens if you register after that. It will be great to show you that you're in the waiting list with reasons - not made payment or competitor limit has been reached.

**Comment by c-goodyear** [comment]
We've been contacted by a parent of a potential competitor today which reminded me of this.

Because the registration period is still ongoing but the competitor limit had been reached, it would be great to have some kind of text in a more prominent location than just the cream box that currently gets displayed on the "register" page when the competitor starts their registration to a full competition.

**Comment by dunkOnIT** [comment]
@DanielEgdal thanks for the contribution - have assigned you to the issue here for the sake of clarity that is has an open PR/is being worked on.
