### ISSUE TITLE
Not all event names work well in a sentence

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#384]
For example, the name for [444](https://github.com/cubing/worldcubeassociation.org/blob/9afd301346c5cb65c64a1c5f486de29580e17a35/WcaOnRails/app/models/event.rb#L87) is "4x4 Cube". This doesn't work so well in a sentence such as "There are still people registered for 4x4 Cube".

**Comment by AlbertoPdRF** [comment]
I don't really see a problem here. I'm closing this one, although feel free to re-open it if you think it's something we should really handle.
