### ISSUE TITLE
WCAT, not WCAC

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#3844]
On the about [page](https://www.worldcubeassociation.org/about) the following is displayed:

"WCA Competition Announcement Team (WCAT): Henrik Buus Aagaard (leader), Alexander Cohen, Clément Cherblanc, Daniel Vædele Egdal, Ethan Pride, Henry Savich, Jacob Ambrose, Nicolas Perez, and Wilson Alvis (陈智胜) 
This **_committee_** has the role to approve and announce WCA Competitions and ensure such announcements adhere to WCA quality standards."

"committee" should be changed "team" here because WCAT is a Team, not a Committee

**Comment by jfly** [comment]
Fixed by #3845
