### ISSUE TITLE
Do not actually delete registrations, instead mark them as deleted

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#386]
Right now, if an organizer clicks a link such as https://www.worldcubeassociation.org/registrations/91492/edit, they get a pretty confusing error message: "The page you were looking for doesn't exist." I think we should do the following:
- Create a custom 404 page for this route that says something nice like "the registration you were looking for doesn't exist, perhaps it was deleted?" I'm not sure what the right way is to have custom 404 messages, right now we're just throwing a 404 and letting nginx handle it, I think. @larspetrus, do you know what the right way to do something like this is?
- Bonus points: Don't actually delete registrations from the database, instead mark a "rejected_by" flag, and then we can display a very useful message to people following the link: "This registration was rejected by Joe"

**Comment by larspetrus** [comment]
It seems hard to hack Rails to display something resource type specific for a missing resource. The framework is built on things existing in the DB.

The leading Soft Delete gem seems to be https://github.com/rubysherpas/paranoia, but what we want isn't really Soft Delete.

So I think the manual route is not only the right solution, but the easiest solution.

**Comment by jfly** [comment]
Closing in favor of #1005.
