### ISSUE TITLE
Modification of MISSING_RESULTS_ERROR

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#3880]
We (WRT) ran into a minor problem after #3127 was pushed live, as we failed to properly think through the case when a planned event was eventually not held. Currently, this triggers an error message referencing to WCAT (see [competition_results_validator.rb](https://github.com/thewca/worldcubeassociation.org/blob/9c58c1a1f77187052dfd2321e6493d2cfaa4c93a/WcaOnRails/lib/competition_results_validator.rb#L11)), while the delegate crash course refers to WRT.  We have now discussed with WCAT and agreed on the following action:

1. The MISSING_RESULTS_ERROR should be transformed to a warning.
2. The current message needs to change to refer to WRT instead of WCAT. Proposal: "Missing results for %{event_id}. The event is not present in the results but listed as an official event. Please leave a comment about that to the WRT."

**Comment by Jambrose777** [comment]
I can take care of this!
