### ISSUE TITLE
Teams should be renamed to something else (groups?)

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#3886]
We now have Committees/Teams, banned competitors, Officers, and soon Councils (#3884) all handled as `teams` on the website, which is confusing and error-prone. Renaming `teams` to `groups` and a bit of clean up seems necessary at this point.

**Comment by jfly** [comment]
I like the term "group", it only potentially conflicts with "google group", and I think that's a manageable bit of confusion.

**Comment by danieljames-dj** [comment]
Assigned this to myself because I'm already working on this. The discussion on the model of groups (or rather user_groups) can be found here: https://github.com/thewca/worldcubeassociation.org/issues/8122.

**Comment by maxidragon** [comment]
I think this can be closed, as we now have `user_groups` and `user_roles` tables.
