### ISSUE TITLE
Windows development issues

### ISSUE THREAD

**Issue by flee135** [thewca/worldcubeassociation.org#393]
- [ ] phpMyAdmin doesn't work on Windows. Workaround is to neuter https://github.com/cubing/worldcubeassociation.org/blob/9ed2e83476540e9d2279c3c25b658443550585b9/webroot/results/admin/phpMyAdmin/libraries/Config.class.php#L1184

**Comment by jfly** [comment]
I've added a link to this issue to the README: https://github.com/cubing/worldcubeassociation.org#run-in-vagrant-easier-and-gets-everything-working.

**Comment by jfly** [comment]
I'm closing this issue. I don't suggest that people use vagrant for local development anymore.
