### ISSUE TITLE
Increase WCA ID claim automation using WCA registration data

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#3933]
**Is your feature request related to a problem? Please describe.**
I find it frustrating the (admittedly small) amount of time I spend managing WCA ID claims. I average 0.9 WCA ID claims per day and it is annoying spending 2 minutes of my time doing something a computer could do instantaneously. Especially since it is tedious to do it via mobile, which mean claims pile up and I get home from work and sometimes have 5+ to churn through.

While each WCA ID claim is small, they add up.

**Describe the solution you'd like**
This is my process for approving a WCA ID claim:

- Has WCA ID competed exclusively at competitions I have delegated? If yes, continue.
- View registration of competition(s) that competitor attended - match competitor name to WCA ID name and check email address(es) used for registration.
- If email address(es) used for registration match claiming account email, approve. 

All but 3 claims I have managed have followed this process, hence the frustration.

It would be good to have a system that uses similar logic:
If competitions matching WCA ID were exclusively using WCA registration, match names, check email addresses. If all WCA registration, and all emails match, approve.

If we still want a manual step, then include in the email to delegates a "recommendation". It would be also good to see where it failed either WCA registration not in use (I should forward to the delegate who has the registration data, or manually check it myself) or email mismatch (I should email the claimant and ask for extra information).

**Describe alternatives you've considered**
Either this or I continue wasting ~45 minutes a month that could be more productively spent (and I'm sure other delegates feel the same way). Happy if others have different solutions though.

**Comment by jfly** [comment]
Hey @EdHollingdale, thanks for the report. Sorry about this, it was never meant to be a long term solution. See https://github.com/thewca/worldcubeassociation.org/issues/21 for a bit more history about why this hasn't happened yet.

I can say with some confidence that the "Has WCA ID competed exclusively at competitions I have delegated? If yes, continue" was not usually true for me when I was a delegate. Do you feel like this is an important check to have?

I'm going to close this issue, let's continue the conversation over on #21.
