### ISSUE TITLE
Clarify that on-the-spot registrations are not accepted when the competitor limit has been reached

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/worldcubeassociation.org#3935]
The current way the registration requirements are phrased is misleading when there is a competitor limit and on-the-spot registrations are being accepted. It should be clarified that on-the-spot registrations will only be accepted when the competitor limit hasn't been reached, to prevent unregistered competitors from thinking that the competitor limit only applies to online registrations and that on-the-spot registrations do not apply to this limit.

See below for example.

![screenshot 2019-02-20 08 17 12](https://user-images.githubusercontent.com/5139750/53094809-2be59000-34e9-11e9-8e70-95ae23af7022.png)

I suggest that the line about on-the-spot registrations be changed to:  

*On-the-spot registrations will be accepted with a base registration fee of [cost] **if the competitor limit has not been reached by [online registration end date].***

(Side note: "On the spot" should be "On-the-spot" since it is a compound adjective that is directly in front of a noun).

**Comment by ligio90** [comment]
Good point! If nobody objects this I could implement this

**Comment by jfly** [comment]
Yes please go for it, @ligio90! This sounds like a good change to me. Thanks for the report, @sarahstrong314
