### ISSUE TITLE
Social media links are over homepage link

### ISSUE THREAD

**Issue by zeecho** [thewca/worldcubeassociation.org#3955]
**Describe the bug**
When you want to click on the lower part of the big "World Cube Association" text above social media logos, it opens one of the social media. I'm having the feeling it's mostly on "big" screens (meaning I do not have the issue when the menu becomes a dropdown).

**To Reproduce**
Click on the lower part of the "L" of "World Cube Association". It should open reddit.

**Expected behavior**
Going back to the homepage when we click on "World" instead of opening a social media.

**Screenshots**
For instance, here is the clickable area of the twitch logo:
![2019-02-26-102745_3360x1050_scrot](https://user-images.githubusercontent.com/5508488/53402943-01954600-39b3-11e9-9209-f287c6d86aab.png)

**Desktop:**
 - OS: Ubuntu 16.04
 - Browser: Firefox 65 and Chromium 71

**Comment by jfly** [comment]
@AlbertoPdRF, do you have time to look into this? As always, we should make sure that whatever we do here works well on desktop and mobile.

**Comment by AlbertoPdRF** [comment]
Not really, sorry! I won't be much available until March is over :confused:
