### ISSUE TITLE
Schedule - Calendar View is very dense & colour is desaturated

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#3956]
Currently the default view is 30 minutes per row, and this is unable to be changed for the competitor view of the schedule. With lots of finals and small rounds taking place it makes it nearly impossible to read.

Also for some reason the colours within the calendar view are very desaturated. In the UK I've been setting up the schedule view with the blue and red colours from the UK flag when there are multiple stages. However on the competitor view it shows up with much less colour than anticipated. I had a root around the files and cannot find the reason for this...

For the calendar view, I suggest the default view should be changed to 15 minutes per row (very easy to change in the files from what I can see), and allow an option to change it similar to the editing view (a bit more work).

**Comment by jfly** [comment]
I think changing this to 15 minutes is a good default, and adding an option to change the default feels like something we can do separately.

**Comment by jfly** [comment]
Oh, sorry, I missed the part about color being desaturated. @Mollerz, could you provide a link and/or screenshots demonstrating that issue?

**Comment by viroulep** [comment]
I assume that's because fullcalendar modifies the original color?
Its default behavior is to create a background color slightly different, and add another layer of the desired color slightly smaller (to create a border effect); but it was rather ugly so I had to remove the layer IIRC.

**Comment by Mollerz** [comment]
@jfly Sorry I can't provide a picture just now, but have a look at UK Championship 2019 calendar schedule, and have a look at the Union Jack - the RGB values input are correct, but obviously the colours are very different. This seems to be because of what @viroulep has said - this desaturated colour is intended to be a border or a different layer and not the main colour.

**Comment by Jambrose777** [comment]
For this issue, the first part of changing the default to 15 minutes was merged. The color saturation seems to be fixed now, so I am closing this PR, please feel free to reopen if you notice this still :D
