### ISSUE TITLE
Remove "<Competition> is not confirmed" Notification

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#3959]
The current iteration of the notifications panel aren't _really_ notifications, and I would like to suggest a small change.

I have a template competition created with all the information relevant to our area filled out, including tabs with lots of information and instruction for organisers to follow. I also tend to create competition pages quite early for competitions to allow organisers enough time to fill in information, etc.

These sit in "My Competitions" which is absolutely fine, and I'm almost certain that most organisers will access edit pages from here. But unfortunately it means I'm always going have at least a (1) sitting in the top right of my WCA pages, when in reality this is not a notification, and is not really important to me.

I don't know how useful this notification is for other people, and maybe we should get some feedback on it? But I would be in favour of removing it.

**Comment by cubewhiz** [comment]
I would support this change. I like keeping my notifications at 0 so I know that I have no pending actions.

**Comment by EdHollingdale** [comment]
I also have a template competition and typically several unannounced competitions on the go so I would also appreciate this change.

**Comment by ligio90** [comment]
I'm working on it
