### ISSUE TITLE
Competitors Page does not update when new event is added by Psych Sheet does

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#3987]
**Describe the bug**
When an organiser/delegate adds an event to someone's registration, the Competitors page does not update to have the little picture of that event next to their name. However when looking at the psych sheet for that event it is shown, and it is also shown when (as an organiser/delegate) you look at their registration or on the main registrations edit page when you click "show events".

**To Reproduce**
1. Go to CompetitionName/edit/Registrations and edit a registration, adding an event (click save etc.)
2. Go to CompetitionName/Registrations and that new event does not appear next to their name
3. Go to CompetitionNameRegistrations/pysch-sheet/AddedEventId and that competitor does appear

**Expected behavior**
On competitors the event appears next to the competitors name when it is added.

**Comment by jfly** [comment]
This sounds likely to be a caching issue. I imagine the problem eventually goes away. See https://github.com/thewca/worldcubeassociation.org/blob/00b66534978cd467eff5c0ecef0e12971deb2bcf/WcaOnRails/app/views/registrations/index.html.erb#L4-L9

Maybe when you update a registration from the `<compname>/edit/registrations` page, the registration's `updated_at` doesn't change?

**Comment by Jambrose777** [comment]
This caching issue seems to be fixed now, closing this, but feel free to reopen if it is still a problem :)
