### ISSUE TITLE
/.well-known/change-password

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#3991]
**Is your feature request related to a problem? Please describe.**
There is a standard for apps aware of credential management, specifically for asking a site to send you to the place to change the current user's password: https://wicg.github.io/change-password-url/index.html

**Describe the solution you'd like**
Redirect `/.well-known/change-password` to [`/profile/edit?section=password
`](https://www.worldcubeassociation.org/profile/edit?section=password
)

**Comment by LukasBatema** [comment]
I will try if that’s okay, it might be a little though
