### ISSUE TITLE
Upload results: right to left names messed up in warning messages

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#4000]
**Describe the bug**
In the email sent to the WRT when posting results (and maybe on the "upload results" page of a competition), names containing right to left characters are not displayed properly.

**To Reproduce**

The issue was detected when posting results for Alborz Green Cup 2019, as the results contains sensitive information the WST person working on it should contact either the WRT or me to get the data to reproduce the bug.

(it should be easily reproducible by submitting the same json locally)

Here is an excerpt from the mail:
```
Please find below the list of warnings for the competition's results: 
Warnings detected in persons

Wrong birthdate for Ali Niazi (علی نیازی) (2018NIAZ01), expected '' got '****'.
```

**Comment by jfly** [comment]
Potentially helpful page https://www.jflei.com/temp/text-direction-test/. Relevant issue: https://github.com/thewca/worldcubeassociation.org/issues/1116.

**Comment by Jambrose777** [comment]
I can confirm that this was some issue with @SAuroux's email, not sure why it happened yet, but I don't think there's any issues with the wca's codebase for this.
