### ISSUE TITLE
Create and automate regional groups on GSuite

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#4002]
(Breaking this out from my email thread with the Board titled "Re: Moving the regional groups to GSuite")

We'd like the website to manage mailing lists for delegate "teams" aka "delegate regions". This introduces some trickiness: we don't have a very firm data model for representing "delegate regions" (see [Delegate geographic information](https://docs.google.com/document/d/1a9IyCxwGehc4uUnPSi78W6mKZMj1MN8aCIqc25RiHqk/edit) for more information about this).

This is actually pretty easy for us to do (and we could hack it together today without big structural changes if we wanted to), all the pain is just around hypothetical situations where we change up the regions. Has anyone thought through those hypotheticals and decided how we want to handle them? Stuff I'm worried about:

1. Managing archive access. For example, there used to be a USA West delegate region. If we had created that mailing list back then, who should have access to it today?
   - We're going to avoid this problem by setting up the groups to be "Public to everyone on worldcubeassociation.org"
2. What happens if someone emails one of these legacy groups? Should we make it impossible for people to email these groups? That would cause some noise whenever we change groups (existing email threads would break as people try to reply to them), but might be a short term pain that is better than the alternative of letting people post to legacy groups.
  - @AlbertoPdRF says "I think yes, we should make it imposible for people to email legacy groups."

It also may be that the smartest decision is to just not worry about any of this, and go ahead and implement some regional mailing lists according to whatever system we want to, and figure out how to change it when/if the time comes. My gut feeling is that since we're expecting changes as we figure the region leads project, we should at least wait to see how that goes before we start working on regional mailing lists, but I will defer to anyone who feels otherwise about that.

**Comment by EdHollingdale** [comment]
What exactly would these regional groups be used for? They're certainly a nice thing to have, but I can't think of an email that I would have sent or received where it going to all Oceania Delegates would have been necessary. I don't see the reason for having a hundred GSuite groups if nearly all of them are unused. These groups would only be useful if we also changed standard practice for certain types of emails internally.

**Comment by LinusFresz** [comment]
One example is the use of these groups for organising multi-location
competitions. It's much easier so write to one European Delegate group (or
3 if we would use Western, Eastern and Northern European groups) instead of
collection mail addresses of 50+ delegates.

EdHollingdale <notifications@github.com> schrieb am Sa., 30. März 2019,
03:27:

**Comment by EdHollingdale** [comment]
@LinusFresz that is a very good point that I hadn't considered! I would still see the region lists as things that are used infrequently but they could be useful in a few cases.
