### ISSUE TITLE
Background refresh of rankings

### ISSUE THREAD

**Issue by Logiqx** [thewca/worldcubeassociation.org#4022]
The refresh process appears to be run directly on the live rankings table(s), leading to people seeing incomplete profiles for a short period of time.

This behaviour has recently been reported in Cyoubyx's friends:
https://www.facebook.com/groups/cyoubxfriends/permalink/2731447653548337/

Suggestion: The rankings could be build into a different table name which is renamed at the end of the process.

A more involved but neater solution is to build into a table name which is named / versioned according to when it was built and have a simple view on top which provides consistent access to the underlying data.

An added benefit of both of these approaches is that if the refresh should fail for any reason (e.g. unexpected MySQL error) then the rankings will not be left in a partial / inconsistent state.

**Comment by jfly** [comment]
Thanks for the report, @Logiqx! This is definitely not ideal behavior, but it's also not something we've prioritized working on.

Another way of getting a consistent view of data in mysql is to take advantage of doing everything in a transaction. I'm not familiar enough with the results upload process to say if that's something we could actually leverage here.

**Comment by Logiqx** [comment]
That's a very good point Jeremy since the RanksSingle and RanksAverage tables are pretty small in the grans scheme of things.

I decided to have a look at the Ruby code and since it is a straightforward change, I've submitted a pull request so that someone can review it and possibly implement in the near future.

Hopefully my change works as expected, I'm an experienced application and database developer but I'm not a Ruby / Rails guy and have no quick / easy way to test the change myself.

**Comment by Logiqx** [comment]
I see that you have CI set up for the WCA.org project. Very nice!

https://travis-ci.org/thewca/worldcubeassociation.org/builds/520199761?utm_source=github_status&utm_medium=notification

**Comment by Logiqx** [comment]
As an aside, I checked the rest of the project and this was the only instance of "TRUNCATE TABLE".

It is therefore my belief that similar problems do not exist elsewhere in the code.

**Comment by Logiqx** [comment]
Since my PR has been merged into master, I believe this issue can be closed.
