### ISSUE TITLE
Enable cron on staging server

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#4039]
A cron job on our staging server just clobbered our gsuite google groups with email addresses from staging. I've disabled cron on the staging server, but we should change things so that the staging server doesn't even have the secrets needed to talk to gsuite.

**Comment by viroulep** [comment]
wow that's scary!
any idea why that occur?
We've been running that for months and got no issue at all.

**Comment by jfly** [comment]
I think this has actually always been an issue, but we weren't running into it because cron was disabled on our staging server. I'm not sure why cron was disabled on staging, but I recently re-enabled it to make sure we keep refreshing our let's encrypt certificate.
