### ISSUE TITLE
Make it possible to query users by email address

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#4069]
(Pulled out from https://github.com/thewca/worldcubeassociation.org/issues/3759#issuecomment-456993520)

Right now, the "find a user" flow isn't great with some names. @Jambrose777 describing an issue he ran into:

> Since Ram Kumar is a very popular name, it shows up on the 4th page of the manage users and does not show up whenever selecting organizers. Since this organizer does not have a wcaid, I could not enter that either. I had to edit the account to include numbers then search for the new name to select the organizer, and then remove the numbers. This could probably be avoided by allowing the ability to add the organizer by email. I've added this to our wishlist issue.

**Comment by jfly** [comment]
@Mjic99 is going to look into this.

**Comment by AlbertoPdRF** [comment]
This issue got fixed on #4069, so I'm closing it!
