### ISSUE TITLE
Remove "Missing Averages" page

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4106]
Now that we have big cube BLD means, https://www.worldcubeassociation.org/results/misc/missing_averages/ is obsolete.
(It also covers "2-means", but I don't think those are worth keeping around on the official site.)

**Comment by AlbertoPdRF** [comment]
I'm adding this issue to https://github.com/thewca/worldcubeassociation.org/milestone/2 to make sure we don't forget to **not** port this :stuck_out_tongue:.

**Comment by jfly** [comment]
I think to remove this, we'd want to do the following:

  - [ ] Remove `index.php` from https://github.com/jfly/worldcubeassociation.org/blob/fd5a534f7b118cb192225d911aae4fcd98122969/webroot/results/.gitignore#L24
  - [ ] Remove `webroot/results/misc/missing_averages/update7205.php`: https://github.com/jfly/worldcubeassociation.org/blob/master/webroot/results/misc/missing_averages/update7205.php
  - [ ] Remove all references to `git grep update7205` (try `git grep update7205`) specific to `missing_averages`. (Don't remove the stuff for `evolution`!)
  - [ ] Remove all references to `missing_averages` (try `git grep missing_averages`)

After this, I think the `webroot/results/misc/missing_averages/index.php` file will still exist in on our prod server (when deploying, we don't remove untracked files), so we'll need to either ssh to the server and manually rm the file, or spin up a brand new server.

**Comment by denthebro** [comment]
Pinging this, because this still hasn't been fixed

**Comment by Jambrose777** [comment]
This will be fixed in https://github.com/thewca/statistics.

We would still need to deleted all together.

**Comment by campos20** [comment]
Fixed #6912. I took care of @jfly's list, except for the last two. git grep list only 2 lines and they look harmless

https://github.com/thewca/worldcubeassociation.org/blob/b1f0180616b6367cd0e95ab36ef6578b4679077b/webroot/results/includes/_parameters.php#L138-L139
