### ISSUE TITLE
Remove "the" in front of competition name

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#4116]
Currently when a competition is announced or results are posted the english language versions of the posts have a "the" before the competition name. E.g. "The Guildford Open 2020 will take place on January 18 - 19, 2020 in Guildford, Surrey, United Kingdom" or "Jayden McNeill won the Warm Up Sydney 2018 with an average of 7.53 seconds". 

The names of competitions do not require a "the" in front of them. I'd like to see the announcement and results posts edited to remove it. I don't know what impact it would have on non-English translations, but I assume these should be assessed as well.

**Comment by pedrosino** [comment]
I agree with you, it looks a little weird.

@SAuroux @sam596 @Baiqiang @Jambrose777 @danieljames-dj

**Comment by sam596** [comment]
I've always thought that too. It works when it's an "xxx Open" or "xxx Championship" but not in many other cases.

**Comment by Jambrose777** [comment]
The first the in each announcement is incorrect,
The second one in the competition announcement is correct as it is for the website.

**Comment by Mollerz** [comment]
Agreed this is just incorrect use of English in both cases in OP. In the announcements where it says "the [competition] website" is correct as @Jambrose777 mentioned as one is referring to the website as opposed to the competition.

With the current naming conventions both iterations of "the" as the examples are incorrect and should just be removed.

**Comment by Jambrose777** [comment]
Ya I/WRT can work on fixing this soon.
