### ISSUE TITLE
Add permissions for WEC

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#4131]
From Ethan Pride via email:
>Dear WST,
>
>In discussion with the board we have requested the following permissions for WEC members to aid with current and future investigations:
1: Have the ability to view Delegate reports on the website
2: Have the ability to see the registration lists for competitions using the wca registration system as well as payment status
>
>Could you please advise the board which permissions are required to grant this access?

The first one is easy: [can_view_delegate_report?](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L654)

As for second one, I'm not sure. There is https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L654 and https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L654

**Comment by pedrosino** [comment]
@jfly @jonatanklosko I'm leaning towards can_manage_competition?

What do you think?

**Comment by jonatanklosko** [comment]
Ideally we'd have a read-only competition mode and allow only that, but I imagine it would require a lot of changes, so `can_manage_competition?` sounds fine to me for now. @jfly?

**Comment by cubewhiz** [comment]
@jfly ?

**Comment by AlbertoPdRF** [comment]
@pedrosino please proceed with `can_view_delegate_report?` and `can_manage_competition?` for now, as we are blocking WEC's work.

Also, I think we should also open an issue to keep track of @jonatanklosko's comment:

> Ideally we'd have a read-only competition mode and allow only that, but I imagine it would require a lot of changes
