### ISSUE TITLE
Modify Competition Confirmation Email per WCAT and Seniors

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4143]
Modify Competition Confirmation Email according to research on from WCAT/Seniors/Board.

WCA accounts only: https://docs.google.com/document/d/1IQmVTRkjfAktzvw53OBer0fRam7MOwGSr3ze-aMiCaw/edit?usp=sharing

I'm going to work on this along with #3885.

After research this is the email we came up with:

![image](https://user-images.githubusercontent.com/11577241/57807993-71a0a600-7730-11e9-97c9-aa72c63f87dd.png)

List of changes:
- [x] Remove Delegate name from subject line
- [x] Add greeting
- [x] Make all text the same size (no h2s)
- [x] Change is confirmed in body to include the Delegate submitting (what the original title said)
- [x] Add the competition Date and how many days away it is.
- [x] Add a red warning if it is 30 days or sooner.
- [x] Add probation red text
- [x] Add link to Probation sheet OR give reason for probation.
- [x] Add red warning if potential proximity conflicts
- [x] Add quotes to remarks
- [x] Add reason for competition Name
- [x] Add periods after each section
- [x] Change Z1 to be submit puzzles early
- [x] Change Z3 wot be qualification times
- [x] Add signature listing all delegates of the competition.
- [x] Add red text if limit is < 50.

Other things to do on the competition form while implementing this:
- [x] Remove ability to confirm a comp if < 28 days
- [x] Change Z1 to be “I would like to require competitors to submit puzzles at a specific time before an event is scheduled to begin”
- [x] Change Z3 to be “I would like to select competitors who directly qualify for certain rounds of certain events based on the results of specific previous competitions”

**Comment by cubewhiz** [comment]
Is the "48 hours" warning exact? i.e., if the competition is submitted with only 2 hours remaining, will it say 48 hours or 2 hours?

**Comment by Jambrose777** [comment]
> Is the "48 hours" warning exact? i.e., if the competition is submitted with only 2 hours remaining, will it say 48 hours or 2 hours?

It is not, changing to "There is less than 48 hours..." would be better.

**Comment by cubewhiz** [comment]
Ok. In that case, I'd recommend "There are less than 48 hours..."
