### ISSUE TITLE
[Bug] Nearby Competitions use only the start date

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4146]
Nearby competitions uses only the start_date to calculate if there is a proximity collision.
This is a bit misleading since if I have 2 competitions:
- CompA on May 1st to May 3rd
- CompB on May 20th.

It will not show in red even though this would be in violation of the proximity policy

**Comment by michaelrp** [comment]
So the problem is in `competition.rb` here: `days_until = (c.start_date - self.start_date).to_i`?

I can fix this with a little guidance. Does the system allow end date to be left empty by users? Should the code take `c.end_date` by default, and only use `c.start_date` if `c.end_date` is null?

**Comment by jonatanklosko** [comment]
Looking at the following method
https://github.com/thewca/worldcubeassociation.org/blob/96cf7bad540e3689bb246afa5a912af5e225fa72/WcaOnRails/app/models/competition.rb#L869-L875
we take into account that `start_date` may be `nil`, so if we change the code to use `end_date` we should add a similar check.
Note: we use `days_until.abs` here to measure distance between start dates. When using both start and end date we need to distinguish between `self` happening before and after `c`.

Context: in the competition form, whenever the user updates start/end date we reload the list with nearby competitions and mark with red those that our competition is `dangerously_close_to?`. If start date is not entered we render a warning instead:
https://github.com/thewca/worldcubeassociation.org/blob/2f2a1b591a64fcef5cfb5ad7e0ee01a1e61f4e21/WcaOnRails/app/views/competitions/_nearby_competitions.html.erb#L20-L22
`Competition#has_date?` checks for `start_date` only, so in updated implementation it should check for `end_date` as well.
