### ISSUE TITLE
Create Regional Delegates and give them permissions

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#4185]
The recent passage of the amendments to the Motions creates the role of Regional Delegate.

This role should be created within the Delegate organization and nested below their supervising Senior Delegate, with the ability to then nest subordinate Delegates below them.

Regional Delegates should be automatically included in cc involving subordinate Delegates that would normally go to the Senior Delegate. Examples include:
- when a Delegate confirms a competition
- reminders for late Delegate reports
- reminders for late competition results

**Comment by AlbertoPdRF** [comment]
I'm closing this one in favor of #4222.
