### ISSUE TITLE
[WCAT] emailing organizers in addition to delegates 

### ISSUE THREAD

**Issue by UnderwaterCuber** [thewca/worldcubeassociation.org#4200]
Currently if there is a problem with a competition and WCAT cannot accept it they email only the delegate(s) of the competition being organized, the organizers aren’t notified until the delegate tells them. It would be nice to include organizers in the emails to open up communication more and to stop having to have everything go through the delegate to communicate.

**Comment by Jambrose777** [comment]
WCAT does not approve this request.

Here are some reasons:
- Organizers are not wca staff. Having to explain the same thing over and over again to a delegate is already a pain, multiplying that to organizers (who many of which don’t speak English) would greatly impact the amount of work we have to do. WCAT is there to educate delegates and the Delegates educate organizers. It makes a simple line of communication and pinpoints specific people to contact.
- WCAT receives 1000+ competition related emails a month, adding organizers and their responses only increases our workload even more.

Can someone from WST please close this issue.
