### ISSUE TITLE
Edit Confirmed Competition, modify fields that Delegates shouldn't be able to

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4201]
If you force the edit view to allow a Delegate to edit a confirmed competition, they can modify items like the start and end date of the registration period. This is also an issue in the tests.

**Comment by Jambrose777** [comment]
I'll add this to the probation PR: https://github.com/thewca/worldcubeassociation.org/pull/4144

**Comment by Jambrose777** [comment]
Working on this now.

**Comment by Jambrose777** [comment]
I can't figure out what the difference is in some fields versus others.

Basically to reproduce, inspect the page, remove the disabled attribute on the fieldset, and edit a field and click submit.

when updating items like the start_date, or cellName, the update doesn't actually happen despite the POST being made and getting a success. But for other fields like the registration dates, the change is made. I'm not entirely sure if that behavior is defined anywhere.

**Comment by AlbertoPdRF** [comment]
Probably this is a good second issue, so I'm labeling it as such. Feel free to remove the label if you think otherwise!

**Comment by jfly** [comment]
> when updating items like the start_date, or cellName, the update doesn't actually happen despite the POST being made and getting a success. But for other fields like the registration dates, the change is made. I'm not entirely sure if that behavior is defined anywhere.

This behavior is defined in [`competition_params` in `competitions_controller`](https://github.com/jfly/worldcubeassociation.org/blob/ba22e73fca5c1b0125155078c3cc9650aa457fdb/WcaOnRails/app/controllers/competitions_controller.rb#L611). It looks like some fields (such as `registration_open`) are always put in `permitted_competition_params`, but others (such as `start_date`) are only added if the competition is not confirmed.

Way back, we used to (intentionally) allow delegates to edit the registration open/close dates, but we changed that in https://github.com/thewca/worldcubeassociation.org/pull/2999 (see https://github.com/thewca/worldcubeassociation.org/issues/3287#issuecomment-416300895 for some more information). I think that in #2999, we ended up hiding the fields, but didn't actually change the backend to ignore attempts to update them. Oops!

**Comment by AlbertoPdRF** [comment]
> I think that in #2999, we ended up hiding the fields, but didn't actually change the backend to ignore attempts to update them. Oops!

Yep, that's the case :disappointed: @Jambrose777 do you plan on fixing this or should I?

**Comment by Jambrose777** [comment]
> > I think that in #2999, we ended up hiding the fields, but didn't actually change the backend to ignore attempts to update them. Oops!
> 
> Yep, that's the case 😞 @Jambrose777 do you plan on fixing this or should I?

I'll get to it eventually if someone hasn't. But go ahead if you want to!

**Comment by AlbertoPdRF** [comment]
I'll will handle it now that I have a bit of time.
