### ISSUE TITLE
Refactor z1 and z3

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4217]
Z1 and Z3 no longer exist as regulations.

These should be refactored:
- regulation_z1 -> early_puzzle_submission
- regulation_z1_reason -> early_puzzle_submission_reason
- regulation_z3 -> qualification_times
- regulation_z3_reason -> qualification_times_reason

or something similar. These names are just suggestions.

**Comment by AlbertoPdRF** [comment]
Nit: `times`->`results`.

**Comment by AlbertoPdRF** [comment]
And this one should be a good second issue too!

**Comment by jfly** [comment]
For the record, `z1` and `z3` made their way over to the competition requirements document: https://www.worldcubeassociation.org/documents/policies/external/Competition%20Requirements.pdf. If we wanted to follow the previous naming scheme, we could potentially do something like:

- `regulation_z1` -> `requirement_10_1`
- `regulation_z3` -> `requirement_5_1`

**Comment by AlbertoPdRF** [comment]
The problem I see is that while Regulations' numbering would never change, that's not the case with the WCRP numbering, so probably more descriptive names as the ones suggested by @Jambrose777 are better.

**Comment by Jambrose777** [comment]
Working on this!
