### ISSUE TITLE
Redirect to user profile when clicking on avatar

### ISSUE THREAD

**Issue by Joon7891** [thewca/worldcubeassociation.org#4258]
Add a personalized `href` to a person's user profile if they are logged in and have a linked WCA ID.

**Comment by AlbertoPdRF** [comment]
Hey @Joon7891, thanks for reaching out to us!

In the future, we will appreciate it if you use the issue template for feature requests so it's easier for us to understand what you are exactly asking for. In particular, where would you exactly want this? Everywhere where we display users' avatars?

Regardless of where we put this, I think this would make it for a good first issue.

**Comment by Joon7891** [comment]
I was thinking just where the user's avatar is displayed in the top right corner, right next to the language drop down tab; if the user hovers over the avatar, the drop down menu for profile settings appears (which already implemented), whereas if the user clicks the avatar, they are redirected to their own WCA profile; if it exists.

**Comment by AlbertoPdRF** [comment]
Thanks for clarifying! However, after #4158 has been taken care of I, don't think this is necessary so I think it's better to close this one.
