### ISSUE TITLE
UI for demoting members from team.

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#426]
Please note that there's a difference between deleting a member and "demoting".

All past members stay in the database, with their end_date value set to a point in the past. This is demoting a member.
Currently the end_date box is show with the other boxes. Ideally we would have a nice "Demote" button, which would prompt for an end_date.

Deleting a record should only be done via SQL in case of a mistake, and optimally would never happen :)

**Comment by pingskills** [comment]
Was the intention to add delegates to the teams and team_members tables at some stage?

**Comment by pedrosino** [comment]
Yes, we thought about that, but didn't come to a conclusion on the best format.

**Comment by jfly** [comment]
Yeah, we'd love to see delegates as a team, but there are some differences (delegates can be one of 4 types: candidate_delegate, delegate, senior_delegate, and board_member). Delegates also have this silly region string that I'd like to do away with in favor of a proper lat long (related to #114).

**Comment by pingskills** [comment]
@jfly do you have any extra thoughts on storing the longitude and latitude for a delegate? If we stored this how would it be displayed on the delegates page? Would we still need a region string?

**Comment by jfly** [comment]
I've created #680 to discuss adding delegates to our team tables.

**Comment by jfly** [comment]
I don't think there's any value in adding a demote button. Speaking as a team leader who has removed members from his team before, it's quite easy (and useful!) to set an end date instead.
