### ISSUE TITLE
Delegate reports: include a way to request WRC input

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4267]
Delegate reports often ask the WRC for input, but then the Delegate doesn't CC the WRC on the thread. As the WRC is currently down to 3 members (although I'm about to put out a call for new members), this makes it easy for something to slip through the cracks unless another Delegate notices.

From #483:

> "A +/- data entry feature for incidents with auto-numbering, instead of rich text, might make it easier to track and comment on particular issues. They could then be escalated to the WRC/WDC for review individually." -@TimMcMahon (here)

Middle ground could include (in order of preference):
- Split the incidents section into at least two: "routine" and "needs input".
- Provide a separate free-form field to specify when WRC input is needed.
- Including an overall checkbox for "WRC input requested". I'm *not* in favor of this, and would prefer something to help the WRC get to the part that needs input easily.

**Comment by AlbertoPdRF** [comment]
This would probably make it for a good second issue!

**Comment by Rubiks-boy** [comment]
Hello! I'd like to take a stab at this!
Was speaking with @AlbertoPdRF, and he had the idea of a checkbox that then makes available a text field to specify the specific incident numbers that need feedback. This list, if non-empty, would then cause wrc to be cc'd in the email, and something like `@WRC: please give input on incidents x, y, and z` would be added to the top of the report email. I really like this approach - concerned going down a 2 incidents sections approach will lead to some confusion with numbering (ex. now you'll have two incidents sections that possibly both start at 1?), and this would require changing the structure of the report.

**Comment by lgarron** [comment]
> Was speaking with @AlbertoPdRF, and he had the idea of a checkbox that then makes available a text field to specify the specific incident numbers that need feedback. This list, if non-empty, would then cause wrc to be cc'd in the email, and something like `@WRC: please give input on incidents x, y, and z` would be added to the top of the report email. I really like this approach - concerned going down a 2 incidents sections approach will lead to some confusion with numbering (ex. now you'll have two incidents sections that possibly both start at 1?), and this would require changing the structure of the report. Does this sound good @lgarron?

Sounds good! :-)

**Comment by lgarron** [comment]
By the way, another nice feature would be to mark the status of an incident — it could be resolved, pending decision, or decided but with followup (e.g. incidents log, Regulations change). Doesn't have to be in v1, though!

**Comment by AlbertoPdRF** [comment]
That does indeed sound like a nice (and every day more necessary) feature @lgarron, but also like much more work :stuck_out_tongue: FYI: @thewca/board is investigating on workflow/business process management solutions that could suit us, although I think it will definitely take a lot of time to have one implemented.

**Comment by lgarron** [comment]
Thanks for implementing this!

At the moment, this seems to add a bright red message at the top of the email. We don't need to grab every Delegate's attention, so I'd be happy to put it at the end. As long as we can set an email filter for it, that should be good enough.

Good ooptions for filtering:

- Use a constant text string in the email.
- CC an email like `regulations+decision@worldcubeassociation.org`
- Emphasize the need for feedback at the top of a followup email tot he WRC: https://github.com/thewca/worldcubeassociation.org/issues/4400

**Comment by AlbertoPdRF** [comment]
The first option is already the case, as every email will include `@WRC: Feedback requested on incidents:`. I just tested filtering emails with this and it seems to work fine :slightly_smiling_face:

**Comment by Rubiks-boy** [comment]
👋 Sorry for the delay in response! Yep, it does always have a constant string at the top. Moving to the bottom/removing the red is an easy change. Fwiw, I actually kind of like having the banner at the top, as someone who is on reports@ but doesn't necessarily have time to read every report word for word. This lets me filter through a lot of the usual/less controversial incidents.

**Comment by Rubiks-boy** [comment]
👋 Sorry for the delay in response! Yep, it does always have a constant string at the top. Moving to the bottom and/or removing the red would be an easy change. Fwiw, I actually kind of like having the banner at the top, as someone who is on reports@ but doesn't necessarily have time to read every report word for word. This lets me filter through a lot of the usual/less controversial incidents. 
I'm thinking keeping it at the top but removing the red so it isn't as bright would be a good compromise. Does that sound good?

**Comment by cubewhiz** [comment]
I also like having the bright message at the top. It may even help reduce the work of the WRC as Delegates may be able to provide answers, too.
