### ISSUE TITLE
Hide (or relocate) post authors.

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4268]
The WCT regularly makes posts like calls for team members on behalf of teams. Now that we have a new posting policy, most posts need to go through the WCT, which means that most posts (other than competition announcements) would be shown as "Announced by [WCT team member, usually the leader]". So showing the announcer for post would be quite low-information.

I'd like to propose one of the following:
- Any team member can draft a post, with the WCT controlling the actual posting process.
- The WCT can set any WCA staff as the author of a post (ideally, with a process for their explicit permission).
- We hide post authors on the site, because they take up space and don't actually matter to most viewers.

**Comment by pedrosino** [comment]
But what is the purpose of this if wouldn't show on the website?

**Comment by lgarron** [comment]
> But what is the purpose of this if wouldn't show on the website?

There arguably isn't one!

(Note: the three options I've proposed are meant to be exclusive, not at the same time.)

**Comment by pedrosino** [comment]
Ah, I see. Personally I'm ok with the current way. Most communication is (supposed to be) done by the WCT, so it makes sense that they make the posts.

I'd like to see an improved homepage, though, with less posts and more cool info.

**Comment by AlbertoPdRF** [comment]
Regardless of the necessity of an improved homepage, which we will hopefully have soon, I would definitely go with option 3 regarding post authors. Maybe we could, instead of get rid of that sentence entirely, put it on a not-so-prominent spot?

The option described above should be easy enough for a good first issue, so I'll label it as such and update the title!

**Comment by Jambrose777** [comment]
Not sure if we would still want this implemented. With the home page redesigned, the post author is less visible and I've personally always found the sub text to be helpful in some regard, so I wouldn't see a reason to remove the author from being visible.

**Comment by denthebro** [comment]
I agree with @Jambrose777
