### ISSUE TITLE
Allow organizers to upload external registrations.

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4272]
I recently visited https://www.worldcubeassociation.org/competitions/mine and had a bit of a scare when Worlds didn't show up there. I'd like to propose that we introduce the concept of an external registration:

- Initial simple version: allow organizers to upload a list of competitors regularly, and provide a link to look up your registration on another site.
- Semi-fancy version: include information like registered events.
- Even fancier version: allow using OAuth to formally register on another site on behalf of the WCA site.

Not all organizers would do this, but a competition like Worlds definitely has the resources for it. Even if we can't (yet) mandate that every competition reflects registrations on the WCA website, I think it's valuable to support it for the big competitions that are more likely to have external registrations.

There might be some fiddly details around partial registrations and waitlists, but just uploading completed registrations for competitors with WCA IDs would be nice.

**Comment by AlbertoPdRF** [comment]
Hmm, wasn't this taken care of in https://github.com/thewca/worldcubeassociation.org/pull/3726 and successive (related) PRs?

**Comment by jonatanklosko** [comment]
Was about to write the same ^^ At this point organizers are able to import registrations with all the events data and this in turn makes them visible on the registration list, as well as through WCIF. Imported registrations are linked to WCA users, so this should also cover the `/competitions/main` concern.

**Comment by lgarron** [comment]
> Hmm, wasn't this taken care of in #3726 and successive (related) PRs?

Hmm, I wasn't aware that we were so featureful!
I'll see about asking the Worlds team.

**Comment by EdHollingdale** [comment]
Just for clarification: for WC2019 we thought it could be confusing to competitors to upload registrations to the WCA website, since registration takes place on a different site and that site is the ultimate "source of truth" for registration data.

**Comment by lgarron** [comment]
> Just for clarification: for WC2019 we thought it could be confusing to competitors to upload registrations to the WCA website, since registration takes place on a different site and that site is the ultimate "source of truth" for registration data.

Oh, I see. Would it help if the registration information linked to the other site in enough places?
