### ISSUE TITLE
Venue photos in Delegate reports

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4309]
The WRC would like to measure adherence to:

> 4b2++) ADDITION Competition organizers should ensure that scramblers, scramble sequences, and partially/fully scrambled puzzles are visually isolated from competitors (see Regulation A2c). For example, the scramblers may be located behind a wall, or a sufficiently high divider (e.g. a cardboard divider placed around the sides of a table where the scramblers are seated) may be used so that competitors are not able to see puzzles as the scramblers apply scramble sequences.
> 7h2+) ADDITION Competitors in a Competitors Area who are waiting between attempts should not be able to see the puzzles of the competitors on stage.

I'd like to put forth the idea that we start encouraging (and eventually requiring) at least one photo to be submitted with every Delegate report, documenting the stage(s), competitors area(s), and scrambling station(s). With the modern availability of smartphones, this should hopefully not be a burden.

(Also see #1507.)

**Comment by jfly** [comment]
This sounds good to me! Two ideas:

1. We go ahead and implement support for uploading images directly when using the markdown editor on the delegate report page, and then update the hint text for the `Venue` field to tell delegates to upload at least one photo documenting "the stage(s), competitors area(s), and scrambling station(s)"
   - This is nice because we were already planning on adding support for uploading images to the delegate report fields, so it's not really any additional work.
2. Add a separate dedicated field for uploading a photo?
   - This would require a database migration, and would get weird if they want to add multiple images, or text accompanying the images.

I feel like 1) is a strictly better option here. @lgarron, what do you think? Did you have anything else in mind?

**Comment by lgarron** [comment]
I think 1) is a good start. We can consider 2) if we don't get enough pictures in practices.

**Comment by AlbertoPdRF** [comment]
With Active Storage configured it should be pretty simple to implement idea 2. instead of 1. -- no migration needed and adding multiple images wouldn't be a problem!

**Comment by jfly** [comment]
> adding multiple images wouldn't be a problem

Wouldn't that get a little tricky? I think we'd need some sort of UI to allow uploading multiple files, *and* we'd need a new table to store the N venue photos associated with an account.

I still think 1) is an ok start.

**Comment by AlbertoPdRF** [comment]
> Wouldn't that get a little tricky? I think we'd need some sort of UI to allow uploading multiple files, and we'd need a new table to store the N venue photos associated with an account.

It shouldn't at all! See https://edgeguides.rubyonrails.org/active_storage_overview.html#has-many-attached.

**Comment by Goosly** [comment]
> I'd like to put forth the idea that we start encouraging (and eventually requiring) at least one photo to be submitted with every Delegate report, documenting the stage(s), competitors area(s), and scrambling station(s).

I am against this idea. What's next? Two photos from different angles? A video of the venue? Requiring delegates to wear bodycams when they resolve incidents and upload them with the report? Use two judges in inspection, one to keep an eye on the stopwatch and the other to keep an eye on the competitor not making moves? Where do you draw the border of what's reasonable to require and what isn't?

**Comment by lgarron** [comment]
@fly, is there a good way for me to try the UI for adding an image to a Delegate report?
Can you already attach one so that it will show up in emails?

> Where do you draw the border of what's reasonable to require and what isn't?

Enough to demonstrate that you've set up a venue to WCA standards (Regulations and WCRP).

**Comment by AlbertoPdRF** [comment]
> @fly, is there a good way for me to try the UI for adding an image to a Delegate report?
Can you already attach one so that it will show up in emails?

You can just test it out on staging! See https://staging.worldcubeassociation.org/competitions/BilbaoOpen2019/report for an example. The image should also get added to the email.

**Comment by AlbertoPdRF** [comment]
By the way, China Championship's report included images with this new functionality and, as expected, they showed up just nice on the email!

**Comment by jfly** [comment]
We have support for uploading images to delegate reports, and it has been shown to work well with email. I think we can close this issue.

@lgarron feel free to reopen or create a new issue if there's more work to be done here.
