### ISSUE TITLE
2018 Regulations Version does not exist

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4323]
https://www.worldcubeassociation.org/regulations/history/

The 2018-01-01 Version of the regulations points to the current version of the regulations.
The 2019-05-01 Version should be added to this list and the 2018 Version should point to a new page with the old regulations.

**Comment by AlbertoPdRF** [comment]
@lgarron can you take care of this? If yes, please assign the issue to yourself!

**Comment by jfly** [comment]
I *think* Lucas's plan is to get rid of the historical links in favor of linking to GitHub? See https://github.com/thewca/worldcubeassociation.org/issues/4311

**Comment by AlbertoPdRF** [comment]
Yep, that's right, although until that's done we should definitely fix this imo.

**Comment by Ivan-Brigidano** [comment]
The bug is still there. Van we fix it @lgarron ?

**Comment by Jambrose777** [comment]
If Im not mistaken, this is fixed? Will wait for confirmation from WRC member, as there are more voices than mine on this issue.

**Comment by Ivan-Brigidano** [comment]
Yes, this was fixed.
