### ISSUE TITLE
Shortcuts on Delegates Page

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#4328]
The delegates page is very long (which is good to see). A byproduct of this is that it requires quite a lot of scrolling to find the delegates of a certain region.

It would be great if there were shortcut links/table of contents that allow you to jump to the start of a particular region.

**Comment by AlbertoPdRF** [comment]
Maybe it would be worth it to also add shortcuts to [the new Committees, Teams, and Councils page](https://www.worldcubeassociation.org/teams-committees)?

**Comment by Jambrose777** [comment]
I like this, or a similar idea of making the tables collapsable. This is probably a good thing to tackle after #4222

**Comment by danieljames-dj** [comment]
I've done a demo on this and attached the screen recording. Please check and let me know if this is fine.

https://github.com/thewca/worldcubeassociation.org/assets/9512698/0a2d19fd-62fe-4d7d-9c85-e99035820b73

**Comment by EdHollingdale** [comment]
This looks fantastic @danieljames-dj !
