### ISSUE TITLE
Rounds can be appended multiple times from the activity picker

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#4329]
**Describe the bug**
A round that has already been added to a schedule can be added again when the box is clicked, despite the opacity being reduced to show that the round is already appended to the schedule.

**To Reproduce**
1. Go to 'manage shedule' of a competition you have edit access with.
2. Click on a round from the 'activity picker'
2a. Keep clicking on the same round
4. The round is allowed to be appended multiple times, when it can only occur once. Saving such a schedule is not blocked.

**Expected behavior**
Once the round button under 'activity picker' is dimmed, the round should not be available to be appended to the schedule a second time.

**Screenshots**
Here, I clicked Megaminx Round 3 multiple times, it was inserted into the schedule between(!!!) rounds 1 and 2.
<img width="188" alt="schedule_bug" src="https://user-images.githubusercontent.com/45567122/61578268-65e8ab80-aaf4-11e9-804d-9ecadac73c67.PNG">

**Comment by LinusFresz** [comment]
I disagree with this. Imagine a competition with BigBLD/Multi where you maybe want to spread the attempts across multiple time slot/days. For this you need the option to use the same round a few times.

Example:
https://www.worldcubeassociation.org/competitions/MentalBreakdownGermany2018#competition-schedule <https://www.worldcubeassociation.org/competitions/MentalBreakdownGermany2018#competition-schedule>

Multi-BLD and BigBLD had multiple time slots. For BigBLD, each time slot meant 1 attempt.

**Comment by LinusFresz** [comment]
OK after a second thought I have to admit that my statement is wrong for multi-BLD as is already has the option, but it remains true for BigBLD (and possibly other events).

**Comment by c-goodyear** [comment]
I didn't think about bigBLD in this way! Maybe a good compromise is to have the button turn a 3rd shade when the regular amount of 1 time slot has been appended to the schedule?

**Comment by LinusFresz** [comment]
Another thing: if a competition has multiple stages, but more than one stage will hold the very same round at the same time. If you disable to select the same round, this would not work too.

Example: 2x2x2 combined first round on the second competition day:
https://www.worldcubeassociation.org/competitions/ChinaChampionship2019#competition-schedule

**Comment by viroulep** [comment]
The behavior you described is indeed the expected behavior, this is not a bug.
As Linus mentioned, it's very well possible to have multiple occurrence of the same activity in the schedule.

The behavior you describe seems to be the one from someone messing up their schedule, and I don't think we should restrict the features available because some users mess up.

I'd be open to display some form of warning when suspicious cases arrise, and it should probably be part of #3335.
@c-goodyear How would you feel about adding your suggestions to the list of nice validations to run on the schedule there and closing this one?

**Comment by c-goodyear** [comment]
@viroulep good idea! I'll do that now :-)
