### ISSUE TITLE
Delegate Avatar Guidelines -> Staff Avatar Guidelines

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4362]
This change was already started as the wording was improved.

However, WRT needs to be able to recognize all team, committee, and council members similar to how we recognize Delegates on the approve avatars page (https://www.worldcubeassociation.org/admin/avatars).

Similar to Delegates all team, committee, and council members should not be able to modify their thumbnail after it has been approved.

**Comment by Jambrose777** [comment]
As I understand, this will block WQAC from being able to track down staff members with photos not abiding by the guidelines and WRT won't be able to apply the additional guidelines and thumbnail to newly uploaded photos for staff members.

**Comment by Jambrose777** [comment]
We also would like to have all staff members (regardless of having a WCAID) to be able to upload an avatar.

**Comment by jfly** [comment]
https://github.com/thewca/worldcubeassociation.org/issues/1246 tracks allowing uploading photos without a WCA ID.

**Comment by Jambrose777** [comment]
working on this.

**Comment by Jambrose777** [comment]
Oh rip, Alberto did this Jul 2nd. https://github.com/thewca/worldcubeassociation.org/pull/4273. I somehow must of looked at something old whenever I saw that staff members weren't listed as such. 

I think this story can be closed

**Comment by AlbertoPdRF** [comment]
Ups! Sorry for not noticing earlier. I'm closing this one!
