### ISSUE TITLE
Retire TNoodle 0.14.0

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4368]
@campos, you did the release; would you mind doing the retirement?

See https://www.worldcubeassociation.org/posts/retiring-tnoodle-0-13-5 for a previous example announcement.

- [x] Update scramble page
- [x] Remove 0.14.0 from the API
- [x] Announce on the website
  - [x] Draft announcement
  - [x] Email the WCT
  - [x] Post announcement
- [x] Announce to staff

**Comment by lgarron** [comment]
Draft Announcement:

> When `TNoodle-WCA-0.15.0` was released, we announced that `TNoodle-WCA-0.14.0` would briefly remain an officially permitted version. Since some time has passed, `TNoodle-WCA-0.13.5` is now officially retired, leaving `TNoodle-WCA-0.15.0` as the only official scramble program.
> 
> Please see [the `TNoodle-WCA-0.15.0`  announcement](https://www.worldcubeassociation.org/posts/tnoodle-0-15-0) for details.
> 
> Please remember that official competitions must use a current version of the official scramble program. This is always available from:
> https://www.worldcubeassociation.org/regulations/scrambles/

**Comment by campos20** [comment]
OK! I'm doing this on July 29th.

**Comment by lgarron** [comment]
The WCT approved the draft announcement. @campos20, could you go ahead? :-D

**Comment by campos20** [comment]
Yes, moving right now

**Comment by lgarron** [comment]
Thanks!

Note that https://www.worldcubeassociation.org/regulations/scrambles/tnoodle/TNoodle-WCA-0.14.0.jar should also move to https://www.worldcubeassociation.org/regulations/scrambles/tnoodle/old/TNoodle-WCA-0.14.0.jar !

**Comment by campos20** [comment]
> Thanks!
> 
> Note that https://www.worldcubeassociation.org/regulations/scrambles/tnoodle/TNoodle-WCA-0.14.0.jar should also move to https://www.worldcubeassociation.org/regulations/scrambles/tnoodle/old/TNoodle-WCA-0.14.0.jar !

Yes, this was the [first step](https://github.com/thewca/worldcubeassociation.org/pull/4304/files) :)

Thanks for your support!
