### ISSUE TITLE
Remove outdated reference to Guidelines

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#4384]
One phrase refers to *Article 8* of Guidelines, that has been moved to [*WCA Competition Requirements Policy*](https://www.worldcubeassociation.org/documents/policies/external/Competition%20Requirements.pdf).
https://github.com/thewca/worldcubeassociation.org/blob/8207c6911b9df21ab51fbf3144c2f307db4ca160/WcaOnRails/config/locales/en.yml#L1793
Also it uses wording `one month`, whereas `four weeks` is the correct version.

**Comment by AlbertoPdRF** [comment]
Also, now it's a `must` -- competitions can't be announced less than 28 days in advance since the WCRP is in place.

Maybe @Jambrose777 can add this to #4144? As he already modified a variable name to this effect on that PR.

**Comment by Jambrose777** [comment]
Sure!

**Comment by Jambrose777** [comment]
oh rip, someone has already done this.

**Comment by AlbertoPdRF** [comment]
Oh, right, this was fixed by @Goosly in #4403, so I'm closing it!
