### ISSUE TITLE
Schedule Tool Sandbox

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#4401]
The schedule tool is great! Not only is it easy to use, it is also a great way of visualising schedules as you build them.

The only issue is I can't use it until I've set up a competition! It would be great if there was a schedule sandbox where it was possible to brainstorm schedules using the awesome interface. It would be very useful to send this to potential organisers so they have a clear way of planning things out (if they visualise schedules anything like me).

I realise this is **low** priority, but I still think it would be a nice idea.

**Comment by jfly** [comment]
@EdHollingdale, does one of these two work for you?

1. Use https://staging.worldcubeassociation.org/ to do whatever you want.
   - Cons: If you want to copy this schedule over to the real prod website sometime, you'll have to do it by hand.
2. Use https://www.worldcubeassociation.org/ to do what you want in an unconfirmed competition. Once you add an organizer to a competition, they will have access to the competition even if it has not been confirmed/publicly announced yet.

**Comment by EdHollingdale** [comment]
@jfly I currently use staging quite frequently for exactly this - but I'm not sure if this is something you want everyone doing. WCAT often ask for "how would you adjust the schedule if this change were made" so now I preemptively go onto staging, make the change, and adjust the schedule as I would. 

Solution 2 works - but sometimes if you are just brainstorming things you might not want to go and create a whole competition!

As I said this is and should be super low priority! I just think it would be a cool organisational planning tool - leveraging the already existing excellent scheduling tool.

**Comment by AlbertoPdRF** [comment]
Just a quick clarification on:

> Solution 2 works - but sometimes if you are just brainstorming things you might not want to go and create a whole competition!

I think what Jeremy meant is keeping an unconfirmed competition and use it for this whenever necessary, not creating one each time. There are Delegates who already do -- they keep a template competition and just clone it whenever they have to announce a new competition.

**Comment by EdHollingdale** [comment]
@AlbertoPdRF that is a good idea. Australia already has a template competition, but I'll create one for schedule sandbox purposes.

**Comment by jfly** [comment]
> I currently use staging quite frequently for exactly this - but I'm not sure if this is something you want everyone doing

That's totally ok in my mind =) Another downside of staging: we do periodically wipe the database on staging, so you shouldn't put anything there that you want to have stick around.

Sounds like we're good here. I'm going to close this issue. @EdHollingdale, feel free to re-open or file a new issue if something else comes up =)
