### ISSUE TITLE
Remove mention of Article Z from Competition Edit Page

### ISSUE THREAD

**Issue by sam596** [thewca/worldcubeassociation.org#4438]
**Describe the bug**
While preparing to send a competition proposal to WCAT, the edit page still asks you if you would like to have additional registration requirements as per Articles Z1 and Z3, which no longer exist.

**To Reproduce**
Self-explanatory

**Expected behavior**
Update these references to the relevant articles in the Competition Requirements Policy. I believe the relevant article for Z1 is 10.1 of the Announcement Criteria section. I do not believe the former Z3 regulation is now available to be used as per the requirements, but I could be wrong.

**Comment by AlbertoPdRF** [comment]
This is being fixed on #4144, which will probably be merged soon.

**Comment by AlbertoPdRF** [comment]
As #4144 has been merged, I'm closing this one!
