### ISSUE TITLE
Split competition results into multiple pages

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#4469]
https://www.worldcubeassociation.org/competitions/CubingUSANationals2019/results/all takes an extremely long time to render on my phone.  Large competitions have way too many results to render all of them at once.

I think performance would be better if we only show results for one event at a time.  We can use the same paradigm on /persons/$PERSON_ID (e.g. https://www.worldcubeassociation.org/persons/2005REYN01) of having a selector at the top with all of the events, and only showing the selected event.

While doing this I would also suggest reverse-ordering the rounds of each event (i.e. show the finals on top, then the semi-finals, then ...)  I think it's clearer to have the overall winner of the event on top, rather than having the winner buried after all of the non-final rounds.  But this may be more controversial :)

**Comment by AlbertoPdRF** [comment]
Yep, totally agreed!

**Comment by jfly** [comment]
I like this proposal!

Does the individual results page actually optimize and only load the requested results? Or is it just "paginating" them client side?

**Comment by timreyn** [comment]
It looks like the pagination all happens client-side.  The full set of results is loaded on page load, and only shown when you tap on the selector..

Reference: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/javascripts/persons.js#L57

Working on this.

**Comment by AlbertoPdRF** [comment]
Assigned! :rocket:

**Comment by jfly** [comment]
It might make sense to first implement true pagination for the individual results page, and then we can leverage our learnings from that when splitting up the competition results page.

**Comment by timreyn** [comment]
@jfly, I don't think I agree.  Rendering time makes a big impact here, and sticking a "display: none" on a big UI element is going to make a pretty big difference.  That was definitely my observation last night while I was working on this -- loading the entire page then hiding it, versus loading the entire page hidden, was a very noticeable difference even on my laptop.

Switching to true pagination may be an improvement, but it also may not be, depending on network conditions and how fast the AJAX requests can go through.  Probably worth a try but I wouldn't guarantee that it'll be an improvement for all users.

In any case, it's not too difficult, the PR's almost done, and it should make an improvement, so I think it's worth pushing ahead :)

**Comment by jfly** [comment]
Sounds good to me!
