### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/worldcubeassociation.org#449]
So we have a https://worldcubeassociation.slack.com - why aren't we using this?!
# Fun things we can do with Slack:
### Automatic User Channel Management

Based off teams they are a part of in WCA, we can automatically add them to (and remove them from) channels. This would be very handy for various WCA Teams and their respective channels. Channel names (like IRC) are prefixed with hash, so consider the following:
- WCA Board: #board
- WRC: #wrc
- WDC: #wdc
- Delegates: #delegates
- Results Team: #results
- Software Team: #software-team

There is also the possibility that we automatically invite Team A into Team B's channel. Example: Automatically invite board members into #software-team. If at any point we were to edit a user to remove them from such a team, this could also remove them from the channel(s) accordingly.
### Urgent Delegate Advice

Delegates will often times find themselves at a competition and needing advice on how to handle a specific situation/incident. This usually means emailing delegates@ and board@. Having a slack channel would make things super handy because you can do something like @channel (everyone in the channel this is sent to) or @here (everyone in the channel who has had activity in the last 30 minutes) and it will send a notification to the relevant users. On phones this means a push notification, or on desktops/laptops this means a desktop notification (if they're enabled) and/or a sound clip (a bell/ding sound). If we had delegates idle the channel while they were online, this would probably be faster than email.
### Replace Group Me

Currently, US Nats Staff relies on GroupMe for communication during the weekend long event. With slack, we could easily have a a #nats-staff channel!
### Integrate production deployment

Slack has some cool plugins with git integration, that we can notify slack channels whenever we deploy to the website :)
### Competition Management

Competition managers (cubecomps, ccm, any future software) could take advantage of slack push notifications and notify users for various events. Such as: calling up when your heat is called, if competition staff needs to talk to you, etc. Note that we could do this either with direct integration with the competition software having a bot in Slack, or we could have a "WCA Bot" in slack and then an API on the WCA website we could communicate with.

There are certainly other things we can add to this section of cool/fun things, maybe @keemy has some ideas since he setup the slack?

**Comment by FatBoyXPC** [comment]
Assuming we can't OAuth, here is a potential solution to keep the accounts (mostly?) in sync:

- User clicks "Join Slack" link
- WCA site consumes Slack API to auto invite the user etc. Note that this creates an account for the user on slack's website, and they'll have to remember their password.
- When the user account gets created, return the Slack user ID from the Slack API (hopefully this is possible) and store it in the users table
- Whenever a user gets saved, any data that changes that would affect slack (such as email) gets sent off to the Slack API

In this scenario, we should notify the user that their slack data would change.

We could do some fancy things like auto-invite and auto-kick users to various channels based off teams they are a part of in WCA. Channel names (like IRC) are prefixed with hash, so consider the following:

Automatically invite a user to #delegates when they receive delegate status.

Other possibilities include: WCA Board (#board), WDC (#wdc), WCA Results Team (#results), WCA Softare Team (#software-team), and so on.

There is also the possibility that we automatically invite Team A into Team B's channel. Example: Automatically invite board members into #software-team.

**Comment by AlbertoPdRF** [comment]
I've been searching and I've found this: https://api.slack.com/scim The bad news is that we can't use this because it requires at least Slack's Plus Plan, while we only have the Standard Plan.

**Comment by gregorbg** [comment]
We don't have the necessary Plan on Slack for this kind of automation feature :sob: 
Closing now
