### ISSUE TITLE
Results Posts - Link Profile in records section

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4512]
Request to add a link to a person's profile whenever they are mentioned in the records section of a results post.

This shouldn't be too hard, but instead of this:

> [Caio Hideaki Sato](https://www.worldcubeassociation.org/persons/2016SATO01) won [V ETEC Jacareí Open 2019](https://www.worldcubeassociation.org/competitions/VETECJacareiOpen2019) with an average of 7.35 seconds. [Iuri Grangeiro Carvalho](https://www.worldcubeassociation.org/persons/2015CARV06) finished second (8.25) and [Antonio Gabriel Freitas da Silva](https://www.worldcubeassociation.org/persons/2015SILV55) finished third (8.33).
South American records: Caio Hideaki Sato&lrm; 3x3x3 Cube 7.35 (average), Iuri Grangeiro Carvalho&lrm; 3x3x3 One-Handed 9.64 (average).  

We'd have:
> [Caio Hideaki Sato](https://www.worldcubeassociation.org/persons/2016SATO01) won [V ETEC Jacareí Open 2019](https://www.worldcubeassociation.org/competitions/VETECJacareiOpen2019) with an average of 7.35 seconds. [Iuri Grangeiro Carvalho](https://www.worldcubeassociation.org/persons/2015CARV06) finished second (8.25) and [Antonio Gabriel Freitas da Silva](https://www.worldcubeassociation.org/persons/2015SILV55) finished third (8.33).
South American records: [Caio Hideaki Sato](https://www.worldcubeassociation.org/persons/2016SATO01)&lrm; 3x3x3 Cube 7.35 (average), [Iuri Grangeiro Carvalho](https://www.worldcubeassociation.org/persons/2015CARV06)&lrm; 3x3x3 One-Handed 9.64 (average).  

Should be a simple change, the harder part is figuring out how to modify all old posts to this new format.

**Comment by jfly** [comment]
Updating the post should be pretty straightforward. Updating old posts doesn't feel worth the effort to me.

I say this on every discussion about our posts: I am not convinced they're worth keeping around. We're so big now, I don't think anyone actually looks at them.

**Comment by AlbertoPdRF** [comment]
I think we should have this conversation before letting more issues pile up. These posts in particular (not the competition announcement ones) add information that can't be found anywhere else:

- The podium of the competition (i.e. who has won the competition)
- A summary of the records set at the competition

I would be fine with adding this information to the competition page itself in some way and remove the posts altogether. Other opinions?

**Comment by SAuroux** [comment]
I would be ok with that @AlbertoPdRF . 

As for the unique information contained in results posts, I actually see only two distinct pieces that should probably be stored in the Competitions table:

- main event
- uploader

**Comment by jfly** [comment]
I quite like the idea of storing main event and uploader, adding the podium information to the competition home page, and getting rid of the results posts!

**Comment by AlbertoPdRF** [comment]
@thewca/board would you agree with us going that way?

Also, what would we do with old posts? Get the information we need from them and then delete them or something else?

**Comment by jfly** [comment]
Yeah, doing some sort of backfill and then removal of the old posts sounds like a good goal to me.

**Comment by AlbertoPdRF** [comment]
And for the announcements ones I guess we should also save the announcer on the database and that's it, right?

**Comment by cubewhiz** [comment]
I'm fine with getting rid of these.

What is the rationale for storing uploader and announcer?

**Comment by AlbertoPdRF** [comment]
> What is the rationale for storing uploader and announcer?

Some reasons I can think of:

- Credit the users who do the work
- Help resolve systematic mistakes of a user that have been found out _a posteriori_

By the way, I'm working on this.

**Comment by SAuroux** [comment]
I am also currently using this information to track the activity of my team members. 

In general, I'd say that **traceability** is the key argument.

**Comment by cubewhiz** [comment]
Seems reasonable. I expect the announcement and results posting date will still continue to be collected as usual?

**Comment by AlbertoPdRF** [comment]
> I expect the announcement and results posting date will still continue to be collected as usual?

Yep!

**Comment by cubewhiz** [comment]
Great, thanks for the clarification.

Anyway, I fully support getting rid of the competition announcements/results on the home page. It's definitely not worth investing more time into features for those posts if we're all on board to get rid of them.
