### ISSUE TITLE
i18n competition mailers

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#4516]
From #4511 

These two mailers should be i18ned:

https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions_mailer/notify_users_of_id_claim_possibility.html.erb
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions_mailer/notify_users_of_results_presence.html.erb

**Comment by dsoegijono** [comment]
I can take a look at this. However, not quite sure how localized strings are generated. Should I submit PR with only `en`?

**Comment by viroulep** [comment]
Yes that's perfectly fine!

We use `en` as the default locale, and all others are translated by volunteers (you can check [this wiki page](https://github.com/thewca/worldcubeassociation.org/wiki/Translating-the-website) for the details).
When implementing we usually just add keys to the `en.yml` file as needed (re-using keys if we already localized the same word/message in the same context), and then when the changes are merged to master, an email is automatically sent to the translators mailing list.
From a quick look at the emails, it looks like only the `common.here` key could be re-used.
And FYI the `users_to_sentence` helper is based on a helper which is [already localized](https://github.com/thewca/worldcubeassociation.org/blob/97e1c5e711ff7375ade6fc1ca2f7ea4e8cbbe8c3/WcaOnRails/config/initializers/monkey_patches.rb#L17)!
