### ISSUE TITLE
Server has security updates pending

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4537]
As can be seen when SSHing:

    > ssh cubing@worldcubeassociation.org
    Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-116-generic x86_64)
    
     * Documentation:  https://help.ubuntu.com/
    
      System information as of Mon Aug 26 05:35:12 UTC 2019
    
      System load:  0.66               Processes:           130
      Usage of /:   54.7% of 31.36GB   Users logged in:     0
      Memory usage: 37%                IP address for eth0: 172.31.33.143
      Swap usage:   0%
    
      Graph this data and manage this system at:
        https://landscape.canonical.com/
    
      Get cloud support with Ubuntu Advantage Cloud Guest:
        http://www.ubuntu.com/business/services/cloud
    
    170 packages can be updated.
    130 updates are security updates.
    
    New release '16.04.6 LTS' available.
    Run 'do-release-upgrade' to upgrade to it.
    
    
    *** System restart required ***

I believe we recently started a new server, so we should have a process for updating. Perhaps we should also consider unattended upgrades?

**Comment by AlbertoPdRF** [comment]
I think what we should do here is try to move to Ubuntu 18.04 (latest LTS available.)

**Comment by UnsolvedCypher** [comment]
A distro upgrade would also allow for an upgrade to Ruby 2.6 as this [appears to be the reason Ruby is still on 2.5.3](https://github.com/thewca/worldcubeassociation.org/pull/3878).

**Comment by FinnIckler** [comment]
We fixed most of that when we switched to Ubuntu 20.4. But a cron job running apt-get upgrade should also be a thing
