### ISSUE TITLE
Implement WRC voting

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4558]
The WRC has set up a tentative voting system. Once we know exactly how we'd like voting to work, I'd like to move towards doing this on the WCA website:

- Have Delegates submit incidents as separate bullets
  - Maybe allow a single text field with a button to auto-split them?
- Allow the WRC to vote on any incident.
- Allow the WRC to introduce new incidents for a Delegate report.
- Support easily publishing a bullet in the Incidents log.
  - Perhaps make this the default, and have a way to mark "important" ones that are shown by default.
  - Note that the Delegate or WRC will need to anonymize a description of the incident for the public version.

I'm imagining that this would be a tab for the Delegate report. We can link to this in the WRC followup email, and even support:
- Directly linking to a vote page in the followup email.
  - This page should have a confirmation!
  - Sending emails to the thread to help the WRC internally keep track of votes.
  - Comments associated with any vote change, to be automatically included in that email.

**Comment by hanwu85** [comment]
I think the current problem is that we jump between too many platforms.  Most of the platforms are not connected, it is hard to track issues.  Inefficient, and easily to miss a incident/report.  A implementation of voting and delegate report would be a big boost.

**Comment by saranshgrover** [comment]
Closing this in favor of #5874
