### ISSUE TITLE
UI to request results changes

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4559]
I'm trying to figure out all the things we can systematize instead of manually handling by email.
It would be nice if there was a way for certain people (e.g. organizers, Delegates, WRC, etc.) to submit results changes with a semantic UI. For most cases, this can reduce the need to communicate the query by hand, and automatically generate/execute the SQL when the WRT accepts the change.

It would be very nice to tie this to votes (#4558) and/or incidents.

**Comment by Jambrose777** [comment]
See: https://github.com/thewca/worldcubeassociation.org/issues/2073

**Comment by lgarron** [comment]
> See: #2073

Ah, I lost track of that, thanks! That issue is sufficient.
