### ISSUE TITLE
Minutes section for Committees and Teams

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/worldcubeassociation.org#4575]
The WRC have just have a meeting and will publish a minute log of it of GitHub. I think it would be much better if we can publish directly on the web page as the Board does.

Also this could be the beginning of more minutes log from others Committees and Teams.

**Comment by Epride** [comment]
This would depend if other committees would have a need for posting public minutes which as far as I am aware few do. Maybe the best spot at the moment would be on the regulations page if anywhere. I will ask other Leaders if this would be useful for them.

**Comment by cubewhiz** [comment]
As WRC is already quite transparent in their work, I expect that the minutes may not be very useful. Won't the resolutions from the meeting be posted as updates to issues anyway?

I think the best solution might be to find a place on the github regulations repository for them.

**Comment by Ivan-Brigidano** [comment]
The idea is to publish the minute on GitHub. And yes, the resolutions have been posted as individuals Issues.

But I think it's also be a good idea to publish the minute on the website as it's more visited by the community because it's easier to use. This would probably enhance the transparency of the WRC even more.

Maybe the best idea if no more Leaders want to publish minutes is to post ir in Regulations section, as @Epride said.

**Comment by Epride** [comment]
Feedback from other Leaders was that they do not have a need to publicly post minutes of their meetings. Can someone please close this issue?
