### ISSUE TITLE
Add missing registration features for major competitions

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#4578]
Euros 2018 and Worlds 2019 both used a similar external registration system, the core of which was developed by Luis for Euros 2018. Major competitions in 2020 and beyond may continue to use this codebase.

There are many registration features that are incredibly useful for modern major competitions included in this. I don't believe it should be a necessity to set up an external registration just to get key features for major competitions. Organising such competitions is logistically challenging enough, without creating an external website to handle registrations etc. I feel integrating some features (not necessarily all) of Luis' code into the WCA website would be incredibly powerful.

A list of features that made us use external registration for WC2019. @Epride feel free to add:
- [ ] Per-event registration fees and base fee
- [ ] Ability to increase base fee for "early-bird" pricing etc.
- [ ] Automated registration acceptance (far more meaningful when you have 500+ competitors. See #328)
- [ ] Implementation of qualification times and automated event de-selection (see #2051) as well as calculation of the correct refund amount if using per-event fees
- [ ] Allowing competitors to change events, including automated additional payment features if per-event fees are used (as well as tracking "credits" if competitors de-register for an event). Saves dealing with literally hundreds of emails for event change requests.
- [ ] Integrated staff application form, with option for delegate voting

Some of these overlap with #329. I understand that this kind of thing should **not be priority** but I thought it would be useful to create an issue to track it. Key easy-fix big-impact registration flow limitations (see #2413, or #3798) should be prioritised over this.

**Comment by Jambrose777** [comment]
The second would go along nicely with multiple registration periods.

**Comment by Jambrose777** [comment]
Closing this for as there are already PRs for all of these (listed below). Maybe this kind of thing would be better as a project or label @gregorbg ??

> * Per-event registration fees and base fee

#1674

> * Ability to increase base fee for "early-bird" pricing etc.

#3267

> * Automated registration acceptance (far more meaningful when you have 500+ competitors. See #328)

#328

> * [ ]  Implementation of qualification times and automated event de-selection (see #2051) as well as calculation of the correct refund amount if using per-event fees

#2051 

> * [ ]  Allowing competitors to change events, including automated additional payment features if per-event fees are used (as well as tracking "credits" if competitors de-register for an event). Saves dealing with literally hundreds of emails for event change requests.

#941

> * Integrated staff application form, with option for delegate voting

For this, there are very many specific questions that differ from competition to competition, that it doesn't really seem feasible to have a uniform form on the WCA wesbite, but instead use Google Forums for example. Feel free to open a separate PR for this if you think it is a show stopper after the others would be implemented, or if there is a good idea for a generalized forum that works for all competitions. But overall, we wouldn't want to reinvent the wheel and remake google Forums on the WCA site :)
