### ISSUE TITLE
Add YouTube Icon to Header

### ISSUE THREAD

**Issue by Epride** [thewca/worldcubeassociation.org#4579]
Now that the WCA has a YouTube channel I believe this should be listed at the top of our website with all the other social media Icons

https://www.youtube.com/channel/UC5OUMUnS8PvY1RvtB1pQZ0g

**Comment by jfly** [comment]
Do we not have a nice, custom url for our channel? https://support.google.com/youtube/answer/2657968?hl=en

**Comment by dnpratama** [comment]
> 
> 
> Do we not have a nice, custom url for our channel? https://support.google.com/youtube/answer/2657968?hl=en

No, unfortunately not at the moment, but as soon as the channel turns 30 days old the feature will be  unlocked and we can change it. For the moment, Rui generated a bit.ly link (bit.ly/WCAyoutube)
