### ISSUE TITLE
Make the WCA Staff labels visible from the profile

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/worldcubeassociation.org#4581]
Right now to identify if someone is a WCA Staff you have to search him/her on [WCA Delegates list](https://www.worldcubeassociation.org/delegates) or the [WCA Teams, Committees, and Councils list](https://www.worldcubeassociation.org/teams-committees).

I think it would be helpful if the labels were visible from the profile. So it would be way easier to identify if someone is a Delegate. This is what I mean when saying "labels":

<img width="355" alt="Captura de pantalla 2019-09-07 a las 15 41 18" src="https://user-images.githubusercontent.com/47502355/64475693-2b130380-d186-11e9-84e8-e5e42c091224.png">

**Comment by moralsh** [comment]
Any Ideas where to place this info? I've got two ideas, right after the name or below, will probably also lose the "Member of" part. I'll try to post some screenshots during the weekend to help us decide.

**Comment by Ivan-Brigidano** [comment]
As the idea is to make it visible maybe the best place is just at the bottom of the name. What do you think?

**Comment by moralsh** [comment]
See for yourself:
![Iván Brigidano Pérez _ World Cube Association](https://user-images.githubusercontent.com/12932500/66233621-19247200-e6ec-11e9-8e3d-3d91d220709a.png)

The idea is to mirror the colors in the teams-committees page (blue leader, green senior, grey member) ant to link to that team section on that page, I've not decided yet whether to use the short version (WRC Member) or the long one (WCA Regulations Committee member) but of course I'm open to suggestions. 

I think I'll  code this option first and, see how that looks for people with various roles and then look at other options

**Comment by Ivan-Brigidano** [comment]
Looks nice to me!
Maybe rectangular labels with rounded corners will match better other label of the website. For example, incidents log labels
<img width="182" alt="Captura de pantalla 2019-10-04 a las 21 59 42" src="https://user-images.githubusercontent.com/47502355/66236293-6acffb00-e6f2-11e9-909d-d60f8407cae2.png">

Anyways this looks nice!

**Comment by moralsh** [comment]
I'll try when I have time to make a custom label for this, for now I'm sticking with classes we already have.

Some examples here:
![JA](https://user-images.githubusercontent.com/12932500/66274505-d8f5f880-e87f-11e9-8a99-0332a981d33a.png)
![apdrf](https://user-images.githubusercontent.com/12932500/66274512-de534300-e87f-11e9-9bca-66a8d493c4c9.png)
![GB](https://user-images.githubusercontent.com/12932500/66274533-080c6a00-e880-11e9-8671-f49a86642356.png)


I'm thinnking also in adding Delegate status.

**Comment by Jambrose777** [comment]
+1 for Delegate status as well.

**Comment by moralsh** [comment]
new screenshot today:

![Screenshot from 2019-10-07 20-37-39](https://user-images.githubusercontent.com/12932500/66338967-76196580-e942-11e9-97a8-cd888217cf23.png)

- Added Delegate tags (Either Senior Delegate, Candidate Delegate or Delegate)
- Fixed Diferent Size here and on the teams page

As of now, I'm adding every position except WCA Board, because it seems redundant with the officers tags, but would like to hear  other opinions, as well as the Board's.

What's left to do:

- Link to the teams page (with an anchor to the selected team) or delegate page
- I18n

I'll put together a PR and ask for review as soon as I'm done with it, I fear there's too much code on the view and that I should move some of the logic to the model or controller, I'd like to hear advice from anyone more used to RoR than me (which I guess is almost everybody here)

**Comment by Epride** [comment]
Given that not all Board members are necessarily officers I would say having the Board tag would be good.

**Comment by moralsh** [comment]
Done linking and internationalizing, plus adding a board tag for Board members, I've changed The <whatever> Member tag by just the acronym of the team, and also added councils, which weren't yesterday.

**Comment by moralsh** [comment]
I've been refactoring this (almost done) and would like input in the order the tags are shown, right now is delegate, officers, board, leaders, senior members and members.
I'm as bit unsure where to place delegates, the rest seems logical.

Anybody wants to where his/her opinion?

**Comment by Ivan-Brigidano** [comment]
I think placing Delegate status with the rest of the labels might work pretty well

**Comment by EdHollingdale** [comment]
If we want these labels to be used by competitors to identify who they can speak to, then a label for WCA Delegate is the most important of all in my opinion.

**Comment by Ivan-Brigidano** [comment]
> If we want these labels to be used by competitors to identify who they can speak to, then a label for WCA Delegate is the most important of all in my opinion.

So Delegate labels could appear before Teams labels, for example

**Comment by moralsh** [comment]
Just bumping the issue to see if PR #4704 can get merged and this closed :)

**Comment by Ivan-Brigidano** [comment]
Awesome work, @moralsh 🚀
