### ISSUE TITLE
Better refund audit trail

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#4582]
It is hard to find out who issued a refund (if at all, as I don't know the back-end) when managing competitions. The "Registration History" has a list of users who made the actions, but "Payment History" does not, whereas it definitely should. I would like this audit trail to be added.

This is part of a larger set of concerns which I will email the WST about privately, which also incorporates what was raised in #3224 and can expose individuals (mostly delegates), organisations, and in turn the WCA to considerable financial loss due to a lack of financial controls.

**Comment by viroulep** [comment]
I definitely agree with your points.

Some insight on how to implement this: we represent each payment and refund by a `RegistrationPayment` (which may be of negative value in the case of a refund).
An easy way to be able to track the history would be to add a `belongs_to :user` relation to the model, add the `user_id` column to the db table, and populate it with the user id making the request.

When doing this we should populate existing payments with a nil user id, and make sure in the view to display something like `<unknown user>` if it's not set.

It should be fairly straightforward for someone used to the rails framework.

**Comment by viroulep** [comment]
I'll work on this after #4682.
