### ISSUE TITLE
URL error/bug on FMC single rankings

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/worldcubeassociation.org#4604]
On desktop on chrome windows 10, going to https://www.worldcubeassociation.org/results/rankings/333fm/single and clicking on the profile link for anyone on there goes to a URL like https://xn--c1an.worldcubeassociation.org/persons/2011TRON02
this results in 
![image](https://user-images.githubusercontent.com/48773372/64901972-8c970e80-d66d-11e9-9039-2ede6fca199f.png)

**Comment by alexmaasswca** [comment]
Is fixed now it seems like, someone close if it has already been addressed and fixed just now.

**Comment by viroulep** [comment]
Hopefully it got fixed by #4486, I'm going to close this for now.
