### ISSUE TITLE
Allow organisers to set score_taking_url on the competition form

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#4642]
Would be cool to allow competitions to set live results URL and display it on the competition page if there is one (regardless the platform used).

**Comment by danieljames-dj** [comment]
I would like to take this up. Currently if the competition is ongoing, we are showing "This competition is ongoing. Come back after %{date} to see the results!". If the competition is imported in WCA Live, can we make it something like "This competition is ongoing. Click here to see the live results in WCA Live."?

**Comment by jonatanklosko** [comment]
The message sounds good to me, but I think we should support other platforms as well, which requires adding an optional URL field to the competition form. Also we don't have direct access to the information whether a comp is imported into WCA Live or not (we could obviously call the API, but that restricts the solution to WCA Live and adds an additional "dependency").

**Comment by danieljames-dj** [comment]
> which requires adding an optional URL field to the competition form
This solution looks good. Is it fine to have an extra field in competition form? Also, it will help in knowing how many competitions are using WCA Live and we can also know what are the different options used by people for live results.

**Comment by jonatanklosko** [comment]
@danieljames-dj sounds good to me =)
