### ISSUE TITLE
Allow full visibility of the schedule

### ISSUE THREAD

**Issue by Epride** [thewca/worldcubeassociation.org#4644]
**Describe the bug**
If there are events in the schedule between 23:00 and 24:00 it is impossible to remove them from the manage schedule page

**To Reproduce**
1. Create a new competition and add events
2. Set up venue information on the "manage schedule" tab however leave the "timezone" blank
3. Add events to the schedule around the middle of the day
4. Set timezone of the venue to "Melbourne"
5. Observe all of the events have moved in time and there is no way to retrieve any listing between 23:00 and 24:00

**Expected behavior**
Visibility should have the option to set schedule end time to 24:00

**Comment by Jambrose777** [comment]
related: #4081

**Comment by danieljames-dj** [comment]
PR #6566 fixed this issue as well.
