### ISSUE TITLE
URL Links to Wrong Page

### ISSUE THREAD

**Issue by ArchieMaclean** [thewca/worldcubeassociation.org#4679]
**Describe the bug**
When clicking on an event on the `records` page, the event always goes to `333/single` no matter what event is clicked on.

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/results/regions.php
2. Click on any event (e.g. Megaminx) - the green text.
3. It takes you to the 3x3 rankings no matter what you clicked on.

**Expected behavior**
Take you to the rankings of whatever event you clicked on.

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser: Chrome
 - Version: 76.0

This also happens on https://www.worldcubeassociation.org/results/regions.php?regionId=&eventId=&years=&mixHist=Mixed+History

This should probably be pretty easy to fix, but unfortunately I don't know Ruby :(
Thanks

**Comment by ArchieMaclean** [comment]
I think clicking on Megaminx goes to https://www.worldcubeassociation.org/results/e.php?i=minx which redirects to the new page.

**Comment by jonatanklosko** [comment]
Fixed in #4882 and #4883.
