### ISSUE TITLE
Server status script

### ISSUE THREAD

**Issue by jbcm627** [thewca/worldcubeassociation.org#47]
Have a script (as decoupled from everything and robust as possible) that monitors the status of things, and alerts someone when things go down.

**Comment by jfly** [comment]
[Newrelic](http://newrelic.com/)'s free tier might be sufficient for this.

**Comment by gagou9** [comment]
Many use Nagios for supervision.

**Comment by jfly** [comment]
This becomes more important after we merge up #633.

@larspetrus mentioned pingdom in https://github.com/cubing/worldcubeassociation.org/pull/635#issuecomment-220088491, although New Relic might be good enough for us.

**Comment by jfly** [comment]
Our delayed jobs stopped running sometime yesterday, and nobody noticed. It is important that we set up some sort of external monitoring that makes sure our jobs are still running.
