### ISSUE TITLE
WRC Delegate report email sender does not match Delegate reports

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#4753]
As of #4639, Delegate reports are sent from `reports@`, but the `wrc_delegate_report_followup` is still sent from `notifications@`. This is causing WRC members to miss some Delegate reports.

**Comment by Jambrose777** [comment]
If WRC replies to these, they should probably come from regulations@, right?

**Comment by Ivan-Brigidano** [comment]
@Jambrose777 it's better that they come from the same mail than reports so GMail will automatically group them

**Comment by moralsh** [comment]
Having regulations as sender guarantees that replying will get to all members and it's quite easy to make a filter on Gmail. But I guess you all are used to not having the email as sender already.

**Comment by lgarron** [comment]
I think there's a bit of a misunderstanding here. This is about the followup email that is sent to WRC members by the website: https://github.com/lgarron/worldcubeassociation.org/blob/091bd97dee8c1d15f881add5cb510cdb3034edef/WcaOnRails/app/views/competitions_mailer/wrc_delegate_report_followup.erb

As @Ivan-Brigidano, we need the sender and subject to match the main report, else GMail does not group the emails into a single thread. This is causing us to miss track of who should be reviewing each report.
