### ISSUE TITLE
Create a light version of the database export, use it in WCA Assistant

### ISSUE THREAD

**Issue by Claster** [thewca/worldcubeassociation.org#4756]
Hi,

Today I used WCA Assistant to generate results. The tsv.zip file it downloads has a size > 100 MB nowadays and takes quite some time to download. On the other hand, I doubt that every single line in every CSV is used, most likely only competitors and competitions list is needed. How about creating a lite version of the WCA database specifically for WCA Assistant?

(Of course, this is not relevant if you use WCA Live)

**Comment by jonatanklosko** [comment]
Actually, as we have [Scrambles Matcher](https://viroulep.github.io/scrambles-matcher) now, I think it's not an actual issue. We should drop WA somehow soon instead.
