### ISSUE TITLE
Main event selection from competition submission form is not reflecting in results posting

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#4765]
There is a field to select the main event in the competition submission form, but while posting the results, it's still asking to select a main event for announcement and it is creating an ambiguity.

**Comment by jonatanklosko** [comment]
The plan is to get rid of the results announcement posts, effectively removing the other even selector. The selector in the competition form was added in #4529, but we still need to fill them for past competitions and then deploy #4554 right away (so it needs to be finalized first).

**Comment by AlbertoPdRF** [comment]
Shouldn't this be closed now that #5140 (which superseeded #4554) has been merged?

**Comment by jonatanklosko** [comment]
Yeah, thank for keeping an eye on it! :eyes:
