### ISSUE TITLE
Not updated reg list

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#4782]
**Describe the bug**
If I edit registration, it's not change in list of registrations. 

**To Reproduce**
1. Go to registrations list as an organizer / Delegate
2. Edit registration, for example add event 
3. Go to competitiors list opened for everyone
4. See that registration change is not visible

**Expected behavior**
Changed events list in competitors list

**Comment by viroulep** [comment]
Just coming across this, may simply be a caching issue.

**Comment by tussosedan** [comment]
Taking a look at this one.

**Comment by EdHollingdale** [comment]
Looks to be the same as #3987
