### ISSUE TITLE
When I remove an event or round, it is still visible in the "Manage schedule" page

### ISSUE THREAD

**Issue by Goosly** [thewca/worldcubeassociation.org#4793]
**Describe the bug**
When I remove an event or round, it is still visible in the "Manage schedule" page

**To Reproduce**
1. Go to a competition you can manage
2. Add some events and add all rounds to the schedule
3. Go to "Manage events" and remove an event or remove a round
4. Go to "Manage schedule". The removed round(s) are still there

**Expected behavior**
In step 4, I expect the removed round(s) to be removed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Jambrose777** [comment]
Closing this as expected behavior. We also give a warning/error before the competition is announced and we have an open issue for after its announced: #4653
