### ISSUE TITLE
Additional validations when banning a competitor

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#4800]
When banning a competitor we should ensure they aren't registered for an upcoming competition (unless the registration is deleted). In such case we want to show a validation error, so that whoever bans the given person would need to ensure to delete the registration(s) in question.

**Comment by tussosedan** [comment]
I'm taking a look at this one.

**Comment by tussosedan** [comment]
What if, after this change, a user's registration is deleted and then they are banned -- but later their registration is moved back from deleted to pending or accepted? Do we want to protect from that as well, and not allow a registration to be undeleted if the user is banned?

**Comment by jonatanklosko** [comment]
I think ideally we'd have a registration validation that would ensure a banned competitor registration cannot go to the approved state.
