### ISSUE TITLE
[Delegate Admin Page] Change Results Posted to Results Submitted at

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4802]
After discussion with Board and WRT, the Results Posted at Column should be changed to Results Submitted at as that would better reflect the Delegate's quality. Screenshot of page attached.

![image](https://user-images.githubusercontent.com/11577241/68266843-56975a80-001e-11ea-8194-b1876c211ef2.png)

**Comment by pedrosino** [comment]
Just to clarify, since old competition don't have a results_submitted_at, we would keep results_posted_at for those, right?
Might be good to add a (?) thing with this information.

**Comment by SAuroux** [comment]
No, results_submitted_at was actually set to results_posted_at for older competitions:

> SELECT MIN(start_date) FROM Competitions WHERE results_posted_at <> results_submitted_at

returns '2019-01-14'
