### ISSUE TITLE
Intermittent test failure in registrations requests spec

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#4841]
I've gotten this in many travis build lately:
```
  1) registrations POST #do_import when signed in as competition manager registrations re-import CSV registrant already in the database, but deleted acceptes the registration again
     Failure/Error:
       expect {
         post competition_registrations_do_import_path(competition), params: { registrations_import: { registrations_file: file } }
       }.to not_change { competition.registrations.count }
         .and change { registration.reload.accepted_at }
     
       expected `registration.reload.accepted_at` to have changed, but is still nil
     # ./spec/requests/registrations_spec.rb:336:in `block (6 levels) in <top (required)>'
```

It usually goes away when restarting the build.
Any idea what could be going on @jonatanklosko?

**Comment by jonatanklosko** [comment]
Looking at the test, I'm pretty sure this line is responsible:
https://github.com/thewca/worldcubeassociation.org/blob/86529fe9180f04bbd44e1850fbf844c4d501c0be/WcaOnRails/spec/requests/registrations_spec.rb#L334
We use `user.country.name` whereas an id is expected, for most countries these two match, but as the country is randomly assigned it could fail from time to time!

**Comment by viroulep** [comment]
Oh nice catch!
Do you want to fix it or should I?

**Comment by jonatanklosko** [comment]
Doing so!
