### ISSUE TITLE
Incidents Log

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/worldcubeassociation.org#488]
This came up in an email thread to the delegates list, and this is an idea I was discussing with @jfly before that email came out.

I think it would be quite handy if we had a log of incidents that delegates could reference, and preferably be searchable. This would allow a delegate to search the incidents to try and find reasonable precedent on how to handle a situation/incident they experience at a competition that they might not know how to handle otherwise. Usually this means sending an email out to the delegates list and putting "Urgent" in the subject line.

Unfortunately, I'm not sure how to put incidents into the log, and how to merge similar incidents. I think this log should be more of a broad thing rather than a log of every single incident we experience at a competition. I do fear that maintaining such log will end up being manual labor (which we always want to try and avoid).

Another possible feature: Have the incidents log be a bit general, and link incidents in the delegate reports to an incident entry in the log. When we see an incident type / category from the log, we could be given a list of delegate reports that contain these incidents. The delegate could then read through the various specific scenarios and see which one closest resembles their specific situation, or maybe to get a general thought about how it was handled in the past, etc. If we did this feature, it would be nice if the link to the delegate report linked to an anchor to the incident in the report, scrolling the user directly to that incident in the report.

@viroulep and @jfly  might have some opinions to add to this!

**Comment by jfly** [comment]
:+1: with a :confused: what's best

**Comment by FatBoyXPC** [comment]
Here's a great example of why this could be useful:

At Spring Scramble 2016 Anthony Brooks had a practice cube with him at the station. The runner grabbed that cube rather than the cube Anthony had just solved. He noticed the cube was wrong during the next attempt and asked for an extra scramble. People replying to the thread seem to have trouble coming to agreement whether the extra scramble should count or not. Apparently, this same thing happened at Michigan 2014 to Rami Sbahi, and nobody was opposed to him getting an extra scramble.

"Nobody" refers to the delegate list when discussing these incidents in the Delegate Reports.

**Comment by viroulep** [comment]
For those watching this issue, please take a look to #1862 which implements this.
At the time of writing this it is deployed [to staging](https://staging.worldcubeassociation.org/incidents) if you want to try it (keep in mind everyone's password there is "wca").
