### ISSUE TITLE
Clarify possibility to reassign WCA-ID between user accounts

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#4897]
Problem: Many WCA Delegates currently fail to understand the intended way for assigning WCA-IDs if the WCA-ID is already claimed by a different account, which is first removing the WCA-ID from the old account and then assignbing it to the new one.

Proposal: Extend current warning "WCA ID is already used by <name> with <email>." by something like "To free the WCA-ID, you can edit that account and unassign the WCA ID here.", where "here" should lead to the edit page of the account the WCA-ID is currently assigned to.

**Comment by tussosedan** [comment]
I'll take a look at this one.
