### ISSUE TITLE
Add user preference for calendar view by default in schedule tab

### ISSUE THREAD

**Issue by zeecho** [thewca/worldcubeassociation.org#4939]
I might be wrong but I have the feeling that most people prefer (and expect) the calendar view over the table one. Therefore, it might make more sense to show the calendar view by default?

**Comment by AlexKatyukov** [comment]
Don't think so. I'm a fan of calendar view but a big part of another cubers like table view.

**Comment by Jambrose777** [comment]
See poll: https://forum.worldcubeassociation.org/t/competition-schedule-default-view/14287

I personally prefer the Calendar view and always have to change it.

**Comment by Jambrose777** [comment]
Community feedback indicates a 2:1 favor of keeping as is. Because of that, I’m changing this to be a feature for adding a user preference for which schedule view you would want to view by default.

**Comment by kr-matthews** [comment]
This will be resolved in the new registration system: your browser will remember which view you last used (independent of the competition). No need for accounts/preferences to be involved.
