### ISSUE TITLE
Prevent DNS-only results to enter the database

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#4964]
Neither WCA live nor the results validation on the website currently prevent DNS-only results to be entered and submitted. This is actually a flaw of both, but since cubecomps didn't allow DNS-only results to be entered, this filter being missing in the website's result validation was no problem in practice so far.

Proposed solution:
1. Disallow DNS-only results to be entered in WCA live.
2. Add a check to catch DNS-only results in the results validator. Quote by @viroulep: _I believe a simple check either in the resultable model or in the individual results validator would be able to detect that._

**Comment by viroulep** [comment]
@tussosedan you've been doing a bit of work in the results validator recently, would you be interested in taking a look?
It should be a fairly straightforward fix :)

And for the record, no matter what WCA Live/Cubecomps are doing, we should definitely validate that on the website.

**Comment by tussosedan** [comment]
Of course! I'll try finding some time for it.

**Comment by viroulep** [comment]
@tussosedan I think I just stole this from you while working on #4638 :s

**Comment by tussosedan** [comment]
Hahaha no worries, I haven't started yet.
