### ISSUE TITLE
Public unlinked profiles don't load

### ISSUE THREAD

**Issue by notkevin888** [thewca/worldcubeassociation.org#4974]
**Describe the bug**
Trying to load a competitor's profile when their account isn't linked seems to consistently return the "We're sorry, but something went wrong" error page.

**To Reproduce**
1. Attempt to hit a new competitor's profile, eg https://www.worldcubeassociation.org/persons/2019HOEB01 from Grossmont Fall 2019.
2. See error.

**Expected behavior**
We should be able to see 2019HOEB01's results in a typical competitor profile page.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**
Add any other context (for instance the language you're using the site in) about the problem here.

**Comment by moralsh** [comment]
I'll take a look at this later today, as most probably is something related to #4704
