### ISSUE TITLE
Add links to organizer and delegate profiles from competition info

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#4985]
It'd be quite useful to be able to click on an organizer/delegate and link to their WCA profile. For delegates we already have `mailto:` links, but I'm not sure if that's more valuable, a room for ideas here.

**Comment by EdHollingdale** [comment]
I would prefer this change - people should be using the contact email rather than emailing delegates individually. For organisers, there are lots of organisers who do not have a WCAID, so that would be challenging.

**Comment by moralsh** [comment]
I see no downside at all for this change as the Delegate's emails is easy to get to and as Ed says it's better that the competitors email organizers than delegates, if the delegates want their email shown they can always add their emails to the contact field.

Another option could be to add a little envelope icon after the Delegate's name, but It's ugly and a worse idea IMHO.
