### ISSUE TITLE
Allow user to invalidate his sessions on other devices

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#5004]
It's been suggested that we implement a "Sign out of other devices" button, as currently achieving this requires resetting password (resetting to the same password has the desired effect, but it's obviously not intuitive). This probably means overriding some Devise methods, but that's something to investigate.

**Comment by Nanush7** [comment]
Hi Jonatan, 
Are you planning to release this feature?

**Comment by jonatanklosko** [comment]
@Nanush7 I've just created #5542 with a potential implementation.
