### ISSUE TITLE
Bug in Sum Of Ranks regarding MBLD rankings

### ISSUE THREAD

**Issue by GuidoDipietro** [thewca/worldcubeassociation.org#5005]
The Sum Of Ranks section presents the following mistaken behaviour when it comes to MBLD rankings:

Competitors from South America that haven't competed in MBLD receive 1 extra point than what they should on SOR.
Check it out [here](https://www.worldcubeassociation.org/results/misc/sum_of_ranks/?regionId=_South%2BAmerica&single=Single).
They get 170 extra points for not having competed, but there are only 168 recorded PRs in this event in this continent. [Top 1000 persons in SouthAm.](https://www.worldcubeassociation.org/results/rankings/333mbf/single?region=_South+America&show=1000+persons)

When it comes to Europe, the issue is the inverse. Such competitors get 1 point less than they should:
They get 898 points when they should be getting 899. Check it out [here](https://www.worldcubeassociation.org/results/misc/sum_of_ranks/?regionId=_Europe&single=Single):
[Europe top1000 persons](https://www.worldcubeassociation.org/results/rankings/333mbf/single?region=_Europe&show=1000%2Bpersons)

I must also note that this issue does not prevail **for every** country in South America or Europe; for example, note the following:
Brazil has 71 MBLD PRs, competitors that don't have a result get 72 points -> good
Belarus has 14 MBLD PRs, competitors that don't have a result get 15 -> good
Argentina has 14 MBLD PRs, competitors that don't have a result get 16 -> bad

I expect there to be only 1 single country in Europe to have said behaviour, therefore impinging on the total European SOR.
Other continents work properly. This might be because

- There is no problem, or
- There are +1 and -1 countries which cancel out (or more)

Note that could be the case for Europe as well (why not, 2 -1 countries and one +1?)

Thanks for the read.

**Comment by GuidoDipietro** [comment]
6 months later, bug is still present

**Comment by campos20** [comment]
> 6 months later, bug is still present

What about you trying to solve it? Since the website is not really my thing, I can't help you, but this is likely to be just an SQL statement.

**Comment by GuidoDipietro** [comment]
Wouldn't know how, really, I am not too confident with SQL

**Comment by maconard** [comment]
I haven't dug into this issue at all, but a motivating question: is there any chance it relates to an issue with counting people who have changed their WCA nationality?
