### ISSUE TITLE
Remove Feet Icon

### ISSUE THREAD

**Issue by campos20** [thewca/worldcubeassociation.org#5028]
2020 regulations does not require the feet icon on the ranking

https://www.worldcubeassociation.org/results/rankings/333ft/single

![Captura de tela de 2020-01-01 18-04-55](https://user-images.githubusercontent.com/10170850/71646104-3fdd4f00-2cc1-11ea-8b63-a4e3e687dcf6.png)

It's also necessary to remove it from personal rankings, history and other references.

**Comment by Louis-dM** [comment]
It's also still on people's "Current Personal Records" table on their profiles

**Comment by campos20** [comment]
Good point. I'm renaming this and removing the first issue thing.

**Comment by AlexKatyukov** [comment]
And we should remove feet event from events menu in competition settings.

**Comment by jronge94** [comment]
It should also be removed from SOR.
It's after 3 weeks still visible on people's pages
