### ISSUE TITLE
Bugs in sum of ranks when someone changes citizenship

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/worldcubeassociation.org#5044]
https://www.worldcubeassociation.org/results/misc/sum_of_ranks/?regionId=Mauritius&average=Average

Going to here, you can see that Ryan Pin Harry should receive a bunch of red numbers in the sum of ranks for events he has not competed in under his country, but he doesn't receive any.

Similar issue with Antonie Paterakis

https://www.worldcubeassociation.org/results/misc/sum_of_ranks/?regionId=Netherlands&single=Single

**Comment by LinusFresz** [comment]
I think this has already been discussed here: https://github.com/thewca/worldcubeassociation.org/issues/2399

**Comment by viroulep** [comment]
Yep that's a duplicate.
