### ISSUE TITLE
Competition page: The 'Competitors' link shown/hidden depends on where I navigate to

### ISSUE THREAD

**Issue by Goosly** [thewca/worldcubeassociation.org#5084]
**Describe the bug**
When you go to a competition for which the registration is not open yet, the 'Competitors' link in the menu on the left suddenly appears when I navigate to 'Register'

**To Reproduce**
1. Go to a competition for which registration is not open yet (for example: https://www.worldcubeassociation.org/competitions/BarwonForTheBush2020)
2. Click on 'Register' on the left
3. 'Competitors' on the left suddenly appears

**Expected behavior**
I expect the availability of the 'Competitors' link to be consistent, and not dependent on where I navigate to or which page I'm currently on

**Screenshots**
![image](https://user-images.githubusercontent.com/12575384/72721595-b791f180-3b7c-11ea-8ecc-2c510bc3fddf.png)

**Comment by notrichardpeng** [comment]
Currently, it seems like I can only reproduce this bug when I'm logged into an account that has admin access to the website (like being able to create a new competition). Can someone please double-check?

**Comment by Goosly** [comment]
@notrichardpeng  Interestingly enough I cannot reproduce it myself anymore 😃 
e.g. when I go to https://www.worldcubeassociation.org/competitions/GACubersPavilion2021 , I immediately and always see these 4 items in the side menu:

![image](https://user-images.githubusercontent.com/12575384/123856816-d378f580-d921-11eb-95cb-fcfcd065bdde.png)

**Comment by notrichardpeng** [comment]
Nice :D, is this issue resolved then?

**Comment by saranshgrover** [comment]
I also do not see this issue when logged in as an admin on prod
