### ISSUE TITLE
Replace phpBB forum?

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#51]
Something reddit style with threading and voting might be pretty cool, and probably share code with #136.

It also might be desirable to move delegate report discussions off of the delegates mailing list. This could all be started by #222.

**Comment by jfly** [comment]
It might be easier and better to add comments to the posts on WCA homepage instead. Something reddit style with threading and voting could be pretty cool, and probably share code with #136.

**Comment by gagou9** [comment]
Yo!

Jeremy Fleischman:
> It might be easier and better to add comments to the posts on 
> WCA homepage instead. Something reddit style with threading and
> voting could be pretty cool, and probably share code with #136.

Yeah. Do we want to have the same system for the Q&A (for documentation)
and the commenting system ?
I would actually say no I think.
So we would have our documentation in a questionnable format, and a
commenting system for the public posts. Sounds great to me!

**Comment by jfly** [comment]
Closing in favor of getting rid of the forum entirely. See #1653.
