### ISSUE TITLE
Rename "Combined Round" to "Cutoff Round"

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5101]
Regulations 2020 renamed combined rounds to cutoff rounds, we need to reflect this change across the website.
It may just be renaming it in the round type logic, but there may be more hidden stuff on the php side.

**Comment by jonatanklosko** [comment]
For the record: after some discussion I updated WCA Live to not include the "cutoff" fact in the name, so all first rounds are just called "First Round". I think in most places including "cutoff" in the name doesn't really provide any value to the reader, but is longer and may also be a source of confusion (especially for external visitors).

Not sure what's best for the WCA website though, what do you think?
