### ISSUE TITLE
How canceled competitions are handled on the WCA site

### ISSUE THREAD

**Issue by maconard** [thewca/worldcubeassociation.org#5145]
**Describe the bug**
When a competition has been canceled, its WCA site seems to be immediately no longer accessible. Unless there is a good reason I'm yet unaware of (obviously emails are likely sent and such), this seems to promote confusion, as a helpful cancellation message would be more useful than "the page you were looking for doesn't exist."

**To Reproduce**
Try to access the WCA site for any canceled competition **with public permissions** (delegates or organizers may still be able to access it?), such as https://www.worldcubeassociation.org/competitions/FushunOpen2020 or https://www.worldcubeassociation.org/competitions/SingaporeCubeChampionship2020

**Expected behavior**
A simple cancellation message screen, possibly giving the exact reason the event was canceled.

**Screenshots**
For FushinOpen2020, it seems the organizers edited the WCA site to announce the cancellation. But this isn't visible on the WCA site because the site is removed! It is, however, visible on Google's cached search result for the competition:
![canceled_1](https://user-images.githubusercontent.com/31703304/73975783-0b2e6a00-48f5-11ea-9ac7-7b398f32e4dc.png)
![canceled_2](https://user-images.githubusercontent.com/31703304/73975786-0bc70080-48f5-11ea-9a8a-0914c5e4e3db.png)

**Desktop (please complete the following information):**
I don't think this is relevant to the issue at hand, but:
 - OS: Ubuntu 18.04
 - Browser: Firefox

**Additional context**
Discussion arose from a query in the WCA Statistics Facebook group.

**Comment by Jambrose777** [comment]
Typically, if a competition is cancelled, Text will be put in the competition saying that the competition is cancelled, then once the competition date has past, they are removed from the website.

The first one you mentioned is a special case agreed on by WCAT and board to remove early due to using CubingChina. I'm assuming there were similar reasons for the second.

Ultimately this is up to WCAT to handle, and determine appropriateness of which site should be kept up and not.

**Comment by cubewhiz** [comment]
In most cases, the cancelled competition is deleted on the website after it was scheduled to take place. The competitions in China were removed early because competitors in China do not rely on the WCA website for their information--they were canceled on Cubing China, so it was decided it would be less confusing to delete the competitions from the WCA website.

**Comment by maconard** [comment]
Interesting. Having bumped into it for the first time though, my reactionary feeling was we should have a permanent "this event never occurred/was canceled" landing, since people still may have heard about it and go looking for it. 

My brief follow up question is how are competitions marked as canceled? I don't see a `canceled` attribute or anything similar, even in the dev DB table for competitions. 

Regardless, if the consensus then is that this is the best and desired behavior, feel free to close this issue. 

Thanks for your thorough responses!

**Comment by cubewhiz** [comment]
Yes, I do think that having a message indicating the competition was canceled is better in general, but it had not been implemented and we needed a solution, so we did what we think is the next best thing. I think it is worth keeping open unless anyone has a strong reason for deleting the competitions entirely.

**Comment by BrandonMikel** [comment]
I believe cancelled competitions are just reverted back to not confirmed, so they are no longer visible? I can still see all the cancelled ones in my bookmarked competitions list. They are red and say "This competition is not confirmed and not visible.

<img width="1166" alt="Screen Shot 2020-02-20 at 10 49 38 PM" src="https://user-images.githubusercontent.com/33575560/75005226-58512680-5433-11ea-8136-c865f5aa2008.png">

**Comment by maconard** [comment]
Fair enough, @cubewhiz. I may try to work up a page for it (along with some other indicators while searching) and see what everyone thinks.

@BrandonMikel interesting. I wonder if they intended for bookmarks of canceled competitions to remain. It would be weird if you logged in and a bookmark was gone, though.

**Comment by viroulep** [comment]
I don't like very much how we're handling cancelled competitions, basically we're handling them as if they never existed (yet they show up in everyone's "my competitions" page).
With the current software means it's probably the best way to handle this, but we should be able to do something cleaner and less confusing:
  - have a "cancelled_at"/"cancelled_by" field to identify which are cancelled
  - automatically filter our cancelled comp from the competitions list (with an option to include them)
  - automatically indicate in the title/description that they are cancelled
