### ISSUE TITLE
Establish Parity for Public Information between the Competition Page and the Competition API

### ISSUE THREAD

**Issue by FinnIckler** [thewca/worldcubeassociation.org#5161]
**Is your feature request related to a problem? Please describe.**
There is currently not a parity of public information between the Competition page and the API. 
Data that you can get on the Competition page but not on the API includes:
- Organizer Email
- Registration Period
- Competitor Limit (is available through wcif)

**Describe the solution you'd like**
I think all the data that is on the competition page should also be available programmatically through the API, which can easily be achieved by adding the fields in the /competitions/{ID} endpoint

**Additional context**
Currently you need to scrape the competition page for this data, which is both a bad experience for the site, and for the developer trying to work with the data.

**Comment by coder13** [comment]
Should this be closed?
