### ISSUE TITLE
Refund default value to be based off refund policy percentage instead of defaulting to 100%

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/worldcubeassociation.org#5162]
I don't really like the idea of organizers/delegates calculating the percentage because there is a chance of incorrect calculation.  Additionally, one can always mistype.  I think that having the default refund amount follow the policy makes the most sense.

We should obviously still keep the ability to manually edit the refund amount (for example, competitors on the waitlist that have paid in full, etc.).  Just makes it easier to hit the "Refund" button when dealing with a cancelled registration :/

Additionally, maybe have a cancel registration button that's separate from a refund button?  The cancel registration button would automatically delete the competitor's registration and would refund the correct percentage.  This could be confusing though as refund and cancelling might not be as distinct as I think it is (or the distinction may be less obvious to some people).

**Comment by dunkOnIT** [comment]
Closed in favour of #7070
