### ISSUE TITLE
Add "Sort by announcement date" option on competitions page

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#5163]
With the competition announcements no longer being posted, I've noticed a vocal minority of people that used this to check for competitions. I think it might be worthwhile for this vocal minority to add a "sort by announcement date" feature to the competitions page, which is already being stored for admin purposes.

**Comment by viroulep** [comment]
This will most likely require two changes:
  - adding a "sort by announcement date" in the API and the "search" method of the competition model
  - adding a button on the competitions page to actually sort competition by this date

Maybe we should even restrict this button to "upcoming" competitions, since sorting past competition by announced date doesn't make much sense from a user point of view.

**Comment by moralsh** [comment]
I have this more or less working on my development server. As of now, I've just added another button between past and filter but I'm not sure if that's the best place. I'll attach a screenshot tomorrow when I finish updating my dev server with the last dump.

Another question, should I print the announcement date somewhere in the table and/or add options in the filter option to filter by announcement date?

**Comment by jonatanklosko** [comment]
> Another question, should I print the announcement date somewhere in the table and/or add options in the filter option to filter by announcement date?

I don't think it's important enough to show in the table, but one idea would be showing it when hovering over the hourglass icon. Now it says `Starts in X days`, so it could be modified to `Announced X days ago <br /> Starts in X days`. Just an idea!

As for filtering, personally I'd say it's an overkill, but if you find it useful we may have it ^^

**Comment by danieljames-dj** [comment]
Is anybody already working on this? If not, I would like to give a try.

**Comment by viroulep** [comment]
If I understand correctly @moralsh has pretty much done it correctly, maybe it's best to hear from him before actually taking over.

**Comment by moralsh** [comment]
Yeah, I had it mostly finished but then a lot of things happened on the last month. I'll look onto it and update you later today or tomorrow.

**Comment by moralsh** [comment]
Ok, I have it working already, I'll do a little of cleanup later and commit afterwards.

**Comment by moralsh** [comment]
Last minute doubts: As of now, The By announcement button sorts by announcement date in ascending order which is what one understands by sorting by announcement date.

![image](https://user-images.githubusercontent.com/12932500/78979596-7c201700-7b1c-11ea-8d9d-9a77198c72dc.png)

However, I'm guessing most people who'd want to use this feature would like to see the lastly announced competitions. I'm torn between leaving it as it is, reversing the ordering (and adapting the messages)  or maybe adding a dropdown to select announced on last week, last month, etc. I'd very much appreciate more input here.
