### ISSUE TITLE
Result-based advancement condition is conveyed incorrectly

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#5176]
That's what result-based advancement condition means:

> [9p2+](https://www.worldcubeassociation.org/regulations/guidelines.html#9p2+)) CLARIFICATION Result refers to the single or average that determines the ranking of the corresponding round.

On the contrary, the current wording clearly refers to single attempts:

https://github.com/thewca/worldcubeassociation.org/blob/20cc8f080e0f605fbbaf405563b9d0a7c01ef635/WcaOnRails/config/locales/en.yml#L153-L156

https://github.com/thewca/worldcubeassociation.org/blob/20cc8f080e0f605fbbaf405563b9d0a7c01ef635/WcaOnRails/config/locales/en.yml#L159-L162

Also see https://github.com/thewca/wca-live/issues/54.

**Comment by viroulep** [comment]
I think that's a duplicate of #3597.

**Comment by jonatanklosko** [comment]
Closing in favor of #5661.
