### ISSUE TITLE
"Main Event" is an option after cloning a competition

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#5187]
**Describe the bug**
When cloning a competition, the main event gets cloned and appears on the new competition form. However, it produces an error that cannot be avoided - the main event is not added to the competition, but events can't be added on the new competition form. After submitting once, the main event field is removed despite the error, and you can then just submit the form with no changes and have no error.

**To Reproduce**
1. Clone a competition with a main event
2. Submit the form with a main event selected

**Expected behavior**
Main event should not be a field that gets cloned when cloning a competition, and the cloned new competition form should not display this field.

**Comment by viroulep** [comment]
It's weird, the main_event_id is definitely in the list of uncloneable attributes [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L136).

When cloning the competition it appears blank for me, even though the competition did have a main event.
In which case unless the user changes it there is no error.

I agree that we should not display that field at that point in the first place!

**Comment by KitClement** [comment]
Maybe I'm not remembering correctly then, and I had set the field myself which caused the error.

**Comment by Mollerz** [comment]
I ran into this as well recently, it is exactly how Kit describes.

**Comment by f3rmat** [comment]
@viroulep 
I took a stab at this in this PR: https://github.com/thewca/worldcubeassociation.org/pull/5783
Tested it on my local.
