### ISSUE TITLE
Change WRT Main Event Warning

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5196]
Original text if the results do not contain 3x3: `Your results do not contain results for 3x3x3 Cube. Please tell WRT in the comments that there was 'no main event' if no event was treated as the main event at the competition. Otherwise, if an event other than 3x3x3 Cube was treated as the main event, please name the main event in your comments to WRT and explain how that event was treated as the main event of the competition.`

I would like to see this changed to: When the main_event_id <> '333' Then: `The selected main event for this competition is: {main_event_id name || 'Nothing'}. Please give WRT an explanation of how that event was treated as the main event of the competition.`

**Comment by danieljames-dj** [comment]
Was this issue solved in https://github.com/thewca/worldcubeassociation.org/pull/5318?

**Comment by SAuroux** [comment]
Ah, yes, it was in fact!
