### ISSUE TITLE
Producing invalid WCIF#persons

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#5200]
WCIF JSON schema requires `birthdate`, `gender` and `countryIso2` for every `Person`:
https://github.com/thewca/worldcubeassociation.org/blob/2bbc318e85202bd8da7d48abf133de9fd0dfde62/WcaOnRails/app/models/user.rb#L1021-L1023

We do require that information for any registered competitor, but we don't do it for organizers! It's quite common to set up group accounts, e.g. "X Association", "Y Cubing Club" and then list them as organizers, but those accounts don't necessarily have the mentioned attributes set.

As a result the `/wcif` endpoint returns an invalid WCIF (with one of `WCIF#persons` having the attributes `null`), so if then someone sends an update with the WCIF slightly modified, the JSON schema validation fails.

As far as I can see there are two solutions:
1. change schema validation to allow `null` (fixes the validation problem, but we'd still produce WCIF differing from the spec)
2. require organizers to have the information filled (addresses the original issue, but what to do with exiting accounts?)

I'd say we should go for `2.` and for existing accounts set gender to `other`, `countryIso2` to the country where the given competition is organized. For some organizations the birthdate could be the establishment date, but setting a random value doesn't sound bad either. Thoughts?

**Comment by viroulep** [comment]
The solution number 2 you described sounds good!
