### ISSUE TITLE
Allow Cutoffs to be by number of people

### ISSUE THREAD

**Issue by jamesquinn1** [thewca/worldcubeassociation.org#5205]
Not sure if this is the best place to suggest this, sorry.

Would be useful for if the second or third attempt of MBLD or FMC can only accommodate a certain amount of people because of schedule, room, etc; and being able to take a number of people over having to guess at result would allow more competitors than guessing.

**Comment by Jambrose777** [comment]
We used to have 9g2, which has since been removed. See: https://github.com/thewca/wca-regulations/issues/425

Also this is a regulation issue, not software ;)

**Comment by viroulep** [comment]
Closing this, @jamesquinn1 feel free to run this by the WRC, I don't think the website's github is the place to discuss this.

**Comment by jamesquinn1** [comment]
Sounds good, I'll consider proposing it there.
