### ISSUE TITLE
Fix German translation of schedule timetables

### ISSUE THREAD

**Issue by dancing-jules** [thewca/worldcubeassociation.org#5207]
Currently the timetables of competitions are translated to German quite literally. "AM" turns into "vormittags" and "PM" turns into "nachmittags". That works okay for most cases, but fails for 12AM/12PM:

![grafik](https://user-images.githubusercontent.com/33940391/75123559-c9e5da80-56a8-11ea-80d9-6b496156528b.png)

When you ask a German speaker what "12:50 VORMITTAGS" means, they'll either think of noon (instead of 12:50 AM = shortly after midnight) or be completely confused.

Two possible solutions:

1. Write "00:50 FRÜH" and use that for anything up to ~8-9AM (and "vormittags" for anything later in the morning)

2. Use the 24-hour-format 00:00-23:59 without any AM/PM descriptors. 

I'd much rather go for option 2.

In German the xx:yy format always implies 24-hour-format. The 12-hour-format is usually only used with descriptors like "o'clock", "half", "quarter" and "ten minutes after". 

PS: I am Austrian, if maybe someone from Northern Germany may chime in whether my statements about 12/24-hour-formats are true in Northern Germany as well.

**Comment by Laura-O** [comment]
Should be fixed with #5218

Apart from that and sorry for being a smart-ass, "Vormittag" and "Nachmittag" is the correct translation for AM (Ante meridiem) and PM (Post meridiem), it's just used completely differently as we usually have a 24h system.

**Comment by dancing-jules** [comment]
@Laura-O Yeah, they are correct translations. They just fall apart in practical usage, especially around 00:00-00:59.

IME no German speaker would ever say "3:28 nachmittags" - they'd say "kurz vor halb 4 nachmittags" or "15:28".

**Comment by Laura-O** [comment]
The time format for the German translation was now changed to 24h:

![Screen Shot 2020-02-25 at 09 39 56](https://user-images.githubusercontent.com/362249/75229720-cb9bc500-57b2-11ea-8042-9f48e10c530b.png)

The PM and AM translations are removed with this format, so the issue should be resolved now.

**Comment by viroulep** [comment]
Thanks!
