### ISSUE TITLE
Remove flags from language dropdown in header

### ISSUE THREAD

**Issue by Goosly** [thewca/worldcubeassociation.org#5245]
Flags represent a country, not a language. Showing a flag for a language is incorrect. In some cases these match, in some cases these don't. The most obvious example is showing the UK flag for English.

![image](https://user-images.githubusercontent.com/12575384/76060993-d90b3900-5f82-11ea-9b46-32e0d2ccb64d.png)

Other websites handle this correctly and don't display flags for languages, for example

LinkedIn:

![image](https://user-images.githubusercontent.com/12575384/76060659-0dcac080-5f82-11ea-9f40-080ffbfab3d2.png)

Google translate:

![image](https://user-images.githubusercontent.com/12575384/76060687-1f13cd00-5f82-11ea-8d49-72d074ea39da.png)

Facebook:

![image](https://user-images.githubusercontent.com/12575384/76060763-52eef280-5f82-11ea-851a-981e4067d6b9.png)

**Comment by jonatanklosko** [comment]
I guess that's debatable, but removing the flags sounds ok to me (if we had `en-gb`, `en-us`, etc. I'd have more doubts, but currently is indeed kinda weird). @viroulep do you have any opinion on that?

**Comment by Goosly** [comment]
It's not debatable :-)

Here's an interesting article:
http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

**Comment by jonatanklosko** [comment]
Good reference, thanks!
