### ISSUE TITLE
Edit Users - WCA ID Assignment - WRT permissions

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5254]
Being able to assign a WCA ID to a user account is a permission given to Delegates, but not WRT members. WRT members should have access to assign the WCA ID via the website on the edit user page (we can already do so via PhpMyAdmin anyways).

**Comment by pedrosino** [comment]
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L843

This should be easy
