### ISSUE TITLE
Results Validator - Incorrect Parenthesis

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5255]
We sometimes get incorrect parenthesis in persons name. Example: "（原田大和）". These are manually catched and then sometime found later in sanity checks. But an additional validator similar to WHITESPACE_IN_NAME_ERROR or WRONG_PARENTHESIS_FORMAT_ERROR would be beneficial!

**Comment by Mollerz** [comment]
Just had this issue when I was reviewing newcomers for a recent competition in the UK. I have even noticed this on some _existing_ competitors. So I think this is great to add!
