### ISSUE TITLE
Show Cancellation Status on Competitions Page

### ISSUE THREAD

**Issue by TheRealDaSaV** [thewca/worldcubeassociation.org#5275]
Since we are still showing cancelled competitions on the competitions page. We should at least show that they are cancelled in some way. Yes, there is a clarification on the actual individual competition page, but not on the competitions page with the list of all competitions.

Not all competitions are cancelled currently. For instance, Brooklyn Spring 2020 is not on the cancelled list nor has an update on its page.

So, temporarily adding an extra column 'Status' showing either Cancelled or Upcoming would be helpful.

**Comment by TheRealDaSaV** [comment]
It turns out that all competitions are getting cancelled. So, just maybe include a header on top of the page saying that all competitions in this period are getting cancelled.

**Comment by viroulep** [comment]
I'm gonna mark this as a duplicate of #5145, since this would be covered in there as well.
