### ISSUE TITLE
Artifacts left over when competitions are deleted

### ISSUE THREAD

**Issue by maconard** [thewca/worldcubeassociation.org#5296]
**Describe the bug**
When competitions are deleted if the registrations/bookmarks weren't deleted first then they remain as red/grayed out lines in the user's My Competitions page, despite the competition no longer existing. If this is intentional, then feel free to close this issue. I imagine it hasn't been run into before because before this season cancellations were far and few between.

**To Reproduce**
1. Be registered for a competition
2. Have WCAT unannounce that competition
3. Go to your My Competitions page

**Expected behavior**
I'd expect artifacts like registrations and bookmarks to be cleaned up for competitions that have been unannounced.

**Screenshots**
Alex Maass presented this example for the Empire State competition, which has been removed from the WCA site: ![example](https://user-images.githubusercontent.com/31703304/77585198-7a1e4d00-6eba-11ea-9184-18b8ba8f3039.jpg)

edit 1: corrected reproduction steps and expected results from "deleting" competitions to "unannouncing" them

**Comment by DanielEgdal** [comment]
To reproduce should actually be:

1. Be registered for a competition
2. Make WCAT hide the competition from the public (Not delete)
3. Have the Delegate/organizer as accepted.

In the cases of the Delegate/organizer deleting your registration, then it will disappear from your list.

A clause to this (in python sudo-code, so likely useless) which would fix it could be the following:
```py
if competition_is_visible == True or (user == Delegate or user == organizer):
 show_competition_in_list = True
else:
 false
```

Someone with ruby knowledge, and knowing the website could probably fix this quite easily.

**Comment by sarahstrong314** [comment]
Here's an example of a bookmarked competition showing up where it shouldn't.

I can't unbookmark the competition since the competition page is private.

![Screenshot 2020-03-26 08 57 18](https://user-images.githubusercontent.com/5139750/77649203-d0819f00-6f3f-11ea-8eb5-62f29894915b.png)

**Comment by viroulep** [comment]
All this is pretty much what #5145 is about (the bookmark issue is mentioned there as well).

**Comment by maconard** [comment]
Yeah, Sarah and Kit pointed out on Facebook that it has to do with un-announcing a competition, not deleting it. So I imagine registrations/bookmarks are properly cleaned up on deletion, just not on un-announcement.
