### ISSUE TITLE
Parentheses after "Events" appeared

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#5317]
**Describe the bug**
A pair of wild parenthesese after "Event" when you go to edit a competitor as a Delegate / organizer.

**Expected behavior**
No wild parentheses :-)

**Screenshots**
![Events ()](https://user-images.githubusercontent.com/45567122/78142645-7431ea00-742d-11ea-98a4-e556113ddeef.png)

**Comment by viroulep** [comment]
Expected behavior is to show the amount of selected events within the parenthesis: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/shared/_associated_events_picker.html.erb#L26
