### ISSUE TITLE
Delegates stats don't filter out invisible competitions

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5334]
To display the number of competitions by Delegate [we use](https://github.com/thewca/worldcubeassociation.org/blob/d88240820815288ac89004b8900cc47e1988b7ba/WcaOnRails/app/views/delegates/stats.html.erb#L21) the `User.delegate_competitions`, but this returns all competitions for which the user is a Delegate, regardles of the competition's status.
While this is nice in some context, we should select only visible competitions when reporting the stats of Delegated competitions.

**Comment by viroulep** [comment]
Reported by @DanielEgdal.

**Comment by danieljames-dj** [comment]
Just tried changing the following line that you mentioned:
`<% competitions = delegate.delegated_competitions.order_by_date.select(&:is_probably_over?) %>`
to:
`<% competitions = delegate.delegated_competitions.order_by_date.select(&:confirmed_or_visible?).select(&:is_probably_over?) %>`
But looks like the value is not changing at all 😬Any problem in my fix?

**Comment by viroulep** [comment]
Invisible competitions are not exported in the developer dump, so if you have not manually "unannounced" a competition by making it invisible and editable again by organizers, it's expected that the number stay the same.

It's a detail, but by doing two selects you iterate twice over each set of competitions for every Delegate.
You can save one loop by doing `select { |c| c.confirmed_or_visible? && c.is_probably_over? }`.

**Comment by danieljames-dj** [comment]
Actually I had already made it 'unannounced' manually. But I thought that just making it invisible will make it unannounced. But yeah as you said, when I made it editable as well, it worked well and is showing the result as expected. :-) Can I send the PR for this?

**Comment by viroulep** [comment]
Yes please!

**Comment by danieljames-dj** [comment]
Done, looks like you merged already -https://github.com/thewca/worldcubeassociation.org/pull/5339.

**Comment by viroulep** [comment]
Indeed.
You can actually use "Fixes #5334" in the PR message to link it to the issue, and it would automatically close the issue when merged into master.
