### ISSUE TITLE
Remove Additional Delegate Information from Profiles

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#5354]
The profiles of WCA Delegates have additional fields of location, phone number, and notes. These fields were added in [#1007](https://github.com/thewca/worldcubeassociation.org/issues/1007).

The Board does not think this information is necessary any more. Perhaps this information was useful years ago, but we believe this is no longer the case.

We would like to see this section of WCA profiles deleted.

**Comment by danieljames-dj** [comment]
I would like to take this issue up as it is a good second issue.
