### ISSUE TITLE
Javascript error in "manage schedule" switching between stages

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#5356]
**Describe the bug**
When switching between stages, a javascript error is triggered and the "manage schedule" page goes blank.

**To Reproduce**
1. Go to https://staging.worldcubeassociation.org/competitions/NortheastChampionship2020/schedule/edit (sign in as 2005REYN01 or someone else with edit access) (this happens in prod as well)
2. Select "Terrance Lounge"
3. Select "Main Stage"

**Expected behavior**
Schedule for main stage loads

**Screenshots**
![error](https://user-images.githubusercontent.com/3885929/79626602-4cb27100-80ff-11ea-89a3-4789a6dab667.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Additional context**
Reproduces on other competitions with multiple stages.  I believe it always happens after selecting one stage then selecting another.  Screenshot and reproduction instructions are from staging; this was first noticed on the prod site, I'm using staging for easier reproduction and testing across multiple competitions.

**Comment by viroulep** [comment]
Thanks for the detailed report @timreyn!
See #5357 for the fix, I'll land it asap.
