### ISSUE TITLE
Trainee Delegate is listed as Junior Delegate on profile

### ISSUE THREAD

**Issue by bmetherall** [thewca/worldcubeassociation.org#5376]
**Describe the bug**
Vladislavs Baranovs (2012BARA03) is listed as a trainee delegate on the delegates page, but, as a junior delegate on his profile

**To Reproduce**
[WCA Delegates](https://www.worldcubeassociation.org/delegates)
[WCA Profile](https://www.worldcubeassociation.org/persons/2012BARA03)

**Additional context**
I assume the issue is with the recent PR https://github.com/thewca/worldcubeassociation.org/pull/5249

**Comment by viroulep** [comment]
Fixed by #5375
