### ISSUE TITLE
Trainee delegates are listed on the Delegates page

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5378]
According to @cubewhiz in #5118, Trainee Delegates are not (yet) WCA Staff and therefore should not be listed on the Delegate page.
It's probably just a matter of adding a `.reject(&:trainee_delegate?)` [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/static_pages/delegates.html.erb#L11).

I noticed this because the the "Trainee Delegate" badge has a link to the Delegates page, so ideally this badge should also be amended to not link there ^^

@danieljames-dj would you mind taking care of this please?

**Comment by danieljames-dj** [comment]
Sure, I would be happy to. I've sent a PR. I hope this will fix the issues.

**Comment by maconard** [comment]
Ah, makes sense. I was curious why some Trainees were listed but others weren't.

**Comment by viroulep** [comment]
Because *Seniors* change delegate statuses, not the WST (but it's not related to this specific issue actually).

The changes were merged yesterday, which is also when the email to Senior/WCAT was sent, so just be patient until the appropriate person actually change your status.

**Comment by maconard** [comment]
Hadn't come on github for a bit, I didn't catch that this is all fresh from yesterday :) Great job to everyone who worked on getting it completed!
