### ISSUE TITLE
New Feature - Create a History Page

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5397]
This page would detail WCA's history (a lot like a wikipedia page). We have a lot about what we are now, but not a lot of emphasis on how many people we've reached, the countries involved, our past staff (teams and delegates), when we became a nonprofit, our founders, how the structure has changed over time.

It's just a rough idea, but maybe somebody would want to fill this in with more ideas!

**Comment by Jambrose777** [comment]
Related: https://github.com/thewca/worldcubeassociation.org/issues/2955

**Comment by saranshgrover** [comment]
We now have https://www.worldcubeassociation.org/speedcubing-history - closing
