### ISSUE TITLE
still emails registration reminder despite competition being cancelled

### ISSUE THREAD

**Issue by alexmaasswca** [thewca/worldcubeassociation.org#5398]
**Describe the bug**
I got an email reminding me or https://www.worldcubeassociation.org/competitions/WestchesterOpen2020 despite the competion

**To Reproduce**
Be someone who was registered and signed up for email notifications/reminders for this competition

**Expected behavior**
I expected to not be sent an email for a competition that was cancelled/deleted

**Additional context**
I was told to report this here, I wasn't going to initially though because it seemed pretty minor/needless.

**Comment by viroulep** [comment]
Thanks for the report, it's indeed nice to create issues there when someone notices something wrong!

This is basically due to #5145, and should be resolved when it's done, so I'll consider this one as a duplicate and close it.
