### ISSUE TITLE
Trainee Delegates shouldn't be able to create competitions

### ISSUE THREAD

**Issue by maconard** [thewca/worldcubeassociation.org#5416]
**Describe the bug**
As a Trainee delegate, I should not have access to the "+ New Competition" delegate button. Additionally, when clicking it I am auto listed in the Delegate field instead of the Trainee Delegate field.

**To Reproduce**
1. Sign in to WCA with Trainee Delegate permissions
2. Drop down the "Competitions" sub-menu
3. Click the "+ New Competition" button
4. Observe

**Expected behavior**
I don't believe Trainee Delegates are meant to have competition creation privileges, so this button should not appear at all. If they should, then they should be auto filled in as the Trainee and not as the full Delegate, and the submission shouldn't be allowed without that filled in. 

**Screenshots**
![Screenshot_20200505-085742~2](https://user-images.githubusercontent.com/31703304/81098347-41b95800-8ed7-11ea-9434-4963e5af1beb.png)
![Screenshot_20200505-085835~2](https://user-images.githubusercontent.com/31703304/81098361-45e57580-8ed7-11ea-8a86-efe2ab234886.png)

Cheers!

**Comment by EdHollingdale** [comment]
On the contrary, I think trainee delegates _should_ be able to create competitions - setting up a competition on the website is something they need to learn. So long as the trainee delegate isn't able to confirm those competitions to WCAT then it is working as intended.

Even in the edge case of trainee delegates who are also on WCAT it seems to be working (on staging at least) - they can create competitions and announce them, but not confirm them to WCAT.

**Comment by danieljames-dj** [comment]
Thanks a lot @maconard for pointing out the issue. While creating a competition, definitely they should be listed as trainee delegate, not delegate. It was a miss from my part while implementing this. I've sent a PR to fix this [here](https://github.com/thewca/worldcubeassociation.org/pull/5421).

Also, as @EdHollingdale said, I too think trainee delegates can create competitions.
