### ISSUE TITLE
Port the posts to Fomantic UI

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5454]
Already being addressed in #5340, but this is an issue to have reference in the "website components rewriting".

The goal of this port is to provide a very simple example of a react component using our Fomantic UI bindings, as well as how to load data from the website's API.

The associated wiki page is [here](https://github.com/thewca/worldcubeassociation.org/wiki/Writing-a-new-React-component).

**Comment by jonatanklosko** [comment]
The corresponding PR has already been merged =)
