### ISSUE TITLE
Missing translation for Multi Blind old style's time limit

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5459]
Reported by @SAuroux, see [here](https://www.worldcubeassociation.org/competitions/CzechOpen2008#competition-events).
The table has a "translation missing: en.time_limit.333mbo".

IIRC there was simply no time limit and arrangements had to be made between the competitors and organizers.
@SAuroux do you have a good suggestion of what text to put here?

**Comment by SAuroux** [comment]
> @SAuroux do you have a good suggestion of what text to put here?

Not really, unfortunately. Maybe empty string would be the best and most simple solution after all.

**Comment by denthebro** [comment]
Addressed this issue in commit https://github.com/thewca/worldcubeassociation.org/pull/6304
