### ISSUE TITLE
Add Links for External Registration

### ISSUE THREAD

**Issue by saranshgrover** [thewca/worldcubeassociation.org#5462]
For competitions that do not use WCA Registration, it would be nice to ask for a URL for where they perform registrations. Would be ideal for the "Register" page on the WCA website to link to that URL in these cases.

Adding a field during the new competition process and a table on the database for registration_url would work well I think. This is similar to #4642

**Comment by Jambrose777** [comment]
This already exist (just uncheck the box "I would like to use the WCA website for registration" and you will be prompted to enter a link to the registration page. This is also displayed in the register here link on the competition page.

**Comment by viroulep** [comment]
Closing for the reason mentioned by Jacob, feel free to re-open if you think something is missing.
