### ISSUE TITLE
Password is shown to user upon sign-up failure

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5478]
**Describe the bug**
Whenever signing up, if the user has something invalid, they wil be taken to a screen showing their errors. The password will be blank and above the field will be the password typed in.

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/users/sign_up without a logged in session.
2. Fill in a bad email address (ie 'wca')
3. Fill in password (ie 'password')
4. Click I have compete in a WCA competition.
5. Enter random WCAID (even if linked)
6. click sign up.

**Expected behavior**
The previous password should not be shown back to the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/11577241/83359967-de8eda00-a34b-11ea-8d54-3b29d6a19a7d.png)

**Desktop (please complete the following information):**
 - OS: OSX El Capitan
 - Browser Chrome

**Additional context**
I'm not sure if this happens with only a bad WCAID (it happens with only a bad email). I'm not sure if it happens on the never competed flow.

**Comment by viroulep** [comment]
Wow, can't believe this was not noticed until now :(
It's definitely a big issue if the person registering is not alone behind their screen...
