### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#5479]
**Is your feature request related to a problem? Please describe.**
I'm try to make some tools to use via WCA API but I have no enough documentation. 

**Describe the solution you'd like**
Page somewhere [here](https://www.worldcubeassociation.org/api/v0/) that described all possible API requests.

**Comment by saranshgrover** [comment]
Have you looked over the [wiki documentation](https://github.com/thewca/worldcubeassociation.org/wiki#are-you-a-developer-looking-to-integrate-with-the-wca-website). It's by no means complete but does have some documentation on how to use it. The [wcif specification](https://github.com/thewca/wicf) is also available.

**Comment by AlexKatyukov** [comment]
Okay, thank you a lot, @saranshgrover, it's helped me!
But maybe it's a good idea to put this link to API page at WCA website? I spent a few hours to find it and did it only with Saransh comment.
