### ISSUE TITLE
Results do not load whenever hitting back

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5493]
**Describe the bug**
When viewing a Competition's results page, going to a different page and then hitting back results in a blank results page.

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/competitions/GACubersFeetFest2019/results/all?event=clock
2. Click WCA at the top left to go to the home page (or redirect the browser, or any other link)
3. Click back in the browser

**Expected behavior**
Results for a competition should be populated.

**Screenshots**
![image](https://user-images.githubusercontent.com/11577241/83545735-9d263800-a4cd-11ea-9634-3e74b43303a2.png)

**Desktop (please complete the following information):**
 - OS: OS x El Capitan v 10.11.6
 - Browser: Chrome 83.0.4103.61

**Comment by viroulep** [comment]
I'm not sure about what's going wrong here, but it would surely go away if #5455 was implemented!

**Comment by UnsolvedCypher** [comment]
#5455 has been implemented. @Jambrose777 could you confirm that the bug is gone with the latest code?

**Comment by Jambrose777** [comment]
Looks good and resolved!
