### ISSUE TITLE
Validations on Persons names

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#550]
From @SAuroux:

> Our general policy is, that we allow non-Roman characters in non-local names as long as they are "roman-readable". This affects lots of Polish competitors for example. However, once a person uses a local name, I feel like we should not allow non-roman characters in the non-local name. 
> 
> @team: Does that make sense for you? Could we easily) implement a check to prevent that? Basically we would need (excude my crappy pseudo code):
> 
> IF '(' in name THEN name[0 : find( '(' , name)-1] must be roman

This is easy enough to do, but should wait until we've ported the admin scripts to Rails.

**Comment by SAuroux** [comment]
@jonatanklosko Just found this and I'd say this can be closed for two reasons:
1. As @jfly had already pointed out back then, it is not straight forward to get or even define a list of "roman readable" letters.
2. We have competitor names sufficiently covered in our sanity checks these days.
