### ISSUE TITLE
Add sub-teams

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#5523]
The WCT would like the ability to display sub-teams on the Teams, Committees, and Councils page. As some of our work has become more segmented we think it would be useful to highlight the members of our team focusing on graphics, for example. 

This would be a purely aesthetic change that would not affect authorization. Perhaps this could be implemented as an additional optional field on `team_member`?

**Comment by denthebro** [comment]
This seems like something that would overcomplicate things for people who are not part of WCA staff. Is this not something that should just remain within the team? I don't see how it would affect non-WCT-members.

**Comment by saranshgrover** [comment]
This has been discussed internally with WCT/Board - going to close the issue in favor of that conversation. If WCT thinks this is still relevant, please reopen.
