### ISSUE TITLE
New API endpoint: competitions where user is registered but registrations now pending

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#5539]
**Is your feature request related to a problem? Please describe.**
I now develop some tools for work with WCA API. One of these tools is a special page where competitor can fill up some form setted by organizers. It should work somewhat like: authentification —> getting all competitions for that user —> if user registered for competition, he can fill up the form.
We can get [future competitions for user](https://www.worldcubeassociation.org/competitions/mine), we can get [future managed competitions for user](https://www.worldcubeassociation.org/api/v0/competitions?managed_by_me=true) and we can get [future competition approved registrations](https://www.worldcubeassociation.org/api/v0/users/1492?upcoming_competitions=true) for user.

**Describe the solution you'd like**
New API method like `https://www.worldcubeassociation.org/api/v0/me?upcoming_competitions=true` (or any other URI, it doesn’t matter) when we can see all upcoming competitions, including pending and deleted registrations with appropriate statuses. 

**Describe alternatives you've considered**
One alternative is to get WCIF using manager account but it's not always okay and this solution can't be universal.

**Additional context**
*I'm tried to make pull request but it's hard for me now*

**Comment by saranshgrover** [comment]
This would be resolved by #6261
