### ISSUE TITLE
Update or capybara javascript driver to something more recent

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5554]
We currently use poltergeist as our javascript driver for tests in capybara.
We should definitely switch to something more recent with a better js support, but I'm unsure of all the changes that may be needed to make the switch.

The most straightforward way to do this would be to follow advice from [there](https://github.com/teamcapybara/capybara#drivers), then update [this file](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/spec/rails_helper.rb) to use the driver (and making sure it is available either through gems or in the CI environment), and then see what goes wrong and fix it.

**Comment by gregorbg** [comment]
Closed as per https://github.com/thewca/worldcubeassociation.org/pull/6253
