### ISSUE TITLE
Result validations for advancement conditions

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#5587]
We (WCA Results Team) were fixing the inconsistencies in the existing advancement conditions. To avoid many inconsistencies in future, it would be better if there is result validation for advancement conditions while submitting results.

According to the discussion within WRT, the following cases can be marked as error:
- actual advanced number > planned advanced number
- actual advanced number or planned advanced number > 75%
- cases where advancement_condition's type is `attemptResult` and it is wrongly applied

Also, it can be marked as a warning if both the following condition are true:
- (actual advanced number / planned advanced number) <= 0.8
- planned advanced number - actual advanced number >= 3

EDIT: Added the third case for error.

**Comment by viroulep** [comment]
To anyone going to work on this, we already have a validator for this kind of checks [here](https://github.com/thewca/worldcubeassociation.org/blob/c304c42066cde9f6063e4f4f6c641bd068f4342e/WcaOnRails/lib/results_validators/advancement_conditions_validator.rb).

> actual advanced number or planned advanced number > 75%

Hum for the actual number of competitors, we actually already have a validation for this [here](https://github.com/thewca/worldcubeassociation.org/blob/c304c42066cde9f6063e4f4f6c641bd068f4342e/WcaOnRails/lib/results_validators/advancement_conditions_validator.rb#L92)!
Did you have case where the validation didn't do what was expected?

**Comment by SAuroux** [comment]
@viroulep No, indeed *actual advanced number > 75%* is already covered and we did not have any such violations. *planned advanced number > 75%* is very relevant though, we found about 800 such cases.

**Comment by Jambrose777** [comment]
@Baiqiang  Are you still planning to work on this?

**Comment by saranshgrover** [comment]
Removing @Baiqiang's assignment since he never responded.

**Comment by danieljames-dj** [comment]
I can give a try on this. But I'm not so confident with how I'll be able to test this. I'll just explore it a little bit and give a confirmation whether I'll be able to do this.

**Comment by viroulep** [comment]
I just submitted #7376 but it's still missing some work.

Regarding this:
> cases where advancement_condition's type is attemptResult and it is wrongly applied

"wrongly applied" could be interpreted both ways: either some people who would have qualified are not there, or some people who shouldn't have qualified are there.
IMO we should only emit an error when people qualified whereas they didn't actually meet the attempt result.
The main issue with emitting an error when qualified people are missing is that there are valid reason that someone drops out of a round, and we certainly don't want to prevent results submission for theses cases.
Does that make sense for you?

**Comment by SAuroux** [comment]
> Does that make sense for you?

Yes! In fact, I would not call the other case "wrongly applied" at all, just like it is not a wrong application of a top N criterium if someone from the top N does not participate in the subsequent round.
