### ISSUE TITLE
Result validation for scrambles per round not working

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#5623]
I just noticed that the the two result validation errors that should be forcing delegates to correct the number of scramble sets used at their competitions are actually not working. The most recent result submission for [Hvidovre Sommerhygge 2020](https://www.worldcubeassociation.org/competitions/HvidovreSommerhygge2020) include several mismatches, but no error is thrown.

The relevant code: https://github.com/thewca/worldcubeassociation.org/blob/7297c4e19b40b9df955cbdabf513f2e22ac08368/WcaOnRails/lib/results_validators/scrambles_validator.rb#L50-L63

**Comment by viroulep** [comment]
Unfortunately I did not understood it this way when implementing the check in the first place :s
I assumed we just needed to check that there was at least one scramble set for each round (which is what the check does).

In theory it should not be too hard: the scrambles are already grouped by round id so we would need to get all round information for the competition and check the value for the number of scrambles sets!

To be honest I'm not surprise at all that there are many violations of this: I never realized the number of scrambles sets in the "edit events" had to be accurate, and actually I used to often set it to "N+1" to have a backup sheet (and I'm pretty sure other Delegates do the same); I don't think I always fixed these numbers once the scrambles were generated :s
