### ISSUE TITLE
Spanish translation detail

### ISSUE THREAD

**Issue by Nanush7** [thewca/worldcubeassociation.org#5624]
**Describe the bug**

I'm going to describe the issue in Spanish because it's not something I can do in English. Maybe @Ivan-Brigidano as a Spanish speaker can handle this.

En las competencias ya terminadas, en la sección de "Destacados" o "Highlights" dice, por ejemplo, lo siguiente:

> **A** ganó con una media de 9.54 segundos en la categoría de Cubo 3x3x3. **B** acabó segundo (9.84) y **C** acabó tercero (9.85).

El tema es que aunque B o C no sean personas del género masculino igualmente dice "segundo" o "tercero". En la captura de pantalla hay un ejemplo.

Creo que se podría cambiar "acabó segundo" por "acabó en segundo puesto", de esta forma no habría que agregar más código para que cambie el texto según el género, ya que de esta forma no se diferencia entre uno u otro.

**To Reproduce**
1. Go to a finished competition page.
2. Set language to Spanish.
3. See the "Highlights" section.

**Screenshots**
![Screenshot_2020-08-02 Montevideo Bisiesto 2020 World Cube Association](https://user-images.githubusercontent.com/59543882/89133667-266ce180-d4f4-11ea-91df-7f44e294833d.png)

**Comment by Jambrose777** [comment]
Ccing: @moralsh

**Comment by moralsh** [comment]
Thanks both @Nanush7 for the catch and @Jambrose777 for the ping, I just submitted PR #5625 with the fix.

**Comment by jonatanklosko** [comment]
I assume the PR fixed the problem and gonna close this, thanks Raúl!
