### ISSUE TITLE
Time limit validation generates warning for 3x3x3 Multi Blind rounds

### ISSUE THREAD

**Issue by poiuytre121** [thewca/worldcubeassociation.org#5642]
**Describe the bug**
During result submission for BrizZon Poznań Side Open 2020 I got following warning:
> [333mbf-f] The time limit for this round is undefined, time limit validations have been skipped. This is expected only for competitions before 2013.

**To Reproduce**
1. Go to the result submission page for competition with 3x3x3 Multi Blind
2. Upload results json file from scrambles matcher
3. Click Submit
4. In warnings section there is warning as described above

**Expected behavior**

**Screenshots**
<img width="1023" alt="Zrzut ekranu 2020-08-11 o 08 59 51" src="https://user-images.githubusercontent.com/20459662/89870978-f63dd680-dbb6-11ea-9a8e-5ea261cf35e9.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Browser Google Chrome 
 - Version 84.0.4147.105

**Additional context**
I contacted @jonatanklosko for this problem on messenger and we are thinking that [that if](https://github.com/thewca/worldcubeassociation.org/pull/5463/files#diff-a59f1336c36da875ef2cd06762ff812cR74) should check if round's event is 3x3x3 Multi Blind or 3x3x3 Fewest Moves which have time limits defined by regulations.

**Comment by SAuroux** [comment]
This is related to https://github.com/thewca/worldcubeassociation.org/pull/5463/

**Comment by viroulep** [comment]
Additionally, the time limits for both events doesn't show up correctly anymore on the events page.
I definitely missed the - expected - null value for these events that don't have a manually editable time limit!
