### ISSUE TITLE
Ambiguous text relating to advancement conditions 

### ISSUE THREAD

**Issue by Epride** [thewca/worldcubeassociation.org#5661]
**Describe the bug**
When selecting result as an advancement condition it displays the following text "Best result < XX.XX advances to next round". This creates ambiguity that a best single below the time is enough to satisfy the advancement conditions even though it is not the intention of the organization team. The current use of the term "best result" describes a situation where you could have more than one result in a round and therefore would imply in this case result means single.

**To Reproduce**
1. Create a competition with at least two rounds of the event
2. Set the advancement conditions to result 
3. Observe the text in the events tab

**Expected behavior**
There are a couple of options on how to fix it here. The easiest would be to change the text to "Result < XX.XX advances to next round" which is more clear that you may only have one result per round making "result" an average, however even this I feel is still ambiguous.

Another option would be to have the text display the following "[Insert round format] < XX.XX advances to next round" where the round format is the format selected for round in which the advancement condition applies ("Average of 5", "Mean of 3", "Best Single") which would more concisely represent what is required to proceed to the next round.

The final option could be to allow the organization team to chose which of the formats they would like to use as the advancement condition however I am not sure that this approach is supported by the regulations (or very practical) so the WRC would need to be consulted if this were the change that was going to be made.

**Comment by denthebro** [comment]
I think this is a good wording change. This should probably be fixed according to your second option:

Another option would be to have the text display the following "[Insert round format] < XX.XX advances to next round" where the round format is the format selected for round in which the advancement condition applies ("Average of 5", "Mean of 3", "Best Single") which would more concisely represent what is required to proceed to the next round.

**Comment by Jambrose777** [comment]
Dup of https://github.com/thewca/worldcubeassociation.org/issues/5176 and https://github.com/thewca/worldcubeassociation.org/issues/3597 if Im not mistaken

**Comment by jonatanklosko** [comment]
The problem is nicely elaborated here, so I closed #5176 and #3597. Whoever works on that, have a look at those issues as well for more details.
