### ISSUE TITLE
Handling Multi-Blind cube submission on the website

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#5670]
Many Delegates and Organisers include Multi-Blind Cube submission as a distinct item in the schedule to be clear to competitors and allow time to scramble, and this appears something that WCAT are also requiring now. 

I think there are two steps to implementing this on the website. The first should be pretty easy - when you go to add an extra item in the schedule have "Cube submission for Multi-Blind" or similar as one of the options (like Lunch, or Registration). I assume this means it can then more easily be translated for everyone.

The second step (and what I assume is harder) would be to incorporate it as an event of sorts in the WCIF. I know for WC2019 the amazing @viroulep created an extra event that all multi-blind competitors and relevant staff were assigned to so that they wouldn't be scheduled to compete in another group, or be judging for it. It'd be nice if this was also the case for local competitions, so Groupifier would know not to allocate multi-blind competitors to the first two groups of 4x4 (for example).

**Comment by viroulep** [comment]
Actually I didn't use an extra event, I used an activity tied to the `333mbf` event!
For the record here is how the WCIF looked like for these activities:
<details>

```
{
  "id": 4,
    "name": "3x3x3 Multi-Blind, Round 1, Attempt 1",
    "activityCode": "333mbf-r1-a1",
    "startTime": "2019-07-11T01:30:00Z",
    "endTime": "2019-07-11T02:45:00Z",
    "childActivities": [
    ]
},
{
  "id": 5,
  "name": "3x3x3 Multi-Blind, Round 1, Attempt 2",
  "activityCode": "333mbf-r1-a2",
  "startTime": "2019-07-12T00:30:00Z",
  "endTime": "2019-07-12T01:45:00Z",
  "childActivities": [

  ]
},
{
  "id": 291,
  "name": "Scramble/Check attempt #2",
  "activityCode": "333mbf-r1",
  "startTime": "2019-07-11T23:00:00Z",
  "endTime": "2019-07-11T23:35:00Z",
  "childActivities": [

  ]
},
{
  "id": 287,
  "name": "Puzzle submission attempt #1",
  "activityCode": "333mbf-r1",
  "startTime": "2019-07-10T23:30:00Z",
  "endTime": "2019-07-11T00:30:00Z",
  "childActivities": [

  ]
},
{
  "id": 289,
  "name": "Scramble/Check attempt #2",
  "activityCode": "333mbf-r1",
  "startTime": "2019-07-11T23:35:00Z",
  "endTime": "2019-07-12T00:30:00Z",
  "childActivities": [

  ]
},
{
  "id": 288,
  "name": "Puzzle submission attempt #2",
  "activityCode": "333mbf-r1",
  "startTime": "2019-07-11T22:45:00Z",
  "endTime": "2019-07-11T23:00:00Z",
  "childActivities": [

  ]
},
{
  "id": 290,
  "name": "Scramble/check attempt #1",
  "activityCode": "333mbf-r1",
  "startTime": "2019-07-11T00:30:00Z",
  "endTime": "2019-07-11T01:30:00Z",
  "childActivities": [

  ]
},
```
</details>

Not sure how to best approach this, but the simplest/quickest way is probably to add an extra predefined "multiblind submission" entry when creating a custom activity (that could therefore be translated automatically). The activity wouldn't be tied to a specific event/round/attempt though.

Implementing the ability to add arbitrary activities to a round would require quite a big amount of work.

**Comment by saranshgrover** [comment]
I think given the work it takes to implement arbitrary activities, this issue can be limited to adding another automatic field for MBLD submission
