### ISSUE TITLE
Use Docker

### ISSUE THREAD

**Issue by UnsolvedCypher** [thewca/worldcubeassociation.org#5685]
Given the recent call for contributors, it might be a good idea to start using Docker to more easily spin up a development environment. I think in some cases getting all of the required programs installed to their correct version and set up can be a pain and discourage new contributors. I have worked with Docker before and would be happy to help with this if there is interest.

Long-term it might make it easier to deploy, although I have no knowledge of how the WST actually does deploys.

**Comment by saranshgrover** [comment]
100% support this, development on windows is basically impossible right now. There is #4944 by @lgarron though I'm not sure how up to date it is.

**Comment by viroulep** [comment]
Most of the PR should be up to date, I there are a couple of details to fix but not linked to the general docker idea.
The mysql version is out of date, and the docker built just have the `app` directory (which also means no regulations/wca-documents included).
If we're letting users have a dockerfile, I think it's better if it reflects the whole server.
Which is definitely possible, as provisioning our server is done automatically through chef recipes!
The whole server bootstrap is [here](https://github.com/thewca/worldcubeassociation.org/blob/master/scripts/wca-bootstrap.sh).
It creates everything from a fresh linux image, but I don't think this is what we want here: I'd guess the use case would be cloning the repo on the host, and setting up the webserver in the docker.
Therefore I guess only the last part of the script could be ran in the dockerfile: getting chef and running the main recipe (which will install all the necessary packages).
There will probably be adjustments necessary to the volumes 

I guess this will help new contributors. The only concern I have is that it would not just be a "getting started" convenience, and that over time we would lack people with necessary knowledge to manage our servers and the internals of the website.

**Comment by moralsh** [comment]
Anyway, setting up a linux virtual Machine on virtualBox or other virtualization technology is not that hard, I don't think it's significantly harder than setting up a docker environment. It might be good to maybe add a troubleshooting section or some FAQ in the wiki on setting up rvm and mysql, as the rest is pretty much copy & paste from the readme.md

**Comment by lgarron** [comment]
@jfly and I *almost* got Docker working well at https://github.com/lgarron/worldcubeassociation.org/tree/Dockerfile , but it still involved a bit too much manual setup to be practical. Feel free to take that branch and extend it!

**Comment by UnsolvedCypher** [comment]
@lgarron Do you remember what in particular was not working? I see you have some Docker instructions [here](https://github.com/lgarron/worldcubeassociation.org/commit/dae2f228ca9acbe0f732f3db75132efe25d1dea0), does this accurately describe all of the issues you encountered?

**Comment by lgarron** [comment]
> @lgarron Do you remember what in particular was not working? I see you have some Docker instructions [here](https://github.com/lgarron/worldcubeassociation.org/commit/dae2f228ca9acbe0f732f3db75132efe25d1dea0), does this accurately describe all of the issues you encountered?

It was all working, but as you can see from the instructions:

1. It takes a bunch of steps to get started (which take quite some time and aren't automated)
2. It doesn't automatically work across invocations. That is, these commands have to be run manually in multiple shells each time you want to resume work.

This could probably be solved with a simple daemon/umbrella development command, but we didn't get that working.
