### ISSUE TITLE
Competitions Map Bug (Firefox)

### ISSUE THREAD

**Issue by Nanush7** [thewca/worldcubeassociation.org#5723]
**Describe the bug**
When using the map option on the list of competitions to see past, present or future competitions, it's not possible to drag with the cursor to move around the map unless you do it pressing on a pin. It works perfectly on Safari (iOS) and Vivaldi (Ubuntu), I think the problem is on Firefox as I tried on Ubuntu and Windows having the same problem on both cases.

**To Reproduce (using Firefox)**
1. Go to 'Competitions' > 'All'
2. Click on the 'Map' button.
3. Try to move around pressing on a random part of the map. (Here is the problem)
4. Try to move around pressing on a pin and dragging.

**Expected behavior**
You should be able to move around pressing on any part of the map, as you can do on any other browser or device.

**Desktop:**
 - OS: Ubuntu 20.04.1 LTS and Windows 10.
 - Browser: Mozilla Firefox
 - Version: 80.0.1

**Other:**
I have tried on the example [here](https://leafletjs.com/) and it works fine.

**Comment by Nanush7** [comment]
I forgot to say that I have tried on the example [here](https://leafletjs.com/) and it works fine.

**Comment by jonatanklosko** [comment]
I can confirm this buggy behavior on Firefox (Ubuntu). Interestingly if you press on the map and then move cursor outside the map it actually starts to move.

**Comment by Nanush7** [comment]
That's right, it also happens if you press on the map and then move the cursor to a pin.

**Comment by louismeunier** [comment]
This is a weird bug with dragging in general on Firefox, outlined (here)[https://bugzilla.mozilla.org/show_bug.cgi?id=339293]. Simply fixed by adding `user-select: none` to the map.
