### ISSUE TITLE
Mistake in "registration opens soon" email

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#5729]
**Describe the bug**
_Slightly boring observation_. There is a phrase in email '<COMPETITION_NAME> registration opens soon':

> Please see the _competition website_ for more information and registration requirements

But if competition have external website, this phrase is incorrect.

**To Reproduce**
1. Bookmark the competition with external website
2. Wait for 24 hours before registration opens
3. Get email

**Expected behavior**
If competition have external website print something like 'Please see the _competition WCA page_ for more information and registration requirements'. Maybe both links to website and WCA page.

**Comment by denthebro** [comment]
Should it not just be this phrase anyways?
Please see the competition WCA page for more information and registration requirements

**Comment by gregorbg** [comment]
Closed as per #6285
