### ISSUE TITLE
Running Code without Docker causes Docker files to not be found

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5797]
So I was still using the old setup running bin/rails server directly I get this error `/Users/jacobambrose/Documents/wca/worldcubeassociation.org/WcaOnRails/config/environments/development.rb:91:in read': No such file or directory @ rb_sysopen - /proc/1/cgroup (Errno::ENOENT)` which is looking at this line of code `if File.read('/proc/1/cgroup').include?('docker')` 
I'll switch over to docker now since I'm very certain that will fix it, but we should fix this for those who choose to not use Docker (or at least provide steps in the README on how to fix this)

**Comment by jonatanklosko** [comment]
Should be fixed now!
