### ISSUE TITLE
Decide how to set locale for i18n

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#595]
For the initial version of #460 I used `default_url_options`, we had some discussions with @jfly and there is a bunch of issues with this, so the current version of the PR has no localized routes nor `defaul_url_options` anymore.
I need to restore that, but we need to figure out the way we want to do this.

Jeremy will comment a bit more on that !

**Comment by jfly** [comment]
Copy pasting my [original proposal](https://github.com/cubing/worldcubeassociation.org/pull/460#issuecomment-217570960):

> It seems to me that it's going to be impossible to avoid having links to urls without locales. For instance, our posts all have urls inside of them in markdown in the database. Have you thought about a javascript based solution to go through and tweak "naked" links according to the current locale? I imagine this would only be a few lines of javascript that could run once after the page loads (so long as we keep @jonatanklosko from adding more ajax to the website =)). This might also be a workaround for that navbar link issue I read about in your diff.

**Comment by jfly** [comment]
Also, despite the scary red box about "break[ing] people's basic assumptions about the web itself" on http://guides.rubyonrails.org/i18n.html#setting-and-passing-the-locale, I'd be open to a discussion about storing the chosen locale in the user account/session/cookie. If we choose to do it this way, we won't have to worry about dealing with our various ajaxing.

**Comment by FatBoyXPC** [comment]
From an email: 

> In regarding how to choose which locale for the future: Could we check to see if it's set in the cookie (and/or user's record in the database), and if not choose the locale based off the request headers? At the very least, we could do some IP geolocation to get a rough estimate. We could always offer the user a choice to set the locale.

It looks like this is fairly in line with @jfly's latest post.

Another fun default we could play with is look at a user's represented nationality. We could have that as their default locale until they change it to something else. I feel like storing locale in the database, session, and cookie are all **good** things.

**Comment by viroulep** [comment]
I changed my mind, I know like the idea of having the locale as a session variable.

I'd like to push this forward and start thinking about what would be needed to implement this part of i18n.
Here is some basic stuff we would need:
- a `locale` session variable (?, if we go the "session" way)
- some kind of `preferred_locale` in the `User` model
- some kind of `get_locale_for_user` that would pick a locale in case the session variable is not set. It should be pretty simple at first (like looking at the user's preferred locale, or default to `:en`), but we could make it smarter later (such as @FatBoyXPC suggestions)
- Not sure if it's in the scope of this issue, but we should also display a country selector (I think both in home page and in user's settings). A while ago I "designed" this ([there](https://github.com/viroulep/worldcubeassociation.org/tree/country-selector)):
![selector](https://cloud.githubusercontent.com/assets/1007485/20500696/d6570d28-b036-11e6-98b6-b9f805dcd3fe.png)It's ugly and won't scale, but at least it shows where I pictured it :stuck_out_tongue: . Anyone with more than my garbage css and artistic skills would be very welcome here!

**Comment by jfly** [comment]
> It's ugly and won't scale

I think it looks great, although I would add a textual description of the locale next to the flag.

I look forward to us having so many languages that we have to reevaluate the design =)

**Comment by viroulep** [comment]
@jfly, did you picture something like this:

![selector-textual](https://cloud.githubusercontent.com/assets/1007485/21144960/d5c84bde-c14c-11e6-83a7-1f67e9dc8a7a.png)

**Comment by jfly** [comment]
That looks good to me!

**Comment by viroulep** [comment]
I'll try to add the support for the locale in the profile and setting it in the session.
I've been through the "Session" section of the rails guide, the examples involves getting information about users that is, for us (and if I got it right), handled by devise.
I didn't see any code related to session manually handled by us, do you have any advice on where the logic regarding this should land?
Would the `ApplicationController` sound good to you?

**Comment by jfly** [comment]
I was confused by your use of the word "session", but then I realized that we want to handle both signed in users and unsigned in users. If you're not signed in, we have to store your language choice somewhere, so I suppose that calls for either a cookie or a session. I don't have a preference which of those we use.

I like putting this in `ApplicationController` as shown here http://guides.rubyonrails.org/i18n.html#internationalization-and-localization. As for the actual implementation of the `set_locale` method, I think it would be quite cool if we could default to the user's Accept-Language header, unless they already have a language preference set via a cookie/session.
