### ISSUE TITLE
Validation errors translation

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#596]
At the moment we don't have prepared validation errors translation which is necessary.

**Comment by viroulep** [comment]
The rails and devise default validation messages are translated in the corresponding locale files, we are missing all the WCA specific ones.

I'm on it :)

**Comment by ronaldmansveld** [comment]
@jonatanklosko @viroulep Are there more places other than the User model where this (still) has to be done, or can this ticket be closed?

**Comment by viroulep** [comment]
I did a quick search for possible candidates, I believe the only remaining ones are in the `Person` model (eg: [here](https://github.com/thewca/worldcubeassociation.org/blob/2f2a1b591a64fcef5cfb5ad7e0ee01a1e61f4e21/WcaOnRails/app/models/person.rb#L49)).

It shouldn't be much work, and for some we might actually reuse the "native" rails error messages.
I'll try to take a look soon.
