### ISSUE TITLE
Footer is off center on pages other than home page

### ISSUE THREAD

**Issue by dsoegijono** [thewca/worldcubeassociation.org#5961]
**Describe the bug**
Noticed a minor UI issue, not sure if this is intended. On the home page, the footer is centered. However, on any other page, it's left-aligned with some margin.

**To Reproduce**
1. Go to any page that's not home page (e.g. Competitions)
2. Scroll down to bottom to see footer

**Screenshots**
On home page:
<img width="1804" alt="Screen Shot 2020-12-22 at 22 02 00" src="https://user-images.githubusercontent.com/867840/102882211-291ba380-44a2-11eb-942e-e25dafb0ddf9.png">

Other page:
<img width="1804" alt="Screen Shot 2020-12-22 at 22 02 07" src="https://user-images.githubusercontent.com/867840/102882226-2f118480-44a2-11eb-991d-61506e00e24b.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser: Chrome, Safari

**Comment by denthebro** [comment]
Created  pull request: https://github.com/thewca/worldcubeassociation.org/pull/6260

**Comment by denthebro** [comment]
Someone, please close this issue, as it's been fixed and merged

**Comment by gregorbg** [comment]
Closed as per #6276
