### ISSUE TITLE
Competition Results Page - Mobile View 

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#5963]
**Describe the bug**
When looking at a competition's Results via mobile, the events selection causes a left-to-right scroll and the table is vertically aligned.

**To Reproduce**
1. On mobile, Go to https://www.worldcubeassociation.org/competitions/NewZealandNationals2020/results/all?event=333

**Expected behavior**
- The event selection should show all selections without needing to scroll.
- The table should scroll left-to-right with the columns aligned with the table headers.

**Screenshots**
Event Selection:
![image](https://user-images.githubusercontent.com/11577241/102923810-6b22f600-445e-11eb-8a23-b2e316c7008e.png)
![image](https://user-images.githubusercontent.com/11577241/102923833-724a0400-445e-11eb-8963-87c6f606fff7.png)
Results table:
![image](https://user-images.githubusercontent.com/11577241/102923850-7b3ad580-445e-11eb-8523-26e305ddba68.png)

**Desktop (please complete the following information):**
Reproduce on Desktop with chrome dev tools :D
 - OS: IOS
 - Browser: Chrome
 - Version 86.0.4240.80
 - Notes: right Click -> Inspect -> Toggle Device Toolbar in top left of the pop up. You will view the website in mobile view.

**Smartphone (please complete the following information):**
 - Device: Iphone Xs (I also know this is present on andriod)
 - OS: 14.2
 - Browser Safari and Chrome

**Additional context**
CC: @saranshgrover

**Comment by saranshgrover** [comment]
Thanks for this. Note that the table being stacked is intentional (see [this](https://semantic-ui.com/collections/table.html)). I'll get to the event selection fix soon!

**Comment by Jambrose777** [comment]
Is the stacked tables better design? For me it makes it super hard to read, especially since most of the items we are displaying are numbers.

**Comment by saranshgrover** [comment]
Closing since this was completed.
