### ISSUE TITLE
Add ability for Trainee Delegates to receive reports by email

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#6017]
Currently Trainee Delegates are able to view Delegate reports on the website but do not receive them via email. This means that they also miss out on any discussion that takes place in the replies to reports (a key part of their training).

There should be a "I would like to receive Delegate Reports of WCA Competitions by email" tickbox on their user profile as with staff, that should be selected by default.

**Comment by danieljames-dj** [comment]
Looks like this was missed while implementing trainee delegate stuffs in websites. I'll take care of this.

**Comment by saranshgrover** [comment]
@danieljames-dj Are you still working on this?

**Comment by danieljames-dj** [comment]
Hi @saranshgrover, sorry for missing this out. I've created [a PR](https://github.com/thewca/worldcubeassociation.org/pull/6540) for this and get this done soon.
