### ISSUE TITLE
MBLD old not displayed correctly in competition results table

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#6018]
See an example [here](https://www.worldcubeassociation.org/competitions/Euro2008/results/all?event=333mbo). It's been recently ported to React and this function is responsible for parsing MBLD attempt results:
 
https://github.com/thewca/worldcubeassociation.org/blob/ce57e2af345d7ad5cb4c0841315073b27eecaf5b/WcaOnRails/app/webpacker/javascript/wca-live/attempts.js#L20-L35

It should handle old-style format as well. The function was originally taken from wca-live, which doesn't have to support that format anyway.

**Comment by Jambrose777** [comment]
Working on this + other things mentioned on the Forum. PR up soon.
