### ISSUE TITLE
Add ability to make profiles private

### ISSUE THREAD

**Issue by kevin8181** [thewca/worldcubeassociation.org#6031]
**Is your feature request related to a problem? Please describe.**
I do not want my info to be public

**Describe the solution you'd like**
A checkbox in the account settings to make your profile private, ie. hidden on WCA search and not indexed by other search engines.

**Describe alternatives you've considered**
A way to hide your name and other info from your profile

**Comment by Jambrose777** [comment]
According to [WCA's Privacy Statement](https://www.worldcubeassociation.org/privacy) a WCA member has a right to be forgotten. A member can invoke this right by contacting our Data Protection Officer;  This can be done by reaching out through [WCA's contact](https://www.worldcubeassociation.org/contact/website) who will direct you with what information is needed to do so and forward the request to the correct part. Or, currently, reaching out directly to the [data protection committee](dataprotection@worldcubeassociation.org), though this will change with the upcoming bylaws amendments. Considering this process is not straightforward a committee has to process such requests, so a simple button click will not be feasible. However, I agree that the access to make such a request should be more accessible and something WCA will look into (ie. when pursuing #3281)

**Comment by kevin8888888888888** [comment]
I just meant a way to hide the profile from the public, not delete the information entirely. It's a standard feature on other platforms to be able to make your profile private and still use the service.

**Comment by c-goodyear** [comment]
Hi Kevin. Yes this is a standard feature on some social media platforms. However, the WCA is not a social media platform. We are recognizing results from competitions. If you have an example of a sporting body that has the feature you are advocating for, please share a link to their site.

**Comment by saranshgrover** [comment]
I think there is not much more to be said - we support anonymizing profiles, and we don't intend to add "public/private" profiles, so I'm closing this issue.
