### ISSUE TITLE
Add section to publish finances in documents

### ISSUE THREAD

**Issue by saranshgrover** [thewca/worldcubeassociation.org#6038]
from @viroulep 

> The build script for the documents keep the existing pdf if there are any, so it should be possible to create a "finances" folder [here](https://github.com/thewca/wca-documents/tree/master/documents) with the pdf inside, and then create an extra section similar to what we do [here](https://github.com/thewca/worldcubeassociation.org/blob/e80e7b22b6ec34a72c050113e7ae7bfae4450442/WcaOnRails/app/views/static_pages/documents.html.erb#L57-L70).

**Comment by viroulep** [comment]
Let me know if you have some trouble getting this to work, but I'd assume you could take pretty much the same approach we used for the WQAC documents.
