### ISSUE TITLE
Allow publication of annual financial returns and reports to WCA website

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#6039]
Per the Motions the WCA's annual returns and financial reports should be published on the WCA Website. This would take the form of a few PDF's per year. 

I feel the best form of this would be a new section on the documents page for "Financials" and ideally the ability for WFC/Board to upload PDF files to that section.

**Comment by viroulep** [comment]
Duplicate of #6038 (which is why it has been closed right away, I assume).

**Comment by EdHollingdale** [comment]
Yes - Saransh was 40 seconds faster than me!
