### ISSUE TITLE
Sorting registrations table is slow

### ISSUE THREAD

**Issue by timhabermaas** [thewca/worldcubeassociation.org#608]
Example page: https://www.worldcubeassociation.org/competitions/Euro2016/registrations

Sorting ~500 competitors takes almost 2s. Here's a screenshot from Chrome's Timeline measuring the sorting of ~500 competitors by name:

<img width="280" alt="screen shot 2016-05-12 at 11 17 41 pm" src="https://cloud.githubusercontent.com/assets/96054/15230791/d942a754-1897-11e6-9d13-7b01f98f8fe3.png">

I feel like we can improve this to be super snappy. It's only 500 rows... Low priority obviously.

**Comment by dunkOnIT** [comment]
Closing as we are moving to v2 reg - if necessary, will create a new issue for v2 performance based on feedback for large competitions
