### ISSUE TITLE
N+1 query during sign up

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#617]
This new `bullet` thing is not happy:

![n1query](https://cloud.githubusercontent.com/assets/1007485/15274751/be780048-1aba-11e6-9b1c-e7b19b8f783a.png)

I guess there is something to fix in the WCA id claim function, but I have no idea how to fix it :)
I got the error when trying to sign up with an already assigned id.

**Comment by larspetrus** [comment]
The line seems to be this one. The problem isn't obvious to me either.

already_assigned_to_user = unconfirmed_person && unconfirmed_person.user &&
!unconfirmed_person.user.dummy_account?

On a side note, I'm really looking forward to the *.&* operator!

http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/

On Sun, May 15, 2016 at 7:35 AM, Philippe Virouleau <
notifications@github.com> wrote:

> This new bullet thing is not happy:
>
> [image: n1query]
> <https://cloud.githubusercontent.com/assets/1007485/15274751/be780048-1aba-11e6-9b1c-e7b19b8f783a.png>
>
> I guess there is something to fix in the WCA id claim function, but I have
> no idea how to fix it :)
> I got the error when trying to sign up with an already assigned id.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cubing/worldcubeassociation.org/issues/617>
>



-- 
Procrastinators - the Leaders of Tomorrow

**Comment by ronaldmansveld** [comment]
Is this still an issue?

**Comment by viroulep** [comment]
Just went through a sign up and didn't notice anything wrong, it must have been fixed elswhere!
