### ISSUE TITLE
Foreign Keys

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/worldcubeassociation.org#625]
It appears as some tables don't have appropriate foreign keys setup. Currently, these tables include:

| Table | Field w/o FK |
| --- | --- |
| competition_delegates | delegate_id |
| competition_organizers | organizer_id |
| oauth_access_grants | resource_owner_id |
| oauth_access_tokens | resource_owner_id |
| oauth_applications | owner_id |
| posts | author_id |
| team_members | user_id |
| user_preferred_events | user_id |
| votes | poll_id |
| vote_options | vote_id, poll_option_id |

**Comment by pedrosino** [comment]
I'm not an expert, but apparently with Rails you don't actually need the FK in the database. The application should make the correct associations (belongs_to or has_many). The votes table probably have user_id with FK because I had no clue back then :)

**Comment by pingskills** [comment]
I think it's a good idea to have this set up in the database. This guarantees the integrity of the data and I don't see a downside to having them.

**Comment by pedrosino** [comment]
Maybe we need to create object A without the objectB_id field for some period of time. Having the foreign key doesn't allow this.

**Comment by FatBoyXPC** [comment]
So regardless of what the rails convention way of doing things is, foreign keys are a **good** thing. That said, The rails documentation actually discusses primary keys with "associations" [here](http://guides.rubyonrails.org/v2.3.11/association_basics.html#the-types-of-associations):

For example, by declaring that one model belongs_to another, you instruct Rails to maintain Primary Key–Foreign Key information between instances of the two models, and you also get a number of utility methods added to your model

**Comment by FatBoyXPC** [comment]
@pedrosino: regarding the "FK's don't allow this" part about object A without object B - FK's can certainly be nullable, so that's a non issue here.

I spoke with some rails devs that I'm in a slack chat with, and they said:

> rails migrations and schema definitions have a “references” type, use that

**Comment by larspetrus** [comment]
I prefer to not use foreign key constraints The arguments against it
constraints are

1. They're not needed in a well tested application
2. They can get in the way when creating and deleting things, so you're
forced to do things in certain order, and it can get quite painful and
complex.

That said, in this app we do not have good testing and we have a separate
PHP app writing to the same DB. So maybe PKCs are a good idea here.



On Tue, May 17, 2016 at 9:22 AM, James LaChance <notifications@github.com>
wrote:

> @pedrosino <https://github.com/pedrosino>: regarding the "FK's don't
> allow this" part about object A without object B - FK's can certainly be
> nullable, so that's a non issue here.
>
> I spoke with some rails devs that I'm in a slack chat with, and they said:
>
> rails migrations and schema definitions have a “references” type, use that
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cubing/worldcubeassociation.org/issues/625#issuecomment-219772262>
>



-- 
Procrastinators - the Leaders of Tomorrow

**Comment by FatBoyXPC** [comment]
So, to be completely honest, if your only defense of not using FK's is because "application code **can** handle it (albeit probably not as well as the database)" then I'm not sure I agree with that reason to not use FK's.

So here's the thing with testing: that completely relies on the developer(s) to create the tests. If a test case is missed (which is going to happen, as we can't account for all future cases) then data can get messed up. FK's will completely prevent this.

Even with 100% test coverage, etc., while FK's do make creating/deleting things out of order more difficult, your testing should be doing them in order (otherwise the tests would fail). I'm not seeing how testing would be anymore difficult. Also, with 100% coverage, doesn't mean that people can't manipulate the data themselves. Since that ability exists, data integrity should be a concern. Especially when we have a PhpMyAdmin link in the admin navigation!

**Comment by larspetrus** [comment]
On Tue, May 17, 2016 at 9:52 AM, James LaChance <notifications@github.com>
wrote:

> So, to be completely honest, if your only defense of not using FK's is
> because "application code *can* handle it (albeit probably not as well as
> the database)" then I'm not sure I agree with that reason to not use FK's.
>
Sure. Most programmers probably don't agree with it.

> So here's the thing with testing: that completely relies on the
> developer(s) to create the tests. If a test case is missed (which is going
> to happen, as we can't account for all future cases) then data can get
> messed up. FK's will completely prevent this.
>
The way I think of it, if your testing isn't good enough to ensure the
quality of your code you *really* need to improve it.

FKCs can help you with some problems, but for 98% of possible bug sources,
there is no such alternative mechanism to lean on.

> Even with 100% test coverage, etc., while FK's do make creating/deleting
> things out of order more difficult, your testing should be doing them in
> order (otherwise the tests would fail). I'm not seeing how testing would be
> anymore difficult.
>
It's not that testing gets harder. It's mostly about bulk data operations.
If you want to delete A, B, C, D and E, you may have to order it D, A, B,
E, C. Now imagine it's thousands or millions of records. It's easy to spend
tons of time and effort on this.

> Also, with 100% coverage, doesn't mean that people can't manipulate the
> data themselves.
>
Again, 90% of the damage people can do with untested manual SQL will not be
caught by FKCs. You just have to not do that, and fire people who do it
anyway.

> Since that ability exists, data integrity should be a concern. Especially
> when we have a PhpMyAdmin link in the admin navigation!
>
Having said all that, I'm not really opposed to FKCs in this project, if
people want it. The team and project is very different from the
professional teams I'm used to. Since Version 4.2 there is even Rails
support for FKCs!


In two previous jobs I wrote a generic foreign key "sanity checker" that
checked all foreign keys every night. I regret not having made a public Gem
from that code.

-- 
Procrastinators - the Leaders of Tomorrow

**Comment by FatBoyXPC** [comment]
> Since Version 4.2 there is even Rails
support for FKCs!

I posted documentation to 2.3.11 having support for FKs!

**Comment by jfly** [comment]
For the record, we just merged up code with foreign key constraints, and something broke (see #891).

**Comment by jfly** [comment]
Closing this issue. I decided to get rid of all foreign keys a while ago. See https://github.com/jfly/worldcubeassociation.org/blob/5637ddd887d14091a58cbbb5959cf8e58bdd02a7/WcaOnRails/db/migrate/20170404184332_convert_utf8_to_utf8mb4.rb#L10-L17.
