### ISSUE TITLE
Relax restriction on Australian States Validator

### ISSUE THREAD

**Issue by Epride** [thewca/worldcubeassociation.org#6255]
**Describe the bug**
Currently Australian competitions are required to list a state that aligns with the list of Australian states for consistancy. however we have run into a situation where we are running a simultaneous competition across multiple states however this is not an accepted input 

**To Reproduce**
1. Create a competition with the country Australia
2. In city name type Multiple Cities
3. Observe error

**Expected behavior**
Ideally we should be able to list Multiple Cities as a valid entry into the city name input for competitions like this.

**Comment by Jambrose777** [comment]
Use a lowercase c in cities :)

**Comment by Epride** [comment]
Thanks!
