### ISSUE TITLE
[Bug] Flickering Accordion Link

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6275]
**Describe the bug**
On the Edit Schedule page there is the flickering according link bug.

**To Reproduce**
1. Go to any competition page as a user that can manage that competition
2. Go to the edit schedule tab
2. try to click on either of the two accordion headers (it can take me around 30 seconds of clicking to finally get it to open).

**Expected behavior**
no flickering and can open accordion smoothly

**Screenshots**
https://youtu.be/TBkYJmyeHyQ

**Desktop (please complete the following information):**
 - OS: MacOs Big Sur 11.2
 - Browser Chrome

**Comment by denthebro** [comment]
Was this not just fixed in the newest WST digest?

**Comment by Jambrose777** [comment]
> Was this not just fixed in the newest WST digest? #6215

I’m not sure if that fix was for this specific part or if it unintentionally introduced this, but I have started getting this when making a new competition.

**Comment by FinnIckler** [comment]
Have we actually deployed this?

**Comment by denthebro** [comment]
> 
> 
> Have we actually deployed this?

It says it's merged, so it would appear so

**Comment by FinnIckler** [comment]
merged does not mean deploy ;). It's an additional manual step that has to be done

**Comment by denthebro** [comment]
> 
> 
> merged does not mean deploy ;). It's an additional manual step that has to be done

Oh, I see. I thought it has been deployed, because it was mentioned in the WST digest.

**Comment by Jambrose777** [comment]
This is fixed now. I'm going to assume it was a deployment issue and the PR was to fix this :)
