### ISSUE TITLE
Make the "spectators can attend for free" text optional

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#6321]
**Is your feature request related to a problem? Please describe.**
When registration fee for spectators is set to $0, this adds a line of text to the registration requirements that "spectators may attend for free".  This is somewhat misleading, especially with the Safety Policy which allows us to limit to only one spectator per competitor.

For Back to Cambridge, I've received a few emails from interested spectators who have seen this text and believe that spectators are permitted.

**Describe the solution you'd like**
Add a few more options to describe the spectator policy of the competition, for example "spectators are only permitted as guests of competitors".

**Comment by EdHollingdale** [comment]
Related #3865
