### ISSUE TITLE
Add time to Registered and paid on dates.

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6326]
**Is your feature request related to a problem? Please describe.**
With Registrations filling up extremely fast, it would be beneficial to know the exact time someone registered and/or paid in addition to the date. Currently for the "Paid on" column only the date is shown

**Describe the solution you'd like**
Have a date + time show instead on the `/edit/registrations` page.

**Comment by gregorbg** [comment]
I agree that this would be a useful feature to have! Note: We already store this kind of information, as can be seen by the mouseover tooltip when you hover over the the "Paid on" column. This is just a matter of actually _displaying_ the existing information in the table.

**Comment by Jambrose777** [comment]
The hover shows the time money was requested which is different than the time paid

**Comment by saranshgrover** [comment]
Working on this - alternative to showing the time, which would generally be needed in specific cases, do you think its better to show the exact time on hover. So when payment not made - hover shows when payment was requested, and when payment is made, hover shows when paid?

**Comment by Jambrose777** [comment]
I think that would be good!
