### ISSUE TITLE
Update COVID warning text on Competitions page

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#6366]
Currently, the competitions page has a red warning:
Please note that due to the COVID-19 pandemic, many countries are currently unable to host competitions.

The situation has improved significantly since that was posted. Perhaps a more appropriate warning text would now be:
Please note that due to the COVID-19 pandemic, _some_ countries are currently unable to host competitions.

I think a yellow color would also be more appropriate than the red now.

**Comment by AnaOddles** [comment]
Hi! I am a beginner and would love to work on this!

**Comment by viroulep** [comment]
I'm not sure if you already contacted someone from the WST to get some insights about how the code is organized, so I'll leave some pointers:
  - strings displayed to non-admin users are usually localized, as such the best place to look for them is our [locale files](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/config/locales/en.yml#L1356) (when updating something you just need to take care of English, translators are notified on changes).
  - most of the strings displayed directly to the users are used in the [app/views](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/) folder; as you can see in the locale file comments the key is used on the competitions index page, so going to `competitions/index.html` is a good first guess (it's [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/index.html.erb#L6) actually).
  - `alert` is a rails helper defined [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/helpers/application_helper.rb#L139), it's basically a wrapper to create a [bootstrap alert](https://getbootstrap.com/docs/3.3/components/#alerts), and using one of the other bootstrap keywords works as expected here.
