### ISSUE TITLE
MBLD Results with DNF/DNS look strange

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6375]
**Describe the bug**
MBLD Results on competition pages have weird spacing, making it look like the DNF/DNS the time and the attempt # are seperate results / all the same result.

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/competitions/BrizZonSideOpen2021/results/all?event=333mbf

**Expected behavior**
Should be able to tell which numbers belong to which attempts

**Screenshots**
![image](https://user-images.githubusercontent.com/11577241/126184015-1101ca3b-abb6-494c-a453-74481f5b1a8c.png)

**Additional context**
Also see #4426

**Comment by kr-matthews** [comment]
Hey, I would like to work on this as my first issue.

**Comment by gregorbg** [comment]
Closed as per #6510
