### ISSUE TITLE
Add the competition events to the emailed report

### ISSUE THREAD

**Issue by druidalek** [thewca/worldcubeassociation.org#6378]
I would like to propose adding the events of a competition in the emailed report. 

Since we already have the date, location, number of competitors and equipment I don't see a reason not to include the events. You can argue that you are able to do this by opening the competition on the website, but I think this will save some clicks and time. 

The reason for adding the events is when I read the report I would like to know what type of a competition this was before I start reading the report. Was it only a few events, was it an all-event competition or maybe just fewest moves or only blind events, etc. As an organizer and delegate I would benefit from having this information directly in the email.

**Comment by Jambrose777** [comment]
I've labeled this under WRC/WQAC as this is for the reports. I overall think that it would be a very nice addition to our reports. Even though the schedule is only a click away, so is other information presented. like date/location/competitors.
