### ISSUE TITLE
Delegate change email getting failed sometimes

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#6409]
When the delegate status of a person is changed, an automatic email will be sent to Board & WEAT. But looks like some emails were not received in the last month. Looks like there is some issue in the automatic mail.

**Comment by EdHollingdale** [comment]
I had this happen to me with a promotion back in mid-April. I changed the delegate status but the website errored (took me to an error page similar to what it looks like when the website is down, but slightly different (didn't take a screenshot sorry). I then went back to the user profile which showed the promotion as having gone through, but the automated email never arrived.

**Comment by danieljames-dj** [comment]
No longer an issue I guess, so closing this.
