### ISSUE TITLE
Staging WCA site is down

### ISSUE THREAD

**Issue by big213** [thewca/worldcubeassociation.org#6423]
**Describe the bug**
staging.worldcubeassociation.com is not working

**To Reproduce**
1. Go to https://staging.worldcubeassociation.org
2. See error message

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/8443042/130165023-7eb5d935-b9f3-4f6a-b382-1b6e276646f9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 92.0.4515.159 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
n/a, but also applies to mobile browsers

**Additional context**
Maybe it is not critical for the staging WCA site to be working, but it is referenced in the wiki documentation [here](https://github.com/thewca/worldcubeassociation.org/wiki/OAuth-documentation-notes), so if it is no longer supported, I think the wiki should be updated.

**Comment by FinnIckler** [comment]
Hi James,
We will be upgrading staging to the newest version on Sunday and it should start working then,

Thanks,
Finn

**Comment by FinnIckler** [comment]
Staging is now up and running at https://staging.worldcubeassociation.org/
