### ISSUE TITLE
Our deploy needs to be run twice if the deploy script itself changed

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#651]
(I just ran into this while deploying https://github.com/cubing/worldcubeassociation.org/pull/635)

Our deploy command is currently `ssh -A cubing@worldcubeassociation.org worldcubeassociation.org/scripts/deploy.sh pull_latest rebuild_rails`, which pulls in the latest versio of the production code (including our precious deploy.sh script), but then proceeds on to do `rebuild_rails` with the currently running (old!) version of the deploy script.

Maybe we should change our deploy command to take this into account? Or maybe change the deploy.sh script to be cleverer and rexec itself... urg.

**Comment by larspetrus** [comment]
Intriguing...

How about a _very_ basic wrapper script that does

1. Pull in latest version of the project
2. Launch the newly arrived deploy.sh

That script would never have to change.

**Comment by dunkOnIT** [comment]
99% sure this no longer applies - @FinnIckler correct me if I'm wrong
