### ISSUE TITLE
Conditional text on Info screen related to competitors updating events

### ISSUE THREAD

**Issue by KerrieJarman** [thewca/worldcubeassociation.org#6546]
In the recent PR [#6305 ](https://github.com/thewca/worldcubeassociation.org/pull/6305), the change did not consider the generated text in the Registration Requirements section on the info page

![image](https://user-images.githubusercontent.com/56055554/141380709-696040bf-35e0-48b6-a178-9c8a78464d37.png)

The text on the Info screen should be conditional on the choice made in the Registration Edits field. 

IF  "Competitors may edit their registration until the deadline for updating events" is chosen 

THEN the text on the Info screen should read "... you may change your own registered events until... on the Register tab" (with a link to the Register tab) 

ELSE "... you may change your registered events until... by contacting the organization team"

@timreyn tagging you as you did the code

**Comment by timreyn** [comment]
Thanks Kerrie for catching this!  Fixed in #6547.

**Comment by KerrieJarman** [comment]
Wow thanks @timreyn for doing so quickly - like magic!
