### ISSUE TITLE
Anonymization Process - WCA Live portion

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6554]
Follow up to #6086. We can more accurately display which competitions use WCA and link directly to all of their sync pages. Here's the high level how:
For Each competition we would somehow ping https://live.worldcubeassociation.org/link/competitions/{wcacompetitionId}. That will either return an error if the competition does not have a WCA Live Page: {"errors":{"detail":"Not Found"}} or redirect to https://live.worldcubeassociation.org/competitions/{wcalivecompetitionId}. So if it we do get the new url back then we can list those competitions on the Anon Process and link to the WCA Live sync page for that competition.

**Comment by gregorbg** [comment]
Closing in favor of https://github.com/thewca/worldcubeassociation.org/issues/6681
