### ISSUE TITLE
Can i use this for my site? And how do i set it up to my site?

### ISSUE THREAD

**Issue by in4mation-hub** [thewca/worldcubeassociation.org#6591]
I want to create my own cubing site and i was wondering if im allowed to use this for my site and how do i set this up?

**Comment by coder13** [comment]
You can't use this to make a website.
This is specifically for competitions. 
Do you mean a cubing site for a competition?

**Comment by in4mation-hub** [comment]
like i want to make my own site like WCA, how do i do that?

**Comment by wrhall** [comment]
If you're not familiar with web dev / programming, it would be difficult for you to start here. (although you could start by following the directions in the README and seeing if that works... then tinkering with it to gain some intuition about how the code works)

A better place to start might be to decide what type of app you're looking to build. If you need to persist state (store users or high scores), you could try to learn (what I think is the backend for WCA) Ruby on Rails -- there are tons of great, free resources to get started.

If you want to just build a front-end layer, you might find a complete beginners guide to front-end web development (https://www.google.com/search?q=vuejs+total+beginner might be a good place to start? Although I have no opinion about which frontend framework you should actually be learning).

Hope this helps! Probably the best place to ask questions like this in the future is to find a beginner-friendly programming discord community you can join (for whichever language or framework you want to get started in)

**Comment by in4mation-hub** [comment]
i have a wca type site but i want like a database thingy so i dont have to go into the code and insert times manually, create comps manually and make profiles manually. How do i do that?

**Comment by wrhall** [comment]
Look into a Ruby on Rails tutorial :)
That would be a good place to start! As you gain familiarity with the language / framework, you can look at how WCA uses Rails for this site in particular, and that could be a helpful example.

I think you can read the Rails Tutorial for free online: https://www.railstutorial.org/book#cha-beginning
And the Rails official guide should be a useful reference as well: https://guides.rubyonrails.org/getting_started.html
Finally, look into a friendly discord. Not sure how beginner friendly this one is, but you might try e.g. https://www.rubyonrails.link/ and ask questions in their #coding channel.

Good luck!

**Comment by in4mation-hub** [comment]
can i do it instead with PHP?

**Comment by wrhall** [comment]
Yes, you can use any language you want. (I don't think this is a good place for this discussion anymore -- for future questions try to find a relevant subreddit or discord & ask them there)

**Comment by in4mation-hub** [comment]
ok thx ill try ruby on rails
