### ISSUE TITLE
Registration Date Time Picker - Clicking Now Issue

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6615]
![image](https://user-images.githubusercontent.com/11577241/148624882-5862fb97-e8b1-4fb7-80a2-759755e9aa9c.png)

**Describe the bug**
When clicking the now button on the registration open/close (the button on the bottom of the screenshot), the time inputted into the field is the current local time, while the field is representing the current UTC time. This means that when WCAT clicks this button to close registration it changes the time to look like it closes at the incorrect time (ie. the current time is 01-08 00:30 UTC and that should fill the registration close, but  instead it is filled with 01-07 19:30 UTC if I am in eastern Time Zone).

**To Reproduce**
1. Go to Admin view on a competition
2. Scroll down to registration close
3. click the field and click the target button at the bottom of the modal.

**Expected behavior**
It should convert the current time to UTC and fill in the field appropriately.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
This mostly affects WCATs work and seems to be a new issue not caused by any of our code changes as this worked as intended years ago when I was on WCAT.

**Comment by kr-matthews** [comment]
There's no longer a "now" button; and there's a dedicated button elsewhere to close registration.
