### ISSUE TITLE
Competitors now able to delete their registration when accepted

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#6621]
When you enable competitors being able to edit their events it seems they are also able to delete their registrations after they have been accepted. This is undesirable for now, since there are further actions that need to be taken for an accepted registration (e.g. processing a refund if it is due, and accepting the next competitor on the waiting list). While competitors being able to edit their events is great, it would be good if the ability to change their status was not an option for them. Obviously this can be re-enabled when there is automated waiting list handling!

**Comment by AlexKatyukov** [comment]
IMO, there should be two checkboxes: one for editing events and second for deleting the registrations. Sometimes deleting is okay, but sometimes are headache.

**Comment by EdHollingdale** [comment]
I know this issue has a high priority label, but it is getting really frustrating. When someone deleted registration there are extra steps (refunds, processing waiting list), and people starting the process themselves rather and having a free spot in the competition until someone notices is very frustrating.

**Comment by gregorbg** [comment]
Fixed in #6991
