### ISSUE TITLE
Decide how to handle markdown fields on competition edit page

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#663]
Currently there are 3 besides `information`:

```
~/gitting/worldcubeassociation.org @kaladin> grep "supports_md" WcaOnRails/app/views/competitions/edit.html.erb
      <%= f.input :venue, hint: t('.venue_html', md: t('.supports_md_html')) %>
      <%= f.input :venueDetails, hint: t('.venue_details_html', md: t('.supports_md_html')) %>
      <%= f.input :contact, hint: t('.contact_html', md: t('.supports_md_html')) %>
```
- I propose that `venue` should become 2 text boxes: text and url.
- I propose that `venueDetails` become a `<textarea>` and become part of a dedicated travel page, a la cubingusa. (#329)
- I'm not sure what to do with `contact`... the last time I tried to change this, I discovered that people are pretty addicted to it.

**Comment by pingskills** [comment]
@jonatanklosko @jfly suggested here that `venueDetails` become a `<textarea>` and become part of a dedicated travel page. I imagine this can be replaced with your competition tabs PR? Once that is implemented can this issue be closed too?

**Comment by jonatanklosko** [comment]
@pingskills yeah I think we will be able to discard the second dot pointed out. Not sure about the others. @jfly?

**Comment by jfly** [comment]
I still like the idea proposed in the first bullet point, I think the second one is not going to happen, as much as I would like to get rid of the damned contact field.

**Comment by AlbertoPdRF** [comment]
Is this issue still relevant?

**Comment by jfly** [comment]
:man_shrugging: seems fine to close it.
