### ISSUE TITLE
Registration Start Time

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#6688]
With the intense demand for local WCA competitions, several competitions opening at the same time can put a strain on loading times for the WCA. It would be nice if there was a way on the delegate's end to see all current registration opening times for announced competitions to avoid overlap when announcing a new event and keep the WCA site stable for those registering.

**Comment by gregorbg** [comment]
Thank you for the suggestion! In the long (or at least medium) term it would be great to have a dedicated timeline.

Right now, as an initial remedy, I suggest adding a "sort by reg opening date" button in the general competitions list. This could even be public, as I don't think there's any reason to hide the registration date of announced competitions.
