### ISSUE TITLE
Create cloned competition button disabled after cancelling alert

### ISSUE THREAD

**Issue by kr-matthews** [thewca/worldcubeassociation.org#6700]
**Describe the bug**
When cloning a competition, if you click create but then hit cancel on the alert, the create button is now disabled and you're unable to create the cloned competition - you need to exit, hit clone again, and re-input all the changed information from scratch (even though it's still there on the page; you just can't submit it).

**To Reproduce**
1. Go to any existing competition as a delegate
2. Click on Clone in the left menu
3. Fill out all (required) fields
3. Scroll down to the bottom and click Create Competition
4. See alert that changes won't be saved
5. Click 'Cancel' on the alert
6. Observe that Create Competition button is now disabled

**Expected behavior**
Selecting cancel on the alert should not disable the button.

Or maybe there should be no alert at all. It's misleading to alert people that changes won't be saved, since they _will_ be saved into the new competition.

**Screenshots**
![image](https://user-images.githubusercontent.com/49137025/154596309-424f365d-ce69-41b4-a462-4a69f88d7863.png)

![image](https://user-images.githubusercontent.com/49137025/154596633-79d9d9d7-341d-4cc4-a928-b8221566ca08.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by gregorbg** [comment]
Hmm... This looks like a JavaScript quirk; I'm no expert on that topic :( Anybody else feel free to pick this up if you know about site alerts!

**Comment by Jambrose777** [comment]
Just some background:
This is an old bug. It also happens when normally creating a competition or updating a competition and cancelling- the confirm button will disable. Way back when I brought this up it seemed like I was the only one having this issue and I had a work around by inspecting the button element and removing the disabled flag which allowed me to click it and proceed as normal
