### ISSUE TITLE
Centering of text and event icon on schedule looks weird

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/worldcubeassociation.org#6704]
![Screenshot_20220218-125740](https://user-images.githubusercontent.com/8561825/154753047-b2845411-88ae-4069-9035-bb5012779063.png)
See specifically clock final, but they're mostly all weird.

**Comment by gregorbg** [comment]
Thanks for making us aware! Looks like some CSS shenanigans... It's on our radar now but it's a pretty minor design issue so I'm assigning a low priority
