### ISSUE TITLE
Internal error when trying to connect to AWS S3 in development

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#6705]
**Describe the bug**

When running the website in development mode, opening the homepage lead to the posts index crashing, and trying to login crashes too with the following internal error:
```
Aws::Sigv4::Errors::MissingCredentialsError at /posts.json
missing credentials, provide credentials with one of the following options:
```

Can anyone actually work in dev mode with the current website state, and if yes how?
(having the private AWS secrets in the dev environment is not the answer I'm looking for :p)

Looking [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/config/initializers/carrierwave.rb#L20-L25) it seems we may want to provide some credentials in dev mode, but I doubt it's actually desirable by default unless we have dev credentials too.

Unless I'm missing something we have a couple of options here:
  - if we do have public credentials, we should put them in the environment.
  - if we don't, we should enable stub responses in dev mode too (this is what I did to get past the error).
  - if we want to enable temporary use of prod credentials for development purposes, I'd suggest to enable stubs if the aws key id or the aws secret is empty.

What do you think?
I can provide a patch if one of my suggestions sounds good.

**Comment by gregorbg** [comment]
Wow, you actually figured out a loophole for non-WST people here. We usually all have our own AWS credentials, but indeed there is no public access key.

Might I suggest a mix between options (2) and (3), such that you enable stub responses in dev mode only if no explicit other credentials are given?
