### ISSUE TITLE
Be consistent about form submission errors (when update_attributes returns false)

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#674]
See discussion https://github.com/cubing/worldcubeassociation.org/pull/673/files#r64659089.

Sometimes we do something like this (note the assignment to `flash.now[:danger]`):

```
    if @delegate_report.update_attributes(delegate_report_params)
      flash[:success] = "Updated report"
      redirect_to competition_report_edit_path(@competition)
    else
      flash.now[:danger] = "Could not update the report!"
      render :edit
    end
```

And sometimes we render `shared/error_messages` in the view, which is arguably more useful. However, I worry about a hypothetical scenario where `.update_attributes` returns false, but there are no validation errors for `error_messages` to show. Is this a realistic fear, @larspetrus, @jonatanklosko, @timhabermaas? Perhaps our `shared/error_messages` could become smart enough to check if the object is not persisted, not new, *and* has no validation errors, and render a scary looking "oh-oh" message?

**Comment by larspetrus** [comment]
The description of `update_attributes ` says 

_Updates the attributes of the model from the passed-in hash and saves the record, all wrapped in a transaction. If the object is invalid, the saving will fail and false will be returned._

"the object is invalid" means a validation failed, and there is an error message.

**Comment by jfly** [comment]
Good to know!

Unless anyone objects, I think we should look into hooking into simple_form to always render `shared/error_messages` first. Maybe in the future, we could do something fancy with `shared/error_messages` to link directly to the problematic fields with anchor tags. I personally am always annoyed by error messages that force you to hunt for the problematic fields.

**Comment by larspetrus** [comment]
I know nothing about `shared/error_messages`, so count me as a non objector.
