### ISSUE TITLE
Create "evolution of records" graph in Statistics 2.0

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6742]
The [Evolution of Statistics graph](https://www.worldcubeassociation.org/results/misc/evolution/) is currently generated by using a PHP script found [here](https://github.com/thewca/worldcubeassociation.org/blob/master/webroot/results/misc/evolution/update7205.php).  

We would like to generate the same graph in a more modern framework. Ideally, your solution should also find a place on the [WCA statistics](https://www.worldcubeassociation.org/results/statistics.php) page where it can be linked from.

## To be clarified

Do we have a preference for whether to use Ruby or React to achieve this?

**Comment by dunkOnIT** [comment]
@gregorbg please advise where the current version of the "evolution of records" graph can be found so that I can expand on the issue spec.

**Comment by gregorbg** [comment]
The graph is computed [here](https://github.com/thewca/worldcubeassociation.org/blob/master/webroot/results/misc/evolution/update7205.php). The live graph is at https://www.worldcubeassociation.org/results/misc/evolution/

**Comment by dunkOnIT** [comment]
@gregorbg thanks! Follow-up question: Do we have a preference/recommendation on whether to implement this with Ruby vs React? Not sure what the capabilities of each are in this regard.

**Comment by gregorbg** [comment]
This very specific graph page should be discussed with Alexandre.

In general, we prefer React for frontend wherever possible, but we're stuck with existing Ruby in a lot of places. And sometimes porting over an entire Ruby layout with historically grown complexity is just not worth it to add a simple button.

**Comment by campos20** [comment]
This PR fixes it

https://github.com/thewca/statistics/pull/66

Since Stats 2.0 already had best ever ranks, I reused it to slip in record evolution.

**Comment by dunkOnIT** [comment]
Thanks @campos20 ! Closed.
