### ISSUE TITLE
Port standard database export to Ruby

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6744]
The WCA database export (https://www.worldcubeassociation.org/results/misc/export.html) currently operates off of PHP. It should be feasible to create a Ruby structure similar to the existing Developer Dump that exports all of the relevant tables for the Results Export as well.

Developers: Note that this is NOT the developer dump you may be familiar with.

**Comment by dunkOnIT** [comment]
@gregorbg was this done by @campos20 as part of the Statistics implementation? or is this different?

**Comment by gregorbg** [comment]
This is different.

**Comment by danieljames-dj** [comment]
This was done by @gregorbg in PHP migration.
