### ISSUE TITLE
Chef provisioning and server configuration

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6746]
## Context

Our provisioning is largely handled by `Chef`, meaning it installs secrets and `Ubuntu` packages and configures our server in general. In doing so, it uses several outdated packages and it is hard to maintain and track these.

We need to investigate alternatives along the lines of `IAC` ("infrastructure as code"). We also need to care about the versions of:
* Ruby (don’t use the orphaned `brightbox-ruby` distribution anymore!!)
* Rails framework
* Ubuntu

## Actions: 
- [ ] Research and propose `IAC`-based provisioning solutions. Make proposal in this thread, tagging Gregor (_sorry Gregor_) with the proposal for his review.
- [ ] Once proposed, implement with PR. Advise if this issue needs be broken down, or create additional tasks for yourself here as needed.

**Comment by dunkOnIT** [comment]
@gregorbg This is currently spec'd at quite a high level technically (to my eyes at least lol). We could do work to break it down to be more approachable for the average contributor, or look to assign it to someone already familiar with the architecture and contraints. My guess would be that the latter makes more sense, given how integral this is to the overall infrastructure.

**Comment by gregorbg** [comment]
Complete-ish. We are having active plans and ideas, although they are not reality yet.
But a lot of the original points of this issue are not relevant anymore / sufficiently solved, so feel free to close.
