### ISSUE TITLE
Design ReactJS-based Registration System

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6747]
The process should be automated as much as possible, meaning new registrations shouldn’t have to be accepted manually (whenever it is possible to detect that, given that not every competition uses Stripe payments).

It should also be much easier for competitors to see their current registration status.

**Comment by coder13** [comment]
I'm thinking about taking this on.
My ruby isn't that great but I excel at react code so I might be able to get some good progress here. I was looking at other erb -> react ports to get an idea of how to do it.

> The process should be automated as much as possible

This seems like it's mutually exclusive from porting the code to react

> It should also be much easier for competitors to see their current registration status.

Once this code is ported over, we should be able to address a lot of the other registration issues with relative ease (or at least I can). 

@gregorbg This is labelled as "needs spec" should I gather more info before taking this on?

**Comment by gregorbg** [comment]
Wow. I really appreciate your enthusiasm but this is a project management issue and the reason that we're building a spec is that we're planning to address this as a team with 3-5 people working on it at the same time. With all due respect and appreciation, please don't take this on single-handedly.

I'll steal the email from your GitHub account and reach out to continue this conversation in private :)

**Comment by coder13** [comment]
> With all due respect and appreciation, please don't take this on single-handedly.
Sounds good

> I'll steal the email from your GitHub account and reach out to continue this conversation in private :)
Sure :)
