### ISSUE TITLE
Event Count Misaligned on Registration Edits Page when Show Events is enabled but Show Birthdays is not

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#6751]
**Describe the bug**
On the edit registrations page there is the option to show events. If this is enabled the events someone registers for appear, with a total at the bottom indicating how many are signed up. However, if birthdays are hidden (which they are by default) then this count is offset by 1 column to the right (see screenshot below). If show birthdays is enabled the problem goes away. 

**To Reproduce**
1. Go to the registration page on a competition you can admin
2. Click on "Show Events"
3. See error

**Expected behavior**
Low priority!!!!!!! But they should line up. cc @kr-matthews as it seems to be related to the hidden birthdays column.

**Screenshots**
(from staging)
![image](https://user-images.githubusercontent.com/45908872/156546327-bb089f5a-95fd-47c0-b099-76b40c5bdd8d.png)
![image](https://user-images.githubusercontent.com/45908872/156546392-8a9e7763-80c2-4b68-a2af-d3cbbc64e137.png)

**Comment by EdHollingdale** [comment]
I don't do any web design, but looks like it could be solved by replacing line 8 of [_edit_registrations_table_footer_html.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/registrations/_edit_registrations_table_footer.html.erb) with an if statement.

**Comment by kr-matthews** [comment]
Oh, oops. Yeah, I only adjusted the table header and body, but not the footer. As you say, it looks like a very easy fix. I can do it tonight.
