### ISSUE TITLE
Change design of Delegates page: remove black background for Seniors

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#6759]
Now we have [Delegates page](https://www.worldcubeassociation.org/delegates) that looks like that:

![Screenshot_20220307-234543_Browser](https://user-images.githubusercontent.com/18090165/157115150-8394a673-617f-4fb9-88e1-496bd9f1b4c7.jpg)

Black background could be misunderstooded as mourning — some cubers told me about it. As far as I know it's true for lot of cultures. So I suggest to change this to any other color 🙂

**Comment by dunkOnIT** [comment]
Great suggestion - apart from anything else, the stark colour difference is quite jarring. My suggestion would be a more subtle colour difference, which still denotes the difference between senior and other delegates?

![image](https://user-images.githubusercontent.com/52967253/157180581-7176563a-ee3e-4787-8348-137ad64846a6.png)

This example uses black for text and #dbd9d9 for the senior delegate table row.

**Comment by ando527** [comment]
I'm happy to start working on this!

**Comment by dunkOnIT** [comment]
Hi @ando527 ! Thanks so much - just checking, are you Mitchell from the email thread?

**Comment by ando527** [comment]
> Hi @ando527 ! Thanks so much - just checking, are you Mitchell from the email thread?

Yes, that's me, I've completed this now, should I make a pull request?

**Comment by dunkOnIT** [comment]
Awesome! Yes, please go ahead with a pull request

**Comment by Nevseros** [comment]
Can this be closed please? #7608 resolved it.
