### ISSUE TITLE
Update statistics website copy/text

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6760]
Please see [issue 68 on the Statistics repo](https://github.com/thewca/statistics/issues/68). 

_Some of the text on the [website](https://statistics.worldcubeassociation.org/) appears to be placeholder text that could be expanded upon (eg, more info could be added to the "About" page), or has phrasing that sounds a bit weird to a native English speaker ("We try always to add new statistics." could be "We're always looking to add new statistics")._

**Comment by Randomno** [comment]
This was resolved on the stats repo

**Comment by dunkOnIT** [comment]
Randomno is correct!
