### ISSUE TITLE
Send email to WEAT on member changes in team/committee towards the month end

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#6761]
It will be good if an automatic email is sent to WEAT on changes in team/committee of that month, so that it will be easy for compiling the monthly digest.

In future, maybe we can include delegates as well (when the new table structure for the delegates is ready), so that 80% of monthly digest work of WEAT will be automated.

**Comment by dunkOnIT** [comment]
@danieljames-dj looks like you are actively working on this right? I remember us talking about it, jsut confirming that it hasn't been closed/merged.

**Comment by gregorbg** [comment]
Currently open as https://github.com/thewca/worldcubeassociation.org/pull/6867
I'm sure Daniel will work on this whenever he finds the time :)

**Comment by dunkOnIT** [comment]
Awesome, this was purely a Duncan github literacy issue, not a Daniel follow-up issue :P
