### ISSUE TITLE
Remove No Competitor Limit option 

### ISSUE THREAD

**Issue by KerrieJarman** [thewca/worldcubeassociation.org#6764]
The WCRP Clause 5 no longer allows for competitions to have no competitor limit  - with the exception of FMC simultaneous competitions. 

On the Organiser View setup tab The option "I Don't want to specify a competitor limit" should be restricted or at the very least the helper text should say: "A Competitor Limit is required - only FMC Simultaneous Competitions can have no Competitor Limit"  (or something similar)

![image](https://user-images.githubusercontent.com/56055554/158003230-b7b25d1f-1dea-4280-8d0c-9c4b7cf4bc4f.png)

**Comment by Jambrose777** [comment]
I closed a PR to modify this here: https://github.com/thewca/worldcubeassociation.org/pull/5986
Basically we should wait until https://github.com/thewca/worldcubeassociation.org/projects/24 to redo the logic here as itll be easier there.
