### ISSUE TITLE
Opt-in for age data to be displayed

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6787]
Currently no age data is made available on the Statistics website. [This forum post](https://forum.worldcubeassociation.org/t/opt-in-for-age-data-to-be-on-the-public-db/19242) suggests making it possible to opt-in to having your age data be part of the statistics website.

This issue simply serves to bring it onto Github, where it can be triaged and discussed. It is not an endorsement of the proposed change.

**Comment by Jambrose777** [comment]
Closing in favor of: #285. (Feel free to reopen that issue).
