### ISSUE TITLE
Expand teams tables to handle delegates

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#680]
It would be really awesome to keep track of just who was a board member when, for instance. Unfortunately, being a delegate isn't quite as simple as just any other team. Right now, we have the following fields thrown into the `users` table just for delegates:

```
  `delegate_status` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `senior_delegate_id` int(11) DEFAULT NULL,
  `region` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
```

`delegate_status` can be one of `NULL`, `candidate_delegate`, `delegate`, `senior_delegate`, or `board_member`.

`senior_delegate_id` identifies a delegate's senior delegate.

`region` is just some arbitrary string that I'd love to see replaced with something more useful such as the delegate's actual location (see https://github.com/cubing/worldcubeassociation.org/issues/426#issuecomment-222375556).

One idea might be to create one "delegate team" per region, where our senior_delegates are the leaders of those teams. The board would be yet another team. We'd also need the ability to mark team members as "candidates", which I'd personally wouldn't mind having for the software team =).

Another idea would be to create one team per delegate type: `candidate_delegate`, `delegate`, `senior_delegate`, or `board_member`, but I don't know how we'd deal with senior delegates that way.

Lastly, we could have just one team called delegates, and introduce some more generic concept of a team member "type", instead of just leader. We could use that type to identify candidate delegates vs delegates vs senior delegates vs board members.

**Comment by pingskills** [comment]
I was thinking along the lines of your last option with a member_type table.

**team_members**
id
team_id
user_id
**member_type_id**  --links to member_types table
**senior_team_member_id** -- links to team_members or users?
**latitude**
**longitude**
start_date
end_date
created_at
updated_at

**member_types**
id
team_id
member_type

**Comment by jfly** [comment]
I like that proposed schema! Although I would move latitude and longitude over to the `users` table, so we can reuse those fields to do #114 later one =)

**Comment by larspetrus** [comment]
I can't stay away from a design discussion...

1. It would make sense to take the delegate info out of the `users` table. Aside from cleaning up the `User` class, a separate `delegate_terms` table can easily keep delegate history by adding `started_at` and `ended_at` columns. But maybe this is superseded by making the whole delegate thing into teams.

2. Let me expand on your member "type" idea:

So we need to keep track of what kind of delegate of the delegate team members are. We already keep track of which team members are team leaders. A [very simple design](http://www.agilenutshell.com/simplest_thing) for this would be a text field used as "tags". Perhaps called `membership_status`. If someone is a team leader, `membership_status` = "team_leader". If they're a senior delegate it's "senior_delegate". If both, it's "senior_delegate team_leader". You'd need a few simple and bulletproof methods on `TeamMember` to set/unset/read tags. If you want to track membership history, each change spawns a new row.

This scheme can handle any kind of "boolean" membership properties you want to keep track of within a constant DB schema.

Adding "candidate" status to any team would be simple. The region could maybe be tags like "africa_region", but that's a stretch.

The `senior_delegate_id` sounds like an entirely different problem... So each non senior delegate has a senior delegate that is their superior in some sense? For a region? It does sound like it can be modeled as regional delegate teams with the senior as team leader. In that model, each delegate would be in the world wide delegate team, _and_ a regional team. Works logically, but I don't know how great it is.

**Comment by jfly** [comment]
@larspetrus, in your proposal, is it possible to know what valid tags are for a given team? That's something I believe we'd get with @pingskills's proposed `member_types` table (although we'd need a UI for changing the set of member types for a given team).

The more I think about it, the more I like the idea of one delegate team per region with each team member having a member type/tag. In order to know if someone is a delegate, we could just look for teams whose friendly ids end in `_delegates`?

**Comment by larspetrus** [comment]
What tags are valid for a given team type would be handled in the Ruby code, not the schema. Avoiding the pain of maintaining lists like that in the schema is the main motivation behind my proposal.

I think an explicit team type column in the `teams` table is the right way to recognize delegate teams, and also how you'd be able to handle the specifics of other types of teams.

**Comment by jfly** [comment]
I like the simplicity of storing the valid tags for teams in our code, rather than the database.

Can you elaborate on this team type column? What do you mean by "specifics of other types of teams"?

**Comment by pingskills** [comment]
I guess there are lots of ways to approach this. I personally prefer to have the lists in the database so no code needs to be changed if you want to add a new member type. You can also add referential integrity in the database which I like (not everyone agrees though). You can also index the `member_type_id` column to make queries faster if you want to select only certain team member types. Otherwise you need to parse the `tags` column in the code.

If you create a separate team for each region then you probably don't need the `senior_team_member_id` and can keep the existing `team_leader` flag to designate who is the "team leader".

**Comment by jfly** [comment]
I like all of the ideas I'm hearing here, so whoever chooses to implement this can make the executive decision.

I agree that the senior_delegate_id field can go if we create teams per region :) I do think that if we create some type of tag/type per user, it might be worth looking into removing the team_leader column.

**Comment by larspetrus** [comment]
_> What do you mean by "specifics of other types of teams"?_

There is a set of rules for how the delegate teams would work, for example. They would - I assume - have to be implemented as Ruby code.

Assuming a structure with a number of regional delegate teams, headed by a the senior delegate of the region, here are some things it needs to do:

- Someone (X) becomes a delegate for the first time: 
  - X gets put in one of the regional delegate teams, with one of the four delegate types, like `candidate_delegate`.
- X gets promoted to regular `delegate`
  - The code understands that means X is no longer a `candidate_delegate`
- X moves from one region to another
  - The code knows to remove X from region 1 when adding to region 2
- Find the senior delegate for X
  - Look up X's regional delegate team, and return whoever is `senior_delegate` there.
- X becomes a senior delegate
  - Whatever rules governs this needs to be implemented.

I imagine this would be in a Model class that does a lot of `Team.where(type: :delegate)` queries.

---

Or were you thinking this would all be handled manually?

---

Maybe this is the only case where we need special code for a team type. Having a `candidate` status in the software team could be managed by just having a list of allowable tags for that team.

But note that just a list of valid tags doesn't get you very far in the delegate case. If that's the only constraint, someone can be `candidate_delegate`, `delegate`, `senior_delegate`, and `board_member` in every region on earth. Using data structures and functions of Ruby makes implementing stuff much easier.

**Comment by viroulep** [comment]
Here is another use case for this:
I just noticed there was some competitions that I delegated but where I was not in the delegate field.

@SAuroux fixed it manually, but here is the internal note he wrote:

> Internal note: I was not able to just make the changes over the website interface which wouldn't allow me to save because Clément is no longer a delegate. So I simply set Philippe and myself as delegates for the competitions, then replaced my user-id with Clément's user-id in the competition_delegates table in the database, which was by far easier and faster than addint new rows to the database manually. :)

Looks like a good scenario where we'd like to know that Clément was indeed a delegate at that time :)

**Comment by pingskills** [comment]
Once the competition tabs have been pushed live, I'll put these changes up on staging for people to have a play with. They do allow you to keep track of delegates history.

**Comment by ronaldmansveld** [comment]
@jfly I see a lot of commits for this ticket, but I don't see any merged PR's. Does this mean that the issue was never resolved, and should stay open?

**Comment by jfly** [comment]
@pingskills put together a PR implementing this, and we decided not to merge it up. This gets tricky for delegates because we keep shifting around the delegate "teams".

I'm going to close this for now. Teams are useful if you want to have historical information about when someone was on a team, but we mostly get that for delegates just by looking at the competitions they've delegated.

**Comment by jfly** [comment]
> Motions only speak of real dates for some things (like promotions), and sometimes first and last delegated competition dates can be very far from appointment and demotion dates

Can we just change the motions? This alone doesn't feel like a compelling reason to invest the engineering effort.

**Comment by AlbertoPdRF** [comment]
> Can we just change the motions? This alone doesn't feel like a compelling reason to invest the engineering effort.

We could change the Motions indeed, but I still think that what we should aim for is to have the real dates on our database instead of changing the Motions due to a current software restriction.

We have also talked about storing these Delegate status changes dates on our database for historical reasons, and I honestly think that for these historical reasons alone this change is worth it.

Apart from that, I think it happened a few times already that the way we currently manage Delegates has hindered/prevented other possible developments.

For these reasons I think this is a problem we should tackle some day, and that's why I would prefer the issue not to be closed.
