### ISSUE TITLE
Issue with Due Calculator after announcment

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6807]
**Describe the bug**
The Due Calculator fails at some point after the competition has been announced:
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/11577241/161468890-333f476a-241a-4d7a-84ff-07240ab6cdfc.png">

**Expected behavior**
The dues should still be calculated based on what is currently filled in.

**Comment by gregorbg** [comment]
Can you verify whether this has been fixed by https://github.com/thewca/worldcubeassociation.org/pull/6829?

**Comment by Jambrose777** [comment]
LGTM, I now get the correct due amount instead of the error.
