### ISSUE TITLE
Issue with selecting which registrations to approve

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/worldcubeassociation.org#6810]
**Describe the Bug**
When an organizer or Delegate approves a registration but there is lag for several seconds between when the 
"Approve" button is clicked and the registration is approved, registrations that were selected after clicking the "Approve" button also get approved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to to a registration page that you have access to (fill in *{competition_id}* in the URL): https://www.worldcubeassociation.org/competitions/{competition_id}/edit/registrations
2. Select a registration and click "Approve"
3. During the delay (if there is a delay), select another registration

Result: Both registrations get approved instead of just the first one.

**Expected Behaviour**
Only registrations selected before clicking "Approve" should get approved. Furthermore, registrations should not be selectable during the time between when "Approve" is clicked and the approval is completed.

**Desktop (please complete the following information):**
 - OS: macOS Monterey version 12.3.1
 - Browser: Chrome version 100.0.4896.75

**Comment by JonEsparaz** [comment]
I recently encountered the same bug, but with the delete button.
