### ISSUE TITLE
Registration form: Clarify event selectability

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#6811]
Following up on a feedback I received today by a parent, who failed at first to fill the registration form for a competition:

The event selection buttons are apparently not clearly perceived as functional buttons. I also remember vaguely to have heard the same also by other people in the past. 

Maybe an additional hint text in the line of "(please select)" or "(please choose)" would help to clarify this.

**Comment by revers3ntropy** [comment]
I am working on this
