### ISSUE TITLE
Waiting list limit

### ISSUE THREAD

**Issue by AlexandreOndet** [thewca/worldcubeassociation.org#6818]
**The problem:**
As an organizer right now, sometimes you have a competition where you know the number of spots is low and you will very likely have a large amount of people who will try to register. And if the competition have registrations fees you will need to reimburse everybody who tried to register and was on the waiting list when the registrations closes. The problem with that system is that it gives hope to people that have absolutely no chance to have a spot (for example the competition I'm organizing at the moment is having 51 people on waiting list and the 50 spots are already filled) and also that for every competitor that registers after something like the 10th on waiting list the organizer is just going to pay stripe fees to reimburse them for no reason. This is a serious problem when the waiting list gets way too long because the fees can become so big that it will eventually become bigger than the income - due.

**My solution:**
I think a solution for that problem that could be not to hard to implement would be to add a setting into the competition administration tab to have a maximum size of the waiting list. That way, organizers can avoid people paying to be on waiting list when they have absolutely no chance to get in and the competitor car easily see that it is full because they  will no longer be able to register and see a message like "the waiting list is full, you can't register for the moment".

**Other ideas:**
As the problem is complex there is probably other things that could be done to solve it but I propose this solution because I think it's doable without changing the registration process at all. Other ideas could be to let organizer edit the registration period at any time, or have a button to close it instantly. But I like the waiting list size limit better as it's something automatic and easier to understand and use for both sides.

**Comment by KitClement** [comment]
A semantic issue, but I think what you truly want is a limit on the waiting list and accepted competitors together. As if you set the waiting list size to 75 for a competition with limit 50 and start accepting competitors, you could take a total of 125 payments as registrations are accepted, but if you set it to 25 for a competition with limit 50, you might have registration close before you have even taken enough competitors to reach the limit. Setting a limit of 75 on both of these lists combined would be more appropriate. 

For competitions that allow registration edits, there could be some strange behaviors that occur when competitors delete their registrations that would have to be thought through. For example, if the competition is full and a competitor deletes their registration, that would open one spot and thus reopen registration for the first person to see that it opens, only for it to close again. This is probably not a desired behavior here.

**Comment by AlexandreOndet** [comment]
Yes you're definitely right, I was thinking about that once the comp is full but we should definitely add the competitor limit to that as you explained.

For the registrations edit part, I would not be too shocked by the case you describe but I think it would probably be better just to keep them closed and warn the organizers when they choose the limit before submitting the comp if the registrations edit are enabled.

**Comment by EdHollingdale** [comment]
I'm not sure a website solution is necessary for this. It is simple enough to email WCAT and ask them to close registration early once the waiting list is already ~30%+ of the competitor limit. This also gets around the issue that Kit mentioned around registrations being deleted.

**Comment by KitClement** [comment]
Often, registrations can come in fast enough to go far beyond what you would expect or can handle, and WCAT does not always respond in a timely manner to these requests, meaning you can take far more payments for the competition than you would like. Additionally, sometimes you might just set an alarm for the wrong time and accidentally take a nap during your initial registration period (guilty). Having a way to cap this is nice for these scenarios so that we don't have to rely on WCAT or the org team to be diligent.

**Comment by EdHollingdale** [comment]
I guess I hadn't thought about the situation where you have the competition fill and then fill basically again almost instantly - I guess I'd say in this case you should have organised a series comp 😛. Agree that it can be frustrating if WCAT take 3 days to actually close registration from Delegates emailing them...

However to actually implement this suggestion there would need to be a considerable update to the current registrations flow on the website (i.e. it will need to be able to distinguish between just "pending" registrations and people on the "true" waiting list, count the number on the waiting list, compare against the waiting list cap, and then close registration but not re-open it). Being realistic I think there are bigger issues with the website and limited resources, and this is ultimately a small issue caused  by huge demand for competitions in some regions with stupidly low times for competitions to fill up.

**Comment by AlexandreOndet** [comment]
Yes I really like your solution too @viroulep. The fact that it's way easier to implement is a considerable benefit in my opinion.

**Comment by AlexandreOndet** [comment]
@gregorbg to a certain level I agree with you, but what I think is that realistically speaking if we want to have a solution soon Philippe's solution is better. Right now as an organiser you can't do anything by yourself, you can just email the WCAT, that solution still gives the ability to organizers to do something about the situation. I think you're right saying that it may not be enough if the number of people is way too big but as it need a lot more work to implement, I think having the other solution (at least as a first step) would be better.
