### ISSUE TITLE
Update Delegate Status at upcoming competitions after promotions

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6892]
**Is your feature request related to a problem? Please describe.**
When updating A Delegate status from Trainee Delegate to Junior Delegate, for that Delegate's upcoming Competitions they are still listed under trainee Delegates.

**Describe the solution you'd like**
Whenever the update is made, their upcoming competitions should be updated to update which Delegate role they are for the competition.

**Comment by viroulep** [comment]
For anyone willing to look into this, I believe implementing something in an `after_save` callback would be appropriate; something like that:
```ruby
  after_save :update_trainee
  private def update_trainee
    if saved_change_to_delegate_status? && delegate_status_before_last_save == "trainee_delegate"
      if delegate_status.present?
        # the user is now some other delegate_status, update the relevant competitions
      else
        # the user is no longer any type of delegate, update the relevant competitions
      end
    end
  end
```

(can be inspired by [this](https://github.com/thewca/worldcubeassociation.org/blob/78afaaf5aa7a51f49e0585ac3b6f4a5f83f5e540/WcaOnRails/app/models/user.rb#L451) method)
