### ISSUE TITLE
Add WAT as a WCA Team

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6907]
_references the email thread "New WCA Teams"_

## Issue summary

A hidden team needs to be created for the WCA Archive Team ("WAT").

Given that WAT has an active membership, quick implementation has been requested by the board.

## Implementation notes from the thread:
> WAT are currently using [archive@worldcubeassociation.org](mailto:archive@worldcubeassociation.org) ([wat@worldcubeassociation.org](mailto:wat@worldcubeassociation.org)) [as their email group]
> @WST Please take a look at https://github.com/thewca/worldcubeassociation.org/pull/6044 and https://github.com/thewca/worldcubeassociation.org/pull/4437 for reference on how to create new teams. Feel free to open a similar PR for WAT and WSOT (hidden team for now), but note that some of the changes in the WEAT PR #4437 like email CCs will not be necessary for the new two teams.
> Adding members can be done by the upcoming Team Leaders, this is nothing we have to worry about. It should not be done as part of the PR.
> You don't have to worry about creating the actual email group addresses, the Board (or their Executive Assistants) will handle that. **You can just write the email addresses as strings in the code and assume that they "magically exist".**

**Comment by dunkOnIT** [comment]
@gregorbg I believe I have captured the essential elements of the email thread, but please advise if there is anything I missed or was incorrect on.

**Comment by MibettyMeanie** [comment]
https://github.com/thewca/worldcubeassociation.org/pull/6915

**Comment by gregorbg** [comment]
Closing as per the PR that Meenakshi mentioned.
