### ISSUE TITLE
Need to compute auxiliary data after moving server

### ISSUE THREAD

**Issue by coder13** [thewca/worldcubeassociation.org#693]
This thing:
https://www.worldcubeassociation.org/results/admin/compute_auxiliary_data.php

**Comment by jfly** [comment]
This bug is currently documented in https://github.com/cubing/worldcubeassociation.org/wiki/Spinning-up-a-new-server-part-1. Once this bug is fixed, we can update the wiki.

**Comment by jfly** [comment]
@jonatanklosko, is this still an issue when moving servers now that the cached database php file no longer exists thanks to your work in #1591?

**Comment by jonatanklosko** [comment]
I think you're right! The auxiliary tables are obviously on our mysql server and removing cache files is irrelevant here (that's what the script has been doing since I removed the cached db).

**Comment by jfly** [comment]
Awesome! Could you optimistically update our wiki (see the second comment in this thread) and close this issue?

Btw, this reminds me that https://github.com/jfly/worldcubeassociation.org/blob/4a45b4a093c365c46ba7f5b8ea2a24baddaa4c77/chef/site-cookbooks/wca/recipes/cronjobs.rb#L63 exists (to try to run this script once when the server starts up). Don't forget to remove that as part of #1602 (or whenver you decide to delete the PHP code).

**Comment by jonatanklosko** [comment]
Wiki updated, thanks for pointing out this file =)
