### ISSUE TITLE
Send reminder to delegates ~24 hours before report / results deadline

### ISSUE THREAD

**Issue by DanielWallin333** [thewca/worldcubeassociation.org#6936]
Hi all! First Github issue, so I hope I got everything right.

Just having missed my report deadline (mainly because I got sick during most of the last week) got me thinking about the fact that no deadline warnings are issued to delegates when the deadline is approaching. I know it is the delegate´s responsibility to get it in on time regardless, but all delegates are just volunteers trying their best to serve their local communities, so a friendly reminder in case they just forgot will surely be beneficial to everyone? It should make our lives a bit easier, and could also reduce the workload for assistants and seniors. 

I propose a 24 hour reminder, and I think that it could be implemented for results submissions at the same time (even though I feel like getting reports in on time might be a bigger issue).

**Comment by dunkOnIT** [comment]
Very reasonable suggestion, thanks very much Daniel! As a newly-appointed Trainee, I can definitely see this being useful :P 

Our capacity is quite constrained, but I am adding it to our backlog and hopefully it can get attention in due course.

**Comment by FinnIckler** [comment]
iirc it's ruby using ActionMailer with the AWS Simple Email Service backend.

**Comment by gregorbg** [comment]
It would involve writing a new cronjob or (preferrably!!) update the existing "Nag" cronjob to also include a reminder email. Relatively straight-forward and good second, if not good first issue.
