### ISSUE TITLE
Delegate report submission nag email

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#696]
Automatically send nag emails for delegates who have not submitted their reports. Should we cc the board immediately or only after a while?

Check out how I implemented the results submission nag email #682.

Don't forget! When we deploy this feature, we obviously don't want to send out 3000 emails nagging delegates about their past competitions without reports.

**Comment by pedrosino** [comment]
I think we should cc Board right away, like Results is cc-ed on those emails.

**Comment by viroulep** [comment]
We've recently discussed this again, it seems like something very useful to implement.

I don't have time to work on it for the upcoming ~2 weeks, but if no one has done it by then I'll assign it to myself.
