### ISSUE TITLE
Combined Third Rounds will have the wrong name

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6968]
**Describe the bug**
A combined third round (roundType = g) will have the name 'Third Round' instead of 'Semi Final' that non combined third rounds will have.

**Expected behavior**
These should show up as 'Semi Final' Instead to be consistent.

**Additional context**
There is no such case yet, but is a small easy fix that just needs a migration.

**Comment by alexanderc360** [comment]
#7610

**Comment by alexanderc360** [comment]
Hey Jacob, this should be resolved. I submitted pull request #7610
