### ISSUE TITLE
View user's ongoing competitions from WCA API

### ISSUE THREAD

**Issue by coder13** [thewca/worldcubeassociation.org#6970]
https://github.com/thewca/worldcubeassociation.org/blob/6e253ed58528223c789897d24909b1fbafba69fd/WcaOnRails/app/controllers/api/v0/api_controller.rb#L124

Right now we can query upcoming competitions but not their ongoing ones.

This would be super useful for applications ([such as mine](https://competition-groups.surge.sh/)) which show a user's groups for an upcoming competitions and it'd be nice to show the competition happening the same day.

I can likely send in a fix. This seems like adding something to the competition model and adding a query param?

**Comment by coder13** [comment]
> One possible solution would be to simply add another query param completely independent (but structurally similar to) the existing upcoming_competitions, along the lines of ongoing competitions.

This was the initial solution I was thinking about.

Is there a reason we might not want to do that?

**Comment by gregorbg** [comment]
> Is there a reason we might not want to do that?

I can't think of any right now :)
