### ISSUE TITLE
Create a "unique result per person" validator

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#6985]
While working on #6360 we realized that there is no validation making sure that a competitor doesn't have more than one result in the same round.

It should be fairly easy to add an extra validator [here](https://github.com/thewca/worldcubeassociation.org/tree/master/WcaOnRails/lib/results_validators), and this is purely ruby.

**Comment by gregorbg** [comment]
Random thought while going through code review: How does this ticket relate to your changes in the `result` model at https://github.com/thewca/worldcubeassociation.org/pull/6360/files#diff-794c87348828ee3618ac3be2058a42a0a2203e313475b1dbb357e624db435fabR24-R35?

**Comment by viroulep** [comment]
Ah right I've actually adjusted a bit the conditions which trigger the validation to fix this issue!
