### ISSUE TITLE
`editSchedule` component refactor

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7020]
The task on this is to (and I quote) "clean up the spaghetti react code that makes up the editEvents and editSchedule components" :D

**Comment by coder13** [comment]
Should this rather be 2 issues for granularity?

**Comment by dunkOnIT** [comment]
@coder13 just wanted to check whether the refactors of `editEvents` and `editSchedule` are related enough that you think they belong in one issue?
