### ISSUE TITLE
Automatically close registration

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#7029]
**Is your feature request related to a problem? Please describe.**
Allowing registration to stay open once full costs the organizer money, and gives competitors false hope. Delegates can email WCAT to close registration, but this is a manual step that depends on the organizers noticing the registration is way over-full, the delegate emailing WCAT, and WCAT responding to the email. By having a limit, there is an upper bound on the stripe fees expense, which will help with competition budgeting.

**Describe the solution you'd like**
Add an option to the competition form "Maximum waitlist size". When the total number of paid competitors is at least competitor_limit + maximum_waitlist_size, close registration automatically. The delegate can always email WCAT to ask them to re-open registration if the waitlist gets low on competitors.

**Comment by EdHollingdale** [comment]
I think this is a duplicate of #6818

**Comment by timreyn** [comment]
Thanks @EdHollingdale ! Didn't see that issue. I'll close this one.
