### ISSUE TITLE
Add registration eligibility to competitions on the competition list

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7036]
From "Fwd: [WCA Website] General Competition Comment by Joshua Wilbourn on 25 Apr 2022 at 12:40":

> Hello! I just has a small suggestion for the WCA Competition list website. If an icon can be added that shows registration is either open, closed, or upcoming before needing to click on it, that would be awesome! I tend to scour the website on occasion so that I can find a competition in my area only sometimes to be disappointed to find that it's already closed. The addition of a quick visual identifier would be a great benefit to potential competitors. Thanks!

From "Fwd: [WCA Website] General Competition Comment by Srisaran on 04 Jul 2022 at 18:24":
>  Kindly show registration FULL or OPEN information. Even if close date has passed alert. 

From these we can infer a few statuses:
- Announced (registration not yet open)
- Open (competitors may now register)
- Full (competitor limit reached, waiting list now in effect)
- Closed (competition is no longer taking registrations)

The task for this issue would be to hook into the existing state management for competitions (likely a superset of what I've described above) and make that represented on the [list of competitions ](https://www.worldcubeassociation.org/competitions) and on the competition page itself.

**Comment by simonkellly** [comment]
Hello!

I might have a go at adding this feature if nobody else is working on it.

**Comment by dunkOnIT** [comment]
Hey Simon! Thanks so much for being willing to help - no one else has put their hand up for this yet, so it's all yours if you'd like it. 

A starting point might be to just get a dev environment working on your machine, following the instructions in the README until you get stuck. Our documentation is quite scattered, so feel free to reach out if (when?) you run into roadblocks.

@gregorbg would you be able to provide (or assign someone to provide) a basic overview of what addressing this issue will entail?

**Comment by simonkellly** [comment]
I have gotten a dev environment all set up so I'll jump right into it

**Comment by dunkOnIT** [comment]
Awesome! Assigned and in progress. Shout here if you need any input :D

**Comment by dunkOnIT** [comment]
Thanks again for working on this @simonkellly ! If there are any other issues you'd like to contribute to, please feel free to jump on them :D
