### ISSUE TITLE
"Application Instructions" in "Regional Organizations" page is displayed in HTML

### ISSUE THREAD

**Issue by BelbioK** [thewca/worldcubeassociation.org#7041]
**Describe the bug**
The link to the form is displayed in HTML.

**To Reproduce**
1. Go to [https://www.worldcubeassociation.org/organizations](https://www.worldcubeassociation.org/organizations)
2. Scroll down to the bottom of the page
3. See error

**Expected behavior**
You should see the link to the form

**Screenshots**
![image](https://user-images.githubusercontent.com/109048458/178169159-d302b151-9173-47e0-8694-168f59c6164f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera GX and Firefox

**Comment by dunkOnIT** [comment]
Thanks for raising this! @gregorbg am I correct that this should be resolved once @notrichardpeng PR with the React Regional Orgs is merged? 

Or if that has already happened, I would assume we need to fix this :P

**Comment by gregorbg** [comment]
It has actually been merged, and this is a follow-up bug from the React migration. We need to fix this.

**Comment by notrichardpeng** [comment]
oops this wasn't spotted, I will try to get this fixed soon

**Comment by gregorbg** [comment]
Fixed per #7042
