### ISSUE TITLE
Implement Instance Scheduler to upgrade WCA Live servers on weekends

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7044]
Per "Suggested WCA Live Infrastructure Plan: July 2022", I believe we can go ahead with implementing an automated upgrade/downgrade of the WCA Live AWS instance for weekends.

We will use this service: https://aws.amazon.com/solutions/implementations/instance-scheduler/

And follow this schedule:
* Upgrade: 23:59 UTC on Friday
* Downgrade: 06:00 UTC on Monday (this gives time for PST competitions running late to wind down)

**Comment by dunkOnIT** [comment]
@FinnIckler assigning this to you as you seem best-placed to implement. Please advise if you don't have capacity or would like to recommend someone else.

Assuming this isn't very complex to set up, **I think we should consider it our highest infrastructure-related priority at present**, given that it holds significant benefit to users for what I'm assuming is relatively little development time*. 

_*again, please advise if I'm wrong on how much effort this would take_

@gregorbg please advise if you disagree with prioritisation

**Comment by FinnIckler** [comment]
I can definitely pick this up, but I don't think I will be able to do this before Euros because I am leaving to go there soon :P. I think for Euros we should do it manually one last time anyway, because it's a Thursday-Sunday comp.

**Comment by FinnIckler** [comment]
Looking at the schedule there are very few second rounds on Thursday and Friday so data entry being a bit delayed due to load wouldn't be an issue. I guess we can do it spontaneously if we notice it gets worse

**Comment by FinnIckler** [comment]
superseeded in favour of https://github.com/thewca/wca-live/pull/140
