### ISSUE TITLE
Rankings of >100 competitors still accessible

### ISSUE THREAD

**Issue by zekemackay06** [thewca/worldcubeassociation.org#7049]
It is still possible to view rankings of any number of competitors, despite them intending to be disabled. To do so, one can change the URL of the ranking site to display as many competitors as they would like.

All that needs to be done to access rankings of more people is to click on the "100 Persons" button in the rankings page, which will add "?show=100+persons" to the URL, then change the URL of the rankings page (e.g. https://www.worldcubeassociation.org/results/rankings/333/single?show=100+persons) to one with a higher count of persons (e.g. https://www.worldcubeassociation.org/results/rankings/333/single?show=500+persons). The only number I have found to not work is 1,000. 

Screenshot of the rankings page displaying ranks > 100:
![image](https://user-images.githubusercontent.com/42594475/179118668-24a5a266-6006-4f06-ab53-2005335e2612.png)

**Comment by gregorbg** [comment]
Thank you for bringing this to our attention! The filter has now been fixed and even manually editing the URL to values like `9000` will still load 100 results internally.
