### ISSUE TITLE
Add championship_type to WFC export

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#7053]
WCA Dues policy exempts World and Continental Championships from paying Dues - currently this requires the WFC member issuing Dues to notice this and manually override the Dues amount. If the championship_type column was joined on using competition_id in the WFC export we would be able to automate this in the Dues calculation spreadsheets. 

WST: probably good to mark as "good first issue" or similar, as someone can leverage the updates from #6497

**Comment by JonEsparaz** [comment]
@dunkOnIT I'd like to start contributing to this repo. This seems like a good intro - can I please be assigned this ticket?

**Comment by dunkOnIT** [comment]
Hey @JonEsparaz , thanks so much for being willing to contribute! Looks like you know your way around an editor - you'll naturally want to get the dev environment working by following the "Setup" section of `README.md`. If you have any issues there, or would like any further technical direction on how to tackle this issue, please feel free to reach out!

@gregorbg just pinging you for awareness that this has been assigned

**Comment by gregorbg** [comment]
This feature has been deployed. Shoutout to @JonEsparaz for his first contribution!

**Comment by dunkOnIT** [comment]
A second note of thanks @JonEsparaz! Please reach out if you'd like any guidance/suggestions on a second issue to work on when/if you have the time + interest :D
