### ISSUE TITLE
Prevent delegates from adding qualification times after a competition is announced

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7054]
This refers to an internal discussion happening in WST which frankly, I don't understand the context or specifics of. 

@Jambrose777 has indicated this is high-priority - feel free to add any detail you feel is necessary here, or advise if this is already being tracked in a separate issue/PR. 

@gregorbg if this isn't actively being worked on already, is there someone we can assign?

**Comment by gregorbg** [comment]
This will be addressed as part of https://github.com/thewca/worldcubeassociation.org/pull/7050

**Comment by gregorbg** [comment]
Fixed as part of #7050
