### ISSUE TITLE
Under "My competitions" some of the Past Competitions are obstructed

### ISSUE THREAD

**Issue by ticklemepierce** [thewca/worldcubeassociation.org#7068]
**Describe the bug**

The  headers  `Bookmarked competitions` table stays in place when `Past competitions` is expanded, thus covering up some of the rows in the `Past competitions` table.

**To Reproduce**
1. Bookmark any upcoming competition
2. Go to `/competitions/mine` (as long as you are a user with past competitions)
3.  Click `Past competitions` to expand that table

**Expected behavior**
I should be able to see all my past competitions and the header for `Bookmarked competitions` should move down the page along with the rest of the elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/8229937/181116181-94e0c926-cf0b-4629-9a8c-6718aea9ff8b.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: 1.41 (Chromium version 103)

**Smartphone (please complete the following information):**
 - Device: Pixel 4xl
 - OS: Android 13
 - Browser: Chrome
 - Version: 103
 
**Additional context**
Add any other context (for instance the language you're using the site in) about the problem here.

**Comment by dunkOnIT** [comment]
Can confirm this happens on Firefox as well, although scrolling can resolve it. This would be a great fix to have from a quality of life perspective, so if anyone wants to pick it up as part of their contributions / as a first issue please do!

**Comment by revers3ntropy** [comment]
I am working on this
