### ISSUE TITLE
Competition Selector (in Contact Form) Fails When competitionId is Set

### ISSUE THREAD

**Issue by mitchell-toth** [thewca/worldcubeassociation.org#7080]
**Describe the bug**
The competition selector on the [WCA Contact Form](https://www.worldcubeassociation.org/contact/website) exhibits faulty behavior when the `competitionId` query parameter is set in the URL.

- The desired competition appears briefly in the selector and then is removed from the list of possible options. 
- Moreover, searching by any first character contained in the value of `competitionId` produces an empty result set. For example, if the URL contains `?competitionId=MilwaukeeFirst2022`, then searching by any of ["m", "i", "l", "w", "a", "u", "k", "e", "f", "r", "s", "t", "2", "0"] produces no results.
- Multiple uncaught "Unrecognized class undefined" errors appear in the browser console.

**To Reproduce**

1. Navigate to the [WCA Contact Form](https://www.worldcubeassociation.org/contact/website?competitionId=MilwaukeeFirst2022) page with the `competitionId` query parameter set to a non-empty value. This occurs, for instance, when clicking the "Organization team" contact link from the "Info" tab of any competition page.

2. Choose contact option "Contact the Organizers of a Specific Competition (please select below)". This is auto-selected whenever `competitionId` is present.

3. Attempt to type a competition name, such as the name of the competition whose page you routed from.

**Expected behavior**
The competition selector automatically selects the competition defined by the `competitionId` query parameter string. Alternatively, searching by the desired competition name would filter as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/55897330/182041252-f21af5b6-ec69-4bd6-8a85-f33dabb662fa.png)
![image](https://user-images.githubusercontent.com/55897330/182041560-1736d91c-733c-43ec-86e5-2670606a1dd8.png)
![image](https://user-images.githubusercontent.com/55897330/182041041-93c989ff-6ecd-4f48-a0e2-2ca68328d95c.png)

**Desktop:**
 - OS: Windows 10 (PC)
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by dunkOnIT** [comment]
@gregorbg could this be related to the changes you made to competition links in Contact Forms recently?

**Comment by gregorbg** [comment]
Sorry never got back to your comment. Yes, it is related and I hope it's fixed with a less sledgehammer-y approach now.
