### ISSUE TITLE
Icons for removed events

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#714]
![image](https://cloud.githubusercontent.com/assets/6166412/15950647/888e3e3e-2e65-11e6-9c53-fe1dae8f445d.png)

![image](https://cloud.githubusercontent.com/assets/6166412/15950657/a3420666-2e65-11e6-9c5b-e8f1f9d51f64.png)

I know that there isn't actually an icon for magic, but because of this, it makes this part of the results pages look a bit unpolished.  At least there's an easy fix for MultiBLD Old style: 

![image](https://cloud.githubusercontent.com/assets/6166412/15950663/bba5721a-2e65-11e6-8139-5ea1dc0eb8d1.png)

**Comment by keemy** [comment]
Oh, I can try to make icons for the magics.

**Comment by jfly** [comment]
Related: https://github.com/cubing/icons/issues/8.

**Comment by keemy** [comment]
https://github.com/cubing/icons/pull/22 adds some simple magics icons if you want to remove css override for them lol.

**Comment by keemy** [comment]
https://github.com/cubing/icons/pull/23 finishes mbo and closes https://github.com/cubing/icons/issues/8 so should be able to remove the override now and all will work.

**Comment by jfly** [comment]
This has been fixed and deployed. Check out https://www.worldcubeassociation.org/competitions/USOpen2008:

![image](https://cloud.githubusercontent.com/assets/277474/18853547/8ee5b9f2-83fa-11e6-8eb0-0e0d397b8b82.png)
