### ISSUE TITLE
Event icons in "manage events" overlapping with event names

### ISSUE THREAD

**Issue by beranka** [thewca/worldcubeassociation.org#7152]
**Describe the bug**
In competitions' "manage events" tab (which is in the left menu, when viewing as an organizer) are the icons of the events slightly overlapping with their names.

**To Reproduce**
1. Login as an organizer of any competition
2. Go to website of that competition and click on Edit > Manage events on the left side
3. The described overlapping should be visible

**Expected behavior**
The icons shouldn't be overlapping with the text, there should be small space between them.

**Screenshots**
[Screenshot_2022-08-19_17-16-32](https://user-images.githubusercontent.com/74115568/185651282-9d05043f-4e98-4d85-9549-c849a6164262.png)

**Desktop:**
 - OS: EndeavourOS Linux x86_64 
 - Browser and version: Chromium 104, Firefox 103

**Smartphone:**
 - Device: iPhone 8
 - OS: iOS 15.6.1
 - Browser: Safari
 - Version: 15

**Additional context**
Happens to me with unconfirmed and finished competitions, on both desktop and mobile phone and it doesn't matter if I have the website in English or Czech.

**Comment by dunkOnIT** [comment]
We can probably expect transitioning to React to solve this.
