### ISSUE TITLE
Do not allow delegates to submit their delegate report until results are posted

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#720]
It's cool that we automatically get the number from the results, but in the event that results are not posted yet, we're stuck with "Competitors Unknown, results are not posted yet. ", which is kinda annoying.

~Two solutions:~
~- [ ] allow delegates to fill this if the results are not up~
~- [ ] once results are posted, come back and change this field~

As per the discussion below, we want to change things so it's not possible to submit the delegate report for a competition until the results have been posted.

**Comment by jfly** [comment]
I think you're under the mistaken assumption that there's actually a field in the delegate_reports table for this?

**Comment by pedrosino** [comment]
Ah, I am :(
Well, in that case I feel there should be a field for that. I remember we also discussed having the number of newcomers. As I said above, updating this once results are posted should be enough to keep information on the website correct. The discussion would be forever impaired/hindered, but we can live with that.

**Comment by jfly** [comment]
I personally don't like the idea of new fields for each of these things. What I would support is requiring delegates to upload results to the website *before* they can lost their delegate report. They wouldn't have to wait for the results team to post the results, but that would let us compute these numbers for them.

**Comment by pedrosino** [comment]
Ah, now that you say, it's not mandatory to have an actual field. It can just be updated on the report's text.
As of now, delegates don't upload results to the website (and given recent history, I'm not sure it's a good idea). I don't have a problem with allowing reports to be sent before results, since you may want to write the report when information is still fresh, while checking results can have other hiccups (missing DOBs, checking for newcomers, etc).
I'll try to take a look at the code for this and come up with a better proposal.

**Comment by jfly** [comment]
> Ah, now that you say, it's not mandatory to have an actual field. It can just be updated on the report's text.

I'm not sure what you mean by this. Remember that we allow delegates to edit and save their report before posting them.

> As of now, delegates don't upload results to the website (and given recent history, I'm not sure it's a good idea)

We trust them to email a json file to results@, I'm just suggesting they upload the json file to the website instead of emailing them. I'm sure there will be some unexpected pain at first, but that always happens when you change things.

> I don't have a problem with allowing reports to be sent before results

I'm trying to make a distinction between a delegate *uploading* results and a results team member *posting* results. I suggest that we don't let a delegate post their delegate report until after they have uploaded their results (so we can compute the number of competitors).

> since you may want to write the report when information is still fresh, while checking results can have other hiccups (missing DOBs, checking for newcomers, etc).

For sure, that's why we let you work on your report before, during, and after your competition. Just because you've written a report doesn't mean you have to post it immediately. That said, this is mostly superceded by my last response distinguishing between uploading and posting results.

**Comment by pedrosino** [comment]
>> Ah, now that you say, it's not mandatory to have an actual field. It can just be updated on the report's text.

> I'm not sure what you mean by this. Remember that we allow delegates to edit and save their report before posting them.

Sorry, I meant "updated once results are posted (and after the report is posted)".

>> As of now, delegates don't upload results to the website (and given recent history, I'm not sure it's a good idea)

> We trust them to email a json file to results@, I'm just suggesting they upload the json file to the website instead of emailing them. I'm sure there will be some unexpected pain at first, but that always happens when you change things.

I know, but sometimes we have to ask them for a new json file...I'm not sure if this ever affected total number of competitors, but probably affected newcomers in some occasion.

>> I don't have a problem with allowing reports to be sent before results

> I'm trying to make a distinction between a delegate uploading results and a results team member posting results. I suggest that we don't let a delegate post their delegate report until after they have uploaded their results (so we can compute the number of competitors).

Ok, this sounds reasonable. The nagging about the report is not done yet, right? It would be more than necessary in case we don't allow posting the report before results.

>> since you may want to write the report when information is still fresh, while checking results can have other hiccups (missing DOBs, checking for newcomers, etc).

> For sure, that's why we let you work on your report before, during, and after your competition. Just because you've written a report doesn't mean you have to post it immediately. That said, this is mostly _*superseded*_ by my last response distinguishing between uploading and posting results.

**Comment by UnsolvedCypher** [comment]
Now that results are uploaded directly to the WCA website, it should be possible to require Delegates to do this upload before submitting the report so that the numbers can be computed properly.

**Comment by jfly** [comment]
I agree! @viroulep, sorry, I still have not caught up on your posting results work, but is this something that could make sense to do now?

**Comment by SAuroux** [comment]
It should be kept in mind that what the delegate uploads are just "temporary" results (pre-WRT), while the current number of competitors for competition reports is taken from final results (post-WRT). 

However, I can confirm that the number of competitors matches for >= 95% of these results and devitations of more than 1-2 people are extremely rare.

**Comment by timreyn** [comment]
Is it a big deal if the two numbers differ by 1-2?  I don't think it matters enough to be worth a parenthetical.

**Comment by viroulep** [comment]
I won't add anything to #3127 anymore, but I believe it would be quite simple, on the delegate report page, to look for inboxresults for the current competition if results are not posted yet :)

**Comment by AlbertoPdRF** [comment]
Based on @viroulep's last comment, I'm labeling this one as a good first issue.

We would still have the problem of Delegates submitting the Delegate Report before they upload the results though. However, to not allow this to happen, we should ask for others' opinions!

**Comment by EdHollingdale** [comment]
I think this is an important issue and is the reason I wait for results to be posted before submitting the report. The number of competitors provides a lot of context about the competition. I don't think it is unreasonable to have to submit results before submitting the report. After all, it could be during the results checking and submission process that new incidents are discovered.

**Comment by AlbertoPdRF** [comment]
@thewca/board would you agree with requiring the results for a competition to be uploaded before being able to submit the report?

**Comment by Epride** [comment]
I agree here, this also forces the Delegate to focus on results rather than report which is far more important IMO

**Comment by cubewhiz** [comment]
I'm fine with that. I don't feel strongly about it.

**Comment by Nanush7** [comment]
It happens that you need help, for example, with a provisional extra. Do you think it's better to post the results before the report and then you just request the change for that particular case?

**Comment by Jambrose777** [comment]
> It happens that you need help, for example, with a provisional extra. Do you think it's better to post the results before the report and then you just request the change for that particular case?

Yes that’s correct. The delegate should use their best judgement for which result to submit and based on the feedback submit any change requests as needed.

**Comment by gregorbg** [comment]
We now have https://github.com/thewca/worldcubeassociation.org/pull/6628 which provides a very real possibility of implementing this feature. What is the current consensus on this topic?

**Comment by KerrieJarman** [comment]
Wouldn't this be better to be achieved with procedures (or convention) rather than code?  Require delegates to not submit reports till results are posted. 

TBH I don't understand why delegates are finalising reports before submitting results.  Is it because they have actually submitted and the results are with the WRT? - if that is the case, surely the delegate can wait 12 hours or so for WRT to do their magic and add into the database?  Why can't they hold off sending the report till that point?   

End of the day though, this is a 6 year old issue, I think it is fine to go ahead.  Good to get it off the books - thanks @kr-matthews

**Comment by Jambrose777** [comment]
>  if that is the case, surely the delegate can wait 12 hours or so for WRT to do their magic and add into the database? Why can't they hold off sending the report till that point?

Disclaimer: I have not followed this discussion closely, nor do I really know why we need to implement this.

Sometimes Delegates treat the 1 week as a deadline opposed to getting materials in ASAP. Meaning we have Delegates submit results and report a few hours before they are due. WRT might not get to them before the time deadline and the Delegate would want to "save themselves" from getting a strike for submitting late.

**Comment by saranshgrover** [comment]
Thanks for starting the discussion, Board will discuss and get back to you. @kr-matthews to clarify - does the implementation stop delegates from submitting reports until the results are published, or until the results are submitted (and may be awaiting WRT approval)

**Comment by kr-matthews** [comment]
@saranshgrover Currently, the implementation only stops delegates from submitting reports until the results are **submitted**.

**Comment by saranshgrover** [comment]
Sounds good then - please feel free to move forward.
