### ISSUE TITLE
Search for organizers

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/worldcubeassociation.org#721]
Damian Bias has requested to have a page similar to [Persons Search](https://www.worldcubeassociation.org/persons?&search=) that also searches organizers

**Comment by jonatanklosko** [comment]
Maybe a check box `organizer` in the form would be sufficient?

**Comment by coder13** [comment]
Adding filtering options rather than another page sounds like a good idea. We could also add more filtering options later on.

**Comment by jonatanklosko** [comment]
Hmm, I wanted to push PR with this feature but after a quick check on the staging I realised that we cannot detect most organizers.
I decided to use `competition_organizers` table which seemed to be the appropriate way, but it doesn't contain *most* organizers. As an example see [Radom Open 2013](https://staging.worldcubeassociation.org/competitions/RadomOpen2013), there are 4 people in the contact field but there are no organizers at all.
I don't know when can we do in this case. Any thoughts here?

**Comment by pingskills** [comment]
I don't think we should try and use the contact field. I see 2 options:

1. Don't offer this feature
2. Use the `competition_organizers` and encourage competition creators to use it more often

**Comment by jonatanklosko** [comment]
@pingskills yeah I think there's no good way to detect all organizers and I don't want to make this feature and let only a few of them appear.
About the second point: I'm sure competition creators always fill this field, but `competition_organizers` table hasn't been there always, thus it contains a small part of all organizers.

**Comment by jfly** [comment]
I tried to remove the contact field with I first introduced the competition organizers join tables, and I was forced to add it back for reasons I still don't understand.

If we're planning to add a search for organizers, are we also planning to do a search on delegates?

**Comment by jonatanklosko** [comment]
@jfly so far it seems that adding search for organizers is impossible.

**Comment by jonatanklosko** [comment]
As en example see [Polish organizers](https://staging.worldcubeassociation.org/persons?region=Poland&search=&organizer=true&page=1) on the staging. Just a few are in the `competition_organizers` table.

**Comment by jfly** [comment]
That's fine by me. What about searching for delegates?

**Comment by jonatanklosko** [comment]
Do you really consider this fine? For me it's kinda unfair that most organizers won't see themselves here (showing 6 Polish organizers is almost like no one is displayed).
I'm not sure whether it makes sense to search for delegates here as we have dedicated page for them (even if it makes sense then it should wait for the PR with teams change).

**Comment by jfly** [comment]
I'd rather have every organizer put in the organizers table, but last time I tried, I found that people are apparently addicted to having a text box they can type anything into.

**Comment by pingskills** [comment]
@jfly I agree with that. I think if we didn't have the contact form it would make the organisers field more important. I don't know the reasons but from what I have heard so far it seems like a lot of organiser's don't have accounts on the website. But this would encourage them to create one, which is again what we want :)

**Comment by pedrosino** [comment]
Sometimes people want to put a phone number or whatever information on the contact field...

I was talking to Jonatan yesterday that I didn't see much utility on this search, but seemed easy enough to do. The problem is the competition_organizers table is fairly new, and unlike the competition_delegates, which we managed to fill almost 100%, organizer information is not well structured at all...

**Comment by jfly** [comment]
One problem is that some organizers prefer to list their organization team
instead of the individual organizers.

Another problem is that organizers want to be able to provide a single
email to contact the entire organization team at once, rather than giving
out their individual emails. Before we get rid of the contact field, we
need to provide a good solution for that.

**Comment by cubewhiz** [comment]
The [contact form](https://www.worldcubeassociation.org/contact/website) allows for sending emails to the organizers without displaying individual emails. Is that good enough? Perhaps the email links can be replaced with this method of contact anyway? I think I saw an issue on github suggesting that anyway.

**Comment by AlbertoPdRF** [comment]
@cubewhiz: I think the contact form isn't good enough in order to remove the contact field because of this:

> Another problem is that organizers want to be able to provide a single email to contact the entire organization team at once, rather than giving out their individual emails.

Also, as the `competition_organizers` table has now 6000+ rows, maybe we should re-consider adding support for the search originally suggested?

**Comment by dunkOnIT** [comment]
I think contacting organizers via the contact form / their defined contact email solves this problem // It isn't clear what need is being met here besides contacting organizers of a specific competition
