### ISSUE TITLE
Records-Page: Selecting regions "Europe"/"North America" show result for "World"

### ISSUE THREAD

**Issue by MichaelStockerVacos** [thewca/worldcubeassociation.org#7223]
When selecting the region "Europe" or "North America", depending on the other selections records shows are "World" records.  
Example:  
![grafik](https://user-images.githubusercontent.com/112937196/190168107-50d89bae-57aa-4b34-8439-87ca45fa33ee.png)  

Some few selections seem to work, I don't really see a pattern when it works:
![grafik](https://user-images.githubusercontent.com/112937196/190168705-9c5246ec-3530-4114-a72d-ac4a10240af5.png)

Edit:  
I tested it again today, now Europe works, but some other don't. It doesn't seem to be deterministic.

**Comment by gregorbg** [comment]
I hope this has been solved by https://github.com/thewca/worldcubeassociation.org/pull/7221
