### ISSUE TITLE
An issue while logging on WCA

### ISSUE THREAD

**Issue by itsmemidhuz123** [thewca/worldcubeassociation.org#7236]
Hey,  I just wanted to inform you that we are conducting a competition and registration has already started. But some of our competitors reported that they are unable to sign in to complete the registration process

Error: Message says username or WCA ID is invalid even if it's correct

Please note that, based on our knowledge we understood that the issue has been affected only on some accounts, kindly check into this and fix it at the earliest

Regards, Team mcubes

**Comment by dunkOnIT** [comment]
Hi @itsmemidhuz123 - sorry that we took so long to respond here, totally my fault.

Just wanted to check if this error got resolved, or was this still an error for the competitors?

**Comment by itsmemidhuz123** [comment]
Haven't checked after that, cos competition has ended already

Definitely open a thread if happens again

Regards, Midhun
