### ISSUE TITLE
Wrong regulation link about cumulative time limit on schedule view

### ISSUE THREAD

**Issue by Randomno** [thewca/worldcubeassociation.org#7275]
![image](https://user-images.githubusercontent.com/17330834/193892559-5cf65dff-f173-414d-a00b-80a9f5456047.png)

This guideline was changed in 2019. The most appropriate regulation to link to now would be A1a2:

> [A1a2](https://www.worldcubeassociation.org/regulations/#A1a2)) For events other than 3x3x3 Fewest Moves and 3x3x3 Multi-Blind, the organization team may define a cumulative time limit. The cumulative time limit must either apply to all attempts in one round (e.g. 3 attempts with a cumulative time limit of 20 minutes), or to all attempts in a combination of rounds for different events. In this case, the time limit for a particular attempt is the cumulative time limit minus the total time in other attempts counting towards the time limit so far (see [Regulation A1a5](https://www.worldcubeassociation.org/regulations/#A1a5)). If a round has an applicable cumulative time limit, it must have at most one.

**Comment by alexanderc360** [comment]
It seems this is not the case anymore and this issue can be closed

![image](https://user-images.githubusercontent.com/33144250/217501150-2f6c7dd4-bd29-4263-a942-ec8695e5d45a.png)
