### ISSUE TITLE
Allow Senior Delegates to see all outstanding WCA ID claims for their team

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#728]
Tim McMahon requested "Would it be possible for Senior Delegates to see WCA ID requests "pending" with Delegates in their Region? I've had a couple of competitors complain. I'm not sure how many outstanding requests there are."

**Comment by jfly** [comment]
This is a big-ish project, but should be fairly straightforward. I think it would make a good ment2 project.

**Comment by jonatanklosko** [comment]
Should wait for #680 of course.

**Comment by TimMcMahon** [comment]
Could https://www.worldcubeassociation.org/users please include "Country" and whether or not the account is waiting for approval by a delegate?

Would this allow another delegate to search for everyone representing "Australia" and follow up if another Delegate hasn't approved?

**Comment by jfly** [comment]
@TimMcMahon, that sounds like a useful improvement, for sure. It's important to remember that someone's nationality is not necessarily the place they live. It's also worth pointing out that some senior delegates manage multiple countries, and some countries are divided up amongst multiple senior delegates (the US, for instance).

**Comment by FatBoyXPC** [comment]
Can we close this issue now?

**Comment by jfly** [comment]
I think so. I just looked over @viroulep's work in #3500 and I'm pretty sure it covered this work.

@viroulep, @pedrosino , please reopen if I'm mistaken!
