### ISSUE TITLE
Modify Registration System to Accept Payments

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#729]

**Comment by jbcm627** [comment]
As a short-term solution, how about having the markdown editor support something like these?
https://www.paypal.com/webapps/mpp/get-started/buy-now-button
https://www.paypal.com/webapps/mpp/get-started/add-buy-now-button-to-email

**Comment by jbcm627** [comment]
Bump - just want to see if any progress has been made on this, or if not, just want to make sure it doesn't drop off the radar.
