### ISSUE TITLE
LIVE projector result missing positions

### ISSUE THREAD

**Issue by peterlauri** [thewca/worldcubeassociation.org#7298]
**Describe the bug**

When using the LIVE projector positions are cut off.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/3514945/195666488-d928ec6b-109a-4667-a035-44872211024b.png">

**To Reproduce**

1. Live projector
2. Wait for second page
3. Position 14 missing

I should have recorded the inner size, but I was lazy.

**Expected behavior**
All positions should be shown.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Latest version at the point of experiencing it. Now I have 106.0.5249.103 (Official Build) (x86_64)

**Comment by dunkOnIT** [comment]
@jonatanklosko is this something you would be able to take a look at and try to reproduce?

**Comment by jonatanklosko** [comment]
Hey @peterlauri! Thanks for the report, it should be fixed now. If you run into this again let us know :)
