### ISSUE TITLE
Better handling of the case where newcomers are incorrectly assigned to existing people

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#73]
@SAuroux asked for the ability to upload _only_ Person data [here](https://groups.google.com/d/msg/wca-software/QbHLvC2Saak/yDME63O6WY8J).

(moved from https://github.com/cubing/wca-website/issues/23)

**Comment by jfly** [comment]
@SAuroux, unfortunately both of these links are now broken. Do you remember what this issue was referring to?

**Comment by SAuroux** [comment]
Oh, wow. This can definitely be closed. :)

**Comment by jfly** [comment]
Ok, thanks!
