### ISSUE TITLE
Add DMARC record to WCA domain

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7302]
From Sam Spendla's email: 

> A lot of my emails have been going to my recipients spam recently, and upon investigation, I've found that there is no DMARC record associated with the [worldcubeassociation.org](http://worldcubeassociation.org/) domain, which I believe could be a fix to stop emails going to spam. Is this something that we could add to @worldcubeassociation.org emails?

@gregorbg could this be a step towards resolving the issues we've been having with emails going to spam / password reset emails not being received?

**Comment by gregorbg** [comment]
Thanks for your diligence in creating an issue. But it's not really necessary to track this as part of our website code. I have installed a DMARC record in our DNS and this should resolve the issue.
