### ISSUE TITLE
Patch WCIF is timing out

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7303]
Please refer to "Patch WCIF is timing out" email thread for more details.

From Manu's original email:

> Sam is trying to save the WCIF of his competition KewbzUKChampionship2022 from AGE. Basically what AGE does is take a csv with assignments (see attachment) and convert it to the WCIF format.
> 
> Unfortunately Sam is getting a timeout after ~ 32 to 33 seconds. I get the same behavior on staging. For smaller competitions (like 100 competitors) this usually takes a few seconds, but this one (450 competitors) seems to time out.

The workaround he found:

> I tried some stuff on the side of AGE and apparently uploading the competitors assignments in chunks did the trick. I'm still interested in figuring out why it did work without my hacky workaround :) But I understand that this is not a priority for you now.

Finn's observations after investigating:

> I've never researched how wcif is implemented, but in
> https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/api/v0/competitions_controller.rb
> There is no timeout specified in update wcif, so the timeout is either a whole server kind of thing or somewhere else

**Comment by jonatanklosko** [comment]
Alleviated by #7453, however ideally we would make the WCIF patch itself faster.

**Comment by viroulep** [comment]
I've put together some explanations on the behavior observed as well as a fix in #7454.
