### ISSUE TITLE
Redefine Registration Full Text to appear when the number of registered competitors exceeds the limit

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#7307]
**Describe the bug**
Currently, we display this message whenever the number of accepted registrations >= the competitor limit:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/11577241/197404956-af6f2cd3-e84a-4408-bf08-2f5f9fabe61e.png">

However, whenever we remove a registration (say someone cancels) and inquire the first on the waiting list about the open spot. During this time the warning disappears (even when there are 70+ people on the waiting list). This causes some confusion as the competition is currently full, but we are working with the waiting list registrants.

**Expected behavior**
The warning should continue to appear if the number of accepted competitors **+ the number of paid registrations on the waiting list** >= the competitor limit. The warning can also be modified to say "may be filled" in this case?

**Additional context**
relevant code: models/competition.rb:342
`def registration_full?
    self.competitor_limit_enabled? && self.registrations.accepted.count >= self.competitor_limit
  end`

**Comment by navaneethkp36** [comment]
hi @Jambrose777 I would like to work on this issue.

**Comment by dunkOnIT** [comment]
Thanks for the interest @navaneethkp36 ! I have assigned you - please shout here if you have any questions or run into any issues.

**Comment by navaneethkp36** [comment]
hi @dunkOnIT I saw this same logic to check if registration is full being used in 3 places:

1. in `/competitions/competition_name/registrations/add`, a warning message - `Note: The competitor limit has been reached and there are no more spots available` is shown with same logic.
2. registration status icon in `/competitions` when `Show registration status icon` checkbox is ticked. A user with clock icon is shown with warning text - `Competitor limit reached, new registrations will go to the waiting list` with same logic.
3. Alert message in `competitions/competition_name/register` with same logic.

The model function `registration_full?` in `models/competition.rb` is used at all these places. Changing the function logic will make the logic change in all the places mentioned above.

So is it fine to make changes at all places or should I create a new function and change the logic for only the registration warning mentioned in this issue? Please advise.

Thanks

**Comment by dunkOnIT** [comment]
Hi @navaneethkp36, 

If I'm understanding you correctly (I mostly deal with project management, not code!) changed the logic of `registration_full?` to "number of accepted competitors + the number of paid registrations on the waiting list >= the competitor limit" will cause the warning to change in .../registrations/add, /competitions, and .../competition_name/register?

If so, I think you can proceed with the change that will affect all 3 places, as we don't want to be sending inconsistent signals between different pages, and I think the initial logic of Jacob's statement applies in all those places.

Thanks a lot for picking up on the implications of that, though! :D 

(@Jambrose777 @FinnIckler shout if either of you disagree with my conclusion above)

**Comment by navaneethkp36** [comment]
sure @dunkOnIT . Thanks for the clarification 👍

**Comment by navaneethkp36** [comment]
hi @dunkOnIT @Jambrose777 I have opened a PR for this issue - https://github.com/thewca/worldcubeassociation.org/pull/7458. Please check

**Comment by dunkOnIT** [comment]
Thanks @navaneethkp36 ! I'm not able to review unfortunately, but have asked the devs to take a look :D

**Comment by gregorbg** [comment]
Fixed per #7458
