### ISSUE TITLE
"World Championship 2015" photo not loading on /about

### ISSUE THREAD

**Issue by khkellis** [thewca/worldcubeassociation.org#7308]
**Describe the bug**
A picture with the caption "World Championship 2015" is not loading on /about.

**To Reproduce**
https://www.worldcubeassociation.org/about

**Expected behavior**
The picture to appear.

**Screenshots**
<img width="1038" alt="Screen Shot 2022-10-24 at 9 31 05 AM" src="https://user-images.githubusercontent.com/27914581/197537646-0bf38667-62e5-4cd4-9f14-9f31b4e2b4c5.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Browser: Chrome
 - Version: 106.0.5249.119 (Official Build) (arm64)

**Additional context**
N/A

**Comment by dunkOnIT** [comment]
Assigning this high priority as it is on a page where we solicit donations - important for things to look professional there I think!

**Comment by gregorbg** [comment]
Solved as per #7358
