### ISSUE TITLE
Trainee Delegate promotions - simplifying changing competition websites

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/worldcubeassociation.org#7324]
I recently became a juniot delegate and it wasn't ideal to send so many emails emails on competition email threads so that WCAT could change me from being listed as a trainee delegate to a delegate on competitor websites. I'm sure WCAT and everyone else on the email threads didn't enjoy all the inbox clutter and that WCAT would appreciate being able to skip out on having to go through that process 😛 

It would be great to make this shift automatic after trainees become juniors. Maybe the website could check at view time instead of assigning a value?

**Comment by dunkOnIT** [comment]
Hi there Sam! Just looking for a bit more context here:

- do you mean you became a **junior** delegate? You say trainee in the Issue report, which is confusing me a bit
- Where exactly are you wanting to see yourself change from Trainee to Junior? My guess is for competition pages of already-approved competitions?
- Could you give more context on the competition email threads you're talking about? Is this on announcement/approval threads?

**Comment by Samuel-Baird** [comment]
Hi Duncan!

yes, I became a junior delegate, apologies for the confusion.

exactly! Currently once a trainee becomes a junior delegate they continue to be listed as a trainee delegate for competitions that have been announced and that are still being planned on the wca website. It would be great to have it automatically update. I also believe that people removed as trainees will remain to stay listed as trainee delegates until they are removed. 

In order to change being listed as a trainee delegate to a delegate, it is necessary to respond to WCAT on the email that confirms the competition announcement

**Comment by dunkOnIT** [comment]
Hey Sam! Apologies for my late response. 

My main thought - and please let me know if you disagree - is that this might be more work to implement than it is worth for users. My underlying assumptions:
* For this to happen, we need an overlap of two relatively infrequent events - the promotion of a trainee delegate, WHILE they're listed as a delegate for an existing competition. 
* It's inconvenient but not too difficult for newly-promoted delegates to change this themselves
* It would require some non-trivial changes to how we implement the competition page (ie, we'd need to query the database for updated information, which we don't currently do). @FinnIckler please correct me if I'm wrong on this. 

@Samuel-Baird first off, please let me know if you disagree with any of my assumptions. If they're more or less accurate, my suggestion for this is that it get added to our backlog for the competition form improvements (not happening soon, but eventually), and we can see if it an be implemented as part of that redesign. 

Also, congrats on your Junior promotion! :D

**Comment by Samuel-Baird** [comment]
Hey Duncan! 

I agree that this shouldn’t not be a priority but rather a small quality of life update that can be made down the road if it isn’t too difficult to implement. 

>For this to happen, we need an overlap of two relatively infrequent events - the promotion of a trainee delegate, WHILE they're listed as a delegate for an existing competition.

I am unsure of other regions so it would be great to see someone run a query but trainee delegates that I know of tend to be listed as a trainee for any upcoming competitions in their region which can often be several.

> It's inconvenient but not too difficult for newly-promoted delegates to change this themselves

for competitions that have been announced it requires that the newly-promoted delegate contacts WCAT, as they cannot make the change themselves

**Comment by gregorbg** [comment]
For reference: This is causing WST some pain to come up with an "easy fix" because the internal database structures for Delegates and Trainee Delegates are duplicated.

We would have to write checks that move records from one database table to another, which feels awkward. A better solution would be to integrate the Delegates and Trainee Delegates linking tables into one (in the wider sense) Delegates table. But we need to figure out the historical context of that duplicate design decision first, before coming up with a proper fix.

**Comment by gregorbg** [comment]
I think it is entirely a software problem. To be honest, I can't come up with a good reason why the tables were exactly duplicated when you can just add a simple `is_trainee` flag to the existing structures.

Doing so would alleviate us of the necessity of implementing either of your solutions, which are well-thought but utterly complex for such a trivial issue. (But rest assured that we will probably come up with a Dashboard at some point in the future anyways)

**Comment by Jambrose777** [comment]
Just throwing this out:
If we are combining these tables, it might be best to combined all these into a single table:
Ie
Competition_Officials table
Compeititon_id, user_id, role

Which would have delegates, trainees, organizers, but also be expandable for the future of wca with allowing role to be main_delegate, compeititon_staff, or I’m sure there are other potential additions that could utilize this new all in one table
