### ISSUE TITLE
Transition Admin View for Competitor Registrations to React

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7356]

**Comment by agrawalishaan** [comment]
Similarly, I would like to help on this transition to ReactJS, along with any other pages that are needed.

**Comment by dunkOnIT** [comment]
Hey @agrawalishaan! Thanks so much for being willing to help. This is still available - if you feel confident getting started, feel free. 

The transition does take a bit of Rails-specific knowledge (both to find the relevant view page, and to request data from the Rails backend, so I've reached out to see if any devs who have already worked with some of the React transitions might be able to help get you started. 

I'd suggest getting started with setting up the Docker image for the website on your local machine in the meantime if you'd like to.
