### ISSUE TITLE
Transition Competition Edit Page to React

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7357]
No redesign of the page envisioned - just a port of existing features. 

This is the page we need to port: https://www.worldcubeassociation.org/competitions/new

**Comment by agrawalishaan** [comment]
Is this issue still available to be taken on? Who can I contact for more info? This would be my first OS contribution, but I am pretty good with React.

**Comment by agrawalishaan** [comment]
That's okay, thanks. Is there any place I can contribute React or JS?
