### ISSUE TITLE
Remove year from display when listing competitions by announcement date

### ISSUE THREAD

**Issue by cranemit** [thewca/worldcubeassociation.org#7366]
**Is your feature request related to a problem? Please describe.**
This is more of a nuisance than an actual problem. Currently, the competitions displaying in the US are split pretty evenly between 2022 and 2023. As a result, when displaying competitions by Announcement Date, a few lines appear and then the year on its own line. The year is redundant since it already shows the date and year in the first column.
This screen shot is from a few weeks back, and now as more competitions are being announced for 2023, the year is cluttering the UI even more.

<img width="857" alt="Screen Shot 2022-10-17 at 9 36 11 AM" src="https://user-images.githubusercontent.com/25484201/200191347-63cec694-1c4e-4ad2-bead-4572e29cec05.png">

**Describe the solution you'd like**
The year is good to include when sorting by date, since the year only appears on its own line once. However, I see no need to include it in the display when sorting by announcement date. 
This screen shot is the alternative to the above, leaving out the lines containing only the year.

<img width="856" alt="Screen Shot 2022-10-17 at 9 34 49 AM" src="https://user-images.githubusercontent.com/25484201/200191490-ddbb3415-acb7-47e4-b54d-e0463605518d.png">

**Describe alternatives you've considered**
I feel removing the year when sorting by the announcement date is the logical fix. I use this view to see competitions that have recently been announced, so it's expected that the results will be distributed across the current and upcoming year, especially as we get late into the year.

**Additional context**
I've got a change prepared for this, and would like to get permissions to the repo so that I can create a PR, and potentially work on other contributions in the future.

**Comment by dunkOnIT** [comment]
Hi there @cranemit ! Thanks so much for the detailed issue write-up, and your willingness to contribute :D 

**For contributing to this repo:** Best practice for submitting PR's is to fork the repo, make the change you want in your repo, and then make a request to merge from the repo - which you don't need permissions for this repo to do. Please let me know if you run into any issues there.

Regarding the change you've suggested - I don't have strong opinions either way as I don't use this feature, but I agree that the current system is quite confusing. Either the row which separates different years should be made more clearly into a divider, or removed entirely.

I think you can go ahead with submitting a PR for removing the row entirely and we can solicit feedback from there.

**Comment by cranemit** [comment]
PR to make this change:
https://github.com/thewca/worldcubeassociation.org/pull/7402 
It's only removing the year when it's in the sort by announcement mode - I've kept in the year when sorting by date, because there I think it is more useful.
