### ISSUE TITLE
Allow delegates to post reports on or after the last day of a competition

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#737]
A comment from Ron:

> Software team: I had no Post the report but yesterday. Could it be that this button only appears the day after the competition? If so, please change this, I want to be able to post reports immediately after the competition.

My response:

> The idea was to not allow posting a report until after the competition, but since we don't actually have competition schedules, it's impossible for us to know when it's over on the day that it is scheduled to end.
> 
> I don't see any problem with letting delegates post their reports anytime after the competition has started.

**Comment by SAuroux** [comment]
I disagree with posting reports after a competition has started. Why not just allow posting reports after the start of the last calendar day of a competition, i.e. one day earlier than we allow now? This solves the problem and minimizes the risk of reports being submitted too early.

**Comment by pedrosino** [comment]
> I disagree with posting reports after a competition has started. Why not just allow posting reports after the start of the last calendar day of a competition, i.e. one day earlier than we allow now? This solves the problem and minimizes the risk of reports being submitted too early.

For one-day competitions this is essentially "...after a competition has started".

**Comment by SAuroux** [comment]
Thanks for pointing out the obvious Pedro... ;)

What is interesting is, that this is not the same for multi-day competitions.

**Comment by pedrosino** [comment]
Yeah, I meant that your proposal works only partly :)

I don't have a strong preference here...maybe the competition ends early and the delegate wants to submit the report on the same day. This would incur in the problem at #720 which doesn't seem to have an easy solution...

**Comment by SAuroux** [comment]
You are confusing me. Why does my proposal only work partially?

Of course I was aware of that this changes nothing for 1-day comps, for 2-day or 3-day comps however I do not see why a report would need to be submitted before the last calendar day of that competition. Thus I think "last calendar day of a competition" makes more sense than "first calendar day of a competition", that's all.

**Comment by pedrosino** [comment]
Now you are confusing me. You said "I disagree with posting reports after a competition has started.", but that's "inevitable" for 1-day comps with your proposal.

Anyway, I'm not opposed to the proposal.

**Comment by SAuroux** [comment]
Ok, then I will formulate more precisely: I disagree with the rule "beginning with first calendar day of a competition". Instead I propose the rule "beginning with last calendar day of a competition". The difference only affects X-day competitions with X > 1.

**Comment by larspetrus** [comment]
Assuming I've understood the problem from this discussion, this could be
less frustrating with simple UI changes.

If you just don't show a button where the user expects to find it, he is
left wondering why. Is this a bug? Am I misremembering where this button
is? Did the button get moved? Should I have configured something earlier to
make the button appear? Etc.

This is why currently unavailable UI elements should usually be greyed out
instead of removed.

In this case it sounds like a brief explanation would also be useful. "The
report can be posted 17:00 GMT (6h 14m from now)"

On Mon, Jun 27, 2016 at 5:27 AM, Sébastien Auroux <notifications@github.com>
wrote:

> Ok, then I will formulate more precisely: I disagree with the rule
> "beginning with first calendar day of a competition". Instead I propose the
> rule "beginning with last calendar day of a competition". The difference
> only affects X-day competitions with X > 1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cubing/worldcubeassociation.org/issues/737#issuecomment-228731411>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAuGK4jkWTljptHNbjZofJuGyK75oLPfks5qP8HGgaJpZM4I-6lL>
> .
>



-- 
Procrastinators - the Leaders of Tomorrow

**Comment by SAuroux** [comment]
I just finished the report of a competition that I have delegated this weekend and that has **now already ended** and the fact that I cannot just submit this report is extremely annoying. Can this simple fix please be tackled soon?

**Comment by jfly** [comment]
Just talked to @SAuroux about this, we both agree that the best thing to do here is to allow posting delegate reports **on or** after the last day of a competition.

@larspetrus brings up a good point. It might be more friendly to provide the user with a submit button that spits out an error when you try to click it.
