### ISSUE TITLE
Simplify entering new results

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#74]
Expand @Luis-J-Ianez's fix_results script to handle entering new results.

**Comment by ronaldmansveld** [comment]
@jfly Can you expand on this ticket please?

**Comment by jfly** [comment]
Luis built this page for fixing existing results https://staging.worldcubeassociation.org/results/admin/fix_results.php:

![image](https://user-images.githubusercontent.com/277474/48432428-2679ec00-e729-11e8-93e0-f62e85d1dc1d.png)

I think it would not be a totally crazy change to have a version of this that handles adding brand new result, rather than only editing existing results. That said, we should check in with the WRT to see if this is still needed. I imagine there's higher priority stuff we could be doing for them. I'm not sure it's very valuable to keep this issue open.

**Comment by SAuroux** [comment]
Currently our approach for adding results consists of preparing an INSERT INTO statement with competitor and event information and then using exactly this script to fill the row with values, average, best. 

So yes, this would be a great improvement!

**Comment by jonatanklosko** [comment]
Closing in favor of #74, so that we have one place for discussion.
