### ISSUE TITLE
Sort competitors by name in registrations#index

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#742]
The controller doesn't order the registrations which are then put into the table only to be sorted again. Is it possible to sort them in the database, render them in the default order, and only have the table sort them when a heading is clicked?

You can see this clearly happening for Euro2016.
https://www.worldcubeassociation.org/competitions/Euro2016/registrations/

**Comment by larspetrus** [comment]
So that delay is JS sorting for 4 seconds?

It should be trivial to sort them either in the SQL query or in memory after loading.

**Comment by jonatanklosko** [comment]
Good point, I think it should be faster =)
