### ISSUE TITLE
Exclude Trainee Delegates from WFC Export

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#7493]
With the recent change in structure of the Delegates table (#7395), Trainee Delegates are now included in the Delegates column of the WFC export, which interferes with the processes the WFC has for addressing Dues invoices. It would be preferable to exclude trainee delegates from this column - I assume by doing a join and a filter somewhere in the query. 

See #7144 for an example of recent changes to the WFC export. cc @danieljames-dj since he suspected this might happen.

**Comment by danieljames-dj** [comment]
https://github.com/thewca/worldcubeassociation.org/blob/f4c8353b0266579772d959ae895c2f158a5e62bd/WcaOnRails/app/controllers/wfc_controller.rb#L21

I'm assuming the above line has to be changed to something like:

```
.includes(:delegates.reject{|delegate| !delegate.trainee_delegate}, :championships, :organizers, :events)
```

I'm not sure though and a bit busy this week to test in my system. If someone can test it and raise a PR, it will be really helpful.
