### ISSUE TITLE
Competition's detail PDF doesn't support Thai

### ISSUE THREAD

**Issue by CristCuber** [thewca/worldcubeassociation.org#7494]
The Competition's detail pdf file is not supported the Thai language.

1. Set the website's language to Thai
2. clicked "Download all the competition's details as PDF here" on the competition's page (e.g. https://www.worldcubeassociation.org/competitions/BangkokCubeDayWinter2023.pdf)
![image](https://user-images.githubusercontent.com/26253448/209494897-8cbb10a7-4ce2-4a8f-963b-222f0709287e.png)
3. the pdf is unreadable as picture below
![image](https://user-images.githubusercontent.com/26253448/209494802-e74e81fb-0bf5-4ed9-887c-ad76609b4cde.png)

I have tried it on my PC, iPad, and phone and it is all the same.

**Comment by FinnIckler** [comment]
Pretty sure this happens because the server doesn't have Thai fonts installed as per this wickedpdf issue: https://github.com/mileszs/wicked_pdf/issues/496
I'll run  `sudo apt-get install fonts-thai-tlwg` and see if it does anything and then we can put those into any chef scripts in the future

**Comment by CristCuber** [comment]
https://www.worldcubeassociation.org/competitions/KrungthepFarewell2022.pdf

It's worked now
![image](https://user-images.githubusercontent.com/26253448/209641978-d1dab2c4-4713-4c7c-8aad-0395cf7a89b8.png)

**Comment by FinnIckler** [comment]
Yes, I installed the fonts. All PDFs that are still cached might be wrong, but that should fix itself eventually. 
I will need to remind myself to add those commands to the bootstrap process
