### ISSUE TITLE
Datetimepicker bug?

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#751]
While editing a competition yesterday, I found that selecting October 15th 2016 is very messy. See gif below.
Basically the field is saved as 2016-10-16 on the database, but for some reason it appear as 2016-10-15 on the input. Also, when the datetimepicker opens, there are two (?!) day 15, one being to the right of everything else.

I'm able to click on the 16th and save, but on reloading the problem repeats.

Could this be something local? Can anybody try to replicate this?
![out](https://cloud.githubusercontent.com/assets/1881933/16451305/8fdd018e-3dd8-11e6-9fc9-1a254908d0dc.gif)

**Comment by larspetrus** [comment]
It's probably some broken assumptions about time zones in the code.

Can you try it at different times of day and see if it acts differently?

**Comment by pedrosino** [comment]
Just tried again and got the same result.
I remember seeing this a couple weeks ago too, in another project of mine.

**Comment by pedrosino** [comment]
I was fixing a birthdate today and realised it also fails for october 1991:
![october](https://cloud.githubusercontent.com/assets/1881933/18599251/c95eadca-7c2d-11e6-98b0-92e54ea9c415.png)

**Comment by pedrosino** [comment]
For the record, I just created https://github.com/zpaulovics/datetimepicker-rails/issues/83

**Comment by pedrosino** [comment]
https://github.com/zpaulovics/datetimepicker-rails/issues/83#issuecomment-247979994
Seems like there is hope :D

**Comment by ronaldmansveld** [comment]
@pedrosino 

Are we still using that same library for the datepicker? Does the issue still exist? I see their last commit was in 2015, so that doesn't give much hope ;)

If we have moved to a different datepicker, then please close this ticket.

**Comment by pedrosino** [comment]
Yeah, it does:
![image](https://user-images.githubusercontent.com/1881933/46886486-749d8600-ce31-11e8-8013-7baa1588910e.png)

**Comment by ronaldmansveld** [comment]
In that case we should move to a different datepicker, one that is still under active maintenance ;)

**Comment by UnsolvedCypher** [comment]
@pedrosino Could you check whether [this branch](https://github.com/UnsolvedCypher/worldcubeassociation.org/tree/october-fix) still has the same issue?

**Comment by pedrosino** [comment]
@UnsolvedCypher Sorry for the delaty
It works fine with your branch, but also seems to work on the WCA website now:
![Peek 28-02-2020 21-54](https://user-images.githubusercontent.com/1881933/75597559-e7ce8900-5a74-11ea-9031-c113f54c8ca4.gif)

**Comment by UnsolvedCypher** [comment]
Oh that's good to hear! In that case I guess this issue can be closed

**Comment by viroulep** [comment]
Love these kind of issues :)
