### ISSUE TITLE
Change link to the current WCA Regulations version

### ISSUE THREAD

**Issue by Nevseros** [thewca/worldcubeassociation.org#7524]
**Is your feature request related to a problem? Please describe.**
When a link to any regulation/guideline is shared, it may become invalid after some time (e.g. after amendments where regulation N1n1 is merged with N1n or moved to the guidelines).

**Describe the solution you'd like**
Make all links to the regulations, including the outdated ones, consistent (so if I'd like to link current A2c1, I link to something like `.../regulations/2022-06-01/#A2c1` and it **always** gives me A2c1 from the 2022-06-01 version).

**Describe alternatives you've considered**
Don't really know if there could be any alternatives.

**Additional context**
Why it's needed: for example, to prepare the report for the Vietnamese competitions results removal, WRC'd like to link current regulations, but the links we're going to add will point to the newer version starting from February. We can still wait for February though, so it's not a high priority, I guess (also guessing this is not an easy implementable change?).

**Comment by dunkOnIT** [comment]
Hey Ekaterina! This sounds super reasonable. I can't comment on how hard it would be to implement, but given our current priorities and capacity, I'd suggest proceeding on the assumption this won't be implemented by February (sorry!).

@gregorbg feel free to disagree ofc :D

**Comment by FinnIckler** [comment]
This is actually pretty easy to do using wca.link and requires a change https://github.com/thewca/wca.link/blob/main/lambda_function.rb#L31 in this line. I am not a regex expert, but you should be able to parse it from the link, as wca.link//regulations/2022-06-01/#A2c already works!

**Comment by Nevseros** [comment]
I actually figured out how to "fix" it for the future regulations updates - I think it would be resolved by just uploading new version's `.html`s to the folder with the previous versions (see PR #7495), so in case someone needs to link the regulation in its wording at certain time, they would be able to do it by using link from the history.

I'm not sure this issue is actually an issue anymore, @dunkOnIT please close if deemed resolved.
