### ISSUE TITLE
Delegate report not showing retired delegates

### ISSUE THREAD

**Issue by MariaBeau** [thewca/worldcubeassociation.org#7530]
On the Irish Championship 2019 Delegate Report on the WCA website, in the delegates section, the only listed delegate is Mary Hennessy, however Daniel Sheppard and Thaynara Santana de Oliveira also delegated. Daniel and Thaynara are no longer delegates.

https://www.worldcubeassociation.org/competitions/IrishChampionship2019/report

![image](https://user-images.githubusercontent.com/122128541/211109588-5997d88b-74c2-4a32-aea6-ef2761143661.png)

It happens to their other competitions too i.e Lincoln 2019 https://www.worldcubeassociation.org/competitions/LincolnOpen2019/report

**Comment by dunkOnIT** [comment]
I'm imagining this requires some thinking around how the logic which handles retired delegates is currently implemented. Anyone looking to work on this issue should:
- investigate/document the current logic for the handling of retired delegates
- propose an updated version that preserves a history of where retired delegates _were_ involved

**Comment by OJCubing** [comment]
There's a table called competition_delegates which stores the userid of each delegate of a competition, which isn't affected by if the delegate was demoted etc.

[Example query for Irish Champs and Lincoln 2019](https://statistics.worldcubeassociation.org/database-query?sqlQuery=SELECT+a.competition_id%2C+b.name%0AFROM+competition_delegates+a%0AJOIN+users+b%0AON+a.delegate_id+%3D+b.id%0AWHERE+competition_id+IN+%28%27IrishChampionship2019%27%2C%27LincolnOpen2019%27%29%0AORDER+BY+competition_id%2C+name%0A)

**Comment by FinnIckler** [comment]
Then it should be quite easy to implement, needs to access the correct delegates here 
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_competition_info.html.erb#L52
I see in the git blame that @gregorbg did something to this line with the unifying trainee delegate commit, maybe he introduced this issue?

**Comment by FinnIckler** [comment]
Just talked with Gregor and it's indeed a visual only bug introduced in the unifying of the delegates, If someone wants to implement it that line + a change in the controller to get the correct data should do it

**Comment by JonEsparaz** [comment]
> Just talked with Gregor and it's indeed a visual only bug introduced in the unifying of the delegates, If someone wants to implement it that line + a change in the controller to get the correct data should do it

I think the relevant code is actually here, right?

https://github.com/thewca/worldcubeassociation.org/blob/689b2a4035ff09f8462f32ed38887df237f4422f/WcaOnRails/app/views/delegate_reports/_delegate_report.html.erb#L53-L61

I guess this is relevant too:

https://github.com/thewca/worldcubeassociation.org/blob/689b2a4035ff09f8462f32ed38887df237f4422f/WcaOnRails/app/models/user.rb#L679-L681

**Comment by FinnIckler** [comment]
You are right, I misread the issue that this happened in the delegate report and the competition page

**Comment by simonkellly** [comment]
This has been fixed with the changes made in #7640
