### ISSUE TITLE
Contact form should direct competition inquiries to `contact` email if provided

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/worldcubeassociation.org#7531]
**Is your feature request related to a problem? Please describe.**
For competitions in Canada, our email workflow gets interrupted when we receive inquiries via the [contact form](https://www.worldcubeassociation.org/contact/website) since it sends an (individual) email to every listed Delegate and Organizer. I'd like the emails to be directed to the `contact` email (if provided).

**Describe the solution you'd like**
In [this if-block](https://github.com/thewca/worldcubeassociation.org/blob/b8832922dea37f7e11089cc04e3933af134a61ea/WcaOnRails/app/models/website_contact.rb#L22-L23), we could do something like `competition.contact || competition.managers.map(&:email)` (note: this is semi-pseudocode).

**Describe alternatives you've considered**
We could have an opt-in/out, but that would involve storing a boolean for each competition.

**Additional context**
N/A

**Comment by JonEsparaz** [comment]
@dunkOnIT not quite. For https://www.worldcubeassociation.org/competitions/ApplebyWinterA2023, the only contact listed is `appleby-winter-2023 [at] speedcubingcanada [dot] org` (see "Contact" just above "Organizer"). We don't have an "Organization team" contact link like some other competitions.

We get these inquires when people go directly to https://www.worldcubeassociation.org/contact/website, then select "Contact the Organizers of a Specific Competition (please select below)".

Competitions that use the "Organization team" contact link would not be affected by the change I'm suggesting.

**Comment by dunkOnIT** [comment]
Ok great, thanks for the clarity there! Makes complete sense, and a great suggestion.

**Comment by JonEsparaz** [comment]
Awesome thanks for confirming @dunkOnIT! 

I'm going to try for a PR tonight.
