### ISSUE TITLE
Add SSHFP record to avoid TOFU

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#7537]
**Describe the solution you'd like**
To improve the security of the server, I'd suggest that you use SSHFP, it's a DNS record which solve the problem of TOFU (Trust-On-First-Use) for SSH.

**Additional context**
When you first connect to your servers in production, you accept the server as being trustworthy. With SSHFP, it will check the record in DNS servers to be sure the fingerpint matches with your hostname (the server) fingerprint. Meaning that when connecting for the first time with SSH, the server is already trusted.

I personnally run a Signal proxy, here's an exemple of SSHFP record :
![image](https://user-images.githubusercontent.com/74207682/212667995-ef80a622-3f39-430c-ac52-d38bb642abcb.png)

**Comment by FinnIckler** [comment]
hey!
We actually recently got rid of SSH access to worldcubeassociation.org so we have no DNS entry to attach the SSHFP entry to.
We will definitely consider this if we ever bring it back, but our current goal is to have port 22 closed forever for our production machine(s) ;)
