### ISSUE TITLE
Improved "report" link in "My competitions"

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#755]
It would be cool to have a visual difference in the report link, depending on the following cases:
- You are a delegate of the competition, the report is not posted
- You are a delegate of the competition, the report is posted
- You are not a delegate of the competition, but you have the right to edit it
- You are not a delegate of the competition, but you have the right to view it

I would suggest to have a "report" icon (just like when results are up or when you're registered), that would appear to all eligible persons when the report is posted, and that would link to the posted report.
Additionally, I would keep the current "Report" link with two different colors depending on if you are a delegate of the competition or not, that would link to the "edit" page of the report.

Maybe the last point could be achieved by adding some kind of visual hint on the rows of the competitions you delegated.

**Comment by jfly** [comment]
Generally speaking, I'm not a big fan of arbitrarily assigning meaning to colors (AFAIK, there's no standard for "can view" and "can edit"). How about having a link to the delegate report, and a pencil afterwards to indicate "you have the right to edit the report":

![image](https://cloud.githubusercontent.com/assets/277474/17005247/1aa3de3a-4e8e-11e6-97c4-06143eb8495a.png)

To convey if your are one of the delegates of the competition, I'd be a fan of adding a delegates column to the table, and maybe bolding your name if it shows up. Maybe something like this:

> Delegates: Philippe Virouleau, Tyson Mao, and **Jeremy Fleischman**

To convey if the report is posted, how about a warning icon with a tooltip explanation? Something like this:

![image](https://cloud.githubusercontent.com/assets/277474/17005507/80967198-4e8f-11e6-8d97-f40dd889e88f.png)

**Comment by jfly** [comment]
I've marked this as a ment1 project, although I believe we should fully spec it out before assigning it to someone.

**Comment by viroulep** [comment]
I played around and used the following logic:
If user can view the report -> show a "view report" icon
If user can edit the report -> show an "edit report" icon
If competition is ended, and the user is one of the delegate, and the delegate report is not posted -> show a warning icon.

As a WST member it shows something like this:
![wst-member](https://cloud.githubusercontent.com/assets/1007485/21806316/deb1359c-d738-11e6-9045-c02e205c0c8c.png)

And as a delegate it shows this:

![delegate](https://cloud.githubusercontent.com/assets/1007485/21806333/f1eba034-d738-11e6-9fa0-d31e50659fdf.png)

For all the competitions but the first two, the current user is one of the organizers but not one of the delegate for the competition, and the report is not posted: this is why there is no icon showing up.
