### ISSUE TITLE
Add "Check-in" as a custom activity on the schedule page

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/worldcubeassociation.org#7552]
**Is your feature request related to a problem? Please describe.**
This is the current selection of custom activities:

<img width="598" alt="custom activities" src="https://user-images.githubusercontent.com/5139750/213873270-37c30fb1-e403-487c-a4ba-a0ef7858bdeb.png">

**Describe the solution you'd like**
Add "Check-in" as a selectable option. 

**Describe alternatives you've considered**
I've been selecting "Registration" then manually changing the name to "Check-In"

**Additional context**
"Registration" is misleading when there is no on-site registration because competitors already registered online. It seems that most of the time when "Registration" is shown on a schedule it's actually a check-in period for competitors to confirm their identification and event selection, show their passport for proof of citizenship if they are new, and get their name tag and/or group sheets.

It might also be good idea to change "Registration" to "On-site registration" to indicate an actual registration period.

**Comment by JonEsparaz** [comment]
Since 2020 (inclusive), there have been 2230 competitions. 1893 (~85%) did _not_ allow on the spot registrations, whereas just 337 (~15%) did.

https://statistics.worldcubeassociation.org/database-query?sqlQuery=SELECT+COUNT%28*%29%2C+on_the_spot_registration+FROM+Competitions%0AWHERE+year+%3E%3D+2020%0AGROUP+BY+on_the_spot_registration

**Comment by dunkOnIT** [comment]
Great suggestion, I agree it is confusing.

**Comment by EdHollingdale** [comment]
I agree with calling it check-in instead of registration, it is much clearer. This issue is probably related to #5670

**Comment by JonEsparaz** [comment]
Do we need to update https://github.com/thewca/wcif/blob/master/specification.md#other-activities too?

**Comment by FinnIckler** [comment]
yes! can you make a pr for this kevin?
