### ISSUE TITLE
Markdown rendering issue for delegates report

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#756]
It seems that we don't use the same rendering for the report fields' preview and for viewing the full report.

Here is a few differences I spotted:
- Fields preview allows lists to break paragraph, full report view doesn't (meaning you have to have a blank line before the list to display it properly, see [here](https://www.worldcubeassociation.org/competitions/LyonMegaminxOpen2016/report) vs [here](https://www.worldcubeassociation.org/competitions/France2016/report)).
- Fields preview renders links for http(s) urls automatically, full report view doesn't.

If we can I'd vote for using the fields preview rendering everywhere, but at least we should use the same rendering for both views, or provide a disclaimer about these differences on the edit report page.

**Comment by jonatanklosko** [comment]
Will be fixed after #719 is merged =)

**Comment by viroulep** [comment]
It has been merged so I looked back at it :)
The default behavior is to not create links automatically, and create lists only if there is a blank line before them.

It remains one tiny thing that is a bit misleading regarding this default behavior: when typing an url, the "preview as you type" will render a link (actually it just underlines it), whereas the actual preview won't.
By just looking a bit into it, it seems that the "preview as you type" uses another css (than the website's), but unfortunately the style is the same for two links where we'd like different behaviors:
![links](https://cloud.githubusercontent.com/assets/1007485/17096108/12a69600-5258-11e6-960d-080da888823b.png)

I'm not sure there is an easy fix for this...

**Comment by viroulep** [comment]
This is not relevant anymore since we switched to EasyMDE (#4376).
