### ISSUE TITLE
Show time until Registration opens in your Bookmarked Competitions list

### ISSUE THREAD

**Issue by TheMagicCuber** [thewca/worldcubeassociation.org#7561]
On the _My competitions_ page in the Competitions page, it may be helpful to people to eliminate a click onto each website to see when registration opens. This could be done by either adding text that displays when registration opens, having an option to add the registration icons from the _All Competitions_ page, or maybe both.

I attached a photo that displays what I am talking about (I'm not that great at photo editing lol). I'm not sure how feasible it is but I feel like it may be useful to have one spot to view when all your bookmarked competitions' registrations open. 
![TimeTillRegistrations](https://user-images.githubusercontent.com/35645519/215628609-d4d45184-f10f-4eb6-8cf5-4e5823927ab6.png)

**Comment by dunkOnIT** [comment]
I like the suggestion personally. One suggestion I have from a design perspective would be to move the registration icon to the left of the competition name. But otherwise I'll leave the UI side of things to those more knowledgeable than me :D

**Comment by maxidragon** [comment]
Hi @TheMagicCuber!

I would like to work on this issue.

**Comment by dunkOnIT** [comment]
Thanks @maxidragon !
