### ISSUE TITLE
Add North America region leads to delegate page

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7598]
Source email thread: "Region Lead Title Addition"

CubingUSA has requested that we add region leads to the delegate page. I assume this would be implemented similar to how it is for Asia at the moment. 

@FinnIckler could you clarify if this page is generated by reading from the delegate database, or is it simply a case of manually reformatting the page? 

Details of regions to be added: 
> Pacific Northwest and British Columbia: Cailyn Hoover
> West: Michael Young
> Rockies: Matthew Dickman
> South: Zachary White
> Southeast: Jacob Ambrose
> Mid-Atlantic: Bob Burton
> New England: Tim Reynolds
> Great Lakes: Mason Langenderfer
> Heartland: Walker Welch
> Canada (minus British Columbia): Kristopher De Asis

**Comment by coder13** [comment]
Quick detail to balance it out: I also cover British Columbia

**Comment by coder13** [comment]
I figured if there's a `senior_delegate_id`, it should be trivial to add a `regional_delegate_id`. From then it could be a lot of duplication of the senior delegate code?

This has also been mentioned here: https://github.com/thewca/worldcubeassociation.org/issues/4851

Which mentions how we have this refactor in progress: https://github.com/thewca/worldcubeassociation.org/pull/5417

What's the status on the refactor though?

**Comment by dunkOnIT** [comment]
Thanks Ed. In that case, I think I might've overcomplicated this DRAMATICALLY - it should be a case of at least:
1. Changing the "Roles" of the delegates listed in the original issue to "Regional Delegate"
2. Changing the "Region" of the those delegates to the regions given for them
3. Organising the US delegates which fall under these different regional delegates so that they appear under them in the delegate page

(1) and (2) seem straightforward, not sure if (3) would be hardcoded or if it is automatically determined somehow.

**Comment by dunkOnIT** [comment]
Just for some clarity (because I didn't realise this), #5417 adds explicit support for Regional Delegates. Marking this issue as blocked until that PR is implemented, and will email all senior delegates when that is implemented. 

Additionally, will follow up with Dan and mark this as needs-attention for if he isn't able to get to it.

**Comment by gregorbg** [comment]
There is no need for an issue that specifically details listing _these_ exact Regionals for _this_ exact region. We simply need general Regional Delegate support on the website, probably there's already an issue for that.

**Comment by dunkOnIT** [comment]
@gregorbg could be closed a duplicate of #4851? There is also #4222, which details a project for the delegate table overhaul - we could close all as a duplicate of that, depending how much overlap there is with features implemented in #5417. Otherwise I'll add it to the backlog as a potential project.

**Comment by gregorbg** [comment]
Closing in favor of #4851.

The Regional Delegate concept was introduced after the Delegate Table design in #4222 was conceived (I think...?) so it makes sense to keep both issues around. Preferrably group #4851 as part of (additional requirement of) #4222.
