### ISSUE TITLE
selectize locking up pages in chrome

### ISSUE THREAD

**Issue by jbmertens** [thewca/worldcubeassociation.org#761]
The selectize plugin from the php system is currently causing chrome to lock up for a minute or so when uploading results (on the [upload page](https://www.worldcubeassociation.org/results/admin/upload_results.php); other browsers seem unaffected). Few possible fixes:
1) remove the selectize plugin ([comment this](https://github.com/cubing/worldcubeassociation.org/blob/5fe5e5c1557c4d5e7d2b49d4caeb585f60e4c2ed/webroot/results/js/data_upload_help.js#L46) or something)
2) replace the selectize plugin
3) port this script to rails (a la #223)

Maybe (1) then (3) is the best option.

**Comment by jfly** [comment]
The php results page is eventually going away, and I haven't heard complains about this from other members of the results team recently, so I think this ok to close. If it proves to be a problem before we revamp the php page, we can revisit this.
