### ISSUE TITLE
Organizers' comment textbox on registrations

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/worldcubeassociation.org#7628]
**Is your feature request related to a problem? Please describe.**
We often add administrative notes on registrations in the same comment textbox that the competitor can fill out. For example, if a new competitor didn't include their last name on their registration, we might write "Note: Emailed to ask about last name".

Currently, we (obviously) don't put sensitive information in this textbox (since the competitor can see it and in some cases could edit it), but it is likely confusing for a competitor to see an administrative note in the comment textbox.

**Describe the solution you'd like**
Add a second textbox for organizers' comments.

Data permissions: only competition managers can view/edit
UI: same as existing comment textbox

**Describe alternatives you've considered**
Could build/use an external tool, but we'd have to sync with WCIF (or keep pulling a CSV) and the data would be in two places.

**Additional context**
N/A

**Comment by Rubiks-boy** [comment]
Hello, this sounds like an awesome feature. I'd love to take a look at building this! :)
