### ISSUE TITLE
Properly configure cache headers for cached endpoints

### ISSUE THREAD

**Issue by coder13** [thewca/worldcubeassociation.org#7630]
**Is your feature request related to a problem? Please describe.**
The public WCIF is cached for 5 minutes despite sending a header of 0 age
![image](https://user-images.githubusercontent.com/881394/219092851-6657a8fc-28b7-44c8-a545-a735d5a277a8.png)

**Describe the solution you'd like**
An accurate max-age header value

**Comment by FinnIckler** [comment]
I am actually doing some work on more performance optimizations and this is a problem all around our codebase. We never set any cache-control headers (except for the js packs ofc), even when we are indeed caching content. I am planning to include this in a PR that will follow up the Redis one.
