### ISSUE TITLE
WCA Dues estimate for competitions without competitor limit

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/worldcubeassociation.org#7648]
**Describe the bug**
Create a competition without a competitor limit (e.g., a multi location FMC competition), then you'll see something like: `The estimated WCA Dues for [missing "%{limit}" value] competitors are $0.00 (CAD)`

**Expected behavior**
We should probably display something like "WCA Dues cannot be estimated without a competitor limit".

**Screenshots**

![image](https://user-images.githubusercontent.com/48423418/220721040-293287eb-e573-48a9-a450-fa57b4a48f1c.png)

**Additional context**
N/A

**Comment by dunkOnIT** [comment]
Will meander my way towards this, but if anyone wants to make the change sooner they're welcome to.
