### ISSUE TITLE
Bookmarked Competition Shows Message for on the Waitlist When Registration is Deleted

### ISSUE THREAD

**Issue by Carter-Thomas** [thewca/worldcubeassociation.org#7656]
Pretty much what the title is, when you have a competition bookmarked and then your registration gets deleted from said competition, the message that you get when you hover over the competition is the same as when you're on the waitlist, which doesn't make sense in this case. 

I have bookmarked MBLD in a Madison Meeting Room and got my registration deleted and in the screenshot below you can see the incorrect message. 
![Screenshot (399)](https://user-images.githubusercontent.com/77213551/221719133-3deb800b-ca54-4655-888e-21aa81732cd0.png)

Pretty obscure and low priority but just something I noticed.

**Comment by dunkOnIT** [comment]
Thanks for reporting it Carter! We'll definitely take a look when we get the chance.
