### ISSUE TITLE
Allow cloned competitions to optionally clone events and schedules

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/worldcubeassociation.org#7737]
**Is your feature request related to a problem? Please describe.**
Currently, cloned competitions preserve venue information and optionally allow users to clone tabs. This is useful when a competition takes place at a venue that has been used at a previous competition, but it's doesn't take it one step further and allow users to clone events (including cutoff, time limits, number of rounds, and round advancements) and schedules.

**Describe the solution you'd like**
Currently, there's a checkbox at the bottom of the competition edit page:
☐ I would like to clone all tabs with additional information as well

I would like this checkbox too:
☐ I would like to clone all events and the schedule as well

**Describe alternatives you've considered**
Allowing users to import event data from another competition in the Manage Events tab is an alternative, but I'm not sure how importing a schedule would nicely fit into this.

**Additional context**
Filling in the data in the Manage Events tab for every single competition is time-consuming and error-prone. I feels like there should be a more efficient way to do this, especially if we're holding the exact same events with the exact same conditions as a previous competition.

**Comment by kr-matthews** [comment]
There's a bunch of discussion about this in #3619

**Comment by dunkOnIT** [comment]
Thanks for raising this Sarah. Merging into #3619.
