### ISSUE TITLE
Incorrect Psych Sheet Rankings for Tied Averages/Means

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/worldcubeassociation.org#7738]
I believe this has been a bug ever since psych sheets were introduced on the WCA site, but I didn't see anything about it when I did a search here. My bad if this is a duplicate.

**Describe the bug**

Whenever there is a tied average or mean on a psych sheet, the ranking for the competitors are the same regardless of their singles.

**To Reproduce**

Go to any psych sheet page with tied averages/means but different singles. Example: https://www.worldcubeassociation.org/competitions/CubingUSANationals2023/registrations/psych-sheet/333fm.

**Expected behavior**

For tied averages/means, the single should be a tiebreaker when determining rankings.

**Screenshots**

This is the top of the psych sheet for FMC at CubingUSA Nationals 2023.

<img width="614" alt="FMC Psych Sheet" src="https://user-images.githubusercontent.com/5139750/225345819-627ca735-ba84-45da-8def-6424224544f4.png">

The rankings shown are { 1, 2, 2, 2, 5, 5, 5, 5, 9 } but it should actually be {1, 2, 3, 4, 5, 6, 6, 8, 9} (note the duplicate 6) since only the 6th and 7th competitors are tied for _both_ mean and single.

**Additional Information**

The rankings are particularly important for the example above since only the top 100 competitors will qualify to compete at the competition. Having multiple rankings near the qualification cutoff can falsely imply that all competitors with a ranking less than or equal to the cutoff will qualify when they actually won't due to other competitors with the same ranking having better singles.

**Comment by maxidragon** [comment]
Hi @sarahstrong314 

I would like to fix this
