### ISSUE TITLE
Give delegates a more informative error message when they try to assign a WCA ID that has already been assigned

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#774]
Right now, the message you get just looks like this:

```
The form contains 1 error:
WCA ID must be unique
```

Which understandably causes confusion for people. @larspetrus recommended that we instead say something like `WCA ID is already used by "Joe Dirt" at foo@example.com`

**Comment by larspetrus** [comment]
If it's shown to the public, we probably don't want to display the email?

**Comment by jfly** [comment]
Oh, good point! We should be okay here because this action is only performable by delegates, who already have the power to view people's email addresses.

**Comment by SAuroux** [comment]
What just popped into my head: Maybe we should not let people claim alread assigned WCA-IDs in the first place?

**Comment by jonatanklosko** [comment]
Hmm I don't think we allow this.
I guess this situation is possible only if two users request the same WCA ID, one of them is approved and a delegate tries to approve the second one (unaware of the first one). Am I right?

**Comment by jfly** [comment]
That's correct, we don't allow claiming an already assigned wca id, but we do allow claiming a wca id that has already been claimed. The idea is that we don't want to let someone squat on someone else's wca id.
