### ISSUE TITLE
DMARC is not properly configured

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#7770]
`v=DMARC1; p=none; rua=mailto:dmarc-reports@worldcubeassociation.org` does actually nothing.
The record should be :
`v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s; pct=100; rua=mailto:dmarc-reports@worldcubeassociation.org`

**Comment by FinnIckler** [comment]
what do you mean nothing? We get DMARC reports every day

**Comment by d4rklynk** [comment]
![image](https://user-images.githubusercontent.com/74207682/226973145-51daff13-696d-428f-97dd-6542557a2ccf.png)
https://www.rfc-editor.org/rfc/rfc7489#page-18

It means there will be a warning while shoudln't even be delivered in the first place.

**Comment by d4rklynk** [comment]
If someone tries to phish users with your domain and that SPF and DMARC are properly configured :
`p=none` means the phishing email will successfully end up in your users' inboxes. Very effective phish.
`p=quarantine` means the phishing email will end up in your users' spam folders. Somewhat effective phish.
`p=reject` means the phishing email will never be delivered. Phishing completely prevented.

**Comment by d4rklynk** [comment]
Hi,

Do you need help to implement it or is it just something that is not on your roadmap yet ?

**Comment by dunkOnIT** [comment]
Thanks for the recommendations on this issue - we had a backlog to work through, but this is something we are in the process of implementing.

**Comment by d4rklynk** [comment]
Hi,

I see you have tagged this issue as blocked. Can I help you in any way ?

**Comment by FinnIckler** [comment]
We are currently slowly changing our dmarc from quarantine to reject and will be closing this issue if everything runs smoothly

**Comment by d4rklynk** [comment]
I'm glad to hear that. Well done

**Comment by d4rklynk** [comment]
Further reading:

- [ADKIM -> RFC7489 section 3.1.1](https://www.rfc-editor.org/rfc/rfc7489#section-3.1.1)
- [ASPF -> RFC7489 section 3.1.2](https://www.rfc-editor.org/rfc/rfc7489#section-3.1.2)
