### ISSUE TITLE
Make it more obvious which events are selected when registering

### ISSUE THREAD

**Issue by nsilvestri** [thewca/worldcubeassociation.org#7817]
**Is your feature request related to a problem? Please describe.**
Often, a new competitor will register for the inverse of their desired events for the first time. This is probably because (presumably by default, but perhaps the user has clicked the "all" button) when all events are selected, and then the user clicks on the events that they wish to register, which actually deselects those events. Even though the number of selected events is listed next to the label "Events", it's possible to misinterpret this as "remaining events available to select", instead of "number of selected events".

**Describe the solution you'd like**
The website should be more explicit about which events are currently selected. The help text seems to me to be a reasonable place to put this information, with the selected events specifically listed. See this mockup: 
![image](https://user-images.githubusercontent.com/33607815/229377834-8d7f077b-1aea-43be-aa95-31bb94e5b3bc.png)

**Describe alternatives you've considered**
Adjusting the UI around the icons to make it more obvious which is selected is a possibility, however it gets complicated to display this information uniquely and clearly when the not-qualified registrations (in the case of championships with qualification times) must also be differentiated.

**Comment by kr-matthews** [comment]
Related to #1519 (which is why "Events (2)" got added) and #7547.

**Comment by nsilvestri** [comment]
I also found that this is probably a duplicate of #7547.

**Comment by dunkOnIT** [comment]
Closed as duplicate of #7547 (moved your suggestion to that thread)

**Comment by nsilvestri** [comment]
I think this was meant to be closed. Closing now :)
