### ISSUE TITLE
Update text in yellow box on "edit profile" page to email WRT, not delegates

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#7820]
When editing a profile that has a WCA ID assigned, competitors are presented with this message in a yellow box:

"You cannot change your name, birthdate, gender, or country. Reason: you have a WCA ID assigned. Contact your [Delegate](https://www.worldcubeassociation.org/delegates) if you need to change any of these."

However, delegates do not have access to change this personal info. In fact, the current regulations suggest reaching the results team through the contact form:

"[2c2](https://www.worldcubeassociation.org/regulations/#2c2)) ... If a competitor wishes to change or update their personal information between competitions (e.g. a change of nationality, name, or gender), they must [contact the WCA Results Team](https://www.worldcubeassociation.org/contact/website)."

I feel like it would be best if these two statements agreed with each other on the website.

**Comment by paarthchhabra** [comment]
Hi, I would like to fix this

**Comment by danieljames-dj** [comment]
Hi @KitClement, WRT had a quick internal discussion regarding it. So, there are cases where the competitor cannot contact the WRT directly - like if there is language barrier. We feel it's better to change it to something like "Contact the WCA Results Team either directly or through their local Delegate".

But this is contradicting a bit to [2c2](https://www.worldcubeassociation.org/regulations/#2c2). @thewca/wrc-team may I know if it's possible to update the regulation statement of 2c2 to "Contact the WCA Results Team either directly or through their local Delegate"?

**Comment by Nanush7** [comment]
Hi all,

We will discuss this and get back to you ASAP. But any change won't be done until the next amendment cycle.

**Comment by Nanush7** [comment]
Hello again. We are going to implement this change to Regulation 2c2 in the next amendment cycle. ;)

**Comment by danieljames-dj** [comment]
Thanks a lot @Nanush7. So, we can change it to "Contact the WCA Results Team either directly or through their local Delegate" in the edit profile page as well.

@paarthchhabra hope you are still interested to fix this issue in code, I've assigned the issue to you. Thanks for your interest again.

**Comment by dunkOnIT** [comment]
Hi @paarthchhabra are you still interested in working on this? Let me know if I can do anything to help!

**Comment by maxidragon** [comment]
@dunkOnIT it's already done, see PR #8090

**Comment by dunkOnIT** [comment]
Ah nice thank you!
