### ISSUE TITLE
Nginx 1.18 is deprecated

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#7829]
Hi, Nginx 1.18 is deprecated for almost 3 years now.
Update it to latest stable version [1.24](https://nginx.org/en/download.html) or 1.25

**Comment by d4rklynk** [comment]
Since you have downgraded the nginx version, it is in 1.18 atm.

Please, update to latest version.

New directive for http2 in Nginx:
https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2

Example:

<1.25.1:
```nginx
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
}
```

And now since 1.25.1<:
```nginx
server {
        listen 443 ssl;
        listen [::]:443 ssl;
        http2 on;
}
```

**Comment by FinnIckler** [comment]
we are no longer using nginx
