### ISSUE TITLE
Capture future improvements to WRT data management tools

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7834]
_Project management only_

A number of "Future improvements" are detailed in [this document](https://docs.google.com/document/d/1AUtcP_9U98ykZrkc9-SPnJJyKZsX8vwC5A9FdgoY6mE/edit). When PHP-related PR's have been merged, capture those item as issues/potential projects.

**Comment by danieljames-dj** [comment]
Looks like all these are implemented @dunkOnIT, safe to close this issue?

**Comment by gregorbg** [comment]
Yes, the document that Duncan mentioned was actually the spec document for replacing PHP.
