### ISSUE TITLE
Read group counts from main site when automatching scrambles on scrambles matcher

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/worldcubeassociation.org#7839]
When generating scrambles, I like to overgenerate a lot in case the absolute worst happens (two extra groups per round of each event).  When I submit, this becomes annoying because I have to drag (and sometimes the drag and drop just breaks and I have to refresh the page and go through the process again: see https://github.com/thewca/worldcubeassociation.org/issues/7220

It would be great if it could read the number of groups I have per round per event that I set in the main site and populate only A, B, C if I have 3.  Obviously, if something happens like an extra round is used, but it's maybe set F from round 1 I'll have to manually do that, but cases like that come up less often, and the general case would make my life measurably improve.

**Comment by kr-matthews** [comment]
This should probably be an issue on the [scrambles matcher repository](https://github.com/thewca/scrambles-matcher/issues)?

**Comment by Sixstringcal** [comment]
Oh my bad.  I looked for it briefly, but couldn't find it and found the linked issue #7220 on this repository, so I figured it was in the same repository.  My bad.
