### ISSUE TITLE
Events added after registration don't currently consult the competitor's auto-selected events

### ISSUE THREAD

**Issue by Sixstringcal** [thewca/worldcubeassociation.org#7840]
I feel this affects organizers/delegates more than most competitors, but in the case where an event is added after someone's initial registration (say skewb gets added late in the org process, but before it's sent to WCAT or Megaminx gets added after registration has initially opened), competitors now have to be alerted of this change, and they then have to modify their registration themselves, or in some cases, email the org team.

Either way, if the competitor is unaware of the change, or forgets to update their registration, they'll be out of luck.

It would be great if the site could reach for each competitor's auto-populated events and then add them automatically (assuming no per-event pricing.  This could also be a setting you could turn off if you are using per-event pricing).

**Comment by dunkOnIT** [comment]
Closing as not planned - as I understand it, this is an edge case that only affects organisers/delegates who registered before comp details were finalised/registrations were opened.

I understand this could be frustrating, but the amount of work to add someone to a group/think to update registration if an event is added is quite small compared to the work we'd need to do to implement this logic in the code. 

Please let me know if I'm trivialising the issue or missing the point - but with my current understanding, the cost/benefit doesn't justify putting work into it.
