### ISSUE TITLE
Developer database export does not update

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#7875]
At the moment (May 7th) the latest `wca-developer-database-dump.zip` is from April 11th, but the job seems to run as usually:

```
mysql> select * from timestamps where name = 'developer_db_dump';
+-------------------+---------------------+
| name              | date                |
+-------------------+---------------------+
| developer_db_dump | 2023-05-06 04:04:31 |
+-------------------+---------------------+
1 row in set (0.00 sec)
```

So likely there's an error during export, but it passes through silently.

**Comment by OldManLink** [comment]
Can confirm. Steps to reproduce: 
* save attached script `wca_dump_date.sh` :
```
#!/bin/bash
DATABASE_EXPORT_URL="https://www.worldcubeassociation.org/wst/wca-developer-database-dump.zip"
ZIP_FILENAME=wca-developer-database-dump.zip
FILENAME=wca-developer-database-dump.sql
VERSION_FILENAME="wca-developer-database-dump.ver"
cd /tmp
wget --quiet $DATABASE_EXPORT_URL
unzip $ZIP_FILENAME
tail -1 $FILENAME > $VERSION_FILENAME
rm $FILENAME
rm $ZIP_FILENAME
cat $VERSION_FILENAME
```
* execute script
* expected result `-- Dump completed on 2023-05-07 04:04:31`
* actual result when executed just now:
````
09:33 $ ./wca_dump_date.sh 
Archive:  wca-developer-database-dump.zip
  inflating: wca-developer-database-dump.sql  
-- Dump completed on 2023-04-11 20:16:20
✔ ~/Downloads/temp/Cube 
09:34 $
````

**Comment by gregorbg** [comment]
The export times out because our database has grown too large. The (terribly, terribly old!) PHP cron scripts are not tied into our usual error reporting, so nobody noticed. There is https://github.com/thewca/worldcubeassociation.org/pull/7642 which will replace the public export cron script by a proper Rails background job instead. Unfortunately, we won't fix this issue on the PHP side in the meantime, so please wait until the aforementioned PR is merged.

**Comment by OldManLink** [comment]
Thanks for the explanation, @gregorbg. Looking at the PR I can see why it's taken a while to get it approved! Fingers crossed that it can be merged soon.

**Comment by jonatanklosko** [comment]
@gregorbg #7642 is about the public export, right? It's actually the dev db dump that's out of date. It is handled by this background job:

https://github.com/thewca/worldcubeassociation.org/blob/bf56fea3922d8d7a964388581f91d0614e948162/WcaOnRails/app/jobs/dump_developer_database.rb#L7-L12

Interestingly, the timestamp gets updated as if everything worked fine.

**Comment by gregorbg** [comment]
Oh, nevermind in that case. You're right, this is the Dev Dump and not the public export.

Will add this to my backlog to investigate, but right now this is not the highest priority

**Comment by OldManLink** [comment]
Even if it might take a while to fix the problem properly, would it be possible to run the Dev Dump job manually every now and then? It's been a month since [**_Jonatan's awesome stats page_**](https://jonatanklosko.github.io/wca_statistics/) has been updated now, and plenty of people do actually use it.

**Comment by timreyn** [comment]
For anyone following along, it looks like this has run successfully:

```
mysql> select * from timestamps;
+------------------------------+---------------------+
| name                         | date                |
+------------------------------+---------------------+
| compute_auxiliary_data_end   | 2023-05-24 07:08:17 |
| compute_auxiliary_data_start | 2023-05-24 07:04:42 |
| developer_db_dump            | 2023-05-21 08:25:44 |
| developer_dump_exported_at   | 2023-05-24 09:09:27 |
| en_translation_modification  | 2023-05-20 19:24:44 |
| linkings_computation         | 2023-05-21 09:05:46 |
| public_results_dump          | 2023-05-23 16:02:50 |
+------------------------------+---------------------+
7 rows in set (0.00 sec)
```
(not sure if #7899 did the trick!)

**Comment by OldManLink** [comment]
I'm not sure how often it is supposed to run, but the latest is from three days ago:

```
07:33 $ ./wca_dump_date.sh 
Archive:  wca-developer-database-dump.zip
  inflating: wca-developer-database-dump.sql  
-- Dump completed on 2023-05-27 10:10:06
✔ ~
```

**Comment by gregorbg** [comment]
It is literally supposed to run every three days, meaning you will get a new export in ~4 hours. You just accidentally happened to check at the veeeery end of the three day time window.

**Comment by OldManLink** [comment]
My apologies for the noise. But now I know!

**Comment by dunkOnIT** [comment]
@OldManLink do you want to take another look quickly? If you see a new one, we can close this :D

**Comment by OldManLink** [comment]
I checked it just now and got:
```
-- Dump completed on 2023-05-30 11:10:11
```
So I'm happy, but maybe we'd better wait until we hear from @jonatanklosko who opened the issue.

**Comment by jonatanklosko** [comment]
Looking good!

**Comment by OldManLink** [comment]
It seems to be happening again, except in a slightly different way. The URL of the db export returns a 301, but the new address gives a 404 instead:
```
13:04 $ wget https://www.worldcubeassociation.org/wst/wca-developer-database-dump.zip
--2024-02-08 13:05:59--  https://www.worldcubeassociation.org/wst/wca-developer-database-dump.zip
Resolving www.worldcubeassociation.org (www.worldcubeassociation.org)... 52.39.252.86, 54.201.161.128, 35.84.122.245, ...
Connecting to www.worldcubeassociation.org (www.worldcubeassociation.org)|52.39.252.86|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.worldcubeassociation.org/export/developer/wca-developer-database-dump.zip [following]
--2024-02-08 13:06:00--  https://www.worldcubeassociation.org/export/developer/wca-developer-database-dump.zip
Reusing existing connection to www.worldcubeassociation.org:443.
HTTP request sent, awaiting response... 404 Not Found
2024-02-08 13:06:00 ERROR 404: Not Found.
```

**Comment by gregorbg** [comment]
Where did you get the original 
`wget https://www.worldcubeassociation.org/wst/wca-developer-database-dump.zip` from?

**Comment by FinnIckler** [comment]
The new link is https://s3.us-west-2.amazonaws.com/assets.worldcubeassociation.org/export/developer/wca-developer-database-dump.zip

**Comment by gregorbg** [comment]
We should probably set up a proper redirect so that legacy projects can still rely on the old link

**Comment by OldManLink** [comment]
You took the words right out of my mouth! 🤣

**Comment by OldManLink** [comment]
I updated my dump date checking script (see above) to use the new s3 URL, and the dump is still working:
```
Archive:  wca-developer-database-dump.zip
  inflating: wca-developer-database-dump.sql  
-- Dump completed on 2024-02-07  0:16:29

```
