### ISSUE TITLE
Clarify wording for registration edit deadline information

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/worldcubeassociation.org#7895]
Related discussion for editing the WCRP can be found [here](https://github.com/thewca/wca-documents/issues/333)

The current message displayed on homepages for registration edit deadline information is the following 
>If you are a registered competitor you may change your registered events until Date at Time on the Register tab.

The spirit behind this isn't to stop competitors from _changing_ events, but rather to stop competitors from _adding_ events, since organizers need time to plan groups, print scorecards, etc. . I believe that changing the wording of this could be beneficial to make it extra clear that the competitors can't _add_ events to their registration (so that the unwritten policy is that competitors can drop events anytime before the competition). I think the change could look something like the following:
>If you are a registered competitor you may change your registered events **to add additional events** until Date at Time on the Register tab.

Of course, I think its fine to lock the ability for competitors to edit their own events after the deadline, but it would be nice to make the language a bit more specific and avoid carrying any sort of idea that competitors can't drop events before the competition. 

For the less common competitions that charge by event, rather than a flat fee, I believe that they already have to use external websites for payments, so they should be able to include their own caveats like not allowing _changes_ to competitors registered events past deadlines (as it may cause issues with refunds).

**Comment by dunkOnIT** [comment]
@Samuel-Baird could you check [this PR](https://github.com/thewca/worldcubeassociation.org/pull/8297) and let me know if you're happy with that wording change?

**Comment by Samuel-Baird** [comment]
> @Samuel-Baird could you check [this PR](https://github.com/thewca/worldcubeassociation.org/pull/8297) and let me know if you're happy with that wording change?

It looks great! However, since the WCRP doesn’t allow changes to events after the deadline to edit events has passed, I think the WCRP itself will have to change before this can be updated :/

**Comment by dunkOnIT** [comment]
Ah I see - sorry for my misunderstanding :P We can leave the PR in draft until the WCRP update goes through.

**Comment by dunkOnIT** [comment]
Closing as not planned, as we cannot work on this until a WCRP update - and when WCRP does update, this work will be "pushed" to us by WCAT, so no need to hold an issue open for it. (Discussion in OP is useful, but still reachable via the issue in wca-documents)
