### ISSUE TITLE
New export contains warning inside tsv

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/worldcubeassociation.org#7903]
**Describe the bug**
Every file inside the zip folder contains the line `mysql: [Warning] Using a password on the command line interface can be insecure.`

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/export/results
2. Download TSV (I called `wget https://www.worldcubeassociation.org/export/results/WCA_export134_20230514T015917Z.tsv.zip`)
3. Uzip zip, and open any tsv file.

**Expected behavior**
Don't have this line

**Screenshots**
![image](https://github.com/thewca/worldcubeassociation.org/assets/28397408/2bf39ac6-2419-4865-bf8b-9ab4c1f2bba9)

**Desktop (please complete the following information):**
 - OS: Ubuntu server (22)

**Comment by gregorbg** [comment]
Whoopsie, forgot a sanitizer. Interesting that this was noticed so quickly, I never expected the TSV export to be widely used.

**Comment by gregorbg** [comment]
For the record, the newest export still has the issue with the MySQL line. But the line breaks have been cleaned, so parsing should be possible. If you really desperately need the export, manually cut (or change your code to automatically skip) the first line. We will look into why this happens ASAP.
