### ISSUE TITLE
Expose registration list via the REST api

### ISSUE THREAD

**Issue by coder13** [thewca/worldcubeassociation.org#796]
Live results websites such as Cubecomps or live.cubing.net need some way to import all the registrants for a competition. We already have a JSON format for this: https://github.com/cubing/worldcubeassociation.org/wiki/WCA-Competition-JSON-Format, we just need to write a page that exports this.

**Comment by jfly** [comment]
(This is for CCM to consume)

**Comment by coder13** [comment]
(Among other competitor sites)
