### ISSUE TITLE
Access "Edit profile" user account management easily from WCA profile

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#797]
For administration purposes, it would be great if the WCA profile would provide a link to the "Edit profile" page for

1) the logged-in user himself
2) Admins/Results team members

Note: Of course this goes only for profiles with associated user accounts.

**Comment by nathanajah** [comment]
Hi there! I'm interested in taking this issue.

Just want to clarify a few things though:
- The WCA profile would be at, for example, https://www.worldcubeassociation.org/persons/2010AZAR01, right?
- Where would be a good place to add a button? Perhaps something like ![this](https://user-images.githubusercontent.com/5294606/34469310-0dd8b342-ef14-11e7-9a4e-9978c8b1b1d1.png) with a more proper styling? (pardon my slightly-disturbing avatar 😄 )

**Comment by jfly** [comment]
Yeah, that's totally the idea! Generally speaking, I prefer using buttons only for things that *do* something, and visiting an edit profile page doesn't do something (tl;dr: **this should be a link, not a button!**)

In the interest of saving space, it might look better to put the link after the name? If not, we should at least have some padding below the button so it's not smooched up against the profile picture like that.

**Comment by nathanajah** [comment]
Something like
![this](https://user-images.githubusercontent.com/5294606/34472340-06c0216e-ef58-11e7-82f3-969fa9b35149.png)
perhaps?

**Comment by jfly** [comment]
I love it!

**Comment by jfly** [comment]
How's this coming along, @nathanajah?

**Comment by nathanajah** [comment]
Hey @jfly ! I'm relatively busy at work lately, but I should be able to find some time this week to work on this. Thanks for checking!

**Comment by jfly** [comment]
This has been merged up, so I'm closing this issue. Thanks @nathanajah!
