### ISSUE TITLE
Add Guidelines for profile pictures and media

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#798]
First of all, this issues applies to both admin and user areas.

Guidelines to be added on top to the Admin "Approve pictures" script:
1. All avatars should be pictures of real persons.
2. The person shown must be the involved member (as far as can be judged).
3. If there is more than one person on the avatar, it should be clear who is the involved member.
4. The head of the involved member, not necessarily the full face, should be visible.
5. The avatar should not include texts other than regular background texts.
6. If the correct orientation of the picture is clear (portrait or landscape) the picture must be submitted in that correct orientation.

Guidelines to be added on top to the Admin "Approve media" script:
1. All media content must be related to the selected competition.
2. All media content must be appropriate and clean and not contain any improper or offensive material.
3. If the media content is huge, the checking can be done on excerpts only.
4. If there is presence of sponsors / ads, it must be moderate.
5. All media content should have appropriate and descriptive titles. If only this condition is not met, a results team members can choose to set an appropriate and descriptive title before approving the content.

Guidelines to be added to the user "Edit profile" pages where pictures can be submitted:
1. All avatars should be pictures of real persons.
2. The person shown must be you.
3. If there is more than one person on the avatar, it should be clear who of them is you.
4. Your head, but not necessarily the full face, should be visible.
5. The avatar must not include texts other than regular background texts.
6. The avatar must be submitted in correct orientation.

Guidelines to be added to the media submission site (https://www.worldcubeassociation.org/results/media_insertion.php):
1. All media content must be related to the selected competition.
2. All media content must be appropriate and clean and not contain any improper or offensive material.
3. The media content must not have extensive presence of sponsors / ads.
4. All media content must have appropriate and descriptive titles.

**Comment by SAuroux** [comment]
Even though this is now marked as "ment1", it would be good to handle this issue together with https://github.com/cubing/worldcubeassociation.org/issues/802

**Comment by jonatanklosko** [comment]
@SAuroux I will handle the avatar guidelines but media are PHP thing at the moment so I think it's ok to do it separately.
