### ISSUE TITLE
Don't show link to wca live for competitions that don't use it

### ISSUE THREAD

**Issue by dmint789** [thewca/worldcubeassociation.org#7980]
Currently, when you open an ongoing competition, it shows a link to WCA live. But some competitions don't use it, so you get an error. The link should not be shown if the competition doesn't use WCA live.

**Comment by gregorbg** [comment]
This is supposed to be configurable and the link is hidden when you configure the competition accordingly.
Is there a specific competition you would like us to take a look at?

**Comment by dmint789** [comment]
It's already had its results posted. I'm not sure how this can be reproduced.

**Comment by danieljames-dj** [comment]
@dmint789 may I know which competition it was?

**Comment by dmint789** [comment]
@danieljames-dj I _think_ it was [this one](https://www.worldcubeassociation.org/competitions/GACubersBigBlindQualifier2023), but this was long enough ago that I can't be sure anymore

**Comment by dunkOnIT** [comment]
Competition linked had "Use WCA Live for scoretaking ticked" - closing as we have no examples to work from. Will reopen if we see another instance of this.
