### ISSUE TITLE
URL to previously uploaded images via WCA Competition Tabs yields error 404 / does not appear anymore

### ISSUE THREAD

**Issue by AnnikaStein** [thewca/worldcubeassociation.org#7987]
**Describe the bug**
Images uploaded to WCA for competition tabs not appearing as they did until a couple days ago. Cross-checking the link to active_record for specific images gives error 404. Newly uploaded images do appear in competition tabs, as well as images uploaded in delegate reports, but not images uploaded a while ago that should be reused for new competitions as well, in our case, e.g. GCA Logo. Is it possible that there is a certain timeframe for which such uploads are kept that has simply just expired now?

**To Reproduce**
1. Go to e.g. https://www.worldcubeassociation.org/competitions/RheinlandPfalzOpen2023#25768-gca
2. GCA Logo as well as two other images should appear below the text, but they don't. Tab had just been copy-pasted. Happens for other competitions as well.

**Expected behavior**
The images uploaded earlier should still be there, a) for using them in new competition's tabs (important), b) when referencing the URL to the picture from somewhere else (less important but a useful cross-check).

**Screenshots**
How the image is loaded in many German competitions in the GCA-Tab:
<img width="1143" alt="Bildschirmfoto 2023-06-08 um 11 39 50" src="https://github.com/thewca/worldcubeassociation.org/assets/53974095/e3f72d7b-c317-44b2-8589-b8faea9f1bee">

What is shown in the end (just the text below, not the image -> left blank):
<img width="309" alt="Bildschirmfoto 2023-06-08 um 11 41 41" src="https://github.com/thewca/worldcubeassociation.org/assets/53974095/a99b21b5-5c59-412a-883d-42dc38f47249">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 113.0.5672.92

**Additional context**
The image in question which now somehow does not exist anymore (GCA Logo)
https://www.worldcubeassociation.org/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGNqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f5a3ffd6896616efd5a223d82b8aa6a160700ee3/Ohne%20Titel.jpg

**Comment by gregorbg** [comment]
This is related to the rotation of our session keys yesterday night. I thought that my script caught all links, but apparently I was wrong. Checking later during the day!

**Comment by AnnikaStein** [comment]
Woah, thanks for the quick reply! :-)

**Comment by gregorbg** [comment]
Yup, indeed had a fluke in my Regex that did not catch certain edge cases when two markdown images where immediately following each other (famous `\w*` vs `\w*?` non-greedy matching).
Fixed internally (thus no corresponding PR) and already migrated :D

**Comment by AnnikaStein** [comment]
Fantastic 🥳, thanks again!
