### ISSUE TITLE
Avatar admin page reject box should have a dropdown

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#7994]
Currently in avatar admin page (https://www.worldcubeassociation.org/admin/avatars), if we click 'reject', it will have a text box to provide reason for rejection. Instead of that, it will be good if we have a dropdown with the list of guidelines (in english language) along with an 'other' option which when clicked the user can manually enter the rejection reason.

**Comment by dunkOnIT** [comment]
@FinnIckler we should take this into account in the avatar rework

**Comment by SAuroux** [comment]
I was also thinking about this more often recently as copy & pasting from the avatar guidelines on top of the page is getting increasingly annoying.

**Comment by dunkOnIT** [comment]
No promises, but the odds are good that this will be worked on in the next month or so.
