### ISSUE TITLE
25 hour schedule for the results export?

### ISSUE THREAD

**Issue by Logiqx** [thewca/worldcubeassociation.org#8003]
The results export is available at https://www.worldcubeassociation.org/export/results

I recently noticed that the refresh time is slipping by about 1 hour every day. I have checked this periodically using curl:

```
Last-Modified: Thu, 15 Jun 2023 14:02:23 GMT
last-Modified: Wed, 14 Jun 2023 13:02:21 GMT
...
last-modified: Mon, 12 Jun 2023 11:02:22 GMT
last-modified: Sun, 11 Jun 2023 10:02:17 GMT
last-modified: Sat, 10 Jun 2023 09:02:09 GMT
...
Last-Modified: Wed, 24 May 2023 17:02:13 GMT
```

Ideally the export should run at roughly the same time each day for the benefit of downstream automated (and manual) processes. The export certainly used to run at the same time every day which iirc was around 0400 UTC.

The [Senior Rankings](https://logiqx.github.io/wca-ipy-www/) automatically refreshes its results once every 24 hours. It has always used a stateless process and simply runs a full refresh at a fixed time each day. If it runs before the latest results export is available then the latest senior rankings are effectively delayed by 24 hours. The process at my end has always been scheduled for around 0410 UTC to ensure it grabbed the results export as soon as possible but the two processes are now out of sync.

Hopefully it shouldn't be a difficult task for somebody to ensure the results export runs once every 24 hours and starts at approximately the same time each day. It wouldn't surprise me if there are other automated processes which also find the 25 hour schedule slightly inconvenient.

**Comment by dunkOnIT** [comment]
@FinnIckler would the migration to Sidekiq have fixed this for free?

**Comment by Logiqx** [comment]
I think this has now been fixed. Latest refreshes:

Last-Modified: Sun, 17 Mar 2024 00:02:50 GMT
Last-Modified: Mon, 18 Mar 2024 00:02:53 GMT
Last-Modified: Tue, 19 Mar 2024 00:23:12 GMT
Last-Modified: Wed, 20 Mar 2024 00:03:02 GMT
Last-Modified: Thu, 21 Mar 2024 00:03:10 GMT
