### ISSUE TITLE
Expose results via the REST api

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#801]
Is this something that you would be willing to see happening?

French and Swiss cubers use  some [script](https://github.com/speedcubingfrance/coupedefrance/blob/master/script/generate_rankings.py) to download the latest TSV export and generate rankings for an unofficial event (French cup).
The generated json is then uploaded to our [website](http://www.speedcubingfrance.org/speedcubing/coupedefrance/) to display the rankings.

Relying on the WCA api would remove the last manual part (ie: I would not have to do anything anymore :p).

**Comment by coder13** [comment]
This is something I want to see happen. I was going to get around to writing up the api so that someone can implement it.

**Comment by UnsolvedCypher** [comment]
This appears to be implemented already via the WCA API. Is there missing functionality or can this issue be closed?

**Comment by viroulep** [comment]
I think only records and per-competition results are implemented, it would also be nice to be able to query for N results in region X for year Y (or all).
Basically some variation of what is done here: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/results_controller.rb

But I wouldn't mind to much if we just have a subset (ie only query concise results for now, scoping with year and region).

**Comment by robiningelbrecht** [comment]
FYI: I released an unofficial WCA API: https://wca-rest-api.robiningelbrecht.be/
Feel free to provide feedback

**Comment by dunkOnIT** [comment]
Thanks @robiningelbrecht for your work on the unofficial API! 

Closing this in favour of #8102, which will document any work on the v1 API release (still _months_ away at the earliest)
