### ISSUE TITLE
Transfer domain to Porkbun

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#8010]
Googles domains [is being sold](https://support.google.com/domains/answer/13689670) to SquareSpace which is quite awful. To be sure you can keep manage your domain easily and without problem, you can switch to Porkbun.

Porkbun supports passwordless authentification as Google does. Problem is, they use Cloudflare DNS, I have heard from sysadmin very recently that CA records was broken in Cloudflare (they don't respect it). You can use [deSEC.io](https://desec.io/) for DNS servers which works wonderfully (fully PowerDNS compliant).

You obviously don't have to do it, it's just a good idea to transfer the domain to avoid problems in the future.

**Comment by FinnIckler** [comment]
Thanks for the info, we are planning to move DNS to Route 53 soon anyway.
