### ISSUE TITLE
Competition incorrectly reports registration closed

### ISSUE THREAD

**Issue by OldManLink** [thewca/worldcubeassociation.org#8015]
**Describe the bug**
A user can't register to an competition even though registration is still open for another four weeks

**To Reproduce**
1. Log in as user Erik Hegardt 
![image004](https://github.com/thewca/worldcubeassociation.org/assets/4593694/3d3ea6eb-bd74-45cc-b46c-0c2ee1911b73)

2. Go to 'https://www.worldcubeassociation.org/competitions/GotlandOpen2023'
3. Click on 'Register'
4. Scroll down to 'bottom of page'
5. See error
![unnamed](https://github.com/thewca/worldcubeassociation.org/assets/4593694/21b6f9c4-3d94-47bd-8905-d2375f0c5305)

The error translates to: Registration closed about a month ago since Thursday 25 May at 23:59 CEST

**Expected behavior**
The user should come to the registration page

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Edge, Firefox
 - Version various

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: unknown
 - Browser stock browser
 - Version unknown

**Additional context**
The user was browsing the site in Swedish

**Comment by FinnIckler** [comment]
I don't see that error. Where you able to reproduce this yourself?

**Comment by OldManLink** [comment]
I created a test user Test Testsson and registered successfully with it. You can see it in the deleted registrations for the comp. 

I have shared a link to this issue with the user in question so that they can follow along and perhaps provide more information. Are there any logs server side for this kind of error, or does the check occur locally?

**Comment by FinnIckler** [comment]
There are logs for every request, but it will be impossible to find if we don't know either
1) the exact time this happened or
2) the request id (which a normal user would not think to write down as it is normally hidden in a response header)

**Comment by OldManLink** [comment]
OK, I’ll ask the user to come here and provide one or both of those data and see what they say.

**Comment by OldManLink** [comment]
User Logged out and logged in again and the problem disappeared. I guess the issue can be closed, now, sorry for the noise.
