### ISSUE TITLE
Incorrectly display of competiton location data

### ISSUE THREAD

**Issue by emmmty-space** [thewca/worldcubeassociation.org#8061]
The competition page shows incorrect, specifically conflicting information, regarding the location of competitons. It is thought that recent updates to the websites has caused this anomaly.

This bug is only seen currently in one competiton, which is described below.

The details of the competiton Maru Cube Day 2023 is shown as both in Taipei and Tainan. Taipei is at the north of Taiwan, and Tainan is at the south of Taiwan, which cannot be in the same place. This is likely a buggy display of the country which shows "Taipei" in the location.

**To Reproduce**
1. Go to the WCA website.
2. Click on Competitons, then All.
3. Filter competitons for "Chinese Taipei".
4. See error.

**Comment by gregorbg** [comment]
This is not a bug as per https://www.worldcubeassociation.org/posts/important-changes-to-the-recognition-of-regions. The ambiguity stems from the fact that the term "Chinese Taipei" references the entire country.
