### ISSUE TITLE
"Entschuldige, etwas ist schiefgelaufen"

### ISSUE THREAD

**Issue by thomasmerz** [thewca/worldcubeassociation.org#8076]
**Describe the bug**
This happens for example on this URL: https://www.worldcubeassociation.org/persons/2015MERZ01

**To Reproduce**
1. Go to 'https://www.worldcubeassociation.org/persons/2015MERZ01'
2. See error

**Expected behavior**
No Error, but some infos about this user should be shown

**Screenshots**
<img width="1255" alt="grafik" src="https://github.com/thewca/worldcubeassociation.org/assets/18568381/7bd4999a-a45e-419f-88dc-d213edf0ba44">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FireFox
 - Version both latest as of today.

**Smartphone (please complete the following information):**

**Additional context**
Request ID: 70679a9b-24b6-4cb6-84d9-68476c67950d

**Comment by gregorbg** [comment]
Congratulations, you managed to open your profile _exactly_ in the 60 seconds when we ran a maintenance upgrade. Should be fine again now. Sorry for the inconvenience!

**Comment by thomasmerz** [comment]
I really should start gambling instead of having this kind of "luck" 🤣 
Once upon a time I even caught the right milisecond in which a DB2 datasharing group on an IBM z-something mainframe wasn't able to be recoverd. IBM support wasn't happy with my "luck", too 🤷🏼‍♂️
