### ISSUE TITLE
Rankings Page - Gender not working

### ISSUE THREAD

**Issue by TheMagicCuber** [thewca/worldcubeassociation.org#8078]
**Describe the bug**
Selecting 'Female' on the rankings page does not correctly display only females.

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/results/rankings/333/single
2. Click on 'Female'
3. See error

**Screenshots**
![image](https://github.com/thewca/worldcubeassociation.org/assets/35645519/30decfe3-2c65-4c8b-b586-cb00aacbbe3a)
![image](https://github.com/thewca/worldcubeassociation.org/assets/35645519/13883ae4-6344-4d09-8da1-947956a1ca27)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 114.0.5735.199

**Comment by FinnIckler** [comment]
Weird, this must have something to do with changing the cache key, but https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/results_controller.rb#L156 does have gender in the cache key and we unpack the values here https://github.com/thewca/worldcubeassociation.org/blob/f75f0dc74a2a2db520d490d4255e04e9aef25cbb/WcaOnRails/app/views/results/rankings.html.erb#L14

**Comment by FinnIckler** [comment]
Seems like it is actually related to #7983

**Comment by gregorbg** [comment]
Hotfixed via https://github.com/thewca/worldcubeassociation.org/commit/133e285698082001ff4eec32ee357e7283e38b9a
