### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by sushantshah-dev** [thewca/worldcubeassociation.org#8101]
The API is missing clear documentation about existing endpoints, Making it difficult for the 3rd Party software ecosystem to grow.

I request the publishing of detailed documentation about the existing API endpoints, and the roadmap for the future development of the API, as it appears to be stagnant.

**Comment by kapuranirudh** [comment]
Hi,

I can help in building or restructuring your API doc, please share the endpoints and other details required.

**Comment by dunkOnIT** [comment]
Hi all! Thanks very much for your interest in the API. 

An unofficial (but endorsed by WST) API is available here: https://wca-rest-api.robiningelbrecht.be/. While there is currently a v0 API on the WCA website, it is not intended for public use and thus there is no documentation for it. 

We do have plans for a v1 API implementation (you can refer to our project board periodically to check progress), but there is a significant amount of work needed to stabilize and modernize the website which WST is currently underway with. The v1 API will only be prioritized once that more fundamental work is in place.

**Comment by sushantshah-dev** [comment]
> Hi all! Thanks very much for your interest in the API. 
> 
> An unofficial (but endorsed by WST) API is available here: https://wca-rest-api.robiningelbrecht.be/. While there is currently a v0 API on the WCA website, it is not intended for public use and thus there is no documentation for it. 
> 
> We do have plans for a v1 API implementation (you can refer to our project board periodically to check progress), but there is a significant amount of work needed to stabilize and modernize the website which WST is currently underway with. The v1 API will only be prioritized once that more fundamental work is in place. 

Can I get just a list of all the endpoints?

**Comment by FinnIckler** [comment]
If you want to use the Data the WCA provides, please use the [WCA Results export](https://www.worldcubeassociation.org/export/results) or the[ WCA Developer Export ](https://www.worldcubeassociation.org/export/developer)

**Comment by kapuranirudh** [comment]
Hey @dunkOnIT : thanks for sharing, yes your v0 looks good, will check your project and will surely extend my help for v1 API doc whenever fundamental work is done...!!

**Comment by robiningelbrecht** [comment]
> 
> Can I get just a list of all the endpoints?

The endpoints are documented on the URI @dunkOnIT shared
