### ISSUE TITLE
API route to expose competition series data

### ISSUE THREAD

**Issue by JonEsparaz** [thewca/worldcubeassociation.org#8115]
**Is your feature request related to a problem? Please describe.**
Speedcubing Canada would like to develop landing pages for a competition series on our website that displays information about all the competitions in a series (so we can provide a single link).

**Describe the solution you'd like**
API route `GET /competition_series/:id` that returns at least:
- the competition series name
- an array of IDs of competitions in the series

(Likely just use the `to_wcif` method from `CompetitionSeries`, then add an API test for the route.) 

**Describe alternatives you've considered**
N/A

**Additional context**
I'm happy to take this on if there are no objections from WST.

**Comment by gregorbg** [comment]
No objections in principle, but we're very busy with US Nats / Worlds prep at the moment so no promises on a swift review
