### ISSUE TITLE
Improvement of Delegates listing page UI

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#8179]
Currently, the delegates page (https://www.worldcubeassociation.org/delegates) have all the delegates listed in single page. Instead can we have a left side bar where the delegate regions will be listed and when we select a region, the delegates of just that region will be shown.

In this way, we can have a sub-heading in each region like - 'Senior Delegate', 'Regional Delegates', 'Delegates' and 'Junior Delegates'. In this way, we won't have the page cluttered when we list the regional delegates too.

What are your suggestions on having this UI improvement? Will it be better or is current UI more better?

PS: Trainee Delegates won't be listed as the Board have instructed [here](https://github.com/thewca/worldcubeassociation.org/issues/5118) that Trainee Delegates need not be listed in the Delegates page.

**Comment by EdHollingdale** [comment]
Similar to #4328 (which has been open for a while...)

**Comment by danieljames-dj** [comment]
Oh yes, didn't knew about that. I'll close this one then. Thanks @EdHollingdale for pointing it out.
