### ISSUE TITLE
Auto-add qualified events

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#8231]
**Is your feature request related to a problem? Please describe.**
For CubingUSA Nationals 2023, we had at least 12 competitors who emailed us that they forgot to add events after qualifying for them, and did not notice this until after the edit events deadline.

Our bid for Worlds 2025 proposes increasing qualifications multiple times, so this is likely to cause more issues then.

**Describe the solution you'd like**
For competitions with qualification times, add an option to the registration flow to "register me for all events that I qualify for". Then, on some frequency, add people to events based on this.

**Describe alternatives you've considered**
Another option is "provisional registration" for events -- select all events that you want to register for, with a different icon for events that you aren't qualified for. This is similar to how it used to be, but many competitors didn't realize they weren't registered for, so the UX will need to be carefully considered.

The interaction between this and top-N qualifications will need to be considered.

**Additional context**
I'm refraining from suggesting specific UXs or implementations, since I'm not familiar with the new registration system.

**Comment by dunkOnIT** [comment]
Great requirement/suggestion, thanks Tim! Closed in favour of the same issue on our registration repo :)
