### ISSUE TITLE
Placeholder for discussion about "full name" vs "given name, last name"

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#826]
We currently have one field labeled "Full name". There have been a lot of discussions about splitting this into multiple fields. I (@jfly) personally think one field is the way to go, but we need a place to point people to when they ask why we do it the way we do it. I hope that this issue can be that place.

Pre-reading:
- https://www.w3.org/International/questions/qa-personal-names -[Tim Habermaas](https://groups.google.com/d/msg/wca-admin/_KeLQkWm7mU/XO8vuVeyAgAJ)
- https://groups.google.com/d/msg/wca-admin/_KeLQkWm7mU/22XFu-roAgAJ Interesting statistics by @pedrosino.
- [Falsehoods Programmers Believe About Names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) - I actually really dislike the tone of this article. He states a bunch of "incorrect assumptions people make", and never actually gives any concrete advice. Still, this article seems to inevitably come up in any sufficiently long discussion about names in software.

Discussions:
- https://groups.google.com/d/msg/wca-admin/_KeLQkWm7mU/TkrZwkWTAgAJ
- [On abbreviations in competitor names](https://groups.google.com/d/msg/wca-admin/8UPEEu1xUQw/JhTB2Vo-BQAJ)
- https://groups.google.com/d/msg/wca-admin/Bt5-ZcoB0eQ/GcqAhH9_EQAJ
- https://groups.google.com/d/msg/wca-admin/nos-FI9GZE8/UryKrT1oBQAJ
- https://github.com/cubing/worldcubeassociation.org/issues/389
- #817
- [Issue with register tab and locating payments tab....confirmed email already.](https://groups.google.com/d/msg/wca-admin/TSfZIvFRhqk/4mUltTRLBgAJ)
- https://github.com/thewca/wca-regulations/issues/407

The WRT has some guidelines on names. From the [delegate crash course](https://www.worldcubeassociation.org/delegate/crash-course):

> New: On abbreviations in competitor names:
> 
> - Competitor names are required to contain a full last name (as noted on a person's legal document) and reasonable first (nick)name a competitor can be called by.
> - Double letter abbreviations such as "AJ", "TJ", etc. are permitted if a competitor wishes to be called accordingly.
> - Single letter abbreviations ("A.", "B.", etc.) for first names are not permitted.
> - Second first names / middle names can be abbreviated if desired.
> - Note: Competitors that prefer to be called by their second first name are permitted to use this as reasonable first (nick)name.
>
> Examples corresponding to the list above:
> 
> - Permitted: "Luis J. Iáñez", "Luis Javier Iáñez", "Javier Iáñez", "OJ Simpson"
> - Not permitted: "L. J. Iáñez", "L. Javier Iáñez", "Luis Javier I.", "L. J. I."

**Comment by AlbertoPdRF** [comment]
Is this still relevant? I'm closing it for now, but feel free to re-open it if necessary!

**Comment by jfly** [comment]
It *is* still relevant (I still think we shouldn't split the field, but I expect people to keep asking about it). Since there isn't actually anything actionable here, I think it's fine to close the issue, though. We can still link people to it if they ask about splitting the field.
