### ISSUE TITLE
Migrate schedule viewer

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#8272]
**Note:** similar to #7025, Kevin and Cailyn can provide valuable input about the scope of this migration

- [x] migrate from react-bootstrap to Semantic
- [x] migrate from manual DOM re-rendering to proper stateful components

**Comment by kr-matthews** [comment]
I'm working on the schedule tab in wca-registration, so I guess this could be assigned to me.
