### ISSUE TITLE
Running tests on main produces an "access denied" error

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#8313]
## To reproduce: 
1. Use the latest version of master
2. Run website with docker
3. Run `docker-compose exec wca_on_rails bash -c "RAILS_ENV=test bin/rake db:reset && RAILS_ENV=test bin/rake assets:precompile && bin/rspec"`
4. Get "Access denied" error

## Current workaround
1. Create `WcaOnRails/.env.test.local`
2. Copy contents of `WcaOnRails/.env.test` to the file created in (1)
3. In `.env.test.local`, delete the value of `DATABASE_PASSWORD=root`, such that it reads: `DATABASE_PASSWORD=`
4. Run `docker-compose exec wca_on_rails bash -c "RAILS_ENV=test bin/rake db:reset && RAILS_ENV=test bin/rake assets:precompile && bin/rspec"`
5. Test should now run

## Potential solutions 
1. This will be solved when we move the repo to a docker deployment - tests will be run with a `docker-compose.dev.yml` script

**Comment by gregorbg** [comment]
The workaround is not really a workaround, it's the intended solution.
We run tests on a wide variety of environments, and currently our codebase is configured in a way that helps the CI to run tests. If you have your own configuration on your own machine, that's kinda "at your own risk" and using the `*.local` environment files is the intended and correct way to go about such changes.
