### ISSUE TITLE
Update About the WCA Page Statistics

### ISSUE THREAD

**Issue by StanFromIreland** [thewca/worldcubeassociation.org#8316]
The following sections should be updated on the [WCA about page](https://www.worldcubeassociation.org/about):
**Who we are**
...over 100,000 people...
**What's next for the WCA?**
...over 100,000 unique competitors across 140 different regions...

To:

**Who we are**
...over 200,000 people...
**What's next for the WCA?**
...over 200,000 unique competitors across 158 different regions...

### SQL Queries for verification:

_Total Number of Competitions_
`
mysql> SELECT COUNT(DISTINCT id) as TOTAL_IDS FROM Persons
`
|TOTAL_IDS            |
|--------------------|
|205792                 |

_Total Number of Countries Where there is at least one competitor_
`
mysql> SELECT COUNT(DISTINCT countryId) as COUNTRIES FROM Persons
`
|COUNTRIES            |
|--------------------|
|158            |

**Comment by dunkOnIT** [comment]
Fair point - PR's welcome

**Comment by Carter-Thomas** [comment]
Would this require changing the about page (currently static) to a dynamic page? Or could we just periodically change the numbers, as changes like this probably don't come too often?

**Comment by gregorbg** [comment]
To be honest, having this number be dynamically generated based on the actual count in our DB sounds pretty cool. And it's also a nice and easy change for people looking to become more familiar with Rails

**Comment by Carter-Thomas** [comment]
I made a commit for the static option, anyone else can feel free to make the dynamically updating page. Imo, having the about page have the exact member count may not look as professional and may kind of feel out of place. This could be done for countries in theory, but it's still quite a rare occurrence for a new country to gain its first competitor.

**Comment by dunkOnIT** [comment]
I tend to agree that having a non-round number would look unprofessional. Perhaps we could round the live number down to the nearer 10,000 though - that way instead of "259 765 competitors", we would have "over 250 000 competitors". I'll create a new issue for this change, and propose we merge Carter's in the meantime.

**Comment by dunkOnIT** [comment]
@Carter-Thomas you can make a PR for your static option and reference this issue - I've created a new one for the dynamic count
