### ISSUE TITLE
Investigate MySQL database lock timeout

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#8320]
Review CAD job not running because of database lock - see Sebatien's message in Slack, and this screenshot: 

![image](https://github.com/thewca/worldcubeassociation.org/assets/52967253/53d40d44-9e58-42b8-b6ba-95a60a825167)

**Comment by FinnIckler** [comment]
It reads to me like the job waits till it is allowed to write to the database (which has some kind of lock on one of the tables) and times out because it never gets the OK. Something to investigate would be the enhanced monitoring on the rds console, the logs seems to be empty

**Comment by gregorbg** [comment]
Considering this as "solved" simply by preventing parallel processing of load-intensive jobs via https://github.com/thewca/worldcubeassociation.org/pull/8322
