### ISSUE TITLE
wca_cronjob.rb aborts a job if recently_rejected > 0 (so we can never run jobs that were rejected)

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#8324]
@gregorbg please advise if this is intended behaviour. As far as I can tell this means that recently_rejected can never be reset to 0, because `statistics.recently_rejected = 0` can never run

**Comment by FinnIckler** [comment]
Context for this: 
The results dump seems to have failed 5 days ago and it hasn't run since, with the error being at this spot in the before_enqueue action

**Comment by gregorbg** [comment]
You must have got something wrong here. The cronjobs don't run if `recently_errored` is > 0, which is absolutely intended because if there's an error during a cronjob, it needs our attention before further cronjobs can run

**Comment by FinnIckler** [comment]
makes sense, but doesn't that mean we have to manually change the column in the database after we fixed it?

**Comment by gregorbg** [comment]
Currently, yes.

**Comment by dunkOnIT** [comment]
Ok cool, makes sense! My naive concern was that jobs can fail for inconsistent reasons (eg database lock when they try and run).

Any tips on surfacing logs on why the original job failed?

**Comment by gregorbg** [comment]
Sidekiq has an error message in the "Dead" panel. We also keep the error message in our database, cronjob_statistics table.

If you really want to dig into the logs, you'd have to query the sidekiq process for information. Hopefully the failures are trivial enough that we can survive until we properly containerize Sidekiq.
