### ISSUE TITLE
Add a warning below the WCA ID box for all authorized WCA staff members 

### ISSUE THREAD

**Issue by lnzainn** [thewca/worldcubeassociation.org#8440]
I believe that at the moment, only the Board, WRT and WST can see the warning (see image below) for special users 

![image (1)](https://github.com/thewca/worldcubeassociation.org/assets/99952754/b19ccd3c-a7d4-4324-a7d2-83a01d471ab8)

I believe having this warning show up for all the staff members (who have the permission to view the edit page of any profile) will be beneficial.

**Comment by dunkOnIT** [comment]
100% agree, and pretty straightforward change for anyone looking to put in a first issue.

**Comment by lnzainn** [comment]
> Should organizers be included in this? The message itself says that they should, however they don’t have permission to view the edit page of any profile.

It doesn't say that organizers should?

**Comment by Carter-Thomas** [comment]
Oh wait, I misread. I thought that special users (which include organizers) were part of the group that were trying to be added.
