### ISSUE TITLE
Fix page redirect error

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#8462]
Currently, if we try to access a page that we don't have access (like https://www.worldcubeassociation.org/panel/seniors), we are getting error 'You are not allowed to board member'. This has to be fixed to something like 'You are not allowed to access the page'.

**Comment by dunkOnIT** [comment]
This is probably just changing `en.yml` right? So a very good, basic first issue for someone.

**Comment by danieljames-dj** [comment]
Actually the mentioned page is no longer available as it is moved inside panel. I couldn't reproduce the issue, when I tried opening https://www.worldcubeassociation.org/panel/board, I'm getting proper error message "You are not allowed to access board panel". Since it's not reproducible, I'm closing it for now. Will reopen if I ever find this issue again. Sorry for the inconvenience.
