### ISSUE TITLE
Help i18n maintainer to easily track changes in the English locale

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#847]
Not sure how to do this right now, but we should be able to provide a way to help translators knowing what we changed in the English version of the website after their last translation.

**Comment by jfly** [comment]
Crazy idea: require that the translated version have a commented out version of the english interspersed through it? That might actually make translating a little easier, and we could use it to track changes.

**Comment by larspetrus** [comment]
How would "helping the translators" work ideally? Maybe there is one (or more) emails for each language, and they get notifications when a translated key changes? What's a realistic workflow?

It should be somewhere between "simple" and "not too painful" to generate a snapshot of the English versions of all keys translated to Elbonian, perhaps automatically when the Elbonian file is checked in, and later do comparisons against that.

**Comment by viroulep** [comment]
Ideally we would have a list of translations somewhere, with a green check if it's up to date, and a red cross if it's not; clicking on it would show a detailed diff justifying the red cross.

This sounds like a diff on two revisions: maybe for each translation we could keep the latest commit of the maintainer(s), and show the diff for the english+translation locales between this latest commit and now?

This is actually pretty much what we do to translate the Regulations: we look at the diff between `official` and the tag corresponding to the latest translated version.

I don't know exactly how (= wiki, readme, something else?) to keep track of the latest commit for every translation, but once we have it the rest looks easy.

**Comment by jfly** [comment]
It would be kind of cool if github issues were automatically created when a translation is out of date. Maybe travis could check for out of date translations and create them? It should be possible to generate an api key for travis and have him do stuff like that.

A wiki keeping track of the state of all our translations would also be cool and maybe less of a mess.

**Comment by viroulep** [comment]
Given we now have a "server status" page on the website, I guess we could add a status for every available languages too.
But I don't think the page should trigger a mail if a translation is not up to date, so we could make it a warning instead of an error.
