### ISSUE TITLE
Admins can delete their own Registration even if deleting registrations for competitors is turned off

### ISSUE THREAD

**Issue by FinnIckler** [thewca/worldcubeassociation.org#8495]
Probably not worth fixing on the old registration system, but I'll document it here anyway:
Even when "User can not delete their own registration" is turned on for competitions, I got shown the button to delete my registration which I was able to user without issue. This caused some confusion with the organizers.

Solution:
- Don't show that button even if you are an admin

This happend for https://www.worldcubeassociation.org/competitions/SeomaraCubeFest2024

**Comment by dunkOnIT** [comment]
Closing in favour of #8237
