### ISSUE TITLE
/users searchbox doesn't update url

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#852]
When I search for a user, click edit, and then click back, I don't end up back on the search results I would expect to end up on. This is because we don't update the /users url to reflect the current query string.

Fixing this would be a good ment2 project. @jonatanklosko, could you add some references to other places in our codebase where we do this correctly?

**Comment by jonatanklosko** [comment]
Hmm this is pretty tricky stuff. Actually it'd say it's not similar to anything we've done before. The bootstrap table search box seems to be troublesome, I managed to make things work when we leave it empty, but filling it with anything (including `search=something` in the url) resets the page to 1st. Actually I think that this is the lib issue and I even found such (probably, as it's in Chinese) and added [a comment](https://github.com/wenzhixin/bootstrap-table/issues/2580#issuecomment-244552699) explaining this.

**Comment by jfly** [comment]
Gotcha. This does sound tricky, so I've removed the `ment2` label. Are there other places in our codebase where we use this feature of bootstrap-table?

Thanks for commenting on the issue upstream. Let's revisit this in month and see if anyone from the project responds. If nothing happens, we can investigate (monkey?) patching it ourselves.

**Comment by jonatanklosko** [comment]
@jfly We update the url on the persons index page and it works well, but it differs as we have our own form (region picker + own search box), whereas on the users index page we just use bootstrap-table's search box, that is just easier as we don't have to provide our own params method and such.

**Comment by pedrosino** [comment]
Would it be too bad to mimic the Persons search for users?
Is bootstrap table a need there?

**Comment by jfly** [comment]
@pedrosino, I think that is one possible workaround that we can investigate in a month from now. If someone is interested in working on this in the mean time, be my guest!

**Comment by jonatanklosko** [comment]
@pedrosino the persons index uses bootstrap-table as well, the difference is that on the persons index we have custom form, and having it requires more effort but as we want more advanced search that's necessary. On the other hand for the users index is perfectly enough to have the lib's search box, and IMO it's not worth overriding this as we can do this easily if there's not bug in the lib.

**Comment by jfly** [comment]
Unfortunately, it looks like https://github.com/wenzhixin/bootstrap-table has been dead since August. @jonatanklosko, how much work would it be for us to implement our own workaround for this?

**Comment by jonatanklosko** [comment]
@jfly I've switched to use our custom text box. See the PR and let me know whether this makes sense or is an overkill.
