### ISSUE TITLE
Unofficial World Cube Association (WCA) Public API - LIVE data

### ISSUE THREAD

**Issue by h3tz** [thewca/worldcubeassociation.org#8531]
**Key Features**
Welcome to the unofficial World Cube Association (WCA) Public API documentation! With this API you will receive data in real-time.

I'm in no way affiliated with or part of the official WCA software team.

Note: This V1 version will be updated multiple times during the next weeks till V2 a stabilized version is released.

Note: Currently this app is running in the staging Phase (that is the reason the the very long URL). Once Tests are done it will be moved to the production stage and the URL will change

Give it a try: https://github.com/h3tz/wca-api

**Comment by h3tz** [comment]
Wrong area sorry. It's no issue. Please close it.

**Comment by h3tz** [comment]
Closed

**Comment by dunkOnIT** [comment]
Hi @h3tz - just wanted to check how you're getting the data for the API? Are you using our v0 API routes, or scraping the website directly?

**Comment by h3tz** [comment]
> Hi @h3tz - just wanted to check how you're getting the data for the API? Are you using our v0 API routes, or scraping the website directly?

I am using a flask, selenium-based scraping running on Heroku. On every request data will be fetched live.

**Comment by h3tz** [comment]
Thanks for your feedback. I will use my api till the official one will be
released with very limited amount of requests (around 2 each day).



FinnIckler ***@***.***> schrieb am Mi., 29. Nov. 2023, 21:43:
