### ISSUE TITLE
Competitor photo too big in the search bar

### ISSUE THREAD

**Issue by dmint789** [thewca/worldcubeassociation.org#8535]
The photos of competitors in the search box we have in the navbar are too big.

To reproduce simply open the WCA website and type any name that doesn't also correspond to a competition name (e.g. Gregor).

You should see that the photos are too big and there is a lot of wasted space.

**Comment by h3tz** [comment]
What is too big? Please provide more information.

**Comment by dmint789** [comment]
@h3tz like I said, the photos of the competitors

**Comment by h3tz** [comment]
Okay, which scale or ratio would be acceptable for you?

**Comment by dmint789** [comment]
@h3tz I think it should just be reverted to how it was a few months ago. Evidently, there was a somewhat recent change that made them way too big. I think they used to be at least 2/3 of the current size.

**Comment by gregorbg** [comment]
I am 80% sure this is related to https://github.com/thewca/worldcubeassociation.org/pull/8527/files

We switched from a custom-build `OmnisearchWidget` component to a more general, reusable `WcaSearch` component.
That new component is probably missing some subtle CSS class, so the selector that was making the images small isn't working anymore.

**Comment by FinnIckler** [comment]
yeah it's definitely related to that

**Comment by dmint789** [comment]
@gregorbg I see, that makes sense. I'd do this myself, but the last time I tried running the wca website locally, I was unable to load the development DB. However, this is not necessary to fix frontend stuff, so if there isn't enough capacity to fix this admittedly small issue, I'm happy to do it myself.

**Comment by dmint789** [comment]
@gregorbg I was able to set things up again. Can you assign this issue to me?

**Comment by gregorbg** [comment]
Sorry Deni, but I needed this fix urgently for a big feature PR.
So I kinda "stole" it from you because it was necessary to unblock some other work. You're welcome to work on other issues, though!

**Comment by dmint789** [comment]
@gregorbg no problem, I was just busy with other stuff and didn't think this was urgent. Thanks for taking care of this.
