### ISSUE TITLE
Change cipher suites of TLS 1.2 to "Good"

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#8539]
The cipher suite is currently set to:

```nginx

ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-CBC-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-CBC-SHA384
```
You can check the results here -> https://www.ssllabs.com/ssltest/analyze.html?d=worldcubeassociation.org&s=54.149.35.21&hideResults=on&ignoreMismatch=on

It would be better to set it to these as recommended by the NCSC https://english.ncsc.nl/publications/publications/2021/january/19/it-security-guidelines-for-transport-layer-security-2.1 among others. (Page 16, Chapter 4 "Versions, algorithms and options", subchapter "Cryptographic algorithms")

Complete list cipher suites by order at page 25, Chapter "Appendix C - List of cipher suites"

```nginx
ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256
```

To have a representation how it will work with clients you can check this example which use the cipher suites:
https://www.ssllabs.com/ssltest/analyze.html?d=grapheneos.org&s=192.99.43.50
As you can see, only very old versions of some software will not be able to visit the site.

For instance, the chacha20-poly1305 cipher can be [safely used](https://caniuse.com/chacha20-poly1305).

It also means you should change RSA to Elliptic Curve Digital Signature Algorithm (ECDSA).

**Comment by FinnIckler** [comment]
We don't have control over this. We are using the recommended AWS Cipher Suit ELBSecurityPolicy-TLS13-1-2-2021-06
