### ISSUE TITLE
Set server_tokens to off to hide nginx version in headers response

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#8561]
![image](https://github.com/thewca/worldcubeassociation.org/assets/74207682/fc8a3cea-de87-49f6-8609-c682a1f975e5)

You can remove the nginx version with this parameter:

```nginx
server_tokens off;
```

It's best practice to hide it, but remember a good hacker can easily retrieve the information by other means.

**Comment by FinnIckler** [comment]
We are no longer using nginx
