### ISSUE TITLE
Switch to report-uri or receive raw email for dmarc report

### ISSUE THREAD

**Issue by d4rklynk** [thewca/worldcubeassociation.org#8591]
I don't know if you pay postmarkapp.com, but it seems expensive, you can try https://report-uri.com/#prices as you can use it for free under 10k mail/month.

At least, you can stick with one or the other by the end of the dmarc rollout.

After that rollout (after `quarantine` to `reject`), maybe you could receive your dmarc report in raw in your WCA mailbox.

After that, the dmarc reports will only be there for debugging. Maybe report-uri or postmarkapp won't be needed.

**_N.B.: This is for information purposes only_**

**Comment by dunkOnIT** [comment]
The postmark report we're using is actually free, and unfortunately we're well over the 10k mails/month limit - appreciate the suggestions though!
