### ISSUE TITLE
Update deploy script to clear Rails caches

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#865]
Unfortunately the structure of our layout files tickles bugs in Rails's fragment caching code. I'll be copy pasting an email thread with @jonatanklosko and @timhabermaas here.

**Comment by jfly** [comment]
# Jeremy

We dug into this a bit more, and here's what we could find. No matter what changes I made to WcaOnRails/app/views/competitions/show_results_by_person.html.erb, the cache key was always the same:

# BEFORE CHANGE
I, [2016-05-24T19:09:01.046824 #6390]  INFO -- : Read fragment views/NationalCapitalRegion2016/by_person/2016-05-24T04:31:48Z/3b9fd42700b830383c9f635f3d3e4511 (0.4ms)

# AFTER CHANGE
I, [2016-05-24T19:24:20.286818 #12316]  INFO -- : Read fragment views/NationalCapitalRegion2016/by_person/2016-05-24T04:31:48Z/3b9fd42700b830383c9f635f3d3e4511 (1.0ms)

After turning on caching in development, I saw the following suspicious message:

  Cache digest for app/views/competitions/_nav.html.erb: 3b9fd42700b830383c9f635f3d3e4511
Read fragment views/My0ResultsComp2016/by_person/2016-05-23T07:02:32Z/3b9fd42700b830383c9f635f3d3e4511 (3.4ms)

It looks like the md5sum is being computed based off of the contents of app/views/competitions/_nav.html.erb, which yeah, we haven't changed. I verified that if I *do* change app/views/competitions/_nav.html.erb, then a new md5 appears, and the cache is busted. As a quick reminder, here's what the relevate files look like:

## WcaOnRails/app/views/competitions/show_results_by_person.html.erb
<% provide(:title, @competition.name) %>

<%= render layout: 'results_nav' do %>
  <% cache @competition.result_cache_key("by_person") do %>
    <% @competition.person_names_with_results.each do |personName, results| %>
      <h3>
        <% first_result = results.first %>
        <%= anchorable "#{personName} - #{first_result.country.name}", first_result.wca_id %>
        <%= link_to "WCA profile", first_result.results_path %>
      </h3>
      <%= render "results_table", results: results, hide_name: true, hide_country: true %>
    <% end %>
  <% end %>
<% end %>

## WcaOnRails/app/views/competitions/_results_nav.html.erb
<%= render layout: 'nav' do %>
  <%= render "competition_info", competition: @competition %>

  <% if @competition.user_can_view_results?(current_user) %>
    <% if !@competition.results_posted? %>
      <%= alert :warning, t('.results_preview_alert'), note: true %>
    <% end %>
    <%= yield %>
  <% end %> 
<% end %>
We dug into this a bit more, and here's what we could find. No matter what changes I made to WcaOnRails/app/views/competitions/show_results_by_person.html.erb, the cache key was always the same:

# BEFORE CHANGE
I, [2016-05-24T19:09:01.046824 #6390]  INFO -- : Read fragment views/NationalCapitalRegion2016/by_person/2016-05-24T04:31:48Z/3b9fd42700b830383c9f635f3d3e4511 (0.4ms)

# AFTER CHANGE
I, [2016-05-24T19:24:20.286818 #12316]  INFO -- : Read fragment views/NationalCapitalRegion2016/by_person/2016-05-24T04:31:48Z/3b9fd42700b830383c9f635f3d3e4511 (1.0ms)

After turning on caching in development, I saw the following suspicious message:

  Cache digest for app/views/competitions/_nav.html.erb: 3b9fd42700b830383c9f635f3d3e4511
Read fragment views/My0ResultsComp2016/by_person/2016-05-23T07:02:32Z/3b9fd42700b830383c9f635f3d3e4511 (3.4ms)

It looks like the md5sum is being computed based off of the contents of app/views/competitions/_nav.html.erb, which yeah, we haven't changed. I verified that if I *do* change app/views/competitions/_nav.html.erb, then a new md5 appears, and the cache is busted. As a quick reminder, here's what the relevate files look like:

## WcaOnRails/app/views/competitions/show_results_by_person.html.erb
<% provide(:title, @competition.name) %>

<%= render layout: 'results_nav' do %>
  <% cache @competition.result_cache_key("by_person") do %>
    <% @competition.person_names_with_results.each do |personName, results| %>
      <h3>
        <% first_result = results.first %>
        <%= anchorable "#{personName} - #{first_result.country.name}", first_result.wca_id %>
        <%= link_to "WCA profile", first_result.results_path %>
      </h3>
      <%= render "results_table", results: results, hide_name: true, hide_country: true %>
    <% end %>
  <% end %>
<% end %>

## WcaOnRails/app/views/competitions/_results_nav.html.erb
<%= render layout: 'nav' do %>
  <%= render "competition_info", competition: @competition %>

  <% if @competition.user_can_view_results?(current_user) %>
    <% if !@competition.results_posted? %>
      <%= alert :warning, t('.results_preview_alert'), note: true %>
    <% end %>
    <%= yield %>
  <% end %> 
<% end %>

## WcaOnRails/app/views/competitions/_nav.html.erb
<div class="container-fluid">
  <div class="row">
      ...
      <%= yield %>
  </div>
</div>

Perhaps fragment caching has bugs with render + yield? The next step for me here would be to add some breakpoints to the digest cache code and figure out why it's looking at this _nav file, but I'm running out of time for the day.

## WcaOnRails/app/views/competitions/_nav.html.erb
<div class="container-fluid">
  <div class="row">
      ...
      <%= yield %>
  </div>
</div>

Perhaps fragment caching has bugs with render + yield? The next step for me here would be to add some breakpoints to the digest cache code and figure out why it's looking at this _nav file, but I'm running out of time for the day.

**Comment by jfly** [comment]
@timhabermaas:

Thanks for digging into it! That's an interesting find and might be a bug, but I don't see how it could be fixed. The block is executed within the `render` method and the only way to get to the place where the block is defined is to use Proc#source_location (http://ruby-doc.org/core-2.2.0/Proc.html#method-i-source_location). So Rails would need to set some global state which `cache` can then read from in order to fix this bug. This sounds extremely hacky.

Can we work around this by setting the layout in the controller instead?

**Comment by jfly** [comment]
@jfly

> Can we work around this by setting the layout in the controller instead?

Oh, that looks promising! I just tried this out by hand, and it does seem to work. Would you recommend following the guide on nested layouts here: http://guides.rubyonrails.org/layouts_and_rendering.html#using-nested-layouts? The whole <%= content_for?(:content) ? yield(:content) : yield %> pattern seems a bit weird.

**Comment by gregorbg** [comment]
Not Finn but happy to confirm :)
