### ISSUE TITLE
Separate page for Board & Officers

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#8659]
Now, Board & Officers are listed under teams & committees page. Definitely Board & Officers are not a team or committee or council, so I think they deserve another page. Requesting feedback for the same.

**Comment by dunkOnIT** [comment]
Have reached out to Kerrie for feedback

**Comment by danieljames-dj** [comment]
This is done here: https://github.com/thewca/worldcubeassociation.org/pull/8935. Will close once merged.

**Comment by danieljames-dj** [comment]
This is live now.
