### ISSUE TITLE
Modification in contact form warning message

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#8664]
Attaching the screenshot of contact form

<img width="1285" alt="Screenshot 2024-01-01 at 06 30 44" src="https://github.com/thewca/worldcubeassociation.org/assets/9512698/258b2192-619a-4af8-b7e4-4b1a7b55d63b">

Since we already have a way to directly contact a team (WRT), adding "not listed here" to the last sentence in info bar will be good. The full sentence will be:

Before making an inquiry, you may wish to take a look at our Frequently Asked Questions! If you wish to contact a specific committee or team **not listed here**, you can find their contact information on this page.

**Comment by leutzed** [comment]
I think this Issue can be closed

**Comment by danieljames-dj** [comment]
Yes, thanks @leutzed. And thanks to @Carter-Thomas for fixing this.
