### ISSUE TITLE
Bug: Custom Activities in the Schedule do not autofill the name

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#8747]
**Describe the bug**
When creating a schedule the text for custom activities does not automatically update

**To Reproduce**
1. Go to the edit schedule page for a competition.
2. Create a custom activity, select one of the options and change the text.
3. Create a new custom activity for something else. Notice that the Name for the activity remains the same.

**Expected behavior**
The activity name updates to what is selected for type of activity.

**Comment by dunkOnIT** [comment]
@kr-matthews is this related to your changes?

**Comment by kr-matthews** [comment]
> @kr-matthews is this related to your changes?

Neither of my PRs have been approved/merged yet.

I can fix this after those PRs are merged/closed.
