### ISSUE TITLE
Unable to easily remove delegates from cloned competition

### ISSUE THREAD

**Issue by 2018RIDA01** [thewca/worldcubeassociation.org#8880]
When cloning a competition, you are unable to remove delegates and organizers as easily as you once could (with the old style of competition page). Only after it has been cloned and created can you slowly remove delegates one by one (as described later). 

**To Reproduce**
1. On any existing competition, click "Clone".
2. After filling in all required details, click "Create Competition".
3. After competition has been made, go to "Edit -> Organizer View".
4. After scrolling down to the listed delegates section (this bug also happens with Trainee Delegates and Organizer section), click the "X" next to **one** of the delegates/organizers names. Hit "Save Changes" and refresh. After this, you can restart the process from step 3. 

**Expected/Desire Behavior**
It is strongly beneficial to be able to remove several delegates at once (as in the old system) compared to having to refresh/save every time. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 121.0.6167.140 (latest)

**Comment by gregorbg** [comment]
@2018RIDA01 Thanks for your clean issue description!

I haven't investigated by trying out exactly what you're describing, but just from reading it feels like this might be related to a patch in one of our data loading libraries. I just merged a fix which might have a positive effect on this issue (i.e. might potentially solve it), can you please check?

If this other fix didn't do anything for your issue, please let me know and I will investigate in more detail.

**Comment by 2018RIDA01** [comment]
@gregorbg yep everything seems to work now!
