### ISSUE TITLE
Automatically make competitions visible when announcing competitions

### ISSUE THREAD

**Issue by slongbehn** [thewca/worldcubeassociation.org#8884]
![image](https://github.com/thewca/worldcubeassociation.org/assets/136729888/f201e2a2-ed55-4295-aee9-6c2f9800259b)

**Is your feature request related to a problem? Please describe.**
When WCAT clicks "announce" on a competition, we then have to make it visible and save the competition. Occasionally, a member either forgets to do this or doesn't save correctly. While most organizers notice this, one did not for several weeks. As far as I am aware, there has never been a time where a competition was announced and was not immediately made visible to the public.

**Describe the solution you'd like**
It would be awesome for WCAT quality of life to automatically make a competition visible when announcing a competition.

**Describe alternatives you've considered**
The alternative is to continue to manually do it. It's fine, would just be nice to not have to :)

Thanks for your time!

**Comment by dunkOnIT** [comment]
Very reasonable, should be a pretty straightforward fix - happy to accept PR's against this, and provide guidance if necessary

**Comment by RamanTheDeveloper** [comment]
Hi, can I get assigned to this task?

**Comment by lnzainn** [comment]
@slongbehn should the 'Make this competition visible to the public' still be there? I assume it may be needed for emergency purposes.

**Comment by slongbehn** [comment]
@lnzainn Yes, the checkbox ideally still there just in case. Thanks!
