### ISSUE TITLE
Error loading results export page

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#8888]
**Describe the bug**
When loading the [results export page](https://www.worldcubeassociation.org/export/results), I get a 500 error:

```
We're sorry, but something went wrong.
If you report this error to the Software Team please mention the Request ID

Request ID: d1b54f3d-53b5-4889-97a2-d3eecf732458
```

Reproduces on Chrome on both desktop (Fedora Linux) and mobile (Android), as well as with curl.

**Comment by FinnIckler** [comment]
The issue is here: https://github.com/thewca/worldcubeassociation.org/blob/a46d1ce0a54f09c87d4e071c03e4092dd8c43485/WcaOnRails/app/controllers/database_controller.rb#L32
This should be ECS Profile credentials

**Comment by FinnIckler** [comment]
I tested this by giving the instance read access to the bucket and there is still the issue that we haven't had a successful run so it still gives a not found error

**Comment by OldManLink** [comment]
Probably related: [the export](https://www.worldcubeassociation.org/results/misc/export.html) used by the [Semi Official Senior Rankings Page](https://logiqx.github.io/wca-ipy-www/Senior_Rankings.html#555-average-60) is also broken:
``` 
The page you were looking for doesn't exist.
If you think this is a mistake please contact the Software Team and include the Request ID

Request ID: 4ac54b0d-5b49-41af-a9d3-0fd4f3270cd0
```

**Comment by gregorbg** [comment]
The Request ID in your pasted error message is trying to access `/results/misc/export.html`. That is a deprecated link from over five years ago, please update the link you're using to fetch the export.

**Comment by FinnIckler** [comment]
Not related. The link https://www.worldcubeassociation.org/results/misc/export.html is super old and I didn't even know that it was ever used

**Comment by OldManLink** [comment]
I'm not the maintainer of that page, it's Michael George. I was just trying to figure out why his page hasn't updated in a over a week. I'll send him a message to update his link if you can let me know what he should be using. I'll also send him a link to this issue so he can follow for himself.

**Comment by Logiqx** [comment]
Just for clarity, I don't use the link mentioned above.

The senior rankings simply download [WCA_export.sql.zip](https://www.worldcubeassociation.org/export/results/WCA_export.sql.zip) each day.
