### ISSUE TITLE
Add validation to length of fields (venue link, name reason string, check for any others)

### ISSUE THREAD

**Issue by soyrandom1** [thewca/worldcubeassociation.org#8894]
**Describe the bug**
After filling the form and pressing "Create competition" nothing happens.
No errors from the front end at all
There are some errors when doing the POST, as you will see in the screenshots section. 
[Here ](https://pastebin.com/z46ff9ZG)you can see a dump from the "options" JSON, this could help.

**To Reproduce**
Create a competition, nothing too specific,

**Expected behavior**
The competition should be created

**Screenshots**
![image](https://github.com/thewca/worldcubeassociation.org/assets/12002910/ec5d2cfd-8493-4520-9ba7-1a967d4730a1)
![WST3](https://github.com/thewca/worldcubeassociation.org/assets/12002910/ec63d6ea-dc28-422c-b842-4d4b70144e64)

Desktop (please complete the following information):

OS: Windows
Browser: Brave
Version: 1.56.20 (Chromium 115.0.5790.171)

**Comment by gregorbg** [comment]
In this specific case, the text you're inserting into "venue" is just too long. Please provide a shorter link so it can fit our database (side note: This has absolutely nothing to do with launching the new frontend, the same error would have occured in the old form as well)

**Comment by soyrandom1** [comment]
Yep, that seems to be the problem. 
Please add a field validation that can bee seen from the front end for this scenario as it's impossible to know what the issue is.
I will close this issue.

**Comment by mirandapedro** [comment]
Thanks for reopening this! I heard a delegate had the same issue with the length of the competition name.

**Comment by mirandapedro** [comment]
Thank you very much for handling this! I really appreciate it!
