### ISSUE TITLE
Add registration date and time to csv export of registrations

### ISSUE THREAD

**Issue by AnnikaStein** [thewca/worldcubeassociation.org#8948]
**Is your feature request related to a problem? Please describe.**
Usually, we need multiple people and hours to go through the list of people who just registered at the WCA page of a competition, to then copy&paste their names, and get their registration time up to the level of seconds. This is then put into another table that can be accessed by the organization team, where payment dates / times (e.g. from PayPal) are used as another column. Eventually, complete registrations are then sorted by whichever of the two came last, and people slowly get accepted from the waiting list. This takes much longer than it needs to take, triggering additional emails of people who don't know if or when the competitor list gets filled. If one could - with few clicks - get all competitors and their registration time as a column from the csv export, it would be a huge step forward - the faster we update the competitor list, the more transparent the process looks from the outside. Technically: no more typing by hand and using mouse-hovering to get the tooltip with precision up to seconds. Organization team members without access to regular workstations (tablets for example) are especially struggling to copy the content of the tooltip over into another tab and we sometimes even need someone to read information out loud to a second person, who is just typing for two hours straight.

**Describe the solution you'd like**
Add one column to the registrations csv export, i.e. `registration.created_at`. This can be formatted the way it is already in the tooltip, YYYY-MM-DD HH:MM:SS UTC, so no need to reinvent anything, we don't need the `registration_date_and_tooltip` function to split the date from the rest, that's something easily implemented in any tabular calculation software (custom date time format as shown above), where one anyway needs to adjust the UTC column to the time zone in which we record payments, or vice-versa. This part is something to be done by each team individually (just tested it with mock columns).

**Describe alternatives you've considered**
a) In the long run, a system that does the matching for us PayPal users (I guess its integration is already WIP).
b) Independent of the csv export function, come up with a hacky way to read whatever gets rendered by `title="<%= date_tooltip %>"` in the console for every row in the table (want to avoid, although parsing this is certainly possible).

**Additional context**
Would probably just edit https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/registrations/export.csv.erb
and do something like
```
<% require 'csv' %>
<% headers = ["Status", "Name", "Country", "WCA ID", "Birth Date", "Gender" ] + @competition.events.map(&:id) + [ "Email", "Guests", "IP", "Registration Date Time (UTC)" ] %>
<%= CSV.generate_line(headers).html_safe -%>
<% @registrations.each do |registration| %>
<%= CSV.generate_line([
  registration.pending? ? "p" : "a",
  registration.name,
  registration.country.id,
  registration.wca_id,
  registration.birthday,
  registration.gender,
] + @competition.events.map { |e| registration.events.include?(e) ? "1" : "0" } + [
  registration.email,
  registration.guests,
  registration.ip,
  registration.created_at,
]).html_safe -%>
<% end %>
```
With one column appended at the end, I hope this does not break anything for anyone, because the columns before that new one are still present in the same order.
I don't know if there are any constraints on the resulting file sizes or how "expensive" in terms of load etc. this added column is though. If there are no concerns, I could just put this modification into a PR of course.

Thanks in advance for your help, WST :)

**Comment by dunkOnIT** [comment]
No concerns from my end - it's basically just adding a column that already exists in the db to the end of the CSV. @gregorbg can weigh in with concerns, but I think you should be fine to go ahead and raise the PR.
