### ISSUE TITLE
Disable illegal competition formats in events page

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#9009]
Currently, the events page allows the BO2 format to be selected for 6x6/7x7 - this should be disabled.

There may be additional illegal formats we want to remove at the same time - I haven't checked, but it may be worth aligning with WRC to make sure we have the requirements clear.

@kr-matthews you may want to take a look at this?

**Comment by kr-matthews** [comment]
See #8494

**Comment by dunkOnIT** [comment]
Closed as duplicate of #7555
