### ISSUE TITLE
Add a feature to disallow the promotions of members to Senior members who haven't crossed their 1 year tenure yet

### ISSUE THREAD

**Issue by lnzainn** [thewca/worldcubeassociation.org#9045]
I would like to start off by saying that this feature should be having low priority.

When you promote a member through the [Groups Manager](https://www.worldcubeassociation.org/panel/leader#groups-manager) , the website only asks for a confirmation and if pressed Yes, it promotes the member. Although, in practice, we wait for the Board to let us know of their decision regarding the promotion, it will be nice if the website itself didn't allow that to happen. 
When someone joins the team, their joining date is stored. So that given date can be used to check whether they have completed their 1 year term on the team yet. 

If someone tries to promote them, then the website should throw an error, or even better, display a message saying something like 'The selected member has not completed their 1 year on the team yet' or '{Name} has not completed their 1 year on the team yet'

**Comment by EdHollingdale** [comment]
There are situations where it is possible to be promoted to a Senior member with less than 1 year in the team however, so this shouldn't be forced.
