### ISSUE TITLE
Leader Panel adding new members

### ISSUE THREAD

**Issue by Rouxles** [thewca/worldcubeassociation.org#9089]
**Describe the bug**
Unable to add new members with the new leader panel.

**To Reproduce**
1. Go to the leader panel and press 'Add New Member'
2. Type in the new member that you want to add
3. Press 'Save'
4. After the pop-up disappears, the new member does not appear in the list afterwards

**Expected behavior**
I expect the new member to show up on the list after pressing save.

**Screenshots**
<img width="273" alt="image" src="https://github.com/thewca/worldcubeassociation.org/assets/7698591/37214ae5-4ee1-48a2-a89e-22475f6f6a7b">
<img width="347" alt="image" src="https://github.com/thewca/worldcubeassociation.org/assets/7698591/146ea322-5df2-4196-8d6b-32e74a61566a">

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2.1
 - Browser Arc Version 1.34.0 (47465) (Chromium based)

**Additional context**
Add any other context (for instance the language you're using the site in) about the problem here.

**Comment by danieljames-dj** [comment]
Thanks for reporting @Rouxles and sorry for this issue. This will get fixed once https://github.com/thewca/worldcubeassociation.org/pull/9091 is merged.

**Comment by Rouxles** [comment]
@danieljames-dj Would you like me to add the new WRC member with the old panel now, or wait until this fix is implemented?

**Comment by danieljames-dj** [comment]
Hi @Rouxles the PR is merged and deployed. Can you try again? If the problem persists you can continue with old panel.

**Comment by Rouxles** [comment]
@danieljames-dj It ended up working! Thanks for the quick fix
