### ISSUE TITLE
Make sure our AJAX requests are configured to indicate that they are `XMLHttpRequest`s

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#9092]
`controllers/application_controller:97` contains a `!request.xhr?` check - this should be sufficient to stop us from saving API requests as "locations" which the user has visited. At present, this check is not working as intended, and so we have deployed #9082 as a hotfix.

* It seems like our requests to our API _should_ contain an `X-Requested-With` header with value `XMLHttpRequest`.
* This is not the case for the Registration Service at present
  * Tested by checking the request headers of staging.wca.org requests made by a [competition page](https://staging.worldcubeassociation.org/competitions/v2/OhioStateRPACCubeClash2024)
* This doesn't _seem_ to be the case for the monolith, although I haven't checked many pages. 
  * Tested by checking headers of staging.wca.org requests made from by [delegate page](https://staging.worldcubeassociation.org/delegates#asia-east)

I'm assuming that adding in this header would be a case of modifying on of the API fetch functions defined in the frontends/in wca-helpers, but I'm not literate enough in React to figure out where. 

@FinnIckler or @kr-matthews you guys might have ideas? Please also let me know if my observations/diagnosis sound accurate.

**Comment by FinnIckler** [comment]
Just a quick google explains that when the web switched from XMLHttpRequest to fetch the XMLHttpRequest was dropped. So I don't think we can rely on that anymore

**Comment by dunkOnIT** [comment]
Ah ok I didn't realize they were distinct JS methods! In that case, `request.xhr?` sounds like it does not hold our solution. 

Doesn't seem like there's a standardized way to identify `fetch` requests (let me know if I'm wrong on that), so I see two options:
1. Inject a header into our requests that we can use to identify requests to the API
2. Continue using the URL to identify API requests

Out of those two, the URL _seems_ more reliable to me - at least, it seems less likely that we would make an API which doesn't contain `/api/` that that we might make a frontend request that doesn't use a standarized `fetch` method (neither _should_ happen, but if either were to happen the latter seems likelier)
