### ISSUE TITLE
Venue form in schedule view disappears when hitting backspace

### ISSUE THREAD

**Issue by GuidoDipietro** [thewca/worldcubeassociation.org#9100]
**Describe the bug**
The issue is self explanatory.

**To Reproduce**
1. Go to an unannounced competition > Manage schedule > Edit venues information
2. Add a venue
3. Click on latitude or longitude fields
4. Hit backspace and try to delete the content of the field
5. Before reaching the end, the form disappears. In the console you can read "Invalid LatLng object (NaN, 57.944834)"

**Expected behavior**
The form shouldn't go away.
I believe this happens when it tries to parse a non-number (such as empty string or `-`) as a LatLng object.

**Screenshots**
![image](https://github.com/thewca/worldcubeassociation.org/assets/48221146/9bbc4472-0ce2-4b9d-ade3-ddb0df7be380)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Brave 1.63.169

**Comment by kr-matthews** [comment]
You also can't type decimals (".") - though you can paste a full decimal number in. And if you do update a coordinate, the map doesn't re-center on the new location (until you save and reload).

I think most venues are created by entering an address, which auto-fills the coordinates, so these issues won't affect most people. But I can look into a fix when I have time.
