### ISSUE TITLE
Have role badges redirect to the relevant team/delegate page

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#9132]
User suggestion in Discord: 
> small thing, but I dislike how if you go to a WCA Staff member's profile, and lets say they're on WCAT. If you press on the "WCAT Member" badge, it doesn't take you to the WCAT page on the teams, committees, and councils page

**Comment by danieljames-dj** [comment]
Fixed by https://github.com/thewca/worldcubeassociation.org/pull/10207.
