### ISSUE TITLE
Touch Icon

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#918]
We should have a touch icon for nice homescreen icons on iOS/Android when people "add to homescreen".

Should be as simple as having a touch-icon image (a single 128x128 image should be fine) and updating every header to include it:

    <link rel="apple-touch-icon" href="touch-icon.png"/>

**Comment by jonatanklosko** [comment]
Duplicate of #109.

**Comment by lgarron** [comment]
> Duplicate of #109.

Heh. :-P
