### ISSUE TITLE
DeserializationError when trying to notify_registrant_of_deleted_registration and notify_organizers_of_deleted_registration

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#922]
Whoops! This happened as part of #642. I'm going to quickly fix this by converting the calls from `deliver_later` back to `deliver_now`, but the proper solution is to add a `deleted_by_user_id` field and not actually delete registrations. This will also allow us to fix #386.

**Comment by ronaldmansveld** [comment]
Solved in https://github.com/thewca/worldcubeassociation.org/pull/1021
