### ISSUE TITLE
Duplicate payments showing on website

### ISSUE THREAD

**Issue by OJCubing** [thewca/worldcubeassociation.org#9239]
We have a couple of competitors registered where the website says they have paid £60 rather than £30 (both on our side and on theirs). On their individual registration pages, it shows two £30 payments made at the same time. We have confirmed through Stripe and through the competitor that only £30 was charged, so it must just be a website error.

**To Reproduce**
https://www.worldcubeassociation.org/competitions/WakefieldSummer2024/edit/registrations
https://www.worldcubeassociation.org/registrations/890456/edit
https://www.worldcubeassociation.org/registrations/890457/edit

**Expected behavior**
Only 1 payment should be showing and the total should be £30 not £60.

**Screenshots**
![image](https://github.com/thewca/worldcubeassociation.org/assets/40577393/16b3866b-4ba1-4845-9db1-ea13f0da1310)
![image](https://github.com/thewca/worldcubeassociation.org/assets/40577393/6b442eba-3811-4e37-bd82-e206a45c99fb)

**Comment by gregorbg** [comment]
Checking!

**Comment by gregorbg** [comment]
Fixed via https://github.com/thewca/worldcubeassociation.org/pull/9240.

We also sent out a detailed email communication to all organizers who were affected.
