### ISSUE TITLE
Warn user before removing an event that has people registered for it

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#925]
In #926, we added a `dependent: :destroy` that ensures that registrations get deleted when the corresponding event is removed.

**Comment by jfly** [comment]
@Mjic99 and I are pairing on this right now.

**Comment by jfly** [comment]
Nevermind! Since filing this issue we completely rewrote the events page in react, and we don't have a good way to display errors/warnings from the backend.

**Comment by EdHollingdale** [comment]
I'm not sure how important this is anyway. If people have registered for the event then that means the competition is announced and locked for editing. The only people who will be removing events will be WCAT members when specifically asked by the delegate, and I'd assume they'd do due diligence to check how many people were registered, if any.

**Comment by Jambrose777** [comment]
I can concur, removing an even is not something wcat will do without careful consideration.

The other team that can remove events is wrt, which at that point the registrations don’t matter anymore.

**Comment by jfly** [comment]
Sounds good! Closing this issue.
