### ISSUE TITLE
Dark Mode for the website

### ISSUE THREAD

**Issue by czhou578** [thewca/worldcubeassociation.org#9250]
**Is your feature request related to a problem? Please describe.**

I'm personally not really a fan of white webpages, as it causes eye strain especially at night.

**Describe the solution you'd like**

A toggle to activate dark mode on the entire website would be helpful.

**Describe alternatives you've considered**

Originally, I was wondering how difficult it would be from a UI/UX perspective to just permanently change the website to a dark mode, but I do realize that in certain scenarios, people do prefer a white background.

**Comment by kr-matthews** [comment]
We have existing issues #4893 & #7075.
