### ISSUE TITLE
2fa page often served in incorrect language

### ISSUE THREAD

**Issue by 0xAda** [thewca/worldcubeassociation.org#9254]
**Describe the bug**
When logging in during busy periods, the 2fa page is often served in a random language.

**To Reproduce**
1. Login with an account using 2fa before a comp opens registration
2. Hope it reproduces the bug

**Expected behavior**
The 2fa page should be in the language other pages are served in

**Screenshots**
![Screenshot_20240423-172717.png](https://github.com/thewca/worldcubeassociation.org/assets/8531139/9bb1471a-59ce-42b2-95f1-778167bea7ac)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora
 - Browser [e.g. chrome, safari] firefox

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Pixel 6 pro
 - OS: [e.g. iOS8.1] android 14
 - Browser [e.g. stock browser, safari] firefox

**Additional context**
N/A

**Comment by dunkOnIT** [comment]
@FinnIckler my first thought is a caching issue - could that apply here?

**Comment by gregorbg** [comment]
Not Finn but quite certain this is an issue with filter chains in Rails Controller logic (ie the order in which callbacks are applied).

@jonatanklosko I vaguely remember we talked about this a long time ago. Do you recall the details? And better yet, do you know an easy fix?

**Comment by FinnIckler** [comment]
We don't have a CDN in front of the website (except for the API) so it's definitely not CDN related. 
I also remember that we talked about this at some point!

**Comment by jonatanklosko** [comment]
@gregorbg probably the same as #7735?

**Comment by jonatanklosko** [comment]
Only the theory I commented on the other issue.

**Comment by dunkOnIT** [comment]
Closing in favor of #7735
