### ISSUE TITLE
"info" in "General info" on comp pages isn't capitalized

### ISSUE THREAD

**Issue by adamschwenn** [thewca/worldcubeassociation.org#9256]
The Problem:
"info" in "General info" on comp pages isn't capitalized.

1. Go to any competition page.
2. Look at "General info" tab.
3. See error

What WST should do:
Capitalize "info."

Screenshot:
<img width="261" alt="Screenshot 2024-04-23 at 5 01 26 PM" src="https://github.com/thewca/worldcubeassociation.org/assets/139075936/7ba0bae5-982c-4426-94c2-1bd26234a004">

**Comment by dunkOnIT** [comment]
Closed by #9259
