### ISSUE TITLE
Change "You are not allowed to staff or any delegate" Message to Something Grammatically Correct

### ISSUE THREAD

**Issue by Carter-Thomas** [thewca/worldcubeassociation.org#9263]
When a non-staff member visits a link such as: https://www.worldcubeassociation.org/#groups-manager, a red banner appears with a message that says "You are not allowed to staff or any delegate". I suggest that this is changed to something like "You must be a staff member of delegate to view this page". Here's a screenshot of the issue: 
<img width="1439" alt="Screenshot 2024-04-24 at 10 41 43 AM" src="https://github.com/thewca/worldcubeassociation.org/assets/77213551/fff9ea7f-3e87-4634-a501-89fe06ea51f1">

**Comment by dunkOnIT** [comment]
This is a great first issue for anyone looking to make a trivial PR - steps as follows: 
- Search for the string "You are not allowed to staff or any delegate" in `en.yml`
- Change it to something grammatically correct
- Submit the change

**Comment by Nanush7** [comment]
@dunkOnIT I couldn't reproduce the issue, and the string "You are not allowed to staff or any delegate" is not present in the en.yml file.

**Comment by Carter-Thomas** [comment]
Okay, oddly enough I cannot reproduce this error, that's a win I guess?
