### ISSUE TITLE
Contact form doesn't populate properly

### ISSUE THREAD

**Issue by SK927** [thewca/worldcubeassociation.org#9276]
**Describe the bug**
When trying to contact organizers via the 'Organization team' link on a competition page, the generic contact form loads. Users have to select that they want to contact the organizers and then provide the competition name by themselves. 

**To Reproduce**
1. Go to 'https://www.worldcubeassociation.org/competitions/BayonneAtoutcubesOpen2024'
2. Click on 'Organization team' on the information section
3. The contact form should load without any prefilled inputs

Bug should be reproducible on any competition page

**Expected behavior**
I would expect to have the form prefilled like this:

![Capture d'écran 2024-04-27 092649](https://github.com/thewca/worldcubeassociation.org/assets/96429132/bd5a6491-01ab-49c7-a4c8-0b85cf23a4ba)

Note: the competition ID is embedded in the contact form link as a parameter.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Firefox Version 124.0.2 and Chrome Version 124.0.6367.91

**Comment by dunkOnIT** [comment]
#9264 in progress to resolve this

**Comment by danieljames-dj** [comment]
This is now fixed.

**Comment by SK927** [comment]
Thanks for the quick fix
