### ISSUE TITLE
Check country names that change using i18n-country-translations

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#928]
We should check country names that don't match the one we use before, and restore the previous one if needed.
eg: "USA" changed to "United States" but that's fine, "Hong Kong" changed to "Hong Kong SAR China" which is not fine and we restored it.

See #927 for another change in name.

If anyone has an easy way in mind to do it, please say so before I start thinking about it :p

**Comment by jonatanklosko** [comment]
If I understand this we need to compare countries from [here](https://github.com/onomojo/i18n-country-translations/blob/master/rails/locale/iso_639-1/en.yml) with these from [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/db/seeds/countries.seeds.rb).

I've made a [script](https://gist.github.com/anonymous/b2cfb1e837412509b0105a1cbba94f15) doing this =)
Here's the result:
```
Conflict 1.
  - WCA version: Antigua
  - gem version: Antigua & Barbuda

Conflict 2.
  - WCA version: Bosnia and Herzegovina
  - gem version: Bosnia & Herzegovina

Conflict 3.
  - WCA version: Congo
  - gem version: Congo - Brazzaville

Conflict 4.
  - WCA version: Cote d''Ivoire
  - gem version: Côte d’Ivoire

Conflict 5.
  - WCA version: DR Congo
  - gem version: Congo - Kinshasa

Conflict 6.
  - WCA version: Hong Kong
  - gem version: Hong Kong SAR China

Conflict 7.
  - WCA version: Korea
  - gem version: South Korea

Conflict 8.
  - WCA version: Macau
  - gem version: Macau SAR China

Conflict 9.
  - WCA version: Myanmar
  - gem version: Myanmar (Burma)

Conflict 10.
  - WCA version: Palestine
  - gem version: Palestinian Territories

Conflict 11.
  - WCA version: Saint Kitts and Nevis
  - gem version: St. Kitts & Nevis

Conflict 12.
  - WCA version: Saint Lucia
  - gem version: St. Lucia

Conflict 13.
  - WCA version: Saint Vincent and the Grenadines
  - gem version: St. Vincent & Grenadines

Conflict 14.
  - WCA version: Sao Tome and Principe
  - gem version: São Tomé & Príncipe

Conflict 15.
  - WCA version: Trinidad and Tobago
  - gem version: Trinidad & Tobago

Conflict 16.
  - WCA version: Turks and Caicos Islands
  - gem version: Turks & Caicos Islands

Conflict 17.
  - WCA version: USA
  - gem version: United States

Conflict 18.
  - WCA version: Multiple Countries (Asia)
  - gem version: undefined

Conflict 19.
  - WCA version: Multiple Countries (Europe)
  - gem version: undefined

Conflict 20.
  - WCA version: Multiple Countries (South America)
  - gem version: undefined
```

**Comment by viroulep** [comment]
Thanks @jonatanklosko, that's exactly what we needed!

Apart from those we fixed, nothing seems too fancy except the Congo/DR Congo that are now named with their capitals. According to Wikipedia it sounds fine though.

I'm closing this because I think no further Country names overriding is needed, feel free to re-open it if you think otherwise!
