### ISSUE TITLE
Anonymization - Banned Competitors and WR holders

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#9343]
**Is your feature request related to a problem? Please describe.**
When anonymizing a person, WRT will need to know the following
- If the person is banned or has been banned.
- If the person has held any records (and which type of records).

**Describe the solution you'd like**
When running the anonymization check on a person:
- If the competitor is currently banned, add a point "1. This person is currently banned and cannot be anonymized" 
  - Optional (but helpful): prevent actioning the anonymization
- If the competitor has been banned in the past, add a point "1. This person has been banned in the past, please email WIC and WRT to discuss whether to proceed with the anonymization"
- If the competitor has held any records, add a point and list which types of records and how many "1. This person has held 2 World Records, 3 Contential Records, and 20 National Records" for example.

**Comment by sushantshah-dev** [comment]
Can you elaborate Anonymyzation?

**Comment by slongbehn** [comment]
As a note, this must now be changed to WIC rather than WDC.
