### ISSUE TITLE
Move competition events to its own page

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#937]
We will soon be collecting more information about competition events such as entry fees, and perhaps scheduling information. The first step of this process will be to remove the events from the main competition page and create a dedicated events page.

**Comment by jfly** [comment]
Before you get started on this, take a look at my open PR #926. It involved added a database migration that slightly changed the way registering for an event is handled.

**Comment by dahermansson** [comment]
What are the thoughts on scheduling information? https://www.worldcubeassociation.org/competitions/VinderupOpen2016#139-schedule for example are using some sort of tab for it but it looks just like normal text. 
A specified schedule-format could make it possible to create .iCal-files to subscribe to for the competitions I register for and by that get the schedule in my smartphones calender.

**Comment by jfly** [comment]
@dahermansson, could you continue the discussion of scheduling over on #278?
