### ISSUE TITLE
%{short_name_limit} not being passed in new Competition Form

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#9410]
See screenshot below for an example of this issue (halfway through the sentence at the bottom of the picture):
![image](https://github.com/thewca/worldcubeassociation.org/assets/52967253/3377f200-49d2-4ec2-93a6-828a510350ec)

My suspicion is that the React Competition Form is rendering the i18n string but not passing in the variable value it expects. Should be a straightforward change to how the i18n string is invoked - and I'm pretty sure short_name_limit should be 32 characters*. 

*_This can probably be confirmed by grepping the repo for variants of short_name_limit - it's probably defined in the backend somewhere_

**Comment by lnzainn** [comment]
@dunkOnIT you can close this issue now
