### ISSUE TITLE
3x3x3 frequency distribution of scrambles

### ISSUE THREAD

**Issue by bcube2** [thewca/worldcubeassociation.org#9414]
Hi,

I believe there are currently no available data for https://github.com/thewca/statistics, so I am asking in this repo instead.

Out of curiosity, and following my query at https://github.com/thewca/wca-regulations/issues/1192, I would like to ask if the WCA software team could generate and publicly maintain the 3x3x3 frequency disribution of scrambles (as it can bee seen at https://docs.google.com/spreadsheets/d/1J-16IUC6FBB_GSvQbZ9zPr_yWrL0MgHhplfxURYM_6U/edit#gid=0 for some competitions)?

**Comment by dunkOnIT** [comment]
Thanks for the suggestion. I have good news and bad news:
* Good news: This is very possible for any 3rd-party developer to achieve. We provide an API endpoint at `/api/v0/competitions/{competition-id}/scrambles/333fm` where the scrambles for any competition can be queried. It should be pretty straightforward for a developer to put together a website that displays the scramble frequency you'd like to see.
* Bad news: This falls outside of the scope of the work we are doing at the moment, or the systems we are looking to maintain, so it is not something the Software Team would take on.

**Comment by bcube2** [comment]
Perhaps I didn´t make myself clear in this issue so allow me to clarify what I am looking for.

I would like to obtain all official 3x3x3 scrambles (from events 3x3x3, 3x3x3 OH, 3x3x3 FMC, 3x3x3 MBLD, 3x3x3 BLD and their extra attemps) from all WCA competitions (currently, according to https://www.worldcubeassociation.org/competitions from 1982 to 2024).

However, I can see such data in the WCA database (from https://www.worldcubeassociation.org/export/results) only since 2014. Do I understand it correctly that WCA doesn´t have 3x3x3 scrambles for competitions before 2014?

The other thing I am looking for (which the WCA/statistics team is currently missing) is generating an optimal move count for those 3x3x3 scrambles, so that the 3x3x3 frequency distribution of scrambles could be seen from the WCA data (so basically, I would like to see graphs like https://kociemba.org/moves20.htm based on the WCA 3x3x3 data). Do I understand it correctly that the WCA software team is not going to generate and maintain those data?
