### ISSUE TITLE
Setup payments may be broken in staging for competitions with payments connected in production

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#9529]
Just got the following error - makes me think that something in our database dumper still needs to be adjusted because of the `fake_stripe_account` value still floating around in there

> F, [2024-06-10T09:43:34.571268 #540] FATAL -- : [dc18b5b5-320c-4c8f-8402-42674f27764a]   
> [dc18b5b5-320c-4c8f-8402-42674f27764a] ActionView::Template::Error (The provided key 'sk_test_********************ziXd' does not have access to account 'fake_stripe_account' (or that account does not exist). Application access may have been revoked.):
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     297:         <%= alert :info, message, note: true %>
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     298:       <% end %>
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     299: 
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     300:       <%= yield %>
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     301:     </div>
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     302:   </div>
> [dc18b5b5-320c-4c8f-8402-42674f27764a]     303: </div>
> [dc18b5b5-320c-4c8f-8402-42674f27764a]   
> [dc18b5b5-320c-4c8f-8402-42674f27764a] app/models/connected_stripe_account.rb:93:in `account_details'
> [dc18b5b5-320c-4c8f-8402-42674f27764a] app/views/competitions/payment_integration_setup.html.erb:14
> [dc18b5b5-320c-4c8f-8402-42674f27764a] app/views/competitions/_nav.html.erb:300
> [dc18b5b5-320c-4c8f-8402-42674f27764a] app/views/competitions/payment_integration_setup.html.erb:3
> [dc18b5b5-320c-4c8f-8402-42674f27764a] lib/middlewares/warden_user_logger.rb:13:in `call'
> [dc18b5b5-320c-4c8f-8402-42674f27764a] lib/middlewares/fix_accept_header.rb:14:in `call'

**Comment by gregorbg** [comment]
This simply means that our most recent changes hadn't been deployed yet when the last staging dump was imported.

Importing a new dev dump will fix the issue.

**Comment by dunkOnIT** [comment]
Updated staging db
