### ISSUE TITLE
Speed up Persons search

### ISSUE THREAD

**Issue by larspetrus** [thewca/worldcubeassociation.org#956]
The persons search page (https://www.worldcubeassociation.org/persons) looks like the biggest performance drain in the system (in New Relic). Response times can go up to 15 seconds, and they probably have a knock-on effect on other queries as well.

We haven't profiled the code, but the likely culprit is the `rails_persons.name LIKE :part OR wca_id LIKE :part", part: "%#{part}%"` query. The only way the DB can execute `LIKE %foo%` is by looking at every row in the table.

Some possible improvements:
1. Don't perform searches for the empty string. These are 26% of all searches and are quite pointless.
2. Don't perform searches for 1 or 2 character strings (11% and 7% of the non empty searches). This probably requires UI changes.
3. Add a MSQL FULLTEXT index to the columns. This should speed things up enormously, but at a price: You can search for the beginning of any word, but not in the middle. So searching for `pet` would return `Lars Petrus` but not `Amy Spetter`. I think that's fine for searching names, but I'm less sure about WCA ID.
4. One idea is to recognize when the search is for a WCA ID and do a much faster query for that, but looking at the search data, that's only 3% of searches if you count partial IDs. 0.6% for complete IDs.
5. 10-20% of queries are duplicates from the same person typing or reloading. A quickly expiring result cache (~5 minutes) could help with those without going too deep into caching complexity.

There are probably other good ways to approach this.

[New Relic response times last 24 hours](https://rpm.newrelic.com/accounts/1068954/applications/10385163/transactions#id=5b22436f6e74726f6c6c65722f706572736f6e732f696e646578222c22225d) - (I hope that's a permanent link)

**Comment by viroulep** [comment]
Unfortunately my PR was just a small bit of performance improvement on the users search page (accessible only to admins).
I think Lars initial thoughts are still relevant: overall the "query" part of the users  search is still more than a second which seems a bit high to me :s

Again we'd need to do a quick review of the persons search vs users search to see exactly where we are.
@jfly added a fulltext index on Persons.name and it looked alright after that, maybe fixing this is as simple as adding the same index on users.name.

**Comment by viroulep** [comment]
I'm looking into this now.
Apart from a potential similar issue on the name search, we have some *terrible* queries in there:
```
Processing by UsersController#index as JSON
  Parameters: {"search"=>"", "sort"=>"name", "order"=>"asc", "offset"=>"0", "limit"=>"10", "user"=>{}}
  TeamMember Load (0.2ms)  SELECT `team_members`.* FROM `team_members` WHERE `team_members`.`user_id` = 277 AND (end_date IS NULL OR end_date > '2018-10-18')
  User Load (1570.5ms)  SELECT `users`.* FROM `users` INNER JOIN Countries ON iso2 = country_iso2 ORDER BY `users`.`name` ASC
Completed 200 OK in 12193ms (Views: 0.5ms | ActiveRecord: 1570.7ms)
```

A similar query (empty search, ending up displaying everyone) for the persons search is done in less than 100ms.

I'm gonna use a similar approach as the person search and offer a region selector, this way we will end up with a cheap `where` instead of this inner join.
