### ISSUE TITLE
Incomplete ranks shown while CAD is running

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#9569]
We have the manually-triggered background job for computing ranks information (CAD). For each of the ranks tables, it removes all rows, then computes and inserts fresh rows. While the computation is running, the ranks tables have missing information, which surfaces in the UI and API.

Here are a few screenshots while running CAD on the staging, where it can be seen how CAD progresses:

<details><summary>Screenshots</summary>

* Records showing only average as ConciseSingleResults are being computed
  <img width="1512" alt="image" src="https://github.com/thewca/worldcubeassociation.org/assets/17034772/1d757643-7035-415a-9c50-bf21d91d4018">
* Records showing only single as ConciseAverageResults are being computed
  <img width="1512" alt="image" src="https://github.com/thewca/worldcubeassociation.org/assets/17034772/82f5c9da-b6ed-485a-ab42-1b73fef58f80">
* Incremental entries in the profile as RanksSingle are being computed
  <img width="1512" alt="image" src="https://github.com/thewca/worldcubeassociation.org/assets/17034772/9a4ea9e4-030b-40b5-a909-1affc72ce61a">
  <img width="1512" alt="image" src="https://github.com/thewca/worldcubeassociation.org/assets/17034772/7fddaeab-58d2-425f-ad72-1449dee2d305">

</details> 

The same issue affects API endpoints that rely on ranks (records, WCIF personal bests), and that is a bigger problem, because API users definitely don't expect records to suddenly have no entries.

For more context, I believe this is the underlying issue behind a few strange false-positive record tags we've seen on WCA Live https://github.com/thewca/wca-live/issues/145.

Note that some of the pages/endpoints are cached, so keep that in mind when reproducing.

**Comment by gregorbg** [comment]
Interesting... Taking a complete shot in the dark here but would wrapping the whole CAD process into a transaction help?

**Comment by jonatanklosko** [comment]
We already update each table in a transaction, so it should be atomic:

https://github.com/thewca/worldcubeassociation.org/blob/1e83c26f9b204bfbd236c6a074fff309eb9d8a47/lib/auxiliary_data_computation.rb#L15-L19

Just looking at the code I don't have any reasonable idea, unless the queries skip the transaction somehow. One option to test would be to add rollback after the delete and see if that works as expected.

**Comment by dunkOnIT** [comment]
#9742 is an example of a fix for this issue which would help us determine if the issue is indeed the in-progress table being read while CAD is running.

The other approach was to increase the isolation level of the CAD transactions, but that seems like a very bad idea because it can lead to database locks etc.

**Comment by jonatanklosko** [comment]
I believe we can close this now, thanks @dunkOnIT :)
