### ISSUE TITLE
Date for qualification requirements should be inclusive

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#9654]
As per WCAT / WRT discussion, in the **events tab** of a competition page, under the "Qualification" column, the current phrasing of "Any single solve by DATE" is ambiguous as to whether the date is inclusive or not.

To reduce the effects of confusion from ambiguity, we will update the wording to have the date be inclusive.

**Changes needed:**

1. At the bottom of the events tab "Qualification times must be set before DATE" needs to be replaced with "Qualification times must be set on or before DATE".
2. All wording of "... by DATE" in the event table needs to be replaced with "... on or before DATE".

**Comment by dunkOnIT** [comment]
This is being implemented in the new reg system, and so should naturally come into rotation in the next couple of months.

**Comment by dunkOnIT** [comment]
Fixed in #9412
