### ISSUE TITLE
Run delayed job daemon under a process manager

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#967]
We now know that delayed_job periodically dies. Thanks to #942, we get emails when it looks like our background jobs are not being processed.
#966 should help us track down the reason(s) why delayed job dies, but I think we should be running delayed_job under a process manager that will start it back up whenever it does die.

Some options:
1. while true; do delayed_job; done
2. http://supervisord.org/
3. https://mmonit.com/monit/
4. upstart/systemd - Upstart comes with our current os (ubuntu 14.04), but at some point we're probably going to upgrade to ubuntu 16.04, which will mean going the systemd route.

I'm leaning towards upstart, knowing that we'll have to port that to systemd someday.

**Comment by larspetrus** [comment]
Another option is to move on to Resque. That's what we did at NeedFeed.

The downside is the added complexity of a Redis server.

**Comment by FatBoyXPC** [comment]
I feel like at least taking a look at this by the weekend. If anybody else feels the desire to get to it before then, by all means, but I figure I'll assign it to myself just so we don't double up on work :)
