### ISSUE TITLE
Competitors Option Disappearing from Competition Info Page

### ISSUE THREAD

**Issue by AlphaSheep** [thewca/worldcubeassociation.org#9744]
**Describe the bug**
On the competition info page ([example](https://www.worldcubeassociation.org/competitions/LightsOutDiliman2024) in the side menu, the "Competitors" item is missing from the menu. When you click on "Register", then the "Competitors" item appears. When you click on any other page, the "Competitors" item disappears from the menu again.

**To Reproduce**
1. Go to [this competition](https://www.worldcubeassociation.org/competitions/LightsOutDiliman2024).
2. See the items in the side menu on the left (Info, Clone and Register). Note that Competitors is missing.
3. Click on "Register"
4. See the items in the side menu on the left now includes Competitors.
5. Click on "Competitors"
6. Note that Competitors is missing from the side menu again.

**Expected behavior**
The "Competitors" item in the menu should be there for all pages.

**Screenshots**
![Screenshot 2024-08-06 081156](https://github.com/user-attachments/assets/5a65cd6f-dda8-42dc-a968-762fc9bfd552)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox 128.0.3 and Edge 127.0.2651.86

**Comment by dunkOnIT** [comment]
Thanks for reporting - this is very likely my fault.

**Comment by dunkOnIT** [comment]
Will be fixed by #9709

**Comment by dunkOnIT** [comment]
Fixed by #9748
