### ISSUE TITLE
Store whether a round is combined or not in the database

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#979]
Right now we just have a list of all combined round ids: https://github.com/jfly/worldcubeassociation.org/blob/54ebe32683e3959f9b184745f49aabf33f78bdd4/WcaOnRails/app/models/round.rb#L10-L13.

**Comment by larspetrus** [comment]
What would this help achieve?

**Comment by jfly** [comment]
Nothing I can think of. As mentioned elsewhere, I'd rather move to a system where we keep track of "nth round" and what the round cutoffs were. This would be enough to encode this information, except maybe for weird round types we don't use anymore such as [qualification round](https://github.com/thewca/worldcubeassociation.org/blob/5125d87e4aa59bb7d9d17006ceab8c60a3ab1a73/WcaOnRails/db/seeds/round_types.seeds.rb#L3) and b final](https://github.com/thewca/worldcubeassociation.org/blob/5125d87e4aa59bb7d9d17006ceab8c60a3ab1a73/WcaOnRails/db/seeds/round_types.seeds.rb#L7).
