### ISSUE TITLE
Contact form enhancements

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#980]
(requested by Ron, but I think this is a good improvement)

Most of the messages that are sent via the contact form are related to a competition.
Would it be possible to add a selection to the contact form?

Something like:

Topic:
Competition (default)
WCA Regulations
Member administration
Results administration
WCA Website
Other

If Competition is selected:
list of competitions
Then redirect to organiser of competition.

If WCA Regulations is selected:
Direct to WRC

If Member administration is selected:
Direct to WRT

If Results administration is selected:
Direct to WRT

If WCA Website is selected:
Direct to Software team

Other:
Direct to Contact@

**Comment by coder13** [comment]
To break it down:

If Competition is selected, create a search box and you type in the competition name. Internally, this will determine who the organizers are an email them

Regulations: email the WRC?
Same for Results and... What's Member Administration?

And for website, email the software team.

Other: you type in...what will other email?

**Comment by jfly** [comment]
As Ron requested, Regulations should email the WRC, and Other should email contact@.

Im not sure what member administration is... I'd leave it out for now. Just write things in a way that makes it easy to add new stuff in the future :)

**Comment by SAuroux** [comment]
I think member administration concerns name changes or DOB changes (the
latter in case that ID claiming doesn't work).

2016-11-04 8:20 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by LinusFresz** [comment]
This was dealt with in https://github.com/thewca/worldcubeassociation.org/issues/2690.
