### ISSUE TITLE
Software Team SSH Keys

### ISSUE THREAD

**Issue by FatBoyXPC** [thewca/worldcubeassociation.org#985]
Have a script that looks at the GitHub team and grabs their public keys stored on each user's GitHub account. @jfly, @coder13, and I all set this up for CubingUSA. I hear that @viroulep would be interested in this happening as well.

There is already some discussion on this exact topic:
https://groups.google.com/d/msg/wca-admin/NNVWHemiyTs/t4AmoHAPCQAJ

**Comment by jfly** [comment]
Here's a link to the CubingUSA code that handles this when bootstraping a new server: https://github.com/cubing/usa/blob/59c6c1f66df2f3579765c1ee7130ed88844d1d16/bootstrap/bootstrap.sh#L37-L51. Since the repo is private, here's a copy paste of the code as well:

```bash
function ssh_keys {
  echo Setting up ssh keys
  users_json=`curl -s -H "Authorization: token $GH_ACCESS_TOKEN" "https://api.github.com/teams/$CUBINGUSA_GH_TEAM_ID/members"`

  users=`echo $users_json | jq -r '.[].login'`
  tmp_authorized_keys=/tmp/authorized_keys
  for user in $users; do
    public_keys_url="https://github.com/$user.keys"

    echo "" >> $tmp_authorized_keys
    echo "# Keys for $user" >> $tmp_authorized_keys
    curl $public_keys_url >> $tmp_authorized_keys
  done
  mv $tmp_authorized_keys $AUTHORIZED_KEYS
}
```

**Comment by jfly** [comment]
Big unanswered question for me: what happens when a software team member changes their SSH keys on github? We need to regenerate our `~/.ssh/authorized_keys` file.

**Comment by viroulep** [comment]
I obviously support this :)
My first reaction when @jonatanklosko gave me the link to the doc was "wait, we use a *password* to log in?!" :p

Changes in ssh keys happen quite rarely, what about adding a target to the deploy script that would regenerate the `authorized_keys` file, and ask team members to execute it whenever a change occurs?

**Comment by jfly** [comment]
> Changes in ssh keys happen quite rarely, what about adding a target to the deploy script that would regenerate the authorized_keys file, and ask team members to execute it whenever a change occurs?

My only concern with that is that we have to still have access to the server in order to do that. It's hard for me to get over my fear that "if I lose my laptop, I can no longer access the server, even after generating a new public key and putting it on github". That said, last night, @FatBoyXPC mentioned that with our awesome team of people, I should be able to ask someone else to run the deploy script for me. It's unlikely we'll all lose our private keys at the same time.

**Comment by FatBoyXPC** [comment]
Not only with our awesome team of people, but we have a couple ideas in place to let us generate the script without being in the server. See #989 for those options!
