### ISSUE TITLE
Notify competitors that they should claim their WCA ID

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#991]
I just realized we don't have an automatic mail to remind competitors to claim their id: it could be useful so that they have it ready for their next competition (it saves time when validating the results spreadsheet).

Obviously we cannot know for sure which id belongs to who, however what we could do is, after the competition's results have just been posted, check all the registered competitors without a linked WCA id, and mail them that if they indeed took part to the competition they should claim their id.

How does it sound?
I actually just did that manually for the last competition I delegated, which is why it could be cool if it would be automatic :p

**Comment by jfly** [comment]
Ah, neat idea! I was so focused on doing the complete awesome thing (#21), that I didn't think about a simpler interim solution like this.

**Comment by viroulep** [comment]
Awesome, thanks @jonatanklosko!

**Comment by viroulep** [comment]
Short feedback on that: this is working great, right after the results of my last comp were uploaded I've had roughly 50% of the newcomers claiming their ID, compared to the usual 1 or 2!
