### ISSUE TITLE
Add the ISO Code along with the description for the list of currencies

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#995]
There are 4 Zimbabwean dollars and we need to be able to distinguish between them.

**Comment by jfly** [comment]
![](https://lh3.googleusercontent.com/-Tuc06jaNKTg/WBxHLr8dKoI/AAAAAAAAcRA/7w1ugWhPPnMhJIcflB07dnKAmZRAn0JVQCL0B/h116/2016-11-04.png)

Sad, but true: https://en.wikipedia.org/wiki/Banknotes_of_Zimbabwe

**Comment by jfly** [comment]
This is still an issue in the "currency code" dropdown. See https://staging.worldcubeassociation.org/competitions/GdanskSideDay2018/edit/admin#competition_currency_code:

![2018-11-13_10 03 34_dalinar](https://user-images.githubusercontent.com/277474/48433212-69d55a00-e72b-11e8-92f1-93d7654eb496.gif)

**Comment by jfly** [comment]
Another idea might be for us to maintain a whitelist of currencies that delegates *actually* use. That would be a bit of a pain at first, but then I imagine the list would change quite slowly.
