### ISSUE TITLE
Subject and title are redundant on Website Comments

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#997]
See 2nd message:
![comments](https://cloud.githubusercontent.com/assets/1881933/20032692/490781a8-a377-11e6-9949-c4575f92c87a.png)

Maybe not every mail client does this, but it also looks kinda redundant after you open the message:
![comm](https://cloud.githubusercontent.com/assets/1881933/20032378/0128d500-a370-11e6-9598-f511dae25f5e.png)

**Comment by jfly** [comment]
Sure, I support removing the first line of the body of the email. @pedrosino, I'm going to assign this one to you =)

**Comment by pedrosino** [comment]
Any hints on where this is stored?
I could only find "Website Comments" at contacts_controller, but that doesn't seem to include the message body.

**Comment by viroulep** [comment]
`Contact` is actually a `MailForm` from the [mail_form](https://github.com/plataformatec/mail_form) gem, apparently we use their default template which is [there](https://github.com/plataformatec/mail_form/blob/5c446d5c148a302971c677800b31e46c77272dc8/lib/mail_form/views/mail_form/contact.erb).

Their [doc](https://github.com/plataformatec/mail_form#custom-e-mail-template) says we can create a custom template, so it should be as simple as taking their template and strip off the first line :)

**Comment by pedrosino** [comment]
Thanks, @viroulep
